### ISSUE TITLE
Kiali UI memory leak 

### ISSUE THREAD

**Issue by kebe7jun** [kiali/kiali#1279] opened 2019-07-25 10:36 UTC
**General remarks**

Kiali UI cost too many memory(1.8G+), and can't response anything. 

**Describe the bug**

This page suspend for a long time(20 mins).

![image](https://user-images.githubusercontent.com/7303612/61867175-29a8b700-af09-11e9-809d-3f6e0d3f61d7.png)

**Versions used**
Kiali: 1.1.0
Istio: 1.2.2
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**To Reproduce**
1. Open Kiali UI.
2. Do something what you want(Not in Kaili UI) about 20mins.
3. Back to Kiali UI.

**Expected behavior**
Memory leak.

**Comment by mtho11** [comment] 2019-07-25 15:11
Thanks @kebe7jun I have created a jira for this: https://github.com/kiali/kiali/issues/1279

**Comment by israel-hdez** [comment] 2019-07-25 15:15
Hi, @kebe7jun 
This is a known issue. I hope this will be fixed for the v1.3 release.
As a possible workaround (I haven't tested) choose "Pause" in the Refresh Interval dropdown (next to the refresh button).

**Comment by jotak** [comment] 2019-08-06 14:40
Hi @kebe7jun ,
Just one question: can you tell us how many namespaces do you have visible in the Overview page (or an order of magnitude)?

**Comment by kebe7jun** [comment] 2019-08-06 15:41
@jotak There are 7 namespaces, 25 services, 40 pods, 5 nodes.

**Comment by jotak** [comment] 2019-08-06 21:18
Thanks @kebe7jun 
I did some tests today but unfortunately wasn't able to reproduce yet: i let the overview page opened for more than 2 hours without problem. Memory started at 44MB then piked at 75MB before stabilizing below 70MB.
I suspected first a memory leak in the charting library but could not find any evidence of that.

Differences to note with your setup: 
- Running latest Kiali
- I'm on a single node
- 5 namespaces & 23 services

I will run more tests later this week, with kiali 1.1.0
I suspect single node can make a difference due to low latency with a throttling algo that is in place on this page.

In the meantime if you have any valuable info to provide, don't hesitate to tell us. 1.8GB is huge, I've never seen that.

**Comment by israel-hdez** [comment] 2019-08-07 17:50
@jotak did you try leaving the tab/window inactive (i.e. minimized or as an inactive tab).

From the steps to reproduce, this is what I understand when saying _"Do something what you want(Not in Kaili UI) about 20mins."_.

I guess that if you keep the page visible, the memory leak won't happen.

**Comment by jotak** [comment] 2019-08-08 12:05
@israel-hdez oh, looks you're correct: it only happens if I switch to another tab in chrome. I didn't understand that. So yes I reproduce now. And btw I've tested with a patternfly 4 implementation (so without c3/d3 under the hood) it doesn't have this problem, so I think my fix will be to move right now to pf4 for the charts displayed on overview.

**Comment by jotak** [comment] 2019-08-08 13:59
FYI JIRA ticket to track this issue: https://issues.jboss.org/browse/KIALI-3198

**Comment by israel-hdez** [comment] 2019-08-14 16:17
Closing. The fix is in Kiali v1.3

**Closed** 2019-08-14 16:18 UTC
Labels: UI changes required :art:, bug :bug:
