### ISSUE TITLE
Kiali Graph UI incorrectly shows `version: unknown` label

### ISSUE THREAD

**Issue by bangau1** [kiali/kiali#626] opened 2018-11-05 03:56 UTC
**Describe the bug**
The Kiali Graph UI showns my workload to have `version: unknown`

**Versions used**
Kiali: v0.9.1
Istio: 1.0.0
Kubernetes flavour and version: GKE v1.10.7-gke.6

**To Reproduce**
1. Go to Kiali url
2. Click on "Graph"
3. Select one of the workload
4. See the `version` label has `unknown` value

<img width="630" alt="screen shot 2018-11-05 at 10 51 34" src="https://user-images.githubusercontent.com/352737/47977088-ceb80100-e0e8-11e8-8453-71e7b26b2c71.png">

**Expected behavior**
The Kiali Graph UI should shown the `version:<stable or canary>`
I have set the config.yaml to be this value
```
kubectl exec -it -n istio-system kiali-8cc798ffb-9t859 -- cat /kiali-configuration/config.yaml
server:
  port: 20001
  static_content_root_directory: /opt/kiali/console
  cors_allow_all: true
external_services:
  grafana:
    display_link: true
    url: <redacted>
  jaeger:
    url: <redacted>
  prometheus_service_url: http://prometheus-server.kube-system.svc.cluster.local:80
istio_labels:
  version_label_name: track
```
As you can see, the `version_label_name` is set to `track` label.
My workload already has the `track` label, as stated by this screenshot in kiali workload UI
<img width="907" alt="screen shot 2018-11-05 at 10 54 51" src="https://user-images.githubusercontent.com/352737/47977181-4be37600-e0e9-11e8-9bfc-125db95fed51.png">

**Comment by jmazzitelli** [comment] 2018-11-05 05:03
I think that first screenshot you have is "correct" as it is telling you literally what the "version" label is set to. As you do NOT have a label literally called "version", it is true the value is unknown.

What I think this issue would like to address is to have the UI show you the label which has been configured as the logical "version" label - so, for example, in the side summary panel perhaps we show  some indicator that "here is the label which is customized to be considered the version". Maybe show the label in a different color? Have some special indicator or icon next to it? I don't know.

Lastly, the node titles should also show the value of the label that was customized for the version. So the node text should have its value taken from the "track" label, not the "version" label in this case.

So I see this as two separate issues - the first is the side panel should show the logical "app" and "version" label values even if customized through the kiali config. The second is the node text should be taking the app and version names from the logical app and version labels (if they were customized to be different in the config, Kiali needs to take that in effect).

Note that it may be difficult to do this because the telemetry uses the literal names "app" and "version" - so if the kiali server-side is just taking the information from the telemetry, it has no idea what the labels are where the app and version string came from. Some additional k8s api calls might have to be made?

The workaround for these issues today would be to set a "version" label on your objects - with the "version" label being the same value as the "track" label.

**Comment by jmazzitelli** [comment] 2018-11-05 05:03
@jshaughn you should review this

**Comment by bangau1** [comment] 2018-11-05 06:06
Hi @jmazzitelli, thanks for the respond and though.
For end-user, i think the semantic of this configuration is very clear
```
istio_labels:
  version_label_name: track
```
It means that end-user can override the `version` label shown in the UI to use the `track` label instead.

Also, in the same graph UI, but for different node that **has no traffic** on them (the bug I reported above is only for node that **has** inbound/outbound traffic), it successfully show the correct `version` label value. 

<img width="937" alt="screen shot 2018-11-05 at 13 04 56" src="https://user-images.githubusercontent.com/352737/47980711-7d653d00-e0fb-11e8-83c3-4dcaa3423180.png">
<img width="989" alt="screen shot 2018-11-05 at 13 04 37" src="https://user-images.githubusercontent.com/352737/47980713-7d653d00-e0fb-11e8-81e8-7a9df4901dd9.png">

So, I believe this is indeed a UI bug. What do you think?

**Comment by jmazzitelli** [comment] 2018-11-05 07:40
This could be a server-side bug, perhaps in one of the appenders. Almost all of the data in that graph page comes from the JSON generated by the server-side. @jshaughn would know more details.

Jay - seems at least ONE if not more JIRAs need to be created here.

**Comment by jmazzitelli** [comment] 2018-11-05 07:48
BTW: in my opinion, in the side summary panel where the blue labels are listed - those should be the actual labels; it should NOT show "version" when it should be showing "track" - even though "track" is the logical "version" label. Those blue labels should be showing the actual labels on the objects.

**Comment by jmazzitelli** [comment] 2018-11-05 07:53
Finally, if you expect to use a different label (like "track") rather than "version", you need to tell Istio this as well, not just Kiali. Otherwise, the telemetry your mesh will be generating will not be what you expect. You would need to change the metric definitions in Istio - for example:

 https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/mixer/templates/config.yaml#L361

There you see the "version" label is used when generating Prometheus labels for the metrics. If you expect to use something OTHER than "version" (like "track") you need to tell Istio this. Something like this is what I think you need:

```
source_version: source.labels["track"] | "unknown"
```

I'll assume @bangau1 did this already - if so, Kiali would need to ensure it also knows about the custom version label that is used by the Istio telemetry subsystem.

**Comment by bangau1** [comment] 2018-11-05 08:40
Hi @jmazzitelli actually I don't change the mixer configuration. thanks for pointing that, let me do this and see if it can solves the problem.

**Comment by bangau1** [comment] 2018-11-05 09:20
Hi @jmazzitelli I just want to tell you that it is indeed due to mixer configuration hasn't been configured. Thank you so much.

I am using the configuration something like this, so to have 2 fallbacks (if `version` isn't exists, use `track` -> the last fallback is `unknown` value)
```
    source_version: source.labels["version"] | source.labels["track"] | "unknown"
```
Perhaps, this istio mixer configuration things are better documented explicitly in this repo's README.

**Comment by jmazzitelli** [comment] 2018-11-05 12:54
@bangau1  2 things:

First, Don't forget you need to tell Istio about the destination as well as the source label. For example:

https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/mixer/templates/config.yaml#L434

```
    destination_version: destination.labels["version"] | "unknown"
```
So for all the metrics, you need to change both source and destination.

Secondly, regarding this:

> have 2 fallbacks (if `version` isn't exists, use `track` -> the last fallback is `unknown` value)

Kiali does not support that. Kiali will look to one and only one label. It knows nothing about the Istio metric expression. So it will only look for one label, not primary/fallback set of labels like you have here.

**Comment by jmazzitelli** [comment] 2018-11-05 15:10
@bangau1 yes, the mixer config is fine. But the problem is Kiali doesn't know anything about the mixer config or these metric definitions. Kiali gets the graph data directly from Prometheus - and the prometheus labels just has the values of the k8s labels, not the label names themselves. You have to be familiar with what Istio does with that config and how it translates to the Prometheus timeseries, but suffice it to say, Prometheus doesn't store what the k8s label NAMES are where the values come from - in other words, Prometheus can't tell us "I got the version value from the k8s label called "track"" - all Prometheus is able to tell you is "the version value is "stable"".

This is why Kiali has that configuration setting you are using - its how you tell  Kiali what k8s labels your mesh is storing its app and version values - it has no expression support - it assumes your mesh uses a common, consistent labeling scheme across the mesh.

Honestly, I think this "primary and fallback" labeling scheme for version is not something typically recommended to do - an app name and version string should come from a consistent place.

**Comment by bangau1** [comment] 2018-11-05 16:53
Hi @jmazzitelli noted.
> Honestly, I think this "primary and fallback" labeling scheme for version is not something typically recommended to do - an app name and version string should come from a consistent place.

yes, I think so too. Current fallback is implemented so I can migrate our production existing workload to have proper labeling according to istio's standard (`app` and `version` label) while ensuring the Kiali graph is showing the expected behavior that I want.

So in summary, your first comment https://github.com/kiali/kiali/issues/626#issuecomment-435756124 should be addressed (regarding how Kiali should display the label consistently in accordance to `ISTIO_LABEL_NAME_VERSION` and `ISTIO_LABEL_NAME_APP` configuration).

**Comment by jshaughn** [comment] 2018-11-06 20:17
I created [KIALI-1872](https://issues.jboss.org/browse/KIALI-1872) to use a configured version label name in the side panel labels.  It's PR is merged so the fix is available in the latest image and will be in the next release.

**Closed by jshaughn** 2018-11-06 20:17 UTC
