### ISSUE TITLE
Graph legend not adjusting to screen height

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1587] opened 2019-08-28 08:54 UTC
On a screen size of 1366x768 (quite common in laptops) the graph legend runs out of the viewport.

JIRA:
https://issues.jboss.org/browse/KIALI-3252

**Comment by mwringe** [comment] 2019-08-30 18:34
Duplicate of https://github.com/kiali/kiali/issues/1620

**Comment by mtho11** [comment] 2019-09-13 16:14
closing, in favor of https://github.com/kiali/kiali/issues/1620 which will fix that

**Closed by mtho11** 2019-09-13 16:14 UTC
Labels: backlog, bug, jira, team/saturn
