### ISSUE TITLE
Kiali graphs are not shown - After working for months

### ISSUE THREAD

**Issue by sachithmuhandiram** [kiali/kiali#3842] opened 2021-04-02 08:10 UTC
**General remarks**

 Kiali Graphs were working fine in our baremetal Kubernetes cluster. Traffic animation, delays all were shown perfectly.

But suddenly all graphs were not shown and saying just empty graph.

**Describe the bug**

![Screenshot_2021-04-02 Kiali Console(1)](https://user-images.githubusercontent.com/12854791/113394093-491e0580-93b5-11eb-9ecc-031a579d8875.png)

Kiali logs

```
W0401 09:41:19.941621       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.Pod ended with: too old resource version: 60763828 (60764851)
W0401 09:43:28.869355       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.Pod ended with: too old resource version: 60764360 (60765377)
W0401 11:53:49.050291       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.ReplicaSet ended with: too old resource version: 60465447 (60474659)
W0401 12:22:36.593396       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.Pod ended with: too old resource version: 60799471 (60800471)
W0401 12:31:16.153893       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.Deployment ended with: too old resource version: 60467311 (60474669)
W0401 14:07:17.319242       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.ReplicaSet ended with: too old resource version: 60487608 (60628914)
W0401 14:11:50.185220       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.ReplicaSet ended with: too old resource version: 60487656 (60684274)
W0402 05:32:03.748071       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.Pod ended with: too old resource version: 61023682 (61024136)
W0402 05:33:27.386002       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.Pod ended with: too old resource version: 61024137 (61024716)
W0402 05:35:11.326843       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: watch of *v1.Pod ended with: too old resource version: 61024184 (61024716)
```

**Versions used**
Kiali: 1.22.1
Istio: istio-1.7.0
Kubernetes version: v1.19.2

**To Reproduce**
 -

**Expected behavior**
* Show graphs with service mesh connectivity as previously.

Referred 

1) https://gitmemory.com/issue/kiali/kiali/3808/807766690 (kubernetes version is newer)

**Comment by jmazzitelli** [comment] 2021-04-02 13:49
I think this is a duplicate of: https://github.com/kiali/kiali/issues/3808 - please confirm and if so, close this issue and resume discussion in that original issue.

**Comment by sachithmuhandiram** [comment] 2021-04-02 14:11
> I think this is a duplicate of: #3808 - please confirm and if so, close this issue and resume discussion in that original issue.

I dont think so, as we have `Kubernetes flavour and version:EKS 1.15`

Also I removed Kiali completely and tried installing it again. Still the same result. All pods were in Not used one

**Comment by jshaughn** [comment] 2021-04-02 15:09
Please confirm that for some reason Istio did not stop generating telemetry into Prometheus.  Navigate to a workload detail in Kiali and check the Inbound/Outbound traffic tabs, are they showing data?  Or [go into Prometheus](https://kiali.io/documentation/latest/faq/#prometheus) and verify that you have current data.  Also, ensure you are configured for the correct prometheus db.

**Comment by sachithmuhandiram** [comment] 2021-04-02 16:43
> Please confirm that for some reason Istio did not stop generating telemetry into Prometheus. Navigate to a workload detail in Kiali and check the Inbound/Outbound traffic tabs, are they showing data? Or [go into Prometheus](https://kiali.io/documentation/latest/faq/#prometheus) and verify that you have current data. Also, ensure you are configured for the correct prometheus db.

Inbound  Outbound traffic

> Not enough inbound traffic to generate info

But traffic flows through the system properly.

`istio_requests_total{reporter="source", destination_service_name="reviews"}` 

This does not show any data in `Prometheus` service running in `istio-system`

**Comment by jshaughn** [comment] 2021-04-03 00:16
That seems to be the problem.  For some reason you no longer have telemetry at the prometheus configured for kiali.

**Comment by jmazzitelli** [comment] 2021-04-03 00:57
> `istio_requests_total{reporter="source", destination_service_name="reviews"}`
> 
> This does not show any data in `Prometheus` service running in `istio-system`

Do you have a service called "reviews" in your mesh? That's a query to use if you have the Bookinfo demo installed, but if your mesh doesn't have "reviews" service, then that query is useless.

What do you see in Prometheus when you query for `istio_requests_total{reporter="source"}` ?? Any recent data at all for any services?

If there truly is no data in Prometheus, then what you are seeing in Kiali is expected - without any data in Prometheus, Kiali will show empty graphs. In that case, this isn't a Kiali bug but instead sounds like it is a misconfiguration somewhere. Check your Istio and Prometheus configuration. If Istio is not storing any data in that Prometheus instance, either (a) you changed the Prometheus instance that Istio is using, but you did not re-configure Kiali to use that new Prometheus, or (b) Prometheus has stopped (for some reason) scraping Istio data.

But I would double check that Prometheus query you used to test. I don't think querying for "reviews" is what you want unless you have Bookinfo demo installed OR you really do have a "reviews" service in your mesh.

**Comment by sachithmuhandiram** [comment] 2021-04-03 03:52
> istio_requests_total{reporter="source"}

This also had no data.

> sounds like it is a misconfiguration somewhere

Problem is that, it was working properly for almost 6 months without any errors, traffics and interconnections were shown properly.

In another K8 cluster (with similar spec) , its was showing all services graphs, now just few services are shown. It also worked around 5 months now.

**Comment by jmazzitelli** [comment] 2021-04-03 04:17
> This also had no data.

`istio_requests_total` has data for all HTTP requests (not TCP requests). I'll assume your mesh services have some HTTP traffic flowing. If so, you should contact the Istio community and ask about this because that wouldn't be a Kiali issue - Kiali simply reads the data from Prometheus and visualizes it - without Istio putting data in Prometheus, Kiali would be expected to show an empty graph like you are seeing.

**Comment by jshaughn** [comment] 2021-04-09 14:08
@sachithmuhandiram Any updates?  I'm fairly sure this is due to an unexpected misconfiguration or change in your environment as there is no reason I can think of that Kiali would stop displaying graphs unless the underlying data source no longer reported telemetry.  Closing, feel free to re-open if you believe there is a real Kiali bug here.

**Closed by jshaughn** 2021-04-09 14:08 UTC
Labels: bug

**Comment by sachithmuhandiram** [comment] 2021-04-09 14:14
> @sachithmuhandiram Any updates? I'm fairly sure this is due to an unexpected misconfiguration or change in your environment as there is no reason I can think of that Kiali would stop displaying graphs unless the underlying data source no longer reported telemetry. Closing, feel free to re-open if you believe there is a real Kiali bug here.

Yes, problem is.. We havent changed anything related to Istio or Kiali..
One of our cluster shows just a few service graphs, where all were shown a few weeks ago.

**Comment by jshaughn** [comment] 2021-04-09 14:25
I sympathize, it's frustrating, but despite not making manual changes, it does seem like something changed that has stopped the flow of telemetry to the Prometheus backend.
