### ISSUE TITLE
Add deepsource.io task to review Kiali code and provide reports

### ISSUE THREAD

**Issue by HarshCasper** [kiali/kiali#3748] opened 2021-03-01 05:11 UTC
## Description 

Hi 👋 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/kiali/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point in time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Shadow of builtin detected [here](https://deepsource.io/gh/HarshCasper/kiali/issue/CRT-A0001/occurrences)
- Possibly wrong conditional expression [here](https://deepsource.io/gh/HarshCasper/kiali/issue/CRT-D0003/)
- Empty fallthrough can be avoided [here](https://deepsource.io/gh/HarshCasper/kiali/issue/CRT-A0003/)
- Empty String Tests can be improved [here](https://deepsource.io/gh/HarshCasper/kiali/issue/CRT-A0004/)
- `append`s can be clubed into a single call [here](https://deepsource.io/gh/HarshCasper/kiali/issue/CRT-P0001/)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you would like to integrate DeepSource to autofix some of the commonly occurring issues, I can help you set that up :)

**Comment by lucasponce** [comment] 2021-03-01 09:06
Thanks for the issue @HarshCasper.
We'll take a look.

"autofix" potential bugs is not something we would integrate in an automatic way as sometimes it hides an intended behaviour, specially when code has several layers.

But in the other hands, some of these recommendations may be valid, so, worth to take a look in detail.

But unless it's something broken, I'll change the label from bug to maintenance.

**Comment by lucasponce** [comment] 2021-08-09 13:53
I think this issue can be considered to use deepsource.io and have some periodical reports.
It happens that some "automatic" recommendations miss context and they tend to throw a lot of false positives.

But they can add some relevant.

Not putting in the backlog as I don't think it would have high priority, but given that this service seems free for opensource projects it can be considered:

![image](https://user-images.githubusercontent.com/1662329/128717443-8dc537af-00ee-4244-a11e-b66816f8c860.png)

**Comment by jshaughn** [comment] 2022-11-30 18:43
Closing as out of scope, static analysis is being run in diffrerent ways.  We invite feedback for specific issues.

**Closed by jshaughn** 2022-11-30 18:43 UTC
Labels: maintenance, help wanted, future
