### ISSUE TITLE
Relax cluster names in Graph badges and cluster boxes defaults

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#5248] opened 2022-06-24 08:22 UTC
Commented with @jshaughn about the possibility to show the "cluster names" in graph badges only when the "Cluster boxes" option is enabled.

Also, the default value is "enabled" and perhaps it can start "disabled" until the user would like to change it.

![image](https://user-images.githubusercontent.com/1662329/175494626-c6aa9052-ac1b-4f92-aa21-89cf7d6712e1.png)

**Comment by jshaughn** [comment] 2022-07-01 20:07
@lucasponce I could not reproduce this in some brief testing.  It's weird, I'm not sure why you see what you're seeing in the above screenshot.  It would indicate that maybe, somehow, your cluster name, "cluster-default", did not properly get set in the serverConfig passed back to the ui.  The screenshot doesn't show it, but do you see the cluster name in the masthead, if so is it "cluster-default"?  Do you see it in the clusterInfo in the masthead's debug info ?

**Comment by josunect** [comment] 2022-07-26 14:00
I'm no sure what should be the behavior for "Cluster Boxes", it makes no difference in the graph in my environment (I was expecting to remove (cluster-default): 

![image](https://user-images.githubusercontent.com/49480155/181024399-d4e91314-11e4-4464-bb81-d51eefa4ba68.png)

**Comment by jshaughn** [comment] 2022-07-26 18:34
@josunect The reason the cluster boxing option had no effect is that you only have one cluster, and we don't add boxes when there is only one option.  Having said that, I'm not sure why `(cluster-default)` is present on your namespace box.  Like the original screenshot from Lucas, I don't see the same thing.  I'm not sure why you are seeing the cluster name unless you truly have multiple clusters in play.

**Comment by josunect** [comment] 2022-07-27 07:13
Sure, we can have a video call to share this view.
 
Thanks, @jshaughn

**Comment by jshaughn** [comment] 2022-07-28 13:47
OK, thanks @josunect , that was a useful call because it confirms that we do in fact have different behavior. In your, and presumably Lucas'  env, you are missing the server config indicating the configured home cluster.  As such, the client code assumes your cluster name is the Istio default, "Kubernetes".  But the Istio telemetry is correctly using the configured cluster name, "cluster-default", which is the default cluster name when installing via the hack script.  As such, in your env the graph code basically thinks all of the traffic is on a different, non-home cluster, and therefore is appending the cluster classifier on the labels.

You should see something like this in the debug info:

```
"computedServerConfig": {
      "clusters": {
        "cluster-default": {
          "apiEndpoint": "https://10.96.0.1:443",
          "isKialiHome": true,
          "isGatewayToNamespace": false,
          "kialiInstances": [
            {
              "serviceName": "kiali",
              "namespace": "istio-system",
              "operatorResource": "kiali-operator/kiali",
              "url": "",
              "version": "dev"
            }
          ],
          "name": "cluster-default",
          "network": "network-default",
          "secretName": ""
        }
      },
```

But you don't.   I think your theory is a good one, that running the server outside of the cluster for dev purposes, via the run-kiali.sh hack script, results in this behavior.   If your test proves your theory, we may have to see if there is a  way to resolve the issue with the hack script.

The correct behavior will show something like this:

![image](https://user-images.githubusercontent.com/2104052/181521069-a5ff3144-9145-4b5b-9694-3b1aa7fff29a.png)

**Comment by josunect** [comment] 2022-07-28 14:39
I've just tested installing Kiali inside the cluster, I can see the same behavior than @jshaughn : 

![image](https://user-images.githubusercontent.com/49480155/181557782-28fa4538-8743-45fb-8730-3351e8725b08.png)

**Comment by jshaughn** [comment] 2022-07-28 15:13
OK, great, so we just need to figure out how to get users of `run-kiali.sh` to work as expected.

One workaround, which would be fine as long as you aren't really trying to test a multi-cluster environment, is to install Istio with the default cluster-name.  If using the `install-istio-via-istioctl.sh` hack-script, instead of:

`> install-istio-via-istioctl.sh -c kubectl`

do:

`> install-istio-via-istioctl.sh -c kubectl -cn "" -mid "" -net "" `

That will use all istio defaults, which will match any defaults we have in the code.

**Comment by josunect** [comment] 2022-07-28 15:59
Thanks, @jshaughn ! I have tested but it didn't work :( 

But when I run kiali inside the cluster I think is using the same istio instance, right? 

I was trying to debug business/mesh.go:

`clusterName, ok := secret.Annotations["networking.istio.io/cluster"]`

But for some reason it doesn't look to reach that line. 

I've found the following line, though: 

`2022-07-28T16:38:16+01:00 WRN Failed to fetch Kiali token when resolving cluster info: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`

So it looks related to the issue? 

I will keep looking at this.

**Comment by jshaughn** [comment] 2022-07-28 16:03
Hmm, I thought that workaround would work, did you see the same issue but with the label `(kubernetes)` instead of `(cluster-default`)?

Anyway, that warning seems related, cc'ing @jmazzitelli for any ideas here.

**Comment by jmazzitelli** [comment] 2022-07-28 16:23
> 2022-07-28T16:38:16+01:00 WRN Failed to fetch Kiali token when resolving cluster info: open
> /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

That's most likely because you started run-kiali.sh with `-kc current`. If you require the same permissions as a "real" kiali, don't use that option. See the `--help` on that option: https://github.com/kiali/kiali/blob/master/hack/run-kiali.sh#L165-L180

You can see what that option does here: https://github.com/kiali/kiali/blob/master/hack/run-kiali.sh#L549-L575

BTW: We will probably have to update this part of the script soon - OpenShift will soon no longer create these secrets as part of the service account. We'll probably have to do something differently when that happens.

**Comment by josunect** [comment] 2022-07-28 16:29
> Hmm, I thought that workaround would work, did you see the same issue but with the label `(kubernetes)` instead of `(cluster-default`)?
> 
> Anyway, that warning seems related, cc'ing @jmazzitelli for any ideas here.

I see this is still empty: 

![image](https://user-images.githubusercontent.com/49480155/181590074-d4d15958-539a-4809-8487-833fcf1ae5cd.png)

**Comment by josunect** [comment] 2022-07-28 16:32
> > 2022-07-28T16:38:16+01:00 WRN Failed to fetch Kiali token when resolving cluster info: open
> > /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
> 
> That's most likely because you started run-kiali.sh with `-kc current`. If you require the same permissions as a "real" kiali, don't use that option. See the `--help` on that option: https://github.com/kiali/kiali/blob/master/hack/run-kiali.sh#L165-L180
> 
> You can see what that option does here: https://github.com/kiali/kiali/blob/master/hack/run-kiali.sh#L549-L575
> 
> BTW: We will probably have to update this part of the script soon - OpenShift will soon no longer create these secrets as part of the service account. We'll probably have to do something differently when that happens.

That's right! I'm using --kube-context current
I'll review that option.

**Comment by jshaughn** [comment] 2022-07-28 16:54
>  see this is still empty:

Yes, that is expected when you set the cluster-name to the default value.  In that case Kiali assumes a single-cluster installation.  The question is whether you still see the unwanted cluster-name in the graph.

**Comment by josunect** [comment] 2022-07-29 08:00
> > see this is still empty:
> 
> Yes, that is expected when you set the cluster-name to the default value. In that case Kiali assumes a single-cluster installation. The question is whether you still see the unwanted cluster-name in the graph labels.

It looks like I don't see the cluster-name in the graph labels, installing Istio with that options: 

![image](https://user-images.githubusercontent.com/49480155/181712841-2303b2f2-4ed3-42dc-b7a8-c507974ad0cd.png)

**Comment by josunect** [comment] 2022-07-29 11:48
I finally get the same results, running Kiali in dev mode, outside the cluster: 

![image](https://user-images.githubusercontent.com/49480155/181748037-668be5a6-8f33-45c8-bf5c-dd10e8d96ea3.png)

Steps for the installation: 

1. minikube start
2. ./install-istio-via-istioctl.sh -c kubectl
3. ./install-bookinfo-demo.sh -c kubectl
4. Install kiali: kubectl apply -f _output/istio-1.14.1/samples/addons/kiali.yaml
5. ./run-kiali.sh -pg 13000:3000 -pp 19090:9090 -app 8080 -es false -iu http://127.0.0.1:15014 -ke ~/go/bin
6. Run Kiali in the IDE

This is what confused me a bit (Maybe I'm doing something wrong), kiali needs to be installed in the cluster in order to run kiali in development mode, outside the cluster: 
- I'm using run_kiali to just port forward the services needed by kiali - starting with option -es false
- But, i receive the message "ERROR: Cannot get the service account name. Kiali must be deployed in [istio-system]. If you do not want to deploy Kiali in the cluster, use '--kube-context current'" 
- with the current context it looks like the cluster name is empty (Explained by @jmazzitelli )
- I don't need to specify the "kube-context current" after step 4

**Comment by jmazzitelli** [comment] 2022-07-29 14:32
> kiali needs to be installed in the cluster in order to run kiali in development mode, outside the cluster:

It doesn't "need" to be - but for some things you do need it. `-kc current` allows you to quickly run Kiali outside the cluster without first installing it inside the cluster - this is very useful for most things because most times you don't need that service account/secret - you can just run with the credentials that you have via "kubectl" context. However, in some cases, you need to test things running with the same credentials as the kiali service account (if you are testing permissions-related features).

**Comment by josunect** [comment] 2022-07-29 14:46
> > kiali needs to be installed in the cluster in order to run kiali in development mode, outside the cluster:
> 
> It doesn't "need" to be - but for some things you do need it. `-kc current` allows you to quickly run Kiali outside the cluster without first installing it inside the cluster - this is very useful for most things because most times you don't need that service account/secret - you can just run with the credentials that you have via "kubectl" context. However, in some cases, you need to test things running with the same credentials as the kiali service account (if you are testing permissions-related features).

Thanks for clarifying, @jmazzitelli

**Comment by jmazzitelli** [comment] 2022-07-29 14:54
@josunect there may be other edge cases where you simply can't run kiali outside the cluster and see some things work. I can't think of such a case, but it would not surprise me if that happens. For example, if Kiali needs to connect to some other service in the cluster (say, some Istio service) and that service is NOT accessible from outside the cluster, then this won't work and you need to test with kiali running inside the cluster.

**Comment by jshaughn** [comment] 2022-08-03 15:35
@jmazzitelli @josunect @lucasponce , I think this has been explained and the dev-env workaround presented.  Any reason not to close this?

**Comment by lucasponce** [comment] 2022-08-04 09:19
I'm reading this thread, but I think several things are being discussed in parallel.

What flag/config would need the kiali app not to show these cluster names? 
Let's not jump on the hack scripts used, just that the process would need. Then, any dev environment could easily mimic this without entering into the discussion if installing Kiali inside or outside the cluster is good.

**Comment by josunect** [comment] 2022-08-04 10:31
> I'm reading this thread, but I think several things are being discussed in parallel.
> 
> What flag/config would need the kiali app not to show these cluster names? Let's not jump on the hack scripts used, just that the process would need. Then, any dev environment could easily mimic this without entering into the discussion if installing Kiali inside or outside the cluster is good.

Well, in both setups, if I have the cluster name or not due to different hack script configurations, the "Cluster Boxes" option is not making any change in the graph, I don't know if there is any other option for that, but, I would expect some change with that check.

**Comment by lucasponce** [comment] 2022-08-04 11:09
I wouldn't expect anything complex on this, I understand that the deployment inside the cluster is good, but for other scenarios, I'd expect a flag to pass to that setup to simulate the same scenario.

For example, the global "in_cluster: false" in the config is used for those cases, if the cluster name needs some edge based in that condition to receive a flag, that would be good.

I don't think we should install Kiali in the cluster for this, my suggestion is to track where this name comes and under "in_cluster: false" presence to populate with some config that makes sense.

**Comment by jshaughn** [comment] 2022-09-15 20:20
The easiest solution here is that when working in a single-cluster environment, with kiali outsode of the cluster, don't install with a non-default cluster name.  The easiest way to make that happen is for our `install-istio-via-istioctl.sh` hack script to set the defaults like `-cn "" -mid "" -net ""`.  I'll make that change.

**Closed** 2022-09-16 13:25 UTC
Labels: enhancement, backlog
