### ISSUE TITLE
Documentation doesn't show how to configure Kiali

### ISSUE THREAD

**Issue by fabricetriboix** [kiali/kiali#3858] opened 2021-04-11 10:26 UTC
The documentation available [here](https://kiali.io/documentation/latest/) does not clearly explain how to configure Kiali, especially how to tell Kiali where the various services (Prometheus, Istio, etc.) are.

**Comment by jmazzitelli** [comment] 2021-04-11 12:24
We probably should have something on kiali.io that talks about the documented kiali CR yaml - that's where all the docs you want are located. See: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml

**Comment by fabricetriboix** [comment] 2021-04-12 06:24
@jmazzitelli Can Kiali run outside a Kubernetes cluster? If yes, how it is configured should be documented, not just how to use the operator.

**Comment by lucasponce** [comment] 2021-04-12 06:44
+1 Adding back the "bug" label.

The Kiali CR YAML shouldn't be the documentation reference for users.

There are features and scenarios that are not well covered in the kiali.io and user requires to browse and understand the details in the CR.

**Comment by jmazzitelli** [comment] 2021-04-12 12:18
> Can Kiali run outside a Kubernetes cluster?

No.

**Comment by jmazzitelli** [comment] 2021-05-13 15:07
Just noticed this is a duplicate of this: https://github.com/kiali/kiali/issues/3148
We should close one or the other.

**Comment by xeviknal** [comment] 2021-06-21 10:54
What about a `welcome wizzard / form` guiding users to fill the settings according to their environment?
Like:
"Which namespaces are part of the mesh?"
"Jaeger: tell me the in_service_url, the external_url, the namespace..."
"Prom: same same"
Finish -> this is the suggested kiali CR (and showing the yaml or editing the current CR).

**Comment by fabricetriboix** [comment] 2021-06-21 10:57
Hi @xeviknal ,

I would much prefer comprehensive and accurate documentation over a wizard.

Cheers

**Comment by lucasponce** [comment] 2021-06-21 11:00
Yes, I think this is a documentation issue focused on the CR, I don't think Kiali should offer this kind of wizard for a configuration aspect.

(Perhaps the CR could have some "status" to indicate if something is missing)

**Comment by jmazzitelli** [comment] 2021-06-21 12:05
> (Perhaps the CR could have some "status" to indicate if something is missing)

It actually does have that - if the operator fails to install, the status field will have some things in there to tell you what went wrong. Take a look at your current Kiali CR you may have deployed already and look at "status" field and you'll see the kind of things in there already.

**Comment by lucasponce** [comment] 2021-08-10 12:57
The main issue https://github.com/kiali/kiali/issues/4118 should reflect this request

**Comment by jmazzitelli** [comment] 2021-08-20 19:22
We should consider having something that can process the example CR yaml and automatically produce some .adoc document that we can then publish on kiali.io. Something like swagger for the CR yaml.

**Comment by jshaughn** [comment] 2021-11-12 21:08
Update:  There has already been a lot of improvement here.  There is still some work being done.  It should be completed fairly soon.

**Closed** 2021-11-18 18:11 UTC
Labels: bug, docs, backlog
