### ISSUE TITLE
custom duration components poorly laid out on screen

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3370] opened 2020-10-28 19:13 UTC
![image](https://user-images.githubusercontent.com/2029470/97485075-051f6400-1930-11eb-8feb-e9385efc2cf6.png)

**Comment by jshaughn** [comment] 2020-10-28 19:32
Duplicate of https://github.com/kiali/kiali/issues/3350

**Closed by jshaughn** 2020-10-28 19:32 UTC
Labels: bug
