### ISSUE TITLE
Sorry, there was a problem. Try a refresh or navigate to a different page. - with Show full graph

### ISSUE THREAD

**Issue by cucxabong** [kiali/kiali#3916] opened 2021-04-21 02:55 UTC
**Describe the bug**

I see a page with 'Sorry, there was a problem. Try a refresh or navigate to a different page' when clicking on 'Show full graph' from application details page. After a browser refresh, the error disappear and page loaded correctly

For UI issues please also add a screenshot that shows the
<img width="1437" alt="Screen Shot 2021-04-21 at 9 42 20 AM" src="https://user-images.githubusercontent.com/6996229/115489582-9c81c600-a286-11eb-8767-5c49e8f314ef.png">

**Versions used**
Kiali: v1.33.0
Istio: v1.8.1
Kubernetes flavour and version: EKS v1.19.6

**To Reproduce**

1.  Click 'Application' on the left
2. Click on any service
3. At 'Graph Overview' click on '...' => 'Show full graph'
4. ... and see error

**Expected behavior**

Show full application graph without errors

**Comment by lucasponce** [comment] 2021-04-21 06:59
Thanks @cucxabong I guess it's same blocker issue as reported here https://github.com/kiali/kiali/issues/3913

There is a PR that we'll test today and we plan to release soon to avoid this in the kiali 1.33.x branch.

**Comment by jshaughn** [comment] 2021-04-21 17:37
@cucxabong Kiali v1.33.1 has been released, please see if it resolves your issue.    Closing this as a duplicate of #3913.  If your problem persists please feel free to re-open this issues.

**Closed by jshaughn** 2021-04-21 17:37 UTC
Labels: bug

**Comment by cucxabong** [comment] 2021-04-22 07:30
Thank you for your quick reponses. I have deployed kiali 1.33.1 but the problem still persist. Think this issue is differ from #3913

**Comment by lucasponce** [comment] 2021-04-22 07:44
Thanks for the update @cucxabong, glad it worked.
