### ISSUE TITLE
2 DRs to same host with different formats - No Warning

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1892] opened 2019-11-06 17:39 UTC
When 2 Destination rules referring to the same host, one in a format of servicename, second in serviename.namespace.
DR1 host: reviews
DR2 host: reviews.bookinfo
Both refer to the same host in the same namespace, but the warning message "More than one Destination Rule ..." is not displayed.

**Comment by xeviknal** [comment] 2019-11-21 12:42
This error is related to: https://github.com/kiali/kiali/issues/1884

I am having problems to reproduce the scenario where Istio generated a Destination Rule using the format "grafana.istio-system".

I have installed Istio-1.4 following the getting started (without mTLS by default) + the bookinfo scenario. I only see there the issue with: https://github.com/kiali/kiali/issues/1891

IMO, we shouldn't fix this issue if we can't reproduce this error. And if we can, we should open a bug in istio repo fixing it. As discusses with @burmanm, this format is not documented officially in the docs. On the contrary, they strongly recommend to use FQDN.

@lucasponce do you recall where did you find that scenario?

**Comment by xeviknal** [comment] 2019-12-11 16:03
What do you think of adding this FAQ for covering the odd of this format?
https://github.com/kiali/kiali.io/pull/187

If we want to be really precise and not give false positives, it is much better not to fully support the `sevice.namespace` format. IMO, opening the box of resolving names to guess if hosts are internal or external is not worth it.

**Comment by burmanm** [comment] 2019-12-11 17:40
Shouldn't external hosts be ServiceEntries in any case? Thus, if it's a two part (dot split) hostname, we know it must target a SE or otherwise it's a service.namespace format.

**Closed** 2019-12-20 09:37 UTC
Labels: backlog, bug, team/jupiter
