### ISSUE TITLE
Unify style attribute for config validation icons

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#1952] opened 2019-11-19 12:52 UTC
Success, warning and fail icons for config validation on Istio config page use different ways to define style attribute:
style="color: rgb(62, 134, 53);"
style="color:var(--pf-global--warning-color--100);"
and fail icon does not have style attribute at all.

It would be nice to use --pf-global... vars for all icons as it would be easier to locate elements in UI automation.
 

![screenShot](https://user-images.githubusercontent.com/328182/69148034-aae91280-0ad3-11ea-857e-b82d7140efdb.png)

**Comment by FilipB** [comment] 2019-11-19 13:25
Checked the latest UI (837d0a7d25e69b2f8cbeefaf41134421ea92dd33) and the fail icon now also uses variable: style="color:var(--pf-global--danger-color--100);"
So only one which is not unified is the success icon now.

**Comment by jshaughn** [comment] 2019-11-21 16:07
@FilipB The issue is that the variable --pf-global--success-color--100 is set to light-green-400 in patternfly.  This is not the color that UX wants us to use for success, both for graph edges and alert messages.  We have a custom color to use instead ('#3e8635').  I was under the impression that Patternfly was going to be updated to make this the new success color, but I just checked master and it has not been changed.  We do want to use a variable but we need those variables to be correct.

I think this can be closed but I will add the "Waiting" label if you want to leave it open.  We can follow-up with UX (cc @serenamarie125).

**Comment by FilipB** [comment] 2019-11-22 09:55
@jshaughn Thanks for update. Is it possible to define our own variable instead of using "color: rgb(62, 134, 53);" directly? From UI automation point of view it's better to use variables instead of "color: rgb(62, 134, 53);" as a locator. Any change to "color: rgb(62, 134, 53);" and test will be broken...

**Comment by jshaughn** [comment] 2019-11-22 13:00
@FilipB I'm not actually sure, but I can look into adding maybe a "kiali-success" variable that later could be reset to the updated PF variable, when it isupdated.

**Comment by FilipB** [comment] 2019-11-25 09:28
@jshaughn Adding our own variable or waiting for fix on PF are both fine. Waiting is maybe better as it's not adding extra work.

**Comment by jshaughn** [comment] 2019-12-02 16:58
@FilipB This has been elevated to UX, who in turn is creating a PF issue to get the color variables updated.  I think we can wait and when updated in PF we'll move to the PF variable.

**Comment by FilipB** [comment] 2019-12-02 17:13
@jshaughn Sounds good, thanks.

**Comment by jshaughn** [comment] 2021-02-15 19:57
It's possible that PF has fixed the problem and we can use the standard variables.  Removing the Waiting label and adding to backlog to see if we can move forward.

**Comment by lucasponce** [comment] 2021-06-30 09:52
This task is in the backlog for quite some time, I'm going to see if it's still valid or prepare a fix.

**Comment by lucasponce** [comment] 2021-06-30 10:12
Ok, I see that there is some changes on this side:

![image](https://user-images.githubusercontent.com/1662329/123943321-5474d300-d99c-11eb-9d16-6b9afd99ead6.png)

All styles are centralized with the exception of the 'Success' due the comment in the code below.

I guess we can close this one, we can open a new one for any other automation comment.

**Closed by lucasponce** 2021-06-30 10:12 UTC
Labels: backlog, maintenance
