### ISSUE TITLE
Possible flaky test in CI

### ISSUE THREAD

**Issue by leandroberetta** [kiali/kiali#5817] opened 2023-02-07 14:09 UTC
Results: https://github.com/kiali/kiali/actions/runs/4114402313/jobs/7101859788
```
  Running:  istio_config_validation_filters.feature                                       (13 of 30)


  Kiali Istio Config page
    ✓ Filters should be available in the dropdown (2453ms)
    ✓ Single filter should be usable (1650ms)
    ✓ Filter should be deletable (1636ms)
    ✓ Deleting all filters at once (1604ms)
    ✓ When 4 or more filters are chosen, only 3 are visible right away (2480ms)
    1) "after each" hook for "Show the view of all chosen filters"
```

**Comment by ScriptingShrimp** [comment] 2023-03-29 14:06
I'm currently unable to reproduce the issue locally or in CI running on OCP. Lets wait for a while if the fake will occur again. If not, we can close this issue.

**Comment by jshaughn** [comment] 2023-04-04 13:06
I have not seen this.

**Comment by ScriptingShrimp** [comment] 2023-04-05 11:59
Did not notice even in upstream pipeline on OCP.

**Comment by jshaughn** [comment] 2023-04-05 12:52
Closing as "Can't reproduce".

**Closed by jshaughn** 2023-04-05 12:52 UTC
Labels: bug, backlog, test-cypress :robot:
