### ISSUE TITLE
Performance issues with the Kiali UI

### ISSUE THREAD

**Issue by RaiAnandKr** [kiali/kiali#5867] opened 2023-02-21 18:27 UTC
Hey folks, apologies in advance for the large set of points/questions below (some of it are vague as well) but I wanted to talk about the general slowness with the Kiali UI

So, I have been exploring Istio + kiali for our k8s cluster since the last few months and I have grown to like Kiali a lot, especially all the integrations provided via the UI. I am slowly exposing this UI to more developers at my workplace and the feedback from them is mostly along the lines of `pretty neat integrations but the UI is a bit clunky`.  I might be a bit biased towards Kiali since I have been using it for few months now and might have gotten used to a bit of slowness on the UI but post those feedbacks I wanted to explore this angle more.

Here are few observations from our kiali and k8s setup:

1. Does Kiali not expose any performance metrics? I couldn't find anything in the docs. It would be so useful in monitoring the performance of our kiali deployment as well as share those standard metrics here to report any slowness.

2. To be clear, it's not a big slowness and maybe what I am seeing is expected. In loading the app or versioned app graph for e.g. the UI almost always takes 6-8s. More than half of the time is spent in this one API call: `https://kiali.dev.corp.arista.io/kiali/api/namespaces/graph?duration=300s&graphType=app...` (to be fair, that's the main API call anyway). Attached the network activity for one of the graph refresh

![Screenshot 2023-02-21 at 11 21 20 PM](https://user-images.githubusercontent.com/21973868/220422902-72c9cbd6-9724-4fea-8e87-39d81bfedece.png)

3. Loading the list of `Applications` takes anywhere between 4-6s and more than half of the time is spent in calculating the health of those apps. Attached is network activity for that
![Screenshot 2023-02-21 at 11 26 49 PM](https://user-images.githubusercontent.com/21973868/220423754-d72fd8f0-ec60-4831-b0d4-9681f2c07161.png)

4. We have around 1k services and 4k pods in our cluster.

I have already assessed the health of our prometheus setup via its own UI and even the k8s API server and they all look fine (the native k8s dashboard loads so much faster indicating not much issue with the k8s server).

So here are few of my questions:
1.  Are these numbers expected probably because of the cluster size? Do they not look totally off to you? The devs would have done some performance benchmarking for sure but I couldn't find any benchmarks in the Kiali docs. I totally believe that having those benchmarks available can help set/reset expectations around performance among the users.

2. As I said, I don't think the underlying prometheus and k8s server is contributing much to slowness. Is there anything else I should be checking to see if it could be contributing to the slowness? Do we have some sort of checklist an user can run through to tune the performance of Kiali or help explain the performance at least.

3. This is more of a personal preference and a very specific opinion so feel free to discard it but I think one way to make the UI feel more slick could be to load as minimal info as possible by default. To give an example, should we be computing the health by default if I am loading the `Applications` page? A lot of the times I would further just click on that one app which I manage, to look into it and hence the health information of all the apps is not useful to me. Perhaps then we show it only if users click on some `expand` button which is expected to be slow. So, some of the workflow might require two clicks then but that makes the default state so much faster without loosing much info for most of the use cases. Maybe this feature can be controlled by a knob so that users can make a choice on if they want to see `health` by default or prefer the other way round.

4. Is performance/scalibility something which the developers are focussing on internally "right now" or do we think that we are mostly fine? I ask this because we are totally open to contributing to Kiali if the devs have identified  issues/changes which can improve the performance and they could use any help with bandwidth :)

Thank you for bearing with me. 

As I said, I have been running Kiali for few months now, so I have tried/tested and observed this across different versions (3 to be precise) and hence I am mostly sure that this is not something version specific.

**Comment by jmazzitelli** [comment] 2023-02-21 18:35
1. Kiali does expose metrics. Look at the Kiali app inside Kiali itself.. there should be a tab Internal Metrics or something like that. The config is here: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.server.observability.metrics
2.  A few sprints ago we did concentrate on perf issues. That work was completed. But of course if Kiali can be made with even better performance, the kiali team is all ears.
3. Yes, large environments like yours would likely cause some slowness. How many namespaces? The number of namespaces has a real effect on Kiali performance.

**Comment by jmazzitelli** [comment] 2023-02-21 18:55
> neat. Do you think we should have a dedicated section in the docs on this (excuse me if it's already there) rather than needing to grok through the list of configs in Kiali CR?

Could probably be useful to have something [here](https://kiali.io/docs/features/details/#built-in-dash), with the rest of the built-in dashboards (the Kiali metric dashboard is just one of the built-in dashboards).

**Comment by jshaughn** [comment] 2023-02-21 20:03
Hi @RaiAnandKr.  First, thanks so much for taking the time to write up this feedback.  It's rare to get good feedback and much-appreciated.  I'll make a first pass at some answers but I expect there will be a lot of back-and-forth, and other people adding comments.

@jmazzitelli already makes good points above, I'll duplicate a little of what he says and try adding a bit more...

First, make sure you're not running one of the recent versions with the perf regression.  That's probably not your issue because you have been working with Kiali for a while, but just to make sure (1.62.0, 1.63.0. 1.63.1 are bad).

> Does Kiali not expose any performance metrics? I couldn't find anything in the docs. It would be so useful in monitoring the performance of our kiali deployment as well as share those standard metrics here to report any slowness.

Kiali does collect some metrics although it's not super-extensive and is only timing things in the back-end, so not really looking at issues in the client or interactions between the client and server.  If you navigate to the Kiali workload detail, typically in istio-system or the control-plan namespace, you should see some an additional Tab for `Kiali Internal Metrics`, which will offer some charts and maybe some insight.

>  More than half of the time is spent in this one API call: https://kiali.dev.corp.arista.io/kiali/api/namespaces/graph?duration=300s&graphType=app... (to be fair, that's the main API call anyway).

Graph generation is intensive and it's affected by a lot of things.  It interacts heavily with Prometheus, k8s and istio.  You;ve already said your Prometheus and K8s APIs seems to be responding well but certainly if your Prometheus is overloaded it will affect graph generation (and charts, etc).  Make sure you dedicate enough resources. Also, see https://kiali.io/docs/configuration/p8s-jaeger-grafana/prometheus/#prometheus-tuning for a few tips.

The number of namespaces *selected* (not necessarily the total number of namespaces you have in your mesh) when generating the graph is important.  In short, you end up generating a graph for each and then those graphs get "stitched" together.

> Is performance/scalability something which the developers are focussing on internally "right now" or do we think that we are mostly fine?

To be honest, it's not a current focus.  We actually went through a large period of scale and perf enhancements  in latter 2021 and about half way into 2022.  Both in speed and the ability to visualize large meshes (our internal target is about 100-200 namespaces and 1000-5000 services, although we don't really publish anything about scale goals because there are such huge differences in the way people deploy).

One thing we are considering is moving Kiali from a real-time system to a near-real-time system, basically precomputing almost everything and making the client a fairly thin presentation layer (and likely asking for more resources in the backend).  But this is likely not happening in this calendar year.

Some options will increase the graph generation time because it has to do extra work.  Things like response-time edge labels, the Display Security option, and a few other things.

The Traffic dropdown can speed things up by letting you eliminate TCP or HTTP traffic, for example.

The Duration dropdown is also important, the larger the time period the more date being aggregated.

Of course, sometimes it will just take time, if you have a lot of services and a lot of traffic there are just a lot of metrics to deal with.  Istio reports traffic metrics from both the source and destination proxies, this reporting has to be queried, merged, etc...

> ...I think one way to make the UI feel more slick could be to load as minimal info as possible by default.

We primarily think of Kiali as a tool for identifying issues in your mesh, and a little less as a general console.  And so we historically give health info, validations, misconfigurations a high priority, usually eating that expense.  Of course we are always looking for ways to improve, and also we don't always know what's slow for different users.  That's what's important about your feedback.  Your suggestion is good, we can maybe look at adding more knobs and more ability to set ui-defaults in the configuration.  So, for example, the default for a health knob may be `On`, but for your install perhaps the default could be configured to be `Off`.

**Comment by jmazzitelli** [comment] 2023-02-22 13:46
> > Could probably be useful to have something [here](https://kiali.io/docs/features/details/#built-in-dash), with the rest of the built-in dashboards (the Kiali metric dashboard is just one of the built-in dashboards).
> 
> This makes a lot of sense. Should I open a different issue to track that specific change?

Yes. Open a different issue and label it as "doc" "enhancement"

> So I enabled the Kiali's own metrics collection and I can see metrics in my prometheus UI but the charts on Kiali show nothing.
...
> Note that I can see metrics and traces for all other apps on Kiali so I am not sure what's special about kiali own metrics/traces. It should be query the usual prometheus and jaeger endpoint configured via external_services, right?

Hmm. That is strange. Obviously, you should be seeing the metrics/traces there. Nothing special. I'll take a look at that and see if I can find out if there is a problem.

**Comment by jmazzitelli** [comment] 2023-02-22 14:42
I'm seeing the metrics fine, in both appliation and workload view:
![image](https://user-images.githubusercontent.com/2029470/220651683-e9a39d6b-529f-4e06-b29e-d62a32504df3.png)

![image](https://user-images.githubusercontent.com/2029470/220652049-863dabe5-c6c7-4d46-89ac-88a2f0583a97.png)

**Comment by jshaughn** [comment] 2023-02-23 14:59
I also can not reproduce the charting issue for `Kiali Internal Metrics`.  Not sure what is happening there, although those charts are not particulalry useful to determining where a specific slowness may be happening in graph generation.  You could try to see if you could determine more from the prom metrics themselves. `kiali_graph_appender_duration_seconds_sum` can indicate if there is a specific appender taking a bulk of time, and `kiali_graph_generation_duration_seconds_sum / kiali_graph_generation_duration_seconds_count` can show you avg times for graph gen as a whole.

**Comment by jmazzitelli** [comment] 2023-02-23 15:13
Right .. as jay infers, we don't expose every metric that kiali emits in those Internal Metrics tab in the UI - only the more basic ones. The metrics in prometheus might show you something - there are graph generation related metrics in there as jay shows (the appenders metrics is an important one).

**Comment by jshaughn** [comment] 2023-02-24 16:11
Given the Prom query response times I'm guessing the slowness is more related to the interactions with k8s, when appending information.  Look at that `kiali_graph_appender_duration_seconds_sum` metric more carefully, especially the `istio` appender times.

**Comment by jshaughn** [comment] 2023-02-27 21:08
I'm not exactly sure what to recommend at the moment.  It seems true that the `istio` appender is one reason for the slowness.  This appender queries k8s but the information is typically cached and it should not result in a major hold up most of the time (unless we have a caching issue).  For what it's worth, this appender decorates the graph with a variety of information that we get from the configuration, it's what detects virtual services, circuit breakers, gateways, etc.   I'm not exactly sure where the other 2s is spent.  I'm a little curious what you would see if you took the appenders out of the equation.

In your browser or from a command line try (this may work as-is only if you are using anonymous auth):

This one has the appenders:

`http://YOURHOST:YOURPORT/kiali/api/namespaces/graph?duration=600s&graphType=workload&appenders=deadNode,istio,serviceEntry,sidecarsCheck,workloadEntry,health&namespaces=YOURNAMESPACE`

This one does not:

`http://YOURHOST:YOURPORT/kiali/api/namespaces/graph?duration=600s&graphType=workload&appenders=&namespaces=YOURNAMESPACE`

The second one should only interact with prometheus.

**Comment by jshaughn** [comment] 2023-03-13 17:35
Hi @RaiAnandKr , any more feedback?

**Comment by jshaughn** [comment] 2023-03-22 21:14
This is a fairly broad issue that touches on several points.  Initially I'm just going to look at possibly offering a few "knobs" for controlling whether the list views can optionally pull some of the information that can be time-intensive.  This would at least allow users that mainly want to use the list view for "inventory", and not necessarily as a dashboard for say, health or validations, can do so efficiently, deferring to the detail pages for more complete information.

**Closed** 2023-04-11 16:16 UTC
Labels: bug, backlog

**Comment by jshaughn** [comment] 2023-04-11 17:50
@RaiAnandKr , sorry for the slow response, it doesn't mean we're not interested, just busy.  We will look more closely into the calls you have identified and see if we can better understand those slow times.

On the bright side, I just merged the changes for the configurable lists, hopefully it helps with your issue.  It will be in v1.67, and in the Kiali CR you will be able to configure things under `spec.kiali_feature_flags.ui_defaults.list`, toggling off various data/columns.

That merge closed this issue.  It would be best to to continue in a new issue.  Would you mind creating a new issue, it can refer back to this one, with the content of you most recent comment about the slow calls?

**Comment by jshaughn** [comment] 2023-09-11 18:22
@RaiAnandKr , Not sure if you are still active with Kiali but a couple of comments about the two API calls you singled out above:

> `api/mesh/tls` always takes 1-2s and it returns just

There have been a variety of changes in the logic that may have affected/improved performance.

> `api/istio/status` always takes 0.5-1s. and in my case returns

This call can take time and takes longer if a component is actually down, or is slow to respond.  A current workaround is to disable those component checks by setting in the Kiali CR:

 `.spec.external_services.istio.component_status.enabled: false` 

But, both of these API calls support information in the masthead and are made on any refresh, a graph update or almost anything else as well.   I think we can make some improvements here but I don't think the response times of these API calls should actually be affecting your graph update.  Those results should arrive independently.  We may actually be removing that information from the masthead in the near future, and moving it to a more rich, "Mesh" page, that details your control plane(s), clusters etc.

If you are still using Kiali, and can try a recent version, it would be great if you could again baseline some of your perf numbers, as there have been large changes in the code, including caching, as we have restructured things for multi-cluster support.  Thanks!

**Comment by hhovsepy** [comment] 2024-07-11 07:03
@RaiAnandKr if you are still using Kiali, significant performance improvements have been made starting with Kiali v1.85. For more details, visit: [Kiali Performance FAQ](https://kiali.io/docs/faq/performance/)
