### ISSUE TITLE
kiali.io developer API page doesn't react to clicks or search

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3290] opened 2020-10-05 16:29 UTC
Click here: https://kiali.io/documentation/latest/developer-api/
Now click one (any one) of the left side API names (auth, integrations, config, status, etc).
Nothing happens. But the ">" makes it seem like there should be some menu or action to happen if I click it.

Now type something in the search box and press ENTER. Nothing happens.

**Comment by jmazzitelli** [comment] 2020-10-05 17:47
Clicking anywhere does nothing, now that I play with this page. Can't expand things, or do anything else.

**Comment by lucasponce** [comment] 2020-10-06 12:08
I guess we can re-open the discussion about this "Developer API" section.
I'll be clear, I don't like it.

Our Developer API is not public, it's only for consumption from the Kiali UI, I've been always against to publicity this.

In the other hand, if we want to keep documented the REST API perhaps we can change this a little bit, to put a note on Kiali.io that this API is "private" meaning that there is not guarantee of strong contracts between versions.

And instead to have this section that is causing a headache, perhaps just to let that travis update a swagger.json version in something "readable" but only published as a .md or asciidoc inside the repo and remove that section from the Kiali.io which is always broken and non well maintained with a note to that file.

It's funny, we don't have a proper Config section which probably is more useful and we redirect the user to the raw operator config but we maintain this whole section which is not intended to be used by users.

**Comment by jmazzitelli** [comment] 2020-10-06 18:13
> Our Developer API is not public

We should just get rid of this from kiali.io.

It is still useful to devs (I'm using it now) - so let's put this somewhere else.

**Comment by mtho11** [comment] 2020-10-06 19:09
So two things:

1. It should be removed from kiali.io (and added some other place because it is still useful)
2. It should get fixed. Since it is useful, it would be helpful to have it working.

**Comment by mtho11** [comment] 2020-10-06 19:10
I assume since we are removing from kiali.io that we would only keep the latest version around?

**Comment by lucasponce** [comment] 2020-10-07 08:03
I wonder if at same way travis update the swagger.json, if it can creates at same time some rest-api.adoc or rest-api.md with a nice format that can be easily render in github for the REST API.

That would meet a developer requeriment I think.

And we can use kiali.io to focus more on the user where there are some lacks (i.e. configuration to me is something with more priority, I don't think it's easy to find how to change a config parameter; yes, it's documented somehow but it's less obvious to me; but yes, that's out of the topic of this issue).

**Comment by aljesusg** [comment] 2020-10-07 08:22
> I wonder if at same way travis update the swagger.json, if it can creates at same time some rest-api.adoc or rest-api.md with a nice format that can be easily render in github for the REST API.
> 
> That would meet a developer requeriment I think.
> 
> And we can use kiali.io to focus more on the user where there are some lacks (i.e. configuration to me is something with more priority, I don't think it's easy to find how to change a config parameter; yes, it's documented somehow but it's less obvious to me; but yes, that's out of the topic of this issue).

I can confirm that we can do that and publish it in github pages under kiali/kiali with travis :)

**Comment by jshaughn** [comment] 2020-11-20 19:02
Closing as the dev api doc is removed from the web site.  Will open a new issue for the dev doc for gh.

**Closed by jshaughn** 2020-11-20 19:02 UTC
Labels: backlog, bug, docs, team/saturn
