### ISSUE TITLE
Services/versions are not removed from service graph if they don't exist

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#289] opened 2018-06-15 14:19 UTC
I have deployed https://github.com/redhat-developer-demos/istio-tutorial and Istio 0.7.1.

I followed the readme and deployed recommendation:v2 then I removed it but it was still shown on the service graph screen, even though the duration was last minute. 

![screenshot of kiali console](https://user-images.githubusercontent.com/5618424/41472696-799be1c4-70b7-11e8-80e0-f8ed31cd2db9.jpg)

**Comment by jshaughn** [comment] 2018-06-15 15:04
Hi @pavolloffay , you may be seeing the expected behavior depending on how you removed V2.  Did you scale down to 0 pods or did you completely remove the service definition?   If you have 0 pods the service will continue to appear.  If you removed the service it should be filtered away, although I'm not sure if there is any latency.  Also, the graph must get refreshed, either manually or via auto-refresh.  Let me know, thanks.

**Comment by jshaughn** [comment] 2018-06-15 15:46
Here is a more detailed explanation of what is happening.  It is expected behavior but it should improve going forward.  V2 no longer has any traffic because the pods are gone, but the recommendation service is still defined and Prometheus still has V2 time series in its database.  For the last minute the V2 TS shows no traffic.  The service is stilldefined in K8S and so the node still shows up in the graph.

Because there are no pods we actually have the V2 service flagged (in the backing data of the graph) as isDead=true.  But, we don't yet visualize that flag in the UI.  Something will be done going forward.

**Comment by jshaughn** [comment] 2018-06-15 15:47
I'll close this, let me know if something is not clear.

**Closed by jshaughn** 2018-06-15 15:47 UTC
