### ISSUE TITLE
How do we restrict the "Number of Namespaces" we select in Kiali UI - This can help in reducing the rogue query path

### ISSUE THREAD

**Issue by dinesh4747** [kiali/kiali#3186] opened 2020-09-08 11:47 UTC
Problem Statement:

While I select more than 5 namespaces - Kiali gets into hung state where it takes lot of time to render the service graphs across the cluster and we are running more than ~500 namespaces hence selecting more concurrent namespaces at the same time can crash the Kiali pods as well as Prometheus will stressed inadvertently

we would need to kind of avoid this by restricting on the UI to control only maximum of 5 namespaces which help my kiali pods stable and perhaps my prometheus will also stay healthy

**Comment by jmazzitelli** [comment] 2020-09-08 12:14
This question is being asked in multiple places. Please don't do that :)

This question was also posted verbatim here:
https://groups.google.com/u/1/g/kiali-dev/c/KJvuflQkd7k/m/NrVvbDnvAQAJ

and verbatim here:
https://groups.google.com/u/1/g/kiali-users/c/5EEveKsTIhE/m/6ml_aaVWAgAJ

It looks like the conversation is moving in the latter link. If an enhancement request comes out of it, we can resurrect this github issue. For now, I'm marking this as a "question" and closing.

**Comment by jshaughn** [comment] 2020-09-08 13:04
Although the issue is closed, that sort of load when selecting multiple namespaces is unexpected.  @dinesh4747, which version of Kiali are you running?

**Comment by jmazzitelli** [comment] 2020-09-08 13:22
> Although the issue is closed, that sort of load when selecting multiple namespaces is unexpected. @dinesh4747, which version of Kiali are you running?

There are three threads on this identical question. Let's keep it all together and not spread it out. The thread conversation is here, not in this github issue:

https://groups.google.com/u/1/g/kiali-users/c/5EEveKsTIhE/m/6ml_aaVWAgAJ

**Comment by lucasponce** [comment] 2020-09-08 13:25
I reopen it because I think context is different:

```
Hi

Problem Statment:

While I select more than 5 namespaces - Kiali gets into hung state where it takes lot of time to render the service graphs across the cluster and we are running more than ~500 namespaces hence selecting more concurrent namespaces at the same time can crash the Kiali pods as well as Prometheus will stressed inadvertently

we would need to kind of avoid this by restricting on the UI to control only maximum of 5 namespaces which help my kiali pods stable and perhaps my prometheus will also stay healthy

Thanks for the feedback, it's an opportunity to lean on high populated scenarios.

This sounds an enhancement, yes, there is currently no limitation in the # of namespaces you can select.

Actually, in the list pages by default you can select all.

Kubernetes info is cached, but I agree that then the most performance penalty would be the the p8s one.

Side note, have you tried to tweak the resources of Kiali pods ?

I'm curious when it starts to be impacted in your scenario.

Thanks for sharing it.
```

Scope is not to have only access to N namespaces.
How I understand is that Kiali can access N namespaces but from the UI can only select in the namespace selector a max of 5.

**Comment by dinesh4747** [comment] 2020-09-08 20:03
@jshaughn - we are currently using Kiali version - 1.18.1 (docker.io/kiali/kiali:v1.18.1) and not sure whether this version have any cache enabled as you are pointing out in the google group chat and how would I check on whether its enabled or not?

Let me know whether any sort of enhancements can be made to address this query path unstable issue with multiple namespaces 

@lucasponce - Hi Locus - Thanks for re-circling back the issue from Google groups and my apologies for creating multiple threads across the open forums. To answer your question we are running with 5 pods and below resource profile 

    Limits:
      cpu:     12
      memory:  12Gi
    Requests:
      cpu:      8
      memory:   8Gi

Just curious If kiali is Memory intensive and increasing the memory and enabling cache can solve the problem the that would be more than ideal

**Comment by nirvanagit** [comment] 2020-09-08 20:36
+ on the issue. Just to add, a similar graph in prometheus, loads data from the first namespace, which is automatically selected based on alphabetical order. 

Any of the tabs in kiali for e.g. workload, services loads data from all the workloads across all namespaces, which will definitely overwhelm the system

**Comment by lucasponce** [comment] 2020-09-09 07:27
> Any of the tabs in kiali for e.g. workload, services loads data from all the workloads across all namespaces, which will definitely overwhelm the system.

Kiali offers multi-namespace selection to easily detect / filter / sort applications by specific criteria.
i.e. "show me all unhealthy apps of my cluster"
i.e. "select the namespaces with problems"
i.e. "select the istio configurations with validations warnings/errors that may create undesired scenario"

I agree that when the population of namespaces is high then there is pressure on the pod.

One of the sources of the pressure is on kubernetes API and for that Kiali introduced caching:
https://github.com/kiali/kiali/tree/master/kubernetes/cache
https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L661

Namespace info is cached and most of the Kubernetes objects are watched instead of listed.

This design works just well. But, I think it can improved in high dense of namespaces.

Today one limitation of kubernetes API in general (that affects to any application like Kiali that is intended to use multi-namespace management) is the cluster role.

Kiali (as other similar apps) needs to cache per namespace, because to watch in the entire cluster needs cluster roles.

In your scenario, would be doable to grant Kiali with cluster roles ?

I'm just brainstorming, in that case, instead to have NxWatchers (which overloads the system) it could be reduced to 1xWatchers and probably that would help in terms of performance in high density clusters.

Also, limiting in the UI the # of selected namespace would help, but with the cost to miss some features (that probably would be ok in your scenarios).

In any case, we really appreciate the feedback @dinesh4747 @nirvanagit, as you can imagine is a challenge to test such grade of high level density cluster.

I may have some questions, if you can answer in an anonymous way:

- What is the average of the namespace in terms of services + workloads ?
- The design of the namespaces respond to the domain app or the teams ? I mean, a new namespace is created mostly to allow a different team to work on it, or the same team is working on all namespaces.
- Do you have some figures about when Kiali started to degrade ? Something like N namespaces worked well but with M it's unresponsive.

Probably the Kiali 1.23 and next 1.24 will have improvements in the caching, but no changes in the overall design, I'm curious if you may experiment some perf benefit.

**Comment by dinesh4747** [comment] 2020-09-10 15:57
@lucasponce - Does the Kiali cache comes as a feature only from V1.23 and higher versions of it. so if we upgrade to them we might internally enable namespace caching which would be expected to render service graph more faster  ?

**Comment by lucasponce** [comment] 2020-09-10 16:04
@dinesh4747 default configuration in Kiali v1.23 and higher for cache is enabled, so expectation is that Kiali should render faster, specially those scenarios that query kubernetes resources.

If you had a chance to experiment I'm curious if you get a difference or you scenario (+500 ns) is larger than probably we need to think in alternatives.

**Comment by dinesh4747** [comment] 2020-09-10 18:42
@lucasponce  - sure we are using istio-1.6 and need level check on whether 1.6 version would be compatible to upgrade with kiali v1.23

Just out of curiosity - could you please point out to the kiali cache PR or reference docs on how the cache had been implemented whether its via internal cache bounded with memcached/Redis or golang internal queue cache mechanism

**Comment by jshaughn** [comment] 2020-09-17 15:26
cc @lucasponce, waiting on your response here.   The caching mechanism has been in Kiali for a while but I believe it was turned on by default starting in Kiali v1.15.

**Comment by jotak** [comment] 2020-09-17 15:47
Also, Kiali exposes a couple of internal metrics that could be useful to better understand performance issues (they're expose in prometheus, prefixed "kiali_")

btw perhaps it would be nice to resurrect that task about having cache hits/miss metrics? https://github.com/kiali/kiali/issues/2476

**Comment by jotak** [comment] 2020-09-17 15:51
> Just out of curiosity - could you please point out to the kiali cache PR or reference docs on how the cache had been implemented whether its via internal cache bounded with memcached/Redis or golang internal queue cache mechanism

@dinesh4747 it's kubernetes-client cache (k8s.io/client-go/tools/cache), to be honest I don't know what it's using under the hood

**Comment by lucasponce** [comment] 2020-09-17 16:13
> Just out of curiosity - could you please point out to the kiali cache PR or reference docs on how the cache had been implemented whether its via internal cache bounded with memcached/Redis or golang internal queue cache mechanism

As @jotak it's part of the kubernetes client.

It's a memory cache per client, basically it implements a WATCH pattern with the resources, keeping in memory the namespace objects and reacting to updates.

In that way, when you query Workloads, Services or Istio resources, most of those objects are cached locally in memory of the Pod. The client allows to sync with the backend.

In short, the Pod benefits to reduce the calls to the Kubernetes API and the traffic, but at the cost to use more memory.

**Comment by dinesh4747** [comment] 2020-09-20 12:54
@lucasponce @jotak @jshaughn @jmazzitelli - Thanks for all the healthy discussion and I shall  work on latest version change and enable metrics to validate the changes

BTW, May it's a different scope of discussion but do we have any load test suite/tool for benchmarking Kiali or we have any Restful Kiali API which would enable to create some Jmeter or equivalent load test tool to scrutinize on how Kiali respond and benchmark under dense situations.

Also I beleive we might already have some channel of load testing with Kiali for benchmarking for every release @lucasponce

**Comment by lucasponce** [comment] 2020-09-21 07:02
Hi @dinesh4747 I'm cc-ing @FilipB as he worked in a suite testing for performance Kiali backend.

Not sure if this repo is updated https://github.com/kiali/kiali-performance-testing, probably @FilipB can comment on this.

**Comment by FilipB** [comment] 2020-09-22 07:58
@lucasponce @dinesh4747 We don't have any performance tests which are run regularly. We could re-use Gatling tests which were used to test the caching feature. One is hitting K8sApis and second is hitting /api/namespaces/graph endpoint.
Those test were also used to replicate - https://github.com/kiali/kiali/issues/1603

**Comment by jshaughn** [comment] 2020-11-06 21:55
@lucasponce @jmazzitelli , this topic again came up in IRC today, with a similar issue regarding bad default performance when Kiali is presented with a lot of namespaces.  I think perhaps we should more consistently apply the approach used already by the graph page.  When no namespaces are selected then nothing is shown, other than a message indicating to make a namespace selection.  This would protect against accidentally navigating to one of our pages and immediately hanging.

In addition, I'd suggest revisiting the namespace selector and making it a bit more powerful.  We can easily add a select-all (the standard checkbox above the individual checkboxes) (already an RFE: #3173).   A select all in combination with the current text filter could be a good start.  Also, we may want to revisit our current approach of reacting to every check/uncheck, and just wait until all selections are made and applied, 

Thoughts?

**Comment by jshaughn** [comment] 2020-11-09 19:14
Agan today someone mentioned that hitting a Kiali page hung due to the large number of namespaces.  I'm going to take a little time to throw together a POC of my thoughts above, for consideration.

**Comment by jotak** [comment] 2020-11-10 08:25
> @lucasponce @jmazzitelli , this topic again came up in IRC today, with a similar issue regarding bad default performance when Kiali is presented with a lot of namespaces. I think perhaps we should more consistently apply the approach used already by the graph page. When no namespaces are selected then nothing is shown, other than a message indicating to make a namespace selection. This would protect against accidentally navigating to one of our pages and immediately hanging.

Do you mean, avoid having all namespaces selected by default? It's understandable for every page, except perhaps for Overview since its goal is to show high level health (it doesn't make a lot of sense if just one namespace is displayed).
Perhaps this case must be handled differently. For instance, it could restrict by default the view to just 10 namespaces, and show links to view more and/or all ?

**Comment by lucasponce** [comment] 2020-11-10 08:36
> I think perhaps we should more consistently apply the approach used already by the graph page. When no namespaces are selected then nothing is shown, other than a message indicating to make a namespace selection. This would protect against accidentally navigating to one of our pages and immediately hanging.

I'm not sure if I agree on this. This is against the value of the feature itself.

Please, before that you progress in some coding I guess this design should be discussed.

The multi-namespace nature of Kiali as a key feature that I don't think we should disable by default.

We could have a feature flag to change this on certain situations but I don't want to see an empty list on other pages, so I suggest to sync before you start some PR.

**Comment by lucasponce** [comment] 2020-11-10 08:42
>  For instance, it could restrict by default the view to just 10 namespaces, and show links to view more and/or all ?

I think this is more complicated, because all pages have filtering and sorting, and pagination in backend is not accessible.

So, I don't think this is duable without missing/breaking these features.

Performance scenarios are complex and I think it needs more thinking and a global strategy.

**Comment by jshaughn** [comment] 2020-11-10 15:52
@lucasponce @jotak  I agree that a key part of Kiali is to surface issues, and if we don't look at all of the namespaces we could fail to surface an issue.  But, we can't ignore the reality of performance and that some user's are already running into the problem of having a Kiali page never return.   That sort of user experience can completely drive a user away from a tool, and so I think we need a strategy sooner rather than later.

I don't think the graph or list views can support an all-namespace default.  Instead, I propose they default to a configured set of namespaces.  If none are configured then the default is runtime selection (like the graph does today).

As an aside, we may want to think about views less driven by namespaces and more driven by health.  For example, when querying metrics, ignore namespaces and look for error codes.

By the way, the POC coding I did yesterday was only mildly related.  I think we need to improve namespace selection in general and the POC would already satisfy https://github.com/kiali/kiali/issues/3173.  I will post a screenshot/video in that issue...

**Comment by lucasponce** [comment] 2020-11-10 16:07
> I don't think the graph or list views can support an all-namespace default.

Again, I'm not sure if I agree here. 
Because it's the purpose of the Overview page, which is similar in terms of performance.

I'd separate the discussion, one thing is if we want to make a "select all" for the namespace selector UI component, which is what I understand you are coding.

But a very different discussion is about limiting namespaces, why and how, and that requires a different strategy.

The "select-all" or a default configured set of namespaces won't help anything here, specially when using the Overview page.

So, I'd avoid to address that separately. There are more discussion on this related to understand the limits and the actions to perform under performance scenarios.

**Comment by jotak** [comment] 2020-11-10 16:09
> @lucasponce @jotak I agree that a key part of Kiali is to surface issues, and if we don't look at all of the namespaces we could fail to surface an issue. But, we can't ignore the reality of performance and that some user's are already running into the problem of having a Kiali page never return. That sort of user experience can completely drive a user away from a tool, and so I think we need a strategy sooner rather than later.

Definitely +1, we have seen problems about that too often already

> I don't think the graph or list views can support an all-namespace default. Instead, I propose they default to a configured set of namespaces. If none are configured then the default is runtime selection (like the graph does today).

What is "runtime selection" exactly?

I think we could handle that differently according to the situation. We want to provide the best experience for two extreme use cases, the high-volume-500-namespaces use case, and the demo-bookinfo use case. 
For instance, we can check the number of accessible namespaces and act accordingly, if it's above or below some threshold (let's say 5 namespaces).
So that, in the low-namespaces scenario, we continue to show everything in Overview.
And do something different when many namespaces are found.

The idea of a configured set of namespaces looks interesting, would it be similar to our "accessible_namespaces" config, but for the UI only, browser-based (stored in local browser storage) ? Note that it should be different from the current namespaces dropdown selection IMO ... due to the difference of expectations between overview page versus all other pages.

**Comment by lucasponce** [comment] 2020-11-10 16:18
> I think we could handle that differently according to the situation. We want to provide the best experience for two extreme use cases, the high-volume-500-namespaces use case, and the demo-bookinfo use case.
For instance, we can check the number of accessible namespaces and act accordingly, if it's above or below some threshold (let's say 5 namespaces).
So that, in the low-namespaces scenario, we continue to show everything in Overview.
And do something different when many namespaces are found.

I would be cautious to take any action here.

Again, we are not solving the problem, just hiding, because there are cross namespace operations under the hood that will impact.

(I.e. remember we check that is there is a Gateway connected with other VirtualService in all namespaces available).

So, this requires a different strategy, and also going to the roots: is a 500 namespaces user a valid user for Kiali ? 

I think that perhaps we need to explore to allow the user to create a profile with the interesting namespaces for a group/role instead.

It's not only a UI concern, it's deep and it goes beyond that, so, it's not as simple to just select 5 namespace by default.

**Comment by jshaughn** [comment] 2020-11-10 16:47
> > I don't think the graph or list views can support an all-namespace default.

> Again, I'm not sure if I agree here.
Because it's the purpose of the Overview page, which is similar in terms of performance.

I had limited my proposal to graph and list pages, and left Overview for discussion,

> What is "runtime selection" exactly?

I meant that like the graph, no namespaces are selected by default, the user selects them at runtime via the Namespace selection dropdown.  Note that of course the graph honors namepaces already explicitly selected in the URL or via another page.

> I think that perhaps we need to explore to allow the user to create a profile with the interesting namespaces for a group/role instead.

This is pretty close to what I proposed. A set of configured default namespaces, call them favorites if you like.  I had been thinking globally, along the lines of accessible namespaces, but more user-specirfic could be good.   The main thing is that unless configured the list pages will not default to all namespaces.  If a user does not have any namespaces selected it would require a one-time selection via the namespaces dropdown and that could then be carried across the graph and list pages.

Past that I think we could start to protect ourselves with some timeouts.  For pages, like the graph, that process requests namespace-by-namespace, it could add a time-check between namespaces and return "what it has" if it runs out of time.

**Comment by jshaughn** [comment] 2020-12-17 20:17
Note, it's not clear we need it, but  a set of default namespaces for UI sessions could possibly be supported by the work for https://github.com/kiali/kiali/issues/3371.

**Comment by lucasponce** [comment] 2021-02-09 14:17
I'm in favor to close it with the work done in https://github.com/kiali/kiali-ui/pull/2001 and pending work on #3371.

Note that I will open a new Epic to collect scalability and performance topics where we can collect all of these work.

@dinesh4747 let us know if you are agree, also happy if you can give us feedback about the existing changes in that direction.

Thanks !

**Closed by lucasponce** 2021-02-09 14:17 UTC
Labels: discussion needed, question
