### ISSUE TITLE
Kiali pod crashing continuously 

### ISSUE THREAD

**Issue by Yajnalatha** [kiali/kiali#5870] opened 2023-02-24 16:09 UTC
Kiali pod is continuously crashing, we have check the pod logs not able to find much there. In kiali metric we have found below API’s are taking infinity time to respond. Could you please help us to resolve this issue?

kiali_api_processing_duration_seconds_bucket{route="GraphNamespaces",le="+Inf"} 6
kiali_api_processing_duration_seconds_bucket{route="Healthz",le="+Inf"} 34
kiali_api_processing_duration_seconds_bucket{route="IstioCerts",le="+Inf"} 6
kiali_api_processing_duration_seconds_bucket{route="IstioStatus",le="+Inf"} 6
kiali_api_processing_duration_seconds_bucket{route="NamespaceTls",le="+Inf"} 6
kiali_api_processing_duration_seconds_bucket{route="NamespaceValidationSummary",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.AuthorizationPolicyChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.DestinationRulesChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.GatewayChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.DestinationRulesChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.GatewayChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.NoServiceChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.PeerAuthenticationChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.RequestAuthenticationChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.ServiceEntryChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.SidecarChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.VirtualServiceChecker",le="+Inf"} 37
kiali_checker_processing_duration_seconds_bucket{checker="checkers.WorkloadChecker",le="+Inf"} 37
kiali_graph_appender_duration_seconds_bucket{appender="deadNode",le="+Inf"} 30
kiali_graph_appender_duration_seconds_bucket{appender="idleNode",le="+Inf"} 30
kiali_graph_appender_duration_seconds_bucket{appender="istio",le="+Inf"} 30
kiali_graph_appender_duration_seconds_bucket{appender="serviceEntry",le="+Inf"} 30
kiali_graph_appender_duration_seconds_bucket{appender="sidecarsCheck",le="+Inf"} 30
kiali_graph_appender_duration_seconds_bucket{appender="workloadEntry",le="+Inf"} 30
kiali_graph_generation_duration_seconds_bucket{graph_kind="namespace",graph_type="service",with_service_nodes="true",le="+Inf"} 6
kiali_graph_marshal_duration_seconds_bucket{graph_kind="namespace",graph_type="service",with_service_nodes="true",le="+Inf"} 6
kiali_prometheus_processing_duration_seconds_bucket{query_group="Graph-Generation",le="+Inf"} 180
kiali_prometheus_processing_duration_seconds_bucket{query_group="Metrics-GetRequestRates",le="+Inf"} 12
kiali_validation_processing_duration_seconds_bucket{namespace="******",service="_all_",le="+Inf"} 7
kiali_validation_processing_duration_seconds_bucket{namespace="******",service="_all_",le="+Inf"} 7
kiali_validation_processing_duration_seconds_bucket{namespace="******",service="_all_",le="+Inf"} 7
kiali_validation_processing_duration_seconds_bucket{namespace="******",service="_all_",le="+Inf"} 7
kiali_validation_processing_duration_seconds_bucket{namespace="******",service="_all_",le="+Inf"} 9

**Comment by jshaughn** [comment] 2023-02-24 16:22
It sounds perhaps like your Prometheus DB is under too much pressure.  See https://kiali.io/docs/configuration/p8s-jaeger-grafana/prometheus/#prometheus-tuning.   Or, it may be some other type of environmental issue.  This is likely not a bug in Kiali. Github issues is not a support channel, as such I will close this issue.  If you can't find your problem you can try pursuing this in the #kiali channel on Istio Slack.

**Closed by jshaughn** 2023-02-24 16:22 UTC
