### ISSUE TITLE
custom controllers still have problems

### ISSUE THREAD

**Issue by pantianying** [kiali/kiali#4477] opened 2021-11-04 09:47 UTC
I use kiali operator to install kiali。
version：1.36.5

when I use own custom controllers for replicaSet called DnaApp 
that happened

show the one replicaSet's ownerReferences
![image](https://user-images.githubusercontent.com/20589945/140292517-942c7122-d25d-4922-ae28-335351aceb81.png)

I am sorry that I provided the wrong version information.  please seem the latest
https://github.com/kiali/kiali/issues/4477#issuecomment-969971594

**Comment by lucasponce** [comment] 2021-11-04 13:17
@pantianying could you add more information about the DnaApp framework/controllers ?

A easy/clear example (yaml,gist) to help to reproduce the issues without jumping into the "dian" framework could help us to work on the issue.

Thanks

**Comment by nrfox** [comment] 2021-11-09 19:34
If your custom controller manages pods directly, this also may have been addressed by https://github.com/kiali/kiali/pull/4398 if you can upgrade to Kiali verison v1.41 or greater to test.

**Comment by hhovsepy** [comment] 2021-11-11 08:55
Unable to reproduce the issue on Kiali version 1.35, 1.36 and latest releases.
From the attached screenshot of Kiali UI Workload lists page, it seems that the Kiali version is older than v1.36.

**Comment by pantianying** [comment] 2021-11-16 07:52
I am very sorry that I provided the wrong version information. The screenshot above is inconsistent with the version。
I have now upgraded to the real 1.36.5 version of Kiali and the UI style has changed, but it still looks abnormal

![image](https://user-images.githubusercontent.com/20589945/141943176-93a01d4e-ed56-4e0a-826e-903195bd9652.png)
It seemed workload could not perceive the pod at the bottom

**Comment by pantianying** [comment] 2021-11-16 07:54
Let me explain the logic of our custom controller：Dnaapp controls RS , Architecturally much like the multi-release of ArgoCD.

**Comment by hhovsepy** [comment] 2021-11-16 11:35
Thank you for the screenshots @pantianying
Now I see that those pods are not started on the cluster side, can you please check what is in cluster side logs of those pods. They seems failing to start or are Idle.
The initial issue was in displaying Workload details page, does it work for you now?

**Comment by pantianying** [comment] 2021-11-18 02:30
> Thank you for the screenshots @pantianying Now I see that those pods are not started on the cluster side, can you please check what is in cluster side logs of those pods. They seems failing to start or are Idle. The initial issue was in displaying Workload details page, does it work for you now?

But in fact, every DnaApp has RS under it, and under RS there are pods that work properly. It seems that Kiali was unable to find a relationship between these pods and DnaApp. I wonder how Kiali found pod, was it through RS?

**Comment by hhovsepy** [comment] 2021-11-22 12:45
> I wonder how Kiali found rs that owner by my dnaapp , was it through label? and how Kiali found pod for app?
Right, I should have been notice that earlier, as in your screenshot it says "Missing App" per workload.
Kiali recognizes pods for applications by the "app" label, so in your example the RS and Pods needs to have the same "app" labels set.

**Comment by hhovsepy** [comment] 2021-12-13 18:01
Hi @pantianying is it working for you now?

**Comment by pantianying** [comment] 2021-12-14 06:13
> Hi @pantianying is it working for you now?

Thank you for your reply
I checked that ，all Dnaapp /RS/ POD all have app labels

like that：
![image](https://user-images.githubusercontent.com/20589945/145942764-13ebca95-9ad7-4c9f-823b-d7d25d8b4e6e.png)
![image](https://user-images.githubusercontent.com/20589945/145942894-68bb3782-b2ad-4e97-8be0-1fad4ed04abf.png)
![image](https://user-images.githubusercontent.com/20589945/145942981-13528ec9-8176-4030-add0-0173ca2a8fb4.png)
 
So far the display is still wrong

![image](https://user-images.githubusercontent.com/20589945/145943142-79ff0b0f-1425-4d1a-bd4a-8deca5491865.png)

**Comment by nrfox** [comment] 2021-12-15 19:19
@pantianying in the example you posted, can you try changing the name of your custom resource `stable-abas-container` to just `abas`? I wonder if Kiali is making some assumptions about naming of workloads when there's a replicaset in between the top level workload and the pods.

**Comment by pantianying** [comment] 2021-12-16 03:08
> @pantianying in the example you posted, can you try changing the name of your custom resource `stable-abas-container` to just `abas`? I wonder if Kiali is making some assumptions about naming of workloads when there's a replicaset in between the top level workload and the pods.

<img width="1215" alt="截屏2021-12-16 上午11 05 07" src="https://user-images.githubusercontent.com/20589945/146300967-e6620e44-0224-48a9-8692-2e169fda165e.png">

I tried to do this and it seems to find pod but pod is wrong, I have both 'app=thresh' and 'app=thresh-front' pod but Thresh's dnaapp seems to find Pod for thresh-front on Kiali. There seems to be some kind of bug, but in general, other pods seem to work on Kiali. @nrfox

**Comment by nrfox** [comment] 2021-12-17 14:01
Working on a fix for this

**Closed** 2022-01-04 10:31 UTC
Labels: bug, backlog

**Comment by nrfox** [comment] 2022-01-04 14:04
@pantianying a fix for this will be in the upcoming `1.45.0` release. If the problem persists after deploying and testing with that version, feel free to re-open this issue.

**Comment by pantianying** [comment] 2022-01-05 07:07
> @pantianying a fix for this will be in the upcoming `1.45.0` release. If the problem persists after deploying and testing with that version, feel free to re-open this issue.

👌🏻
