### ISSUE TITLE
Kiali installation failed on v0.21.0

### ISSUE THREAD

**Issue by sniperking1234** [kiali/kiali#1153] opened 2019-06-17 03:59 UTC
This is the installation record and I can't find service in istio-system
![image](https://user-images.githubusercontent.com/7834655/59577471-7c1ada80-90f6-11e9-8e3b-06358e5ea870.png)

And there are many mistakes in the operator log
![image](https://user-images.githubusercontent.com/7834655/59577902-38c16b80-90f8-11e9-9d77-2b2606a2522d.png)

**Comment by sniperking1234** [comment] 2019-06-17 05:54
I installed Kiali in another cluster and succeeded,but I found the logs a little different.
![微信截图_20190617134634](https://user-images.githubusercontent.com/7834655/59581365-3dd9e700-9107-11e9-8420-2e43b8ab16e5.png)
![微信截图_20190617134711](https://user-images.githubusercontent.com/7834655/59581366-3e727d80-9107-11e9-9086-84ce03997361.png)
What's the difference between ‘kiali "kiali" configured’ and ‘kiali.kiali.io/kiali created’

**Comment by lucasponce** [comment] 2019-06-17 07:27
@sniperking1234 thanks for the issue.
Past Friday I was testing the latest version which was used to release v0.21.0.
Do you know if perhaps did you have a previous instance of the operator ?

I'm cc-ing @jmazzitelli who has more deep knowledge about how the operator works.

By the way, could you confirm if you follow some steps similar as I did on this draft:
https://gist.github.com/lucasponce/ac4de4ad5a2994ec7e5a291746db4c28

I'm trying to document how to update Kiali from a standard installation done in Istio so I'm interested to get feedback and also what things can be wrong in existing installations as you are describing, so any help is more han welcome.

Thanks.
Lucas

**Comment by sniperking1234** [comment] 2019-06-17 07:55
@lucasponce The Kiali version I installed before is v0.16,so I think I shoud have v0.16 operator.
I tired 'Update Kiali' command from your link but sadly, it still failed. No kiali service was created.
```
curl -L https://git.io/fj21N | envsubst > $HOME/update-kiali-cr.yaml
 bash <(curl -L https://git.io/getLatestKialiOperator) -oiv latest --kiali-cr $HOME/update-kiali-cr.yaml
```
![image](https://user-images.githubusercontent.com/7834655/59587591-3111bf00-9118-11e9-8378-23042ab11185.png)

**Comment by lucasponce** [comment] 2019-06-17 09:03
If you have an old 0.16 Kiali version, I think operator should be upgraded.

Can you get the Kiali Operator CR to see what error do you see ?

```
kubectl edit kiali kiali -n kiali-operator -o yaml
```

It should have a status section, that probably can give more info here.

**Comment by jotak** [comment] 2019-06-17 09:11
I think you must pass the flag to uninstall existing Kiali, `--uninstall-existing-kiali true` when installing over an old version that doesn't have the operator.

**Comment by sniperking1234** [comment] 2019-06-17 09:40
@lucasponce I think that's the reason. The Kiali Operator CR failed to delete and the configuration inside is strange.
![image](https://user-images.githubusercontent.com/7834655/59594728-fb280700-9126-11e9-8ce4-b551e6041c9c.png)

![image](https://user-images.githubusercontent.com/7834655/59594669-d9c71b00-9126-11e9-9959-7a1e71685677.png)

**Comment by sniperking1234** [comment] 2019-06-17 09:47
@jotak Still not work but thank you！！

**Comment by lucasponce** [comment] 2019-06-17 09:49
@sniperking1234 what environment are you using ?
I can try to reproduce your steps and see if I can spot what is going on.

I think that cleaning kiali-operator namespace and previous kiali installation should work, but it seems anything else is missing.

**Comment by sniperking1234** [comment] 2019-06-17 09:57
@lucasponce k8s version is 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
I think this may have happened by accident and I'm going to cleaning the namespace.

**Comment by lucasponce** [comment] 2019-06-17 10:48
@sniperking1234 are you using minikube / GKE, OpenShift ?
On which cloud are you deploying Istio and Kiali ?

**Comment by lucasponce** [comment] 2019-06-17 11:26
@sniperking1234 I've repeated the steps described in 
https://gist.github.com/lucasponce/ac4de4ad5a2994ec7e5a291746db4c28
(this doc is just a personal draft, not an official doc)

And in step 9, to update Kiali from 0.16 to 0.21 I used the Kiali CR:

```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
annotations:
  ansible.operator-sdk/reconcile-period: "0s"
spec:
  deployment:
    accessible_namespaces: [ "**" ]
  external_services:
    grafana:
      url: http://35.246.65.43:15031/
    tracing:
      service: tracing
      url: http://35.246.65.43:15032/jaeger
  identity:
    cert_file: ""
    private_key_file: ""
```

(You should adjust the public URL of grafana/tracing for your environment).

With the command:

```
 bash <(curl -L https://git.io/getLatestKialiOperator) --kiali-cr $HOME/update-kiali-cr.yaml
```

And I got a successful update from Kiali 0.16 to Kiali 0.21.

On my test I used a default GKE account (with version 1.13.6-gke.6).

**Comment by jshaughn** [comment] 2019-06-17 12:43
Has anyone in this thread actually followed the [documentation at kiali.io](https://www.kiali.io/documentation/getting-started)?   The documentation should be up to date for the 0.21 release and if it it has mistakes then it should be updated.

It sounds to me like you may want to ensure anything previously installed is uninstalled, so see [Uninstall](https://www.kiali.io/documentation/getting-started/#_uninstall).  If that works for you then proceed back to [Installing Kiali](https://www.kiali.io/documentation/getting-started/#_installing_kiali).

The install procedures are constantly evolving so it's important to keep up to date and check the documentation with each new release.

**Comment by lucasponce** [comment] 2019-06-17 12:47
@jshaughn a common scenario (as described by this user) should be to allow users to update Kiali from standard Istio versions.

Reading from kiali.io that is not obvious to me, and kiali.io doc should identify that use case in a easier way that is today.

Feel free to use this thread as an example.

**Comment by jshaughn** [comment] 2019-06-17 13:07
@lucasponce I'll make another pass at the instructions today, and try to better call out the fact that Kiali can be installed with Istio/Maistra or independently, and how to change from one installation approach to the other.

I think the information is all there, still iterating on the layout.

**Comment by lucasponce** [comment] 2019-06-17 13:22
@jshaughn current doc requires a deep knowledge of some configuration pieces.
From a standard user, some default info can be added:
- How to expose Kiali (Istio.io recommend using the Ingress, there are ports defined, my script follows that).
- What default setting to use if I want to upgrade.

These two info should need some kind of direct link:
- "I have installed istio 1.x, I have kiali 0.y and I want to upgrade" -> Follow these steps.

**Comment by jmazzitelli** [comment] 2019-06-17 14:01
> Server Version: version.Info{Major:"1", Minor:"9"

Kubernetes 1.9? I wonder if this might have an impact? Have we tested on 1.9?

@sniperking1234 it would be best if you could log here, or pastebin, or something like that, the entire output of the git.io/getLatestKialiOperator log messages so we can see everything its doing. Plus, the Kiali Operator has two containers - "ansible" and "operator" - the "ansible" one logs things in more human readable fashion. The "operator" has some low-level messages but is less readable. I would post the "ansible" container logs unless there is something in the "operator" logs that shows more.

The new deploy script should ask you to delete kiali if it finds one in the same namespace you are installing the new one (i.e. "istio-system"). Note that we have a new PR coming that should remove it to try to circumvent that k8s bug that causes deletion hangs (I don't think you are hitting that problem now): https://github.com/kiali/kiali/pull/1150

**Comment by sniperking1234** [comment] 2019-06-18 01:47
> @sniperking1234 are you using minikube / GKE, OpenShift ?
> On which cloud are you deploying Istio and Kiali ?

I didn't use them and I deployed on my company's cloud services

**Comment by sniperking1234** [comment] 2019-06-18 02:14
@jmazzitelli The new script can delete the Kiali Operator CR but still can't create the Kiali service.
There's no status section in Kiali Operator CR
![image](https://user-images.githubusercontent.com/7834655/59648379-84841b80-91b1-11e9-9e80-128282fc4e37.png)
Operator ansible log
![image](https://user-images.githubusercontent.com/7834655/59648403-9e256300-91b1-11e9-9acd-2e684f344df0.png)
Operator operator log
![image](https://user-images.githubusercontent.com/7834655/59648432-ba290480-91b1-11e9-89bf-5e4e6b5cdbd1.png)

**Comment by jmazzitelli** [comment] 2019-06-18 02:46
I can't tell what's going on with these image snippets of logs. Let's take a step back.

1. Start from scratch. Do what ever you need to do to completely remove everything "kiali" related. It might mean you have to remove the finalizer from the CR before deleting it, like this:

```
kubectl patch kiali kiali -n kiali-operator -p '{"metadata":{"finalizers": []}}' --type=merge
kubectl delete kiali kiali -n kiali-operator
```

Then remove the operator - `oc delete namespace kiali-operator`

You should not have any kiali pod in the istio-system namespace - `oc get pods -l app=kiali -n istio-system`

2. Now install the Kiali Operator. Please post the full command you execute to install the Kiali Operator and please attach the full output of that command (these small image snippets of the messages don't give us a full picture of what is going on).

3. Attach the full Kiali CR yaml as returned by `kubectl get kiali kiali -n kiali-operator -o yaml` and then attach the full Kiali configmap yaml as returned by `kubectl get cm kiali -n istio-system -o yaml` (assuming you get a configmap created - if the operator is aborting before it has a chance to create the configmap, you won't have one - but that is something important to know, too).

4. At this point, wait for the Kiali Operator to do its thing. Then attach the output of the "ansible" container of the operator pod: `kubectl logs deployment/kiali-operator -c ansible -n kiali-operator`

Hopefully, at that point, with all of that data available, it will be more clear as to what is going on and we can help you.

**Comment by sniperking1234** [comment] 2019-06-18 03:10
@jmazzitelli I can give you complete logs.

1. I removed everything about kiali
![log1](https://user-images.githubusercontent.com/7834655/59650564-09befe80-91b9-11e9-80db-ead282e6ad93.png)
2. Kiali Operator install logs
![log2](https://user-images.githubusercontent.com/7834655/59650605-31ae6200-91b9-11e9-9cf5-11e49e55ea16.png)
3. Kiali CR yaml and there's no Kiali configmap yaml
![log3](https://user-images.githubusercontent.com/7834655/59650691-7fc36580-91b9-11e9-8a59-f9d0409e03a1.png)
4. Kiali Operator logs
![log4](https://user-images.githubusercontent.com/7834655/59650710-9073db80-91b9-11e9-9d9b-11d02a377a30.png)

**Comment by jmazzitelli** [comment] 2019-06-18 03:29
OK, well, I can't copy and paste text from images, but that error in the operator logs that says something about "can't update the status of the CR" is probably the cause of your issue. I have never seen this before.

You are on Kubernetes 1.9 from [what you said before](https://github.com/kiali/kiali/issues/1153#issuecomment-502617577)

```
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

I suspect this older version of Kubernetes is the issue.

The prerequisites of the operator is Kubernetes 1.11.3+ which is what I see here https://github.com/operator-framework/operator-sdk#prerequisites

Even Istio is only confirmed to work with 1.11+ - see https://istio.io/docs/setup/kubernetes/

Have you tried this on a later version of Kubernetes?

**Comment by sniperking1234** [comment] 2019-06-18 03:45
@jmazzitelli I tried on Kubernetes 1.11.1 and the upgrade was successful. Maybe the version of Kubernetes is the cause of failure.
This is the text of the error logs.

> {"level":"error","ts":1560826747.8371637,"logger":"reconciler","msg":"Unable to update the status to mark cr as running","job":"4359605576265514993","name":"kiali","namespace":"kiali-operator","error":"the server could not find the requested resource","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/controller.(*AnsibleOperatorReconciler).Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/controller/reconcile.go:127\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1560826747.8372738,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"kiali-controller","request":"kiali-operator/kiali","error":"the server could not find the requested resource","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

**Comment by lucasponce** [comment] 2019-06-19 07:19
@sniperking1234 just to confirm.
Then, once you have updated to kubernetes +1.1 the reported issue is gone, right ?

Thanks for helping us with your feedback.

Lucas

**Comment by sniperking1234** [comment] 2019-06-19 07:51
@lucasponce I successfully upgraded Kiali from v0.20 to v0.21 on another cluster which kubernetes version is v1.11.1. I didn't upgrade kubernetes on this cluster

**Comment by sniperking1234** [comment] 2019-07-04 12:43
@jmazzitelli There are still problems when updating. Kiali operater looks like something's wrong and stuck in a loop. Ansible container has a lot of log and If you want to see, I can paste it out.
Kubernetes vserion: 1.11.1
> bash <(curl -L https://git.io/getLatestKialiOperator)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  4 43905    4  1921    0     0    146      0  0:05:00  0:00:13  0:04:47   412Using 'kubectl' located here: /usr/local/bin/kubectl
=== UNINSTALL SETTINGS ===
UNINSTALL_EXISTING_KIALI=
UNINSTALL_EXISTING_OPERATOR=
UNINSTALL_MODE=
=== UNINSTALL SETTINGS ===
envsubst is here: /usr/bin/envsubst
Using downloader: wget -q -O -
100 43905  100 43905    0     0   3173      0  0:00:13  0:00:13 --:--:-- 10069
Will use the last Kiali operator release: v1.1.0
Will use the last Kiali operator release: v1.1.0
=== OPERATOR SETTINGS ===
OPERATOR_IMAGE_NAME=quay.io/kiali/kiali-operator
OPERATOR_IMAGE_PULL_POLICY=IfNotPresent
OPERATOR_IMAGE_VERSION=v1.1.0
OPERATOR_INSTALL_KIALI=true
OPERATOR_NAMESPACE=kiali-operator
OPERATOR_SKIP_WAIT=false
OPERATOR_VERSION_LABEL=v1.1.0
OPERATOR_WATCH_NAMESPACE=kiali-operator
OPERATOR_ROLE_CLUSTERROLES=# The operator does not have permission to manage cluster roles
OPERATOR_ROLE_CLUSTERROLEBINDINGS=# The operator does not have permission to manage cluster role bindings
=== OPERATOR SETTINGS ===
It appears the operator has already been installed. Do you want to uninstall it? This will uninstall Kiali, too. [Y/n]: y
The existing operator will be uninstalled, along with any existing Kiali installation.
Deleting resources for any existing Kiali operator installation
customresourcedefinition.apiextensions.k8s.io "monitoringdashboards.monitoring.kiali.io" deleted
Deleting Kiali CR [kiali] in namespace [kiali-operator]
kiali.kiali.io/kiali patched
kiali.kiali.io "kiali" deleted
customresourcedefinition.apiextensions.k8s.io "kialis.kiali.io" deleted
pod "kiali-operator-5f7b8b6d74-269wr" deleted
deployment.apps "kiali-operator" deleted
replicaset.apps "kiali-operator-5f7b8b6d74" deleted
serviceaccount "kiali-operator" deleted
clusterrole.rbac.authorization.k8s.io "kiali-operator" deleted
clusterrolebinding.rbac.authorization.k8s.io "kiali-operator" deleted
namespace "kiali-operator" deleted
Deploying Kiali operator to namespace [kiali-operator]
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/namespace.yaml] to namespace [kiali-operator]
namespace/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/crd.yaml] to namespace [kiali-operator]
customresourcedefinition.apiextensions.k8s.io/monitoringdashboards.monitoring.kiali.io created
customresourcedefinition.apiextensions.k8s.io/kialis.kiali.io created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/service_account.yaml] to namespace [kiali-operator]
serviceaccount/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/role.yaml] to namespace [kiali-operator]
clusterrole.rbac.authorization.k8s.io/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/role_binding.yaml] to namespace [kiali-operator]
clusterrolebinding.rbac.authorization.k8s.io/kiali-operator created
Applying yaml from URL via: [wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v1.1.0/operator/deploy/operator.yaml] to namespace [kiali-operator]
deployment.apps/kiali-operator created
Waiting for the operator to start..
The Kiali operator is installed!
Kiali will now be installed.
Choose a login strategy of either 'login' or 'anonymous'. Use 'anonymous' at your own risk. [login]: login
=== KIALI SETTINGS ===
ACCESSIBLE_NAMESPACES=
AUTH_STRATEGY=login
CREDENTIALS_CREATE_SECRET=false
GRAFANA_URL=
KIALI_CR=
KIALI_IMAGE_NAME=
KIALI_IMAGE_PULL_POLICY=
KIALI_IMAGE_VERSION=v1.1.0
ISTIO_NAMESPACE=
JAEGER_URL=
NAMESPACE=istio-system
SECRET_NAME=kiali
_SECRET_EXISTS=true
=== KIALI SETTINGS ===
Deleting resources for any existing Kiali installation
No resources found
error: the server doesn't have a resource type "routes"
error: the server doesn't have a resource type "oauthclients"
NOTE! A secret already exists. To log into Kiali, you must use the credentials found in that secret.
Deploying Kiali CR to namespace [kiali-operator]
kiali.kiali.io/kiali created
Done.
**Kiali CR:**
```
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kiali.io/v1alpha1","kind":"Kiali","metadata":{"annotations":{},"name":"kiali","namespace":"kiali-operator"},"spec":{"auth":{"strategy":"login"},"deployment":{"image_version":"v1.1.0","namespace":"istio-system","secret_name":"kiali"},"external_services":{"grafana":{"url":""},"jaeger":{"url":""}}}}
  creationTimestamp: 2019-07-04T12:22:12Z
  finalizers:
  - finalizer.kiali
  generation: 1
  name: kiali
  namespace: kiali-operator
  resourceVersion: "441673309"
  selfLink: /apis/kiali.io/v1alpha1/namespaces/kiali-operator/kialis/kiali
  uid: 59e7228d-9e56-11e9-bf4a-6c92bf7360cc
spec:
  auth:
    strategy: login
  deployment:
    image_version: v1.1.0
    namespace: istio-system
    secret_name: kiali
  external_services:
    grafana:
      url: ""
    jaeger:
      url: ""
status:
  conditions:
  - lastTransitionTime: 2019-07-04T12:22:12Z
    message: Running reconciliation
    reason: Running
    status: "True"
    type: Running
```

**Comment by jmazzitelli** [comment] 2019-07-04 19:47
@sniperking1234 this is a different issue - can you close this github issue and create a separate one for this new problem?

**Closed** 2019-07-05 00:35 UTC
