### ISSUE TITLE
Bookinfo is not deploying when installing a Multi-Cluster using install-everything.sh

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#4017] opened 2021-05-14 18:37 UTC
When using install-everything.sh to create a multi-cluster configuration, Bookinfo is not deploying. Looking at the Bookinfo deployments shows errors such as:

      " pods "ratings-v1-b6994bb9-" is forbidden: unable to validate against any
        security context constraint:
        [spec.containers[0].securityContext.runAsUser: Invalid value: 1000: must
        be in the ranges: [1000680000, 1000689999]]"

This has been seen on OCP 4.5, 4.7, and 4.8 clusters running on AWS and Red Hat internal clusters.

**Comment by jmazzitelli** [comment] 2021-05-14 18:39
Here is where bookinfo is installed - find out what else is needed or what is wrong (note: it simply uses the existing hack script to install bookinfo - so this error is strange):

https://github.com/kiali/kiali/blob/v1.34/hack/istio/multicluster/split-bookinfo.sh#L20-L43

**Comment by jmazzitelli** [comment] 2021-05-17 19:12
It appears the cause of this is the way Maistra is doing things. There is nothing here that our hack scripts are doing that cause this to happen.

**Comment by jmazzitelli** [comment] 2021-05-17 19:32
I do know we install bookinfo "differently" when using Maistra - that's why there is a "bi-install" option to our hack/istio/install-sm2.sh hack script: https://github.com/kiali/kiali/blob/master/hack/istio/install-sm2.sh#L564-L579

Maybe the Maistra bookinfo images are built differently than the upstream ones so they don't have this problem??

**Comment by FilipB** [comment] 2021-05-17 19:35
Bookinfo for maistra is different than for upstream istio, we are using following script to install both versions - https://gitlab.cee.redhat.com/istio/servicemesh-qe/jenkins-csb-declaration/-/blob/master/resources/kiali/scripts/install-bookinfo.sh

**Comment by jmazzitelli** [comment] 2021-05-17 20:35
> Bookinfo for maistra is different than for upstream istio, we are using following script to install both versions - https://gitlab.cee.redhat.com/istio/servicemesh-qe/jenkins-csb-declaration/-/blob/master/resources/kiali/scripts/install-bookinfo.sh

note this won't work on non-OpenShift environments (I see it uses "oc project" and creates "routes")..  our [kiali hack script](https://github.com/kiali/kiali/blob/master/hack/istio/install-bookinfo-demo.sh )supports non-OpenShift as well as OpenShift clusters because we need to support users on all cluster types.

**Comment by FilipB** [comment] 2021-05-18 05:48
Yes, it's used only on OCP. Pasted it here just to show different location of bookinfo app for maistra which is https://github.com/maistra/istio/tree/maistra-2.1/samples/bookinfo. Maistra bookinfo images are located at https://hub.docker.com/u/maistra

**Comment by lucasponce** [comment] 2021-08-11 07:48
This issue is not clear to me.
It refers to Istio upstream, Maistra or both ?

The work that is being done under kiali-qe repo (kiali-dev-tools and kiali-qe-tools) is relevant to this ?

**Comment by jmazzitelli** [comment] 2021-08-11 12:42
> The work that is being done under kiali-qe repo (kiali-dev-tools and kiali-qe-tools) is relevant to this ?

We can close this issue. We have those other scripts to install OSSM/bookinfo in multi-cluster on openshift.

**Closed by jmazzitelli** 2021-08-11 12:42 UTC
Labels: bug
