### ISSUE TITLE
%httperr < 1 not working

### ISSUE THREAD

**Issue by ceastman-ibm** [kiali/kiali#1128] opened 2019-06-10 14:29 UTC
**Describe the bug**
I specified %httperr < 1 in the hide dialog but i still see things in the kiali graph that have no errors:

For UI issues please also add a screenshot that shows the issue.

<img width="1678" alt="Screen Shot 2019-06-10 at 9 28 54 AM" src="https://user-images.githubusercontent.com/25593207/59202504-3c864880-8b62-11e9-8b90-95922dc39d1d.png">

**Versions used**
Kiali: Version:"1.1.5"
Istio: Version:"1.1.5"
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
kube v1.12.9+IKS

**To Reproduce**
1. Go to 'kiali'
2. Click on 'graph'
3. enter "%httperr < 1" in the hide box

**Expected behavior**
I am expecting to only see things that have http errors

**Comment by abonas** [comment] 2019-06-10 15:25
@jshaughn

**Comment by abonas** [comment] 2019-06-10 15:30
@ceastman-ibm thanks for opening this issue. As the screenshot here contains a lot of tcp connections, would you expect them to be hidden as well on such a criteria for httperr?

**Comment by gbaufake** [comment] 2019-06-10 15:40
@ceastman-ibm 
Is there a way that we can have this mesh to reproduce it?

**Comment by jshaughn** [comment] 2019-06-10 15:57
@gbaufake I don't think we need the mesh to reproduce this behavior.  The reason this doesn't work as expected it due to the fact that for edges with no reported error the value is not 0 but rather NaN.  There are some technical reasons for this, but we may be able to improve things a bit going forward.

The workaround right now is to change your hide expression from "%httperr < 1" to "%httperr = NaN".  You can also do "%httperr < 1 or %httperr = NaN".

Let me know if that works for you.

**Comment by ceastman-ibm** [comment] 2019-06-10 16:03
@jshaughn i updated the hide dialog and now this is the screenshot for that: 
<img width="1462" alt="Screen Shot 2019-06-10 at 11 02 50 AM" src="https://user-images.githubusercontent.com/25593207/59208761-5bd7a280-8b6f-11e9-889d-9a35bf631ff1.png">

**Comment by ceastman-ibm** [comment] 2019-06-10 16:07
@abonas hmm most of these connections should be http, why do you think there are alot of tcp connections?

**Comment by abonas** [comment] 2019-06-10 16:29
> @abonas hmm most of these connections should be http, why do you think there are alot of tcp connections?

@ceastman-ibm the blue arrows that look like this: ---|-|> are tcp connections, I see quite a few of those on your screenshot.

**Comment by ceastman-ibm** [comment] 2019-06-10 16:46
@abonas ah looks like those -----|-|> connections are to external urls, those should be https connections. I have them defined as service entries: for example: 

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: devtest-service-entries
spec:
  hosts:
    - iam.test.cloud.ibm.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL

is it because i have the number defined its classifying it as a tcp connection rather than an http connection?

**Comment by abonas** [comment] 2019-06-10 19:09
> is it because i have the number defined its classifying it as a tcp connection rather than an http connection?

I'm not sure about that, how is this  connection reported to telemetry? Kiali graph is built based on what's in telemetry.
@jshaughn any idea?

**Comment by jshaughn** [comment] 2019-06-10 19:17
@ceastman-ibm That new graph looks like what you wanted, right?   By the way, I created [this PR](https://github.com/kiali/kiali-ui/pull/1252) to improve things.  When that gets merged the next release should work like you originally expected.

As for why edges are showing up as TCP, it must have something to do with your definitions.  As @abonas says, Kiali is only showing the protocol being used by Istio and reported in the telemetry.

**Comment by ceastman-ibm** [comment] 2019-06-10 19:42
@jshaughn for the new picture, i wasn't expecting to see those stand alone apps/service. I would expect to have only see those 4 lines with the beginning and ending:
1) datalayer & conapi-eval
2) istio-ingressgateway & dev-admin-ui.cfaas.test.cloud.ibm.com
3) istio-ingressgateway & developer-ui
4) istio-ingressgateway & console-slash

**Comment by jshaughn** [comment] 2019-06-10 20:25
@ceastman-ibm  Hmm, interesting.   Perhaps we should also Hide nodes that have only hidden edges.  I'll think about that and maybe see if it's feasible.

**Comment by josejulio** [comment] 2019-06-10 20:48
Perhaps we could add it  in the query (as an operator) or as a display option.

**Comment by jshaughn** [comment] 2019-06-11 14:14
@ceastman-ibm I've created a PR for your expected behavior of having nodes with only hidden edges also be hidden: https://github.com/kiali/kiali-ui/pull/1256.

**Comment by jshaughn** [comment] 2019-06-26 13:05
@ceastman-ibm have you been able to try the latest change?

**Comment by ceastman-ibm** [comment] 2019-08-07 14:44
@jshaughn sorry not yet, waiting for IBM's managed istio to pick up this. I believe it will be available in mid September.

**Comment by lucasponce** [comment] 2019-09-10 11:49
@ceastman-ibm I see @jshaughn created a PR with the result of the discussion and that is merged.
I'm going to close this one.
Please, don't hesitate to open it with any comment about it.
Thanks.

**Closed by lucasponce** 2019-09-10 11:49 UTC
Labels: enhancement
