### ISSUE TITLE
Add validation for "exportTo" fields of VirtualService, ServiceEntry

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1370] opened 2019-08-23 08:38 UTC
Currently the new field "exportTo" is added to show/edit on VirtualService and ServiceEntry YAML editors.

RFE: Add a validation on the values of "exportTo", to the list of namespaces to check:
1. if the user has access to those namespaces
2. those namespaces exists or not

JIRA:
https://issues.jboss.org/browse/KIALI-3075

**Comment by lucasponce** [comment] 2021-02-15 09:35
cc @xeviknal this one is still valid and I guess Kiali could add some support.

I'm going to add to the backlog, just to increase the priority on it and to not forget, we can discuss about assignment.

**Comment by lucasponce** [comment] 2021-02-16 12:53
Duplicated by #3061 which is covering same validation but in all objects.

**Comment by xeviknal** [comment] 2021-07-07 15:55
Sorry this went out of my radar. This is not a duplicate of #3061 

#3061 aims to adapt all the validations to the visibility model introduced by the `exportTo` field.
The idea is that kiali should filter out all the objects not visible in the namespace of the object being validated.

For example, if you are validating the gateways of the VirtualService `v`, Kiali should only take into account the Gateways exported to the `v` namespace. All the other gateways won't be visible to it.

Therefore, kiali should have some false positive.

**Closed** 2021-07-27 07:59 UTC
Labels: area/istio operations, backlog, enhancement
