### ISSUE TITLE
Graph in service Graph type fails to load

### ISSUE THREAD

**Issue by iftachsc** [kiali/kiali#843] opened 2019-02-14 15:14 UTC
**General remarks**
Graph in service Graph type fails to load - other modes work (app, workload, versioned-app)

**Describe the bug**
When navigating to Graph types such as app, workload, versioned app - all works beautifully and Kiali really serves us well.
when navigating to the service graph type we see the following:

![image](https://user-images.githubusercontent.com/28829551/52796186-fd485f00-307b-11e9-92d8-1a2e8768c9d3.png)

this does not occur in other istio deployments i have in other projects.

**Versions used**
kiali-ui 0.15.0 (f727bd85e98740b4ac2658b6709b810bc3cbcb93)
kiali v0.15.0-SNAPSHOT (5e5ddce1745e9bba3c788d543ecf2bcd53882047)
Istio 1.0.3
Prometheus 2.3.1
Kubernetes v1.11.5-gke.5

Istio:
ISTIO served by GKE, kiali added 

**To Reproduce**
I dont know how to reproduce. in other project from scratch it works.
this project is already in UAT mode and there are 40 microservices so really building all of it form scratch would be harder path.
if i delete the kiali pod, the new one has the same behaviour.

**Expected behavior**
works as it should

thank u all. we love kiali.

**Comment by israel-hdez** [comment] 2019-02-14 16:03
Hi, @iftachsc.
Thanks for reporting this issue. Do you have access to the logs of the kiali pod? If so, please post the logs of the time where the error happens. We may see something useful to debug the issue.

Also, if it's OK for you to post an image of the "versionedApp" graph and the JSON of the graph it will be great. To get the JSON, just load the graph and use the "View Debug Info" option that is available under the question mark menu of the main header of Kiali (top right, in the blue bar).

**Comment by israel-hdez** [comment] 2019-02-14 18:43
@iftachsc Adittionally, if you could also post an image and the JSON of the "workload" graph type, it will be great.

**Comment by jmazzitelli** [comment] 2019-02-17 02:31
cc @jshaughn

**Comment by iftachsc** [comment] 2019-02-17 12:17
guys, im no longer at the site. ill be there on Tuesday and post all here. thanks for the fast response. maybe my colleague can do it sooner.

**Comment by gbaufake** [comment] 2019-02-18 13:39
@iftachsc Besides what the colleagues have asked you,  could you try a different layout before changing from workload graph to service graph? 

Also, can you describe how you mesh is connected (eg: I have 40 services, 1 is connected to 16, which is 10 and so on).

**Comment by iftachsc** [comment] 2019-02-19 07:03
Sorry for the delay. 

no matter what working mode we are on. from all of them, if we change to service graph its the same.

stdout logs from the kiali pod while this occurs:

the debug info from the errored service graph:

the Workload graph: (we whitelabels some)
![image](https://user-images.githubusercontent.com/28829551/52995645-ead77800-3423-11e9-8517-e7947a6a3168.png)


the debug info from the errored service graph

{
  "currentURL": "http://kiali.dev.k8sdev.example.com/console/graph/namespaces/?edges=hide&graphType=service&namespaces=test&injectServiceNodes=true&duration=60&pi=15000&layout=dagre",
  "reduxState": {
    "authentication": {
      "token": null,
      "username": null,
      "error": false,
      "message": "",
      "logged": true,
      "logging": false,
      "sessionTimeOut": 1550644276441
    },
    "globalState": {
      "loadingCounter": 0,
      "isPageVisible": true
    },
    "grafanaInfo": null,
    "graph": {
      "cyData": {
        "updateTimestamp": 1550558409969,
        "cyRef": null
      },
      "isLoading": false,
      "isError": false,
      "graphDataDuration": 60,
      "graphDataTimestamp": 1550558431,
      "graphData": {
        "nodes": [
          {
            "data": {
              "id": "4b9d0e7961b12d41c375c25dde6054a8",
              "nodeType": "service",
              "namespace": "test",
              "app": "accountmanagement-server",
              "service": "accountmanagement-server",
              "destServices": {
                "accountmanagement-server": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "097def22fc18d4fcb78468fda8fdb242",
              "nodeType": "service",
              "namespace": "test",
              "app": "api-gateway",
              "service": "api-gateway",
              "destServices": {
                "api-gateway": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "5005424a70ff815391f5febe83fa6d7b",
              "nodeType": "service",
              "namespace": "test",
              "app": "api-gateway-bulk-worker",
              "service": "api-gateway-bulk-worker",
              "destServices": {
                "api-gateway-bulk-worker": true
              }
            }
          },
          {
            "data": {
              "id": "2bc429882191f4ceb4d9b61c5bd86e94",
              "nodeType": "workload",
              "namespace": "test",
              "workload": "bing-api",
              "app": "bing-api",
              "version": "active",
              "isRoot": true
            }
          },
          {
            "data": {
              "id": "8ed9e6b31c51171c3acd2b6304e07a5a",
              "nodeType": "service",
              "namespace": "test",
              "app": "cp-kafka",
              "service": "kafka-main",
              "destServices": {
                "kafka-main": true
              }
            }
          },
          {
            "data": {
              "id": "970d2ee8de958440f033bf77ca4f854e",
              "nodeType": "service",
              "namespace": "test",
              "app": "service1",
              "service": "service1",
              "destServices": {
                "service1": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "c997777c07380445d2d22fd95ce0bce7",
              "nodeType": "service",
              "namespace": "test",
              "app": "enrichment-orchestrator",
              "service": "enrichment-orchestrator",
              "destServices": {
                "enrichment-orchestrator": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "b162e488f1d6f1a18f2869d67eb0ae1e",
              "nodeType": "service",
              "namespace": "test",
              "app": "expansion-api",
              "service": "expansion-api",
              "destServices": {
                "expansion-api": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "3637b637478e5130d0894c228be82271",
              "nodeType": "workload",
              "namespace": "test",
              "workload": "integrations-landing-hubspot",
              "app": "integrations-landing-hubspot",
              "version": "active",
              "isRoot": true
            }
          },
          {
            "data": {
              "id": "fe9b80933173960938d5b9dcbb440bfc",
              "nodeType": "service",
              "namespace": "test",
              "app": "intent-modeling",
              "service": "intent-modeling",
              "destServices": {
                "intent-modeling": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "7d18eb7fc4c64a6ae79ae739b60dd944",
              "nodeType": "service",
              "namespace": "test",
              "app": "leadsearch",
              "service": "leadsearch",
              "destServices": {
                "leadsearch": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "0014f93114dfc7dfda64317e0ea37be2",
              "nodeType": "service",
              "namespace": "test",
              "app": "model-based-matching",
              "service": "model-based-matching",
              "destServices": {
                "model-based-matching": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "2b19f7004c1647105dc126850bc8f664",
              "nodeType": "service",
              "namespace": "test",
              "app": "model-scoring",
              "service": "model-scoring",
              "destServices": {
                "model-scoring": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "f6a22897996f1845306cbee5569acf1b",
              "nodeType": "service",
              "namespace": "test",
              "app": "redis",
              "service": "redis-base-scoring-master",
              "destServices": {
                "redis-base-scoring-master": true
              }
            }
          },
          {
            "data": {
              "id": "4310d43579937c8d46f8042d37ca88b1",
              "nodeType": "service",
              "namespace": "test",
              "app": "redis",
              "service": "redis-hs-integration-landing-master",
              "destServices": {
                "redis-hs-integration-landing-master": true
              }
            }
          },
          {
            "data": {
              "id": "d7108c50fe5d50c49cdc5e43c570f77f",
              "nodeType": "service",
              "namespace": "test",
              "app": "redis",
              "service": "redis-model-scoring-master",
              "destServices": {
                "redis-model-scoring-master": true
              }
            }
          },
          {
            "data": {
              "id": "cdf33f6164bba8d1e032e87e46edac08",
              "nodeType": "service",
              "namespace": "test",
              "app": "redis-ha",
              "service": "redis-api-gateway-announce-0",
              "destServices": {
                "redis-api-gateway-announce-0": true
              }
            }
          },
          {
            "data": {
              "id": "8ef47e6f2fd0aab9354e6c685148dff1",
              "nodeType": "service",
              "namespace": "test",
              "app": "redis-ha",
              "service": "redis-bing-api-announce-0",
              "destServices": {
                "redis-bing-api-announce-0": true
              }
            }
          },
          {
            "data": {
              "id": "cba2da1dd480f4f0c255b34001c104d9",
              "nodeType": "workload",
              "namespace": "test",
              "workload": "rule-base-scoring",
              "app": "rule-base-scoring",
              "version": "active",
              "isRoot": true
            }
          },
          {
            "data": {
              "id": "7f2aa4cc91f38eb4e3071500df7d8fa2",
              "nodeType": "service",
              "namespace": "test",
              "app": "scoring-service",
              "service": "scoring-service",
              "destServices": {
                "scoring-service": true
              },
              "hasVS": true
            }
          },
          {
            "data": {
              "id": "b30b0078325bf2e1adb4d57c4c0c2665",
              "nodeType": "unknown",
              "namespace": "unknown",
              "workload": "unknown",
              "app": "unknown",
              "version": "unknown",
              "isInaccessible": true,
              "isRoot": true
            }
          }
        ],
        "edges": [
          {
            "data": {
              "id": "d68f443dcd7f902110fa48ed42d9113e",
              "source": "0014f93114dfc7dfda64317e0ea37be2",
              "target": "2b19f7004c1647105dc126850bc8f664",
              "traffic": {
                "protocol": "",
                "rates": null
              }
            }
          },
          {
            "data": {
              "id": "6a75ea06b6062fdc1f767d1ac57dcd1c",
              "source": "0014f93114dfc7dfda64317e0ea37be2",
              "target": "8ef47e6f2fd0aab9354e6c685148dff1",
              "traffic": {
                "protocol": "tcp",
                "rates": {
                  "tcp": "0.22"
                }
              }
            }
          },
          {
            "data": {
              "id": "edf7ea83be72cf0862de77f06a25386a",
              "source": "097def22fc18d4fcb78468fda8fdb242",
              "target": "4b9d0e7961b12d41c375c25dde6054a8",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.18",
                  "httpPercentReq": "33.3"
                }
              }
            }
          },
          {
            "data": {
              "id": "c7b845a7358fbcc0709ee5d30c781b48",
              "source": "097def22fc18d4fcb78468fda8fdb242",
              "target": "c997777c07380445d2d22fd95ce0bce7",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.36",
                  "httpPercentReq": "66.7"
                }
              }
            }
          },
          {
            "data": {
              "id": "2f3368294d9464ce1c5cecb156ecc5bd",
              "source": "097def22fc18d4fcb78468fda8fdb242",
              "target": "cdf33f6164bba8d1e032e87e46edac08",
              "traffic": {
                "protocol": "tcp",
                "rates": {
                  "tcp": "14.82"
                }
              }
            }
          },
          {
            "data": {
              "id": "e87cde66efef85bcaf8b37a098d3d495",
              "source": "2b19f7004c1647105dc126850bc8f664",
              "target": "d7108c50fe5d50c49cdc5e43c570f77f",
              "traffic": {
                "protocol": "",
                "rates": null
              }
            }
          },
          {
            "data": {
              "id": "1cfef80077a82a21dc6a297eb0de1a5d",
              "source": "2bc429882191f4ceb4d9b61c5bd86e94",
              "target": "8ef47e6f2fd0aab9354e6c685148dff1",
              "traffic": {
                "protocol": "tcp",
                "rates": {
                  "tcp": "14.91"
                }
              }
            }
          },
          {
            "data": {
              "id": "4782bd03d09222c982612012408dc102",
              "source": "3637b637478e5130d0894c228be82271",
              "target": "4310d43579937c8d46f8042d37ca88b1",
              "traffic": {
                "protocol": "tcp",
                "rates": {
                  "tcp": "7.46"
                }
              }
            }
          },
          {
            "data": {
              "id": "e9886b1de16e344d3abd35f0fac5af75",
              "source": "4b9d0e7961b12d41c375c25dde6054a8",
              "target": "8ed9e6b31c51171c3acd2b6304e07a5a",
              "traffic": {
                "protocol": "",
                "rates": null
              }
            }
          },
          {
            "data": {
              "id": "bce26a680d9ac9ff1eeb2380451d704c",
              "source": "5005424a70ff815391f5febe83fa6d7b",
              "target": "4b9d0e7961b12d41c375c25dde6054a8",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.27",
                  "httpPercentReq": "88.3"
                }
              }
            }
          },
          {
            "data": {
              "id": "c9377fe3f338f420c67fc1f807a9a2e4",
              "source": "5005424a70ff815391f5febe83fa6d7b",
              "target": "8ed9e6b31c51171c3acd2b6304e07a5a",
              "traffic": {
                "protocol": "tcp",
                "rates": {
                  "tcp": "9.11"
                }
              }
            }
          },
          {
            "data": {
              "id": "0e56f27289ca6b6ca20c618a31a6e150",
              "source": "5005424a70ff815391f5febe83fa6d7b",
              "target": "b162e488f1d6f1a18f2869d67eb0ae1e",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.02",
                  "http5xx": "0.02",
                  "httpPercentErr": "100.0",
                  "httpPercentReq": "5.8"
                }
              }
            }
          },
          {
            "data": {
              "id": "6d74e8fc1e1c9d4223c6cd3de7b0ee98",
              "source": "5005424a70ff815391f5febe83fa6d7b",
              "target": "c997777c07380445d2d22fd95ce0bce7",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.02",
                  "httpPercentReq": "5.8"
                }
              }
            }
          },
          {
            "data": {
              "id": "dce31defd3ad286ac541f639e4c3adf9",
              "source": "5005424a70ff815391f5febe83fa6d7b",
              "target": "cdf33f6164bba8d1e032e87e46edac08",
              "traffic": {
                "protocol": "tcp",
                "rates": {
                  "tcp": "12.93"
                }
              }
            }
          },
          {
            "data": {
              "id": "53d0cd27787b39e95dd0f2a7d097500d",
              "source": "b162e488f1d6f1a18f2869d67eb0ae1e",
              "target": "7d18eb7fc4c64a6ae79ae739b60dd944",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.02",
                  "httpPercentReq": "50.0"
                }
              }
            }
          },
          {
            "data": {
              "id": "0b64a340ba3a99d6689c010367a1f1b6",
              "source": "b162e488f1d6f1a18f2869d67eb0ae1e",
              "target": "970d2ee8de958440f033bf77ca4f854e",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.02",
                  "httpPercentReq": "50.0"
                }
              }
            }
          },
          {
            "data": {
              "id": "b1885e2ef068ddf9594f8be8fb18a929",
              "source": "b30b0078325bf2e1adb4d57c4c0c2665",
              "target": "0014f93114dfc7dfda64317e0ea37be2",
              "traffic": {
                "protocol": "",
                "rates": null
              }
            }
          },
          {
            "data": {
              "id": "e0b9d9386c3b3cf210796cfbb2a33f4a",
              "source": "b30b0078325bf2e1adb4d57c4c0c2665",
              "target": "097def22fc18d4fcb78468fda8fdb242",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.36",
                  "httpPercentReq": "10.7"
                }
              }
            }
          },
          {
            "data": {
              "id": "d6e3d788b00561d895c60963863d3167",
              "source": "b30b0078325bf2e1adb4d57c4c0c2665",
              "target": "0f912b81b9b81bb3b3a8dce28fc066ef",
              "traffic": {
                "protocol": "tcp",
                "rates": {
                  "tcp": "43.74"
                }
              }
            }
          },
          {
            "data": {
              "id": "5b0030a34c41d05784b9f804ff60016a",
              "source": "b30b0078325bf2e1adb4d57c4c0c2665",
              "target": "2b19f7004c1647105dc126850bc8f664",
              "traffic": {
                "protocol": "",
                "rates": null
              }
            }
          },
          {
            "data": {
              "id": "73956793c8ab5ab2900c240a22f6155a",
              "source": "b30b0078325bf2e1adb4d57c4c0c2665",
              "target": "5005424a70ff815391f5febe83fa6d7b",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.02",
                  "http5xx": "0.02",
                  "httpPercentErr": "100.0",
                  "httpPercentReq": "0.5"
                }
              }
            }
          },
          {
            "data": {
              "id": "a4f8f352ae6d1f28c8f0369470069357",
              "source": "b30b0078325bf2e1adb4d57c4c0c2665",
              "target": "7f2aa4cc91f38eb4e3071500df7d8fa2",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.98",
                  "httpPercentReq": "28.9"
                }
              }
            }
          },
          {
            "data": {
              "id": "f96507057636bf722b1874c8c7d1f4f8",
              "source": "b30b0078325bf2e1adb4d57c4c0c2665",
              "target": "c997777c07380445d2d22fd95ce0bce7",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "1.82",
                  "httpPercentReq": "53.5"
                }
              }
            }
          },
          {
            "data": {
              "id": "26fd6c464a1aa55747bd9c2bbb4515ff",
              "source": "b30b0078325bf2e1adb4d57c4c0c2665",
              "target": "fe9b80933173960938d5b9dcbb440bfc",
              "traffic": {
                "protocol": "http",
                "rates": {
                  "http": "0.22",
                  "httpPercentReq": "6.4"
                }
              }
            }
          },
          {
            "data": {
              "id": "b9673d8854e9d7f61265070fd0e50cdd",
              "source": "cba2da1dd480f4f0c255b34001c104d9",
              "target": "f6a22897996f1845306cbee5569acf1b",
              "traffic": {
                "protocol": "tcp",
                "rates": {
                  "tcp": "0.94"
                }
              }
            }
          }
        ]
      },
      "layout": {
        "name": "dagre",
        "fit": false,
        "nodeDimensionsIncludeLabels": true,
        "rankDir": "LR"
      },
      "summaryData": {
        "summaryType": "graph",
        "summaryTarget": null
      },
      "filterState": {
        "edgeLabelMode": "hide",
        "findValue": "",
        "graphType": "service",
        "hideValue": "",
        "showCircuitBreakers": true,
        "showFindHelp": false,
        "showLegend": false,
        "showMissingSidecars": true,
        "showNodeLabels": true,
        "showSecurity": false,
        "showServiceNodes": true,
        "showTrafficAnimation": false,
        "showUnusedNodes": false,
        "showVirtualServices": true
      }
    },
    "messageCenter": {
      "nextId": 8,
      "groups": [
        {
          "id": "systemErrors",
          "title": "Open issues",
          "messages": [],
          "showActions": false,
          "hideIfEmpty": true
        },
        {
          "id": "default",
          "title": "Notifications",
          "messages": [
            {
              "id": 0,
              "content": "Error fetching Grafana Info., Error: [ Grafana URL is not set in Kiali configuration ]",
              "type": "warning",
              "show_notification": false,
              "seen": true,
              "created": "2019-02-19T06:39:28.505Z"
            },
            {
              "id": 1,
              "content": "There was an error when rendering the graph: Can not create edge `d6e3d788b00561d895c60963863d3167` with nonexistant target `0f912b81b9b81bb3b3a8dce28fc066ef`, please try a different layout",
              "type": "error",
              "show_notification": false,
              "seen": true,
              "created": "2019-02-19T06:39:28.604Z"
            },
            {
              "id": 2,
              "content": "There was an error when rendering the graph: Can not create edge `d6e3d788b00561d895c60963863d3167` with nonexistant target `0f912b81b9b81bb3b3a8dce28fc066ef`, please try a different layout",
              "type": "error",
              "show_notification": false,
              "seen": true,
              "created": "2019-02-19T06:39:28.605Z"
            },
            {
              "id": 3,
              "content": "There was an error when rendering the graph: Cannot read property 'nodes' of undefined, please try a different layout",
              "type": "error",
              "show_notification": false,
              "seen": true,
              "created": "2019-02-19T06:39:31.131Z"
            },
            {
              "id": 4,
              "content": "There was an error when rendering the graph: Can not create edge `d6e3d788b00561d895c60963863d3167` with nonexistant target `0f912b81b9b81bb3b3a8dce28fc066ef`, please try a different layout",
              "type": "error",
              "show_notification": false,
              "seen": true,
              "created": "2019-02-19T06:40:12.603Z"
            },
            {
              "id": 5,
              "content": "There was an error when rendering the graph: Can not create edge `d6e3d788b00561d895c60963863d3167` with nonexistant target `0f912b81b9b81bb3b3a8dce28fc066ef`, please try a different layout",
              "type": "error",
              "show_notification": false,
              "seen": true,
              "created": "2019-02-19T06:40:12.605Z"
            },
            {
              "id": 6,
              "content": "There was an error when rendering the graph: Cannot read property 'nodes' of undefined, please try a different layout",
              "type": "error",
              "show_notification": false,
              "seen": false,
              "created": "2019-02-19T06:40:27.766Z"
            },
            {
              "id": 7,
              "content": "There was an error when rendering the graph: Cannot read property 'nodes' of undefined, please try a different layout",
              "type": "error",
              "show_notification": false,
              "seen": false,
              "created": "2019-02-19T06:40:28.715Z"
            }
          ],
          "showActions": true,
          "hideIfEmpty": false
        }
      ],
      "hidden": true,
      "expanded": false,
      "expandedGroupId": "default"
    },
    "namespaces": {
      "activeNamespaces": [
        {
          "name": "test"
        }
      ],
      "isFetching": false,
      "items": [
        {
          "name": "test"
        },
        {
          "name": "default"
        },
        {
          "name": "dev"
        },
        {
          "name": "istio-system"
        },
        {
          "name": "logging"
        },
        {
          "name": "mysql-operator"
        },
        {
          "name": "nginx-ic"
        },
        {
          "name": "prometheus-operator"
        },
        {
          "name": "stage"
        }
      ],
      "lastUpdated": "2019-02-19T06:39:28.332Z",
      "filter": ""
    },
    "serverConfig": {
      "istioNamespace": "istio-system",
      "istioLabels": {
        "appLabelName": "app",
        "versionLabelName": "version"
      },
      "prometheus": {
        "globalScrapeInterval": 15,
        "storageTsdbRetention": 21600
      }
    },
    "statusState": {
      "status": {
        "Istio mTLS": "error",
        "Kiali console version": "0.15.0-SNAPSHOT.3403",
        "Kiali core commit hash": "f20762a59f94bfbebb71dccb6116f9b1e6e8f5fe",
        "Kiali core version": "v0.15.0-SNAPSHOT",
        "Kiali state": "running"
      },
      "components": [
        {
          "name": "Istio",
          "version": "1.0.3"
        },
        {
          "name": "Prometheus",
          "version": "2.3.1"
        },
        {
          "name": "Kubernetes",
          "version": "v1.11.5-gke.5"
        }
      ],
      "warningMessages": []
    },
    "userSettings": {
      "interface": {
        "navCollapse": false
      },
      "duration": 60,
      "refreshInterval": 15000
    },
    "_persist": {
      "version": -1,
      "rehydrated": true
    }
  }
}

**Comment by abonas** [comment] 2019-02-19 12:43
Here's what looks to me as the potential root cause:

There is a link that fails to be created between the "unknown" node (id b30b0078325bf2e1adb4d57c4c0c2665) to another entity with id 0f912b81b9b81bb3b3a8dce28fc066ef.

This is the relevant data structure:
"data": {
"id": "d6e3d788b00561d895c60963863d3167",
"source": "b30b0078325bf2e1adb4d57c4c0c2665",
"target": "0f912b81b9b81bb3b3a8dce28fc066ef",
"traffic": {
"protocol": "tcp",
"rates": {
"tcp": "43.74"
}

In the attached workload graph, there are 8 links between "unknown" and other graph nodes. 
7 of them are through service entity.
the 8th one is connected directly to workload, not via a service.
It is also a tcp one, which looks like the only tcp connection from "unknown" in the screenshot.

So it looks to me (@jshaughn @israel-hdez @jmazzitelli please confirm) that the service graph fails to load because there should be a link here, but the service is missing.

@iftachsc can you identify this link on the screenshot and check/confirm why a service is missing? it's the 4th one from the top on the graph with link from unknown, the link is blue, leading to some workload with deleted name so I can't tell (it's a circle, services are a triangle)

**Comment by jshaughn** [comment] 2019-02-19 12:54
@abonas , Good investigation, I independently noticed the same thing in the workload graph.I was about to reply when I saw you had already posted the same :)   So, the service graph generation seems to have an issue.  It's not a rendering problem as we can see in the JSON that the terminal node is missing a definition.  It is probably due to some assumption that all requests in the service-injected workload graph would go through a service node.  I'm not sure why we actually see an edge directly to a workload, it does seem odd.  But most likely we need to handle that situation.  @iftachsc , please do let us know if that node is something unusual.  I'll see if i can recreate this now.

**Comment by jshaughn** [comment] 2019-02-19 13:06
I created [Jira Kiali-2412](https://issues.jboss.org/browse/KIALI-2412).

**Comment by abonas** [comment] 2019-02-19 13:12
@jshaughn What's strange is that there is a node definition missing for 0f912b81b9b81bb3b3a8dce28fc066ef no matter which type that node is, perhaps it's somehow omitted during graph generation, but I did not find the evidence in code.
Is there a way to trace id 0f912b81b9b81bb3b3a8dce28fc066ef ? is it generated just for cytoscape or is used elsewhere as well?

**Comment by jshaughn** [comment] 2019-02-19 13:23
@abonas Service graph generation is unlike other graphs.  It is done by generating a service-injected workload graph and then "reducing" it to a service graph.  That reduction probably has an issue.  I'm investigating.

**Comment by abonas** [comment] 2019-02-19 13:24
> @abonas Service graph generation is unlike other graphs. It is done by generating a service-injected workload graph and then "reducing" it to a service graph. 

yes, I'm aware :)

> That reduction probably has an issue. I'm investigating.

thanks

**Comment by jshaughn** [comment] 2019-02-19 16:57
@abonas @iftachsc , There is a PR for this issue.  The solution is basically to ignore workload-to-workload traffic in the service graph because the requests are not requesting a service, but rather explicitly accessing a workload.  Or, it could possibly be caused by incomplete telemetry.  See [Jira Kiali-2412](https://issues.jboss.org/browse/KIALI-2412). for more.

**Comment by jshaughn** [comment] 2019-02-20 13:13
@iftachsc, The fix has been merged.  Please let us know the result when you get a chance to try it in the problem environment.  Thanks, Jay

**Comment by iftachsc** [comment] 2019-02-24 07:27
Bug is indeed fixed! thank you so much. now our service graph can be used and make our life much easier since all other graphs render 2 nodes per service and with 40-50 microservice and some mesh external nodes its hard to really observe since screen is full of nodes and lines. so THANK YOU! very much. your response times are amazing. we all appreciate this. we will keep open on everything we see.

**Comment by iftachsc** [comment] 2019-02-24 07:27
you can go ahead and close this bug.

**Closed** 2019-02-24 11:50 UTC

**Comment by jshaughn** [comment] 2019-02-25 14:01
> since all other graphs render 2 nodes per service...

@iftachsc , just a note that there is an option 'Display->Service Nodes' that is enabled by default.  If you want the other graph types to omit the service nodes you can uncheck this option.  This will remove non-leaf "triangle" service nodes and typically leave you with a smaller graph displaying only app and workload nodes.

**Comment by jshaughn** [comment] 2019-02-25 14:03
@iftachsc  One more comment, have you tried the Graph Find/Hide feature to highlight/remove graph elements of interest?  It is another way to manage larger graphs.
