### ISSUE TITLE
Wrong KIA1106 "More than one Virtual Service for same host"

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4641] opened 2022-01-10 09:10 UTC
In a demo environment:
![image](https://user-images.githubusercontent.com/1662329/148741206-6eb16a38-f6c2-40c2-baca-d5bd08e7c9d5.png)

I got a wrong message with 2 VS:
![image](https://user-images.githubusercontent.com/1662329/148741595-adb58821-f782-4670-bd80-3bb40f474a01.png)
![image](https://user-images.githubusercontent.com/1662329/148741643-ecd71b8d-413f-46e2-9db5-1e8fc1ad0a08.png)

It's possible that this is a side effect of the WIP related to better using the Istio Registry for host detection, but I have the impression that there is a regression in the code.

**Comment by hhovsepy** [comment] 2022-01-10 13:13
This is general regression issue for all validations, happens after https://github.com/kiali/kiali/pull/4535 merged.
The issue is: that exported Istio Configs are retrieved from Registry and they contains own namespace Configs as well, which is causing duplication, thus the validation issues happens for all configs.
Solution is to have single list fo Configs for validations.
Needs to be resolved ASAP as a blocker issue.

**Closed** 2022-01-13 11:28 UTC
Labels: bug, blocker, backlog
