### ISSUE TITLE
Error in metrics with master version

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1717] opened 2019-09-24 09:18 UTC
```bash
Unhandled Rejection (TypeError): series.forEach is not a function
extractLabelsSettingsOnSeries
src/components/Metrics/Helper.ts:47
  44 |   aggregations: AggregationModel[],
  45 |   extracted: LabelsSettings
  46 | ): void => {
> 47 |   series.forEach(ts => {
  48 |     Object.keys(ts.labelSet).forEach(k => {
  49 |       const agg = aggregations.find(a => a.label === k);
  50 |       if (agg) {
```
```typescript

export const extractLabelsSettingsOnSeries = (
  series: TimeSeries[],
  aggregations: AggregationModel[],
  extracted: LabelsSettings
): void => {
  series.forEach(ts => {
    Object.keys(ts.labelSet).forEach(k => {
      const agg = aggregations.find(a => a.label === k);
      if (agg) {
        const value = ts.labelSet[k];
        let lblObj = extracted.get(agg.label);
        if (!lblObj) {
          lblObj = {
            checked: true,
            displayName: agg.displayName,
            values: {},
            defaultValue: true
          };
          extracted.set(agg.label, lblObj);
        } else {
          lblObj.checked = true;
        }
        lblObj.values[value] = true;
      }
    });
  });
};

```

**Comment by jotak** [comment] 2019-09-24 13:52
@aljesusg can you detail in which situation you saw that? Inbound/outbound metrics, on workloads / apps? Is it systematic?

**Comment by jotak** [comment] 2019-09-24 15:33
Can you please provide more details? I can't reproduce.

**Comment by jotak** [comment] 2019-09-26 06:47
Closing as it seems to be an issue in @aljesusg 's environment (afaik nobody else have seen this). To be reopened if it's seen again.

**Closed by jotak** 2019-09-26 06:47 UTC
Labels: backlog, bug, p1
