### ISSUE TITLE
Kiali Graph view renders duplicate ServiceEntries when multiple namespaces are selected

### ISSUE THREAD

**Issue by erSitzt** [kiali/kiali#2964] opened 2020-07-06 09:25 UTC
**Describe the bug**
Graph displays duplicate ServiceEntries when both the namespace of the originating request and the namespace where the ServiceEntry is created are selected

**Example with one namespace in kiali selected**

![image](https://user-images.githubusercontent.com/1625376/86577672-e2c99b00-bf7a-11ea-86b0-375f5c5ce8f1.png)

**And with both namespaces selected**

![image](https://user-images.githubusercontent.com/1625376/86577690-ebba6c80-bf7a-11ea-80b5-6c784a8f4f1a.png)

**Versions used**
Kiali-ui
1.9.1 (83c6a25f96163c26b4959d5b89ac67a6a2b52da9)
Kiali
v1.9.1 (2431f9b8844202e27ec1c92f404fe7485253ffec)
Components
Istio
1.4.7 (Rancher integrated Helm Chart)
Prometheus
2.17.2
Kubernetes
v1.17.4 (Rancher)

**To Reproduce**
1. Create ServiceEntry in a namespace other than the workload using it
2. Open Kiali Graph view
3. Select only the workload namespace
4. Select both workload and ServiceEntry namespace

**Expected behavior**
Show a single node for the ServiceEntry in Kiali Graph

**Comment by jshaughn** [comment] 2020-07-06 12:41
@erSitzt Thanks for your report, I've prioritized this for our current sprint, so we should be investigating soon. -Jay

**Comment by jshaughn** [comment] 2020-08-04 19:17
@erSitzt This is actually expected behavior I think.  ServiceEntries are exported to namespaces, so the "same" service entry can exist in multiple namespaces.  In v1.22 of Kiali we are now enssuring the service entry node reflects the namespace it is in, when selecting multi-namespace graphs.  Hopefully that distinction will show that the nodes are in fact different.

**Comment by jshaughn** [comment] 2020-08-06 18:32
@erSitzt I'm going to close this based on my comment above.  I still hope to hear back from you and please feel free to re-open.

**Closed by jshaughn** 2020-08-06 18:32 UTC
Labels: backlog, bug, team/saturn

**Comment by erSitzt** [comment] 2020-08-06 18:54
@jshaughn i'm not sure its the same thing as you describe.
i only moved the serviceentries into a separate namespace, because they are used from multiple deployments in different namespaces and i did not want mix up everything.

so that particular serviceentry only exists once, only in the istio-serviceentries namespace, but as soon as i select both the namespace of the deployment using it and the namespace where the serviceentry itself is located, it gets duplicated in the graph

**Comment by erSitzt** [comment] 2020-08-06 18:54
it has been a few days, but i can verify my setup and that behavior if it helps

**Comment by jshaughn** [comment] 2020-08-06 19:22
@erSitzt It's possible that there is an issue but there have been a lot of changes since Istio 1.4 and Kiali 1.9, both out of support.  If you re-test with a newer environment let me know the results.

**Comment by erSitzt** [comment] 2020-08-06 19:32
Ok, will do😊
