### ISSUE TITLE
kiali hangs if istiod pod is evicted

### ISSUE THREAD

**Issue by Ottovsky** [kiali/kiali#5103] opened 2022-05-23 11:20 UTC
When running kiali `v1.50.0`, I noticed that it suddenly stopped working with following error messages:
```
2022-05-23T10:56:53Z ERR Failed to call Istiod endpoint /debug/configz error: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
2022-05-23T10:56:53Z ERR Failed to call Istiod endpoint /debug/endpointz error: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
2022-05-23T10:56:53Z ERR Failed to call Istiod endpoint /debug/registryz error: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
2022-05-23T10:56:54Z ERR Failed to call Istiod endpoint /debug/configz error: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
2022-05-23T10:56:55Z ERR Failed to call Istiod endpoint /debug/endpointz error: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
2022-05-23T10:56:55Z ERR Failed to call Istiod endpoint /debug/registryz error: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
```

After some investigation, it turned out that some of the `istiod` pods were evicted from one of the nodes in the cluster but were still present in the kubernetes  API. After I removed them from kubernetes API, kiali started working again. 

It looks like there is problem with the following line [kubernetes/istio.go#L82](https://github.com/kiali/kiali/blob/v1.50.0/kubernetes/istio.go#L82) , it assumes that first pod in the `istiods` list is healthy, which is not always the case. I suspect it should be using `healthyIstiods[0].Name`.

**Comment by lucasponce** [comment] 2022-05-23 11:25
> After some investigation, it turned out that some of the istiod pods were evicted from one of the nodes in the cluster but were still present in the kubernetes API. After I removed them from kubernetes API, kiali started working again.

I think that's not a new issue, problem is that from kubernetes perspective, an evicted pod may have a grace period that is marked as healthy, then Kiali can't do anything but log the error in that case.

For reference, this is a clone of this issue https://github.com/kiali/kiali/issues/4672

I think first step would be to work first at admin level in evicted scenarios, but if there is new information that Kiali can use to query one pod and no other, is something to consider.

**Comment by lucasponce** [comment] 2022-05-23 11:26
As commented, typically an evicted "istiod" pod may show capacity problems at the cluster level.

**Comment by Ottovsky** [comment] 2022-05-23 11:32
The eviction is the standard part of the pods lifecycle in the managed k8s clusters, especially if those are set to follow release channels. The question is why kiali tries to connect to the unhealthy istiod. It should try to connect to the first healthy instance and not pick first entry from list of all istiod instances.

**Comment by lucasponce** [comment] 2022-05-23 11:34
https://github.com/kiali/kiali/issues/4672#issuecomment-1090053589

I think the issue is that the evicted pod is not marked as "unhealthy" in the Kubernetes API, and that's the gap we are seeing.

But, if you have some suggestions with that code, happy to review them.

**Comment by lucasponce** [comment] 2022-05-24 08:49
Hi @Ottovsky, I'm going to close this issue, we can continue the discussion on the #4672 as it's the same topic.

If we have any new info/data, we can re-open it.

**Closed by lucasponce** 2022-05-24 08:49 UTC
Labels: bug
