### ISSUE TITLE
Develop a mock backend server for local UI work in scalability scenarios

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4585] opened 2021-12-14 08:47 UTC
During the scalability discussion, https://github.com/kiali/kiali/discussions/4518 or https://github.com/kiali/kiali/discussions/4080 one of the challenges identified is how to test a large deployment. 

Developers use small clusters for feature works and there is the need to improve the mocks artifacts to have tools that allow focusing on large deployments without the need to get access to such large infrastructure.

One of the areas identified is the graph usability, where there are some areas in the UI to improve, but as a preliminary step, we'd need to have a better local mock server.

This issue aims to provide an optional mock server that may work as UI proxy:

![image](https://user-images.githubusercontent.com/1662329/145963574-8100713d-b368-4f1c-88b7-bdb5a8dc00be.png)

And would let the developer easily mock the backend calls:

![image](https://user-images.githubusercontent.com/1662329/145963674-3c96463e-8785-4fdf-8b39-ac24b5174a76.png)

As a first thought, the backend calls can be grouped in folders, and as a developer, I can populate those folders as a .json from a real backend, which I can modify later to use in a pure UI standalone work.

The goal here would be to have a mock-up for very large scenarios (hundreds of namespaces) without the need of having a real backend process, in that way, the productivity UI work could be greatly improved.

I wouldn't like to reinvent any existing framework, but on the other hand, we should be able to easily mock any endpoint in a very straightforward way (i.e. I've just copied a JSON to a folder and the UI can use those data like a real endpoint).

Tasks:
- [x] Tool to generate graph json data for different large scale scenarios: https://github.com/kiali/kiali/pull/4658
- [ ] #4665

Suggested test plan (QE @mattmahoneyrh):
- The goal of this Epic is to provide a Developer tool for working "offline" in the UI using large topologies. There is no expectation to have a "formal" QE test for this, but the discussion and the effort may be interesting and it may have synergies with other QE efforts as well.

**Comment by nrfox** [comment] 2021-12-14 15:52
Thanks for opening this. I briefly looked into using kiali's openapi spec to create a mock server implementation. An advantage of using the openapi spec is that it will get updated automatically as the api changes. 

There seemed to be some circular dependencies in the openapi spec perhaps caused by the generation tool we're using. [AuthorizationPolicy](https://github.com/kiali/kiali/blob/master/swagger.json#L4562) references itself which I guess is valid until you want to generate clients/servers from the spec.

**Comment by lucasponce** [comment] 2021-12-14 16:06
In my mind I was thinking in something pretty simple, that would give flexibility to capture a .json from a response in a live server and put it in a folder, ready to be served. Perhaps some regex when using an endpoint with parameters but something that would need a lot of maintenance.

But +1 for ideas, I'm not familiar and probably there should be some framework that fits here.
If the mocking server you had in mind supports to reuse a .json that sounds good to me.

**Comment by nrfox** [comment] 2021-12-14 19:18
> In my mind I was thinking in something pretty simple, that would give flexibility to capture a .json from a response in a live server and put it in a folder, ready to be served. Perhaps some regex when using an endpoint with parameters but something that would need a lot of maintenance.

That's pretty much what I was thinking as well. I was hoping to avoid needing to manually stub out the various api endpoints by using the openapi spec to generate them but I think we'll need to fix the openapi spec first.

I briefly looked at [prism](https://meta.stoplight.io/docs/prism/ZG9jOjkz-concepts#mocking) but didn't see a way to easily serve up predefined responses using that tool.

**Comment by lucasponce** [comment] 2021-12-15 08:12
May be we need a simple file server like in the good Apache days.
For example, this would be my flow:
1.- Update the UI proxy with the local server `"proxy": "http://localhost:8100",`
2.- A target in the package.json may start this i.e. `yarn start:local-server`
3.- Then a query like this:
```
GET http://localhost:8100/api/namespaces/not-exist/services/test
```
can be translated into server a .json file
```
${KIALI_UI}/local-server/api/namespaces/not-exist/services/test/GET.json
```
4.- For queries with web parameters, those can be mapped in the json name in some convention.
I.e.
```
GET http://localhost:8100/api/istio/permissions?namespaces=alpha,beta,default,electronic-shop,istio-system,travel-agency,travel-control,travel-portal
```
can be translated into a .json with name:
```
${KIALI_UI}/local-server/api/istio/permissions/GET-namespaces_alpha_beta_default_etc.json
```

No need to be very sophisticated, more like to extend a helloworld example of basic server coded in NodeJS used as an alternative proxy for these needs.

Because we'll keep using the UI with different proxies (a local backend Kiali, or pointing to another process), but with this mock server we could update and simulate these queries for some scenarios.

**Comment by nrfox** [comment] 2021-12-15 18:48
> May be we need a simple file server like in the good Apache days.

This sounds good to start with.

> For queries with web parameters, those can be mapped in the json name in some convention.

This sounds pretty tedious to deal with and another reason we can hopefully autogenerate this kind of thing in the future. In the short term, instead of capturing _all_ the possible parameters, perhaps we can just start with one or two variations.

> server coded in NodeJS 

Does it have to be :D?

**Comment by ScriptingShrimp** [comment] 2021-12-15 20:57
>The goal here would be to have a mock up for very large scenarios (hundreds of namespaces) without the need of having a real backend process, in that way, the productivity UI work could be greatly improved.

Lets go with Cypress.
https://docs.cypress.io/guides/guides/network-requests#Stubbing
https://docs.cypress.io/guides/guides/network-requests#Fixtures

I can do demo for that if you want.

**Comment by lucasponce** [comment] 2021-12-16 08:30
> I can do demo for that if you want.

+1 @ScriptingShrimp, if it helps, the ideal Developers flow should be something as described in https://github.com/kiali/kiali/issues/4585#issuecomment-994477157

I mean as one of the risk to avoid is to introduce a comprenhensive/complex framework that make developers to spend time updating.

But I'm sure some of the frameworks there should be useful :), please, feel free to prepare anything and we can evaluate.

**Comment by nrfox** [comment] 2021-12-21 01:36
Regardless of what serves up the json files, it'd be nice to have a tool to generate the data based on some selections similar to the [topology generator](https://github.com/kiali/demos/tree/master/topology-generator) but instead of yaml it'd produce the graph data (nodes/edges). Otherwise handwriting a large graph will not be fun.

**Comment by lucasponce** [comment] 2021-12-21 10:16
> Regardless of what serves up the json files, it'd be nice to have a tool to generate the data based on some selections similar to the topology generator but instead of yaml it'd produce the graph data (nodes/edges). Otherwise handwriting a large graph will not be fun.

+1

**Comment by nrfox** [comment] 2022-01-05 19:01
Going to work on a small CLI tool that does this:
> Regardless of what serves up the json files, it'd be nice to have a tool to generate the data based on some selections similar to the topology generator but instead of yaml it'd produce the graph data (nodes/edges). Otherwise handwriting a large graph will not be fun.

A rough outline is to just import the cytoscape models from github.com/kiali/kiali/graph/config/cytoscape and to output some json files. User input can determine the size of graph generated.

**Comment by nrfox** [comment] 2022-01-17 20:02
@lucasponce I'm going to edit the main comment and add some subtasks there to make it easier to track work for the epic.

**Comment by nrfox** [comment] 2022-02-28 19:13
Marking this as done since this tool can presently be used for testing large graph scenarios. Some improvements can be made such as 1. Customizable number of namespaces created 2. Options to generate different types of graph but this can be followup work. The UI work for automating testing of large graphs will be a separate issue.

**Closed by nrfox** 2022-02-28 19:13 UTC
Labels: epic, backlog
