### ISSUE TITLE
Kiali UI - Graph URL doesn't persist namespace selection on refresh

### ISSUE THREAD

**Issue by iliogr** [kiali/kiali#618] opened 2018-11-01 19:23 UTC
The UI doesn't persist the namespace selection on the Graph view. To reproduce this: 

1. Go to the UI on the graph view
2. Choose a namespace from the dropdown
3. Now, if you refresh the page, the UI goes back to showing all namespaces.

The UI should be persisting the namespace selection (and all other selections) on refresh.

**Comment by jshaughn** [comment] 2018-11-02 13:37
I see this as well.  I think the root cause is probably the same as for https://issues.jboss.org/browse/KIALI-1782.  I will update that Jira to say that bookmarkability seems more generally broken.  This is scheduled to be fixed sometime in the next week.

**Comment by jshaughn** [comment] 2018-11-06 16:27
@iliogr , This has been fixed in master and should work as expected in the next release or using the latest container.

**Closed by jshaughn** 2018-11-06 16:27 UTC
