### ISSUE TITLE
Could not fetch TLS status: json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint

### ISSUE THREAD

**Issue by snahil** [kiali/kiali#6591] opened 2023-09-08 07:21 UTC
Could not fetch TLS status: json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint & Danger alert:Error fetching Mesh-wide mTLS status.
**I have tested the kali server installation individually and with the operator getting the same error every time**
**Versions used**
**base-1.19.0 
gateway-1.19.0
kiali-operator-1.73.0
istiod-1.19.0**
Helm version 3.10

**Comment by jmazzitelli** [comment] 2023-09-08 10:50
dup: https://github.com/kiali/kiali/issues/6510

**Comment by jmazzitelli** [comment] 2023-09-08 10:51
@howardjohn this person is saying they see this in 1.19 - wasn't this breaking change going in 1.20, not 1.19?

**Comment by jmazzitelli** [comment] 2023-09-08 10:56
@snahil please provide a full stack trace found in the kiali server pod logs

**Comment by snahil** [comment] 2023-09-08 11:58
2023-09-08T09:17:26Z ERR Error fetching availability of the tracing service: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup tracing.istio-system on 172.20.0.10:53: no such host"
2023-09-08T09:17:26Z ERR Error parsing RegistryEndpoints results: json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint
2023-09-08T09:17:26Z ERR Error parsing RegistryEndpoints results: json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint
2023-09-08T09:17:26Z ERR json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint
2023-09-08T09:17:26Z ERR Error parsing RegistryEndpoints results: json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint
2023-09-08T09:17:27Z ERR Error parsing RegistryEndpoints results: json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint
2023-09-08T09:17:27Z ERR Error fetching Registry Services per namespace poc-k8s: json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint
2023-09-08T09:17:27Z ERR json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint: goroutine 300707 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/debug/stack.go:24 +0x65
github.com/kiali/kiali/handlers.handlePanic({0x2391840, 0xc0008c8930})
        /home/runner/work/kiali/kiali/handlers/graph.go:86 +0x219
panic({0x1c74180, 0xc001af4db0})
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884 +0x213
github.com/kiali/kiali/graph.CheckError(...)
        /home/runner/work/kiali/kiali/graph/util.go:38
github.com/kiali/kiali/graph/telemetry/istio/appender.getServiceList({0xc001af7700, 0xa}, {0xc0018d8710, 0x7}, 0xc00329b2c0)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/appender.go:291 +0x314
github.com/kiali/kiali/graph/telemetry/istio/appender.getServiceLists(0x8?, {0xc0018d8710, 0x7}, 0xc0007f6d80?)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/appender.go:264 +0xac
github.com/kiali/kiali/graph/telemetry/istio/appender.IstioAppender.AppendGraph({0x2089134?}, 0xc00329b320, 0xc0023a8810?, 0xc000cb4438)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/istio_details.go:47 +0x65
github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap({_, _}, {0xc00329b140, {0x0, {0xc001e54120, 0x6, 0x6}}, 0x0, 0x1, 0xc00329b080, ...}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:80 +0x6a3
github.com/kiali/kiali/graph/api.graphNamespacesIstio({_, _}, _, _, {{0x208eb3f, 0x9}, {0x2089134, 0x5}, {{0xc0018d8679, 0x15}, ...}, ...})
        /home/runner/work/kiali/kiali/graph/api/api.go:52 +0x126
github.com/kiali/kiali/graph/api.GraphNamespaces({_, _}, _, {{0x208eb3f, 0x9}, {0x2089134, 0x5}, {{0xc0018d8679, 0x15}, {0xdf8475800, ...}}, ...})
        /home/runner/work/kiali/kiali/graph/api/api.go:33 +0x2fb
github.com/kiali/kiali/handlers.GraphNamespaces({0x2391840, 0xc0008c8930}, 0xc000969300)
        /home/runner/work/kiali/kiali/handlers/graph.go:51 +0x165
net/http.HandlerFunc.ServeHTTP(0x20970a6?, {0x2391840?, 0xc0008c8930?}, 0x7f5a594f8dc0?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/kiali/kiali/routing.metricHandler.func1({0x23a0600?, 0xc0019cc850}, 0xc0008e3401?)
        /home/runner/work/kiali/kiali/routing/router.go:145 +0x13b
net/http.HandlerFunc.ServeHTTP(0x23a1a38?, {0x23a0600?, 0xc0019cc850?}, 0xc0008e3460?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1({0x23a0600, 0xc0019cc850}, 0xc000968f00)
        /home/runner/work/kiali/kiali/handlers/authentication.go:79 +0x3fd
net/http.HandlerFunc.ServeHTTP(0x23a1a38?, {0x23a0600?, 0xc0019cc850?}, 0x2374d30?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/kiali/kiali/server.plainHttpMiddleware.func1({0x23a0600?, 0xc0019cc850?}, 0xc00329aa80?)
        /home/runner/work/kiali/kiali/server/server.go:157 +0x65
net/http.HandlerFunc.ServeHTTP(0xc000968e00?, {0x23a0600?, 0xc0019cc850?}, 0x4?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004ae0c0, {0x23a0600, 0xc0019cc850}, 0xc000968c00)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x23a04b0, 0xc001057500}, 0x0?)
        /home/runner/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x24e
net/http.HandlerFunc.ServeHTTP(0xc00077cd80?, {0x23a04b0?, 0xc001057500?}, 0x40d92a?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0018d8620?, {0x23a04b0, 0xc001057500}, 0xc000968c00)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0xc00329a8d0?}, {0x23a04b0, 0xc001057500}, 0xc000968c00)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc00094c3f0, {0x23a1a38, 0xc000f90150})
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:3089 +0x5ed

**Comment by jmazzitelli** [comment] 2023-09-08 13:25
OK, so its also getting hit in the graph generator. I'm pretty sure this is a duplicate of https://github.com/kiali/kiali/issues/6510

**Comment by jmazzitelli** [comment] 2023-09-08 13:26
Yes, stack traces come from the same place. Closing as duplicate of #6510

**Closed by jmazzitelli** 2023-09-08 13:26 UTC
Labels: bug
