### ISSUE TITLE
Graph Find / Hide: keep a local history

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3180] opened 2020-09-07 08:50 UTC
Feature request: I think it would be interesting to keep some local history for the graph find / hide feature. This would help users to retrieve commonly used formulas quickly, without having to go through the help when not remembering the keywords or operators.

It could take the shape of a "[type-ahead](https://www.patternfly.org/v4/documentation/react/components/select#typeahead)" box, or dropdown list, that opens up when focus is set to graph hide/find, suggesting the last X formulas that were used on this machine. Hence the history would be kept in local browser storage.

![Capture d’écran de 2020-09-07 10-38-48](https://user-images.githubusercontent.com/2153442/92368080-865c3680-f0f7-11ea-9142-fa222a1a1ca8.png)

Thoughts?

**Comment by jshaughn** [comment] 2020-09-15 13:09
@jotak This is actually a duplicate of https://github.com/kiali/kiali/issues/2329, which was closed due to lack of community interest/upvote.  Instead we just apply the browser autocomplete.  I'm not saying it wouldn't be nice, only that the prioritydoesn't seem to be there.  I'll add the Help Wanted tag and leave it open for a while to see if anyone wants to pick it up, or if you are really interested there is hack n' hustle.  By the way, have you tried the autocomplete for the operands, that can help as well.  Use `Tab` to see your autocomplete options when typing the operand names.

**Comment by jotak** [comment] 2020-09-15 14:15
I didn't know the autocomplete, that's nice indeed! When you say it autocompletes operands, is it just the left operand or also the right one, based on graph content?
In my example I try to hide "service startswith jaeger" ; only "service" here is autocompleted, is that expected?
Also I'm not sure what to expect about the browser autocomplete, but it doesn't work for me, perhaps some browser settings? (using firefox)

**Comment by jshaughn** [comment] 2020-09-15 14:47
> I didn't know the autocomplete, that's nice indeed! When you say it autocompletes operands, is it just the left operand or also the right one, based on graph content?

Right, that is expected. At the moment it only autocompletes the LHS of the expression, the static set of operands.  RHS would be pretty nice but it would be a more complex addition and based on the dynamic graph content.

I also don't fully understand how the browser determines what to offer in its dropdown of previous entries, it's browser-specific behavior and I have not been able to figure out what it decides to display.  It is sometimes helpful on chrome.

**Comment by lucasponce** [comment] 2021-02-16 12:41
I think this could be part of the #3708 discussion.
It's also touching similar aspects (but different approaches) for this feautre.

I'm going to close this one to consolidate the discussion in #3708 issue.

**Closed by lucasponce** 2021-02-16 12:41 UTC
Labels: enhancement, help wanted
