### ISSUE TITLE
Windows platform developer support

### ISSUE THREAD

**Issue by PmcFizz** [kiali/kiali#3154] opened 2020-08-26 09:14 UTC
**Is your feature request related to a problem? Please describe.**
I use a windows computer develop `kiali/ui` but the run script don't run

**Describe the solution you'd like**
on windows platform can develop ui project.

**Describe alternatives you've considered**
can add `cross-env` to fix cross platform problem

**Additional context**
This is a great project

**Comment by lucasponce** [comment] 2020-08-26 09:20
Thanks @PmcFizz for the feedback.
Not sure if we have windows computers in the team, but we are open to contributions, if you'd like to help us to setup the windows config parameters that would help to other users as well.

**Comment by PmcFizz** [comment] 2020-08-26 09:40
ok  It's good.  kiali is a great project. I hope for contribute my code。

**Comment by jmazzitelli** [comment] 2020-08-26 10:57
FYI: @jshaughn has a Windows machine. He doesn't develop on it (he uses a Fedora VM for Kiali dev) but I'm sure he could review any PRs that someone wants to submit for this.

**Comment by jshaughn** [comment] 2020-08-26 16:47
Thanks @PmcFizz.  As @jmazzitelli mentioned, I find it best to run a Fedora VM guest on Win10 host via Virtual Box.  A native Win dev environment could be useful but most likely support would have to be contributed.

**Comment by PmcFizz** [comment] 2020-08-27 01:22
@jshaughn ok, I understand.

**Comment by ps-19** [comment] 2021-07-01 19:45
@lucasponce please assign me this issue. I just need a glitter/slack/discord community.

**Comment by lucasponce** [comment] 2021-07-02 10:22
Ok, thanks @ps-19.
Assigned, feel free to ask if you'd need help.

**Comment by jshaughn** [comment] 2021-07-06 14:01
> I just need a glitter/slack/discord community of kiali.

@ps-19 You can find us on the #kiali channel of Istio slack.   And we will respond to any comments here in this github issue, or subsequent PRs.

**Comment by lucasponce** [comment] 2021-08-06 08:58
@ps-19 any update on this issue ?

**Comment by ps-19** [comment] 2021-08-06 14:46
I am sorry, the issue is little bit tougher to resolve at my level.

**Comment by jshaughn** [comment] 2022-11-30 18:09
Possibly useful but closing as part of routine backlog maintenance.  Can be re-opened by anyone wishing to contribute.

**Closed by jshaughn** 2022-11-30 18:09 UTC
Labels: enhancement, help wanted, future
