### ISSUE TITLE
Istio Analysis lost the severity on their messages, kiali is broken

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#3505] opened 2020-12-07 12:38 UTC
Opened an issue in Istio side since the source of the problem comes from there: https://github.com/istio/istio/issues/29445

Besides that, I'd be good to prevent this changes to break kiali.

To reproduce:

```
istioctl install --set profile=demo --set values.pilot.env.PILOT_ENABLE_STATUS=true --set values.global.istiod.enableAnalysis=true

k apply -f samples/bookinfo/platform/kube/bookinfo.yaml -n bookinfo

k apply -f samples/bookinfo/networking/fault-injection-details-v1.yaml -n bookinfo
```

Open Kiali into the `details` virtual service detail page. It'll break the page.

**Comment by jshaughn** [comment] 2020-12-07 15:51
@lucasponce After talking with @xeviknal it looks like this is a regression in Istio 1.8, maybe 1.7, but likely does not affect 1.6.  So, assigning to Xavi to protect Kiali while we wait for a fix from Istio.  It doesn't seem like there is an issue with productized versions.

**Comment by lucasponce** [comment] 2020-12-09 09:03
@xeviknal but the problem here is that the status field populated in istio can be malformed and Kiali should check that.
Am I understanding it ?

**Comment by xeviknal** [comment] 2020-12-09 09:39
yes, exactly it. Istio has a bug and it doesn't send all the expected values. Kiali should prevent breaking in case some data is not present.

**Closed** 2021-01-12 09:46 UTC
Labels: backlog, bug, team/jupiter
