### ISSUE TITLE
Exclude "Out of mesh" for auto generated workloads

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#7618] opened 2024-08-12 13:13 UTC
### What do you want to improve?
When we create a k8s gateway a workload is generated and it is marked as "Out of mesh", but if it shouldn't be part of the mesh, probably there should be excluded somehow (Maybe based on labels?)

![image](https://github.com/user-attachments/assets/d98c1c96-8a28-4d72-a13e-bac179dfc7a0)

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: agency-gateway
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: agency
spec:
  parentRefs:
  - name: agency-gateway
```

### What is the current behavior?
Auto generated workload shown as part of the mesh.

### What is the new behavior?
No "Out of mesh" warning for this workloads generated by the k8s Gateway.

Fixed by https://github.com/kiali/kiali/pull/7721

**Comment by jshaughn** [comment] 2024-09-10 16:38
@josunect Is this now a duplicate of https://github.com/kiali/kiali/issues/7720?

**Comment by josunect** [comment] 2024-09-11 07:03
> @josunect Is this now a duplicate of #7720?

Right, @jshaughn. I added the "Fixed by", but we can also close it.

**Closed** 2024-09-11 08:18 UTC
Labels: enhancement, research
