### ISSUE TITLE
Workload not being shown when using Openshift deployment config to deploy an app

### ISSUE THREAD

**Issue by SionArtingstall** [kiali/kiali#3295] opened 2020-10-06 12:52 UTC
**Describe the bug**
When I deploy an application using a deployment config in OpenShift the application does not appear in the workloads section in Kiali.  A build type is showing as well from an old build which is no longer deployed.

**Versions used**
Kiali:Version: v1.12.10.redhat2
Istio: Openshift Service Mesh - servicemeshoperator.v1.1.9
Openshift 4.4.20_1518 on managed IBM cloud

**To Reproduce**
1. Create a Deployment config on Openshift including sidecar inject annotation to deploy an app in Openshift OR create a build from a build configuration to create a deployment.  Istio proxy container successfully spins up.
2. Navigate to workloads in Kiali
3. Workload for deployment config does not appear.  Workload of type build for the build config does appear, but only for thre build pod and not the actual deployed app.
4. Click on the build type workload to bring up details.  Error show (attached)

**Expected [behavior]([url]([url](url
![Screenshot 2020-10-06 at 13 48 36](https://user-images.githubusercontent.com/55177718/95203749-15359f00-07db-11eb-918f-a90961115b41.png)
![Screenshot 2020-10-06 at 13 48 21](https://user-images.githubusercontent.com/55177718/95203758-1666cc00-07db-11eb-9aa4-3383baa0acd8.png)

)))**
In workloads the app deployed as a deployment config should show in the workloads.  
App deployed as a build type should show the deployed app as a workload and not the build pod (which has completed by this stage)

**Comment by lucasponce** [comment] 2020-10-06 13:03
@SionArtingstall I know that DeploymentConfig are not fetched as controller by default.
I'm going to add a link to the config to add them from the operator.

**Comment by lucasponce** [comment] 2020-10-06 13:06
@SionArtingstall 

There should be a Kiali CustomResource where you need to change the default values of "excluded_workloads" and remove "DeploymentConfig" and "ReplicationController".

https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L727

**Comment by SionArtingstall** [comment] 2020-10-06 14:40
Thanks @lucasponce will give that a try and let you know.

**Comment by lucasponce** [comment] 2020-10-15 17:15
@SionArtingstall did it work ?
I'm sure it's related the config I commented, but let me know to see if there is any additional investigation on this issue.
Thanks !

**Comment by lucasponce** [comment] 2020-10-30 13:17
@SionArtingstall I'll close the issue, I guess with the change in the config the problem is addressed.
Let me know otherwise and I'll review it.

**Closed by lucasponce** 2020-10-30 13:17 UTC
Labels: bug
