### ISSUE TITLE
Browser console warning on Service Graph Page

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2092] opened 2020-01-13 16:39 UTC
**General remarks**
When you open up the service graph page and look at the browser console a Victory charts warning is displayed:

```
index.js:1 Warning: Failed prop type: Invalid prop `events[0].target` of value `data,labels` supplied to `VictoryChart`, expected one of ["data","labels","parent"].
    in VictoryChart (created by Chart)
    in Chart (at RateChart.tsx:61)
    in RateChart (at RateChart.tsx:132)
    in div (at RateTable.tsx:65)
    in RateTableHttp (at SummaryPanelGraph.tsx:167)
    in section (created by TabContent0)
    in TabContent0 (created by ForwardRef)
    in ForwardRef (created by Tabs)
    in Tabs (created by Context.Consumer)
    in ComponentWithOuia (created by Context.Consumer)
    in Unknown (at SimpleTabs.tsx:30)
    in SimpleTabs (at SummaryPanelGraph.tsx:151)
    in div (at SummaryPanelGraph.tsx:150)
    in div (at SummaryPanelGraph.tsx:145)
    in SummaryPanelGraph (at SummaryPanel.tsx:82)
    in div (at SummaryPanel.tsx:68)
    in SummaryPanel (at GraphPage.tsx:349)
    in div (created by FlexView)
    in FlexView (at GraphPage.tsx:316)
    in div (created by FlexView)
    in FlexView (at GraphPage.tsx:289)
    in GraphPage (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (at RenderPage.tsx:16)
    in Switch (at SwitchErrorBoundary.tsx:42)
    in SwitchErrorBoundary (at RenderPage.tsx:31)
    in div (at RenderPage.tsx:30)
    in RenderPage (at Navigation.tsx:116)
    in section (created by PageSection)
    in PageSection (at Navigation.tsx:115)
    in main (created by Page)
    in div (created by Page)
    in Page (at Navigation.tsx:113)
    in Navigation (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(Navigation)) (at App.tsx:107)
    in Router (at App.tsx:106)
    in AuthenticationController (created by ConnectFunction)
    in ConnectFunction (at App.tsx:117)
    in PersistGate (at App.tsx:115)
    in Provider (at App.tsx:114)
    in App (at src/index.tsx:29)
```

**Comment by jshaughn** [comment] 2020-01-22 20:33
@mtho11 I think this is probably a duplicate of https://github.com/kiali/kiali/issues/2088, both due to the underlying issue in Victory.  Can we close?

**Closed** 2020-01-22 20:39 UTC
Labels: bug, duplicate
