### ISSUE TITLE
Graph Display List Info Icons Are Wrapping

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#3752] opened 2021-03-05 20:40 UTC
Reference the screen-shot.

Tested on Chrome Version 74

![image](https://user-images.githubusercontent.com/7262987/110171016-0a525b00-7dc9-11eb-981d-f0bc80b33abe.png)

**Comment by jshaughn** [comment] 2021-03-08 21:36
I can't reproduce this.  @mattmahoneyrh I know you also tested this on a newer chrome and still had an issue.  We had this issue in the past but it had been fixed.  I wonder if you have some sort of old cached CSS.

**Comment by jshaughn** [comment] 2021-05-27 18:13
I still can't reproduce this.  Closing, re-open at your leisure.

**Closed by jshaughn** 2021-05-27 18:13 UTC
Labels: bug
