### ISSUE TITLE
Add indication on status of validations on the side panel in graph

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1570] opened 2019-08-27 15:57 UTC
Add indication on status of validations on the side panel in graph.

JIRA:
https://issues.jboss.org/browse/KIALI-3222

**Comment by jshaughn** [comment] 2019-12-17 20:16
Duplicate of https://github.com/kiali/kiali/issues/1941

**Closed by jshaughn** 2019-12-17 20:16 UTC
Labels: duplicate, enhancement, jira
