### ISSUE TITLE
Add toggle for "Automatic Resize to Fit" in graph view

### ISSUE THREAD

**Issue by seeruk** [kiali/kiali#2514] opened 2020-03-13 10:26 UTC
**Describe the solution you'd like**

I have a relatively small but very active cluster. I have a TV in the office with a Raspberry Pi connected to it that has the Kiali graph view on it. It's fantastic to be able to turn around and see the state of the cluster at a glance and how traffic is moving, etc. However, the graph moves around and parts of it can leave the screen at certain points. At other times it seems to zoom way further out and you end up with a chart in the corner of the screen.

To get things back to a view that's able to be seen I just go over to the Pi (I've left a mouse in it) and I click "Resize to Fit" manually. Ideally I'd just be able to leave it with a constant overview of the graph that's always the best fit when it changes shape.

I've suggested a toggle because I saw in a closed PR that would've resolved this that it was rejected because it was always enabled - a toggle would be ideal so people don't lose their zoom level, etc. if they don't want to.

**Describe alternatives you've considered**\

Manually clicking the button every refresh interval. Creating a script that clicks the button automatically for me.

**Comment by jshaughn** [comment] 2020-03-13 11:57
I like that Pi-powered monitoring!   I have to say, I am a little surprised that you're graph loses the "fit" on refreshes when you aren't interacting with it manually.  That may actually be a bug.  Please tell us the version of Kiali you are running, the layout you have selected, the graph type,  and whether you are using any non-default options, like a Find and/or Hide expression.  Thanks.

**Comment by seeruk** [comment] 2020-03-13 12:02
Hey there, thanks for looking into this.

Here's the info from Kiali's about modal:

Kiali-ui: 1.9.1 (83c6a25f96163c26b4959d5b89ac67a6a2b52da9)
Kiali: v1.9.1 (2431f9b8844202e27ec1c92f404fe7485253ffec)

Components: 
Istio: 1.5.0
Prometheus: 2.9.2
Kubernetes: v1.14.9-eks-502bfb

The current layout I'm using is cose-bilkent. The graph type is a versioned app graph. I'm just looking at the one namespace currently, it consists of this number of nodes / edges, etc.:

5 apps (5 versions)
26 services
23 workloads
97 edges

(Well, that's what was there this refresh, it does move around a bit, but not too dramatically - it might lose a few nodes between refreshes, but most will always be there).

**Comment by jshaughn** [comment] 2020-03-13 12:49
OK, so Istio is quite up to date but Kiali is a bit old.  The version of Kiali packaged with Istio 1.5 is Kiali 1.14.  I'm not saying the behavior will be different but it may be worth updating Kiali just to be sure.  This may also be related to the nature of cose-bilkent.  Thanks for using Kiali, I'll add this to our backlog.  If you update let us know if you see any difference in behavior.

**Comment by seeruk** [comment] 2020-03-15 12:41
Hey @jshaughn,

Just disabled Istio's Kiali installation and installed the latest version of Kiali:

```
Kiali UI: 1.14.0 (9c29fd77cad6da30df3ec868ffdc6188dc6dacd9)
Kiali Server: v1.14.0 (bb2746facfd6f5ed00c61abceb3c48c9df19ad96)
Kiali Container: v1.14.0

Components
Istio: 1.5.0
Prometheus: 2.9.2
Kubernetes: v1.14.9-eks-502bfb
```

I'm still experiencing this issue, it's on most refreshes that it moves around and the chart jumps to a different position, and sometimes ends up off-screen partially or zoomed out. It actually seems to do it on all of the graph layouts - it's clearly shifting to the most optimal view for what is happening in the cluster at the point where it's refreshed - it just moves it around a bit.

If there's anything you want me to try, or any other info you need I'll do my best to help out!

**Comment by jshaughn** [comment] 2020-03-16 12:54
If you have nodes coming and going I can imagine that the graph will layout differently with each change, as it could affect the layout algorithm.    That would be normal I guess but the fact that you get strange zooming, or somenodes layour off-screen, that certainly does not seem right.  We'll see if we can reproduce.

As a possible workaround, to minimize changes perhaps try a larger duration/time window.  The default is only 1 minute of traffic.  If your monitoring allows you may be able to "smooth" things a by upping that window.

**Comment by jshaughn** [comment] 2020-04-13 16:11
I'll look to see if I can reproduce this.  On casual inspection of the code things look fine, so not sure why this would happen.

**Comment by jshaughn** [comment] 2020-04-15 16:19
I have not really been able to reproduce this issue other than to see the graph layout differently when nodes come and go.  But I have not seen the graph zoom in/out unpredictably nor have portions off-screen.  We did recently update the underlying graphing library we use (in Kiali 1.16.0) but it's probably unlikely to have had an effect on this situation.

@seeruk , which browser are you using?  Or any other information that may be useful?

**Comment by seeruk** [comment] 2020-04-15 17:34
Just the latest version of Chrome, I've had to stick to Kiali 1.14 for now because we're running Istio installed via Helm, and Telemetry V2 can't be enabled via Helm, and we can't upgrade Istio to use istioctl yet because of some bugs surrounding ingress gateway migration.

If it's possible, maybe we could jump on a hangout or something I can just show you it happening?

**Comment by jshaughn** [comment] 2020-04-15 18:01
@seeruk a hangout would work.  And it's not that I doubt it happens, I just can't figure out how to make it happen.  Can you find me on IRC (#kiali on freenode?).  Or send me mail and we can set something up (jshaughn@redhat.com).

**Comment by jshaughn** [comment] 2020-04-16 14:54
After having an online session with @seeruk I can confirm this does happen in his mesh.  The mesh is large and does at times have outlier nodes, otherwise disconnected from most of the other mesh nodes, which are connected.  It could be related to cytoscape, or the layouts, but I'm more leaning towards Kiali because hitting the "Fit" button in the Cy toolbar does reliably scale the mesh to fit within the page space.  I'll keep looking at this.

**Comment by jshaughn** [comment] 2020-04-23 20:47
@seeruk I have a PR for at least one zoom/pan/fit issue I found when using graph-hide.  I'm not sure if this will help your use case but please give it a try when possible.  If it gets merged quickly it will be in Kiali 1.17 (to be released tomorrow).

**Comment by seeruk** [comment] 2020-04-23 21:01
Excellent, if that telemetry V1 tweak is also in then I'll just upgrade straight to 1.17 😄

**Comment by seeruk** [comment] 2020-04-27 09:18
Alright, we're on Kiali 1.17 now - those Telemetry changes all went in fast, thank you guys for doing that.

Now I'm on 1.17, I can definitely feel the performance difference in the graph - it's much faster. I think it also is laying things out slightly differently, in a way that seems easier on the eyes and less grouped up and overlapping.

Unfortunately I am still getting the graph moving around, off screen, and zooming in and out though.

**Comment by jshaughn** [comment] 2020-04-27 13:01
@seeruk Thanks for quickly evaluating 1.17.   I'm glad you are now able to use the new version and that V1 telemetry on 1.5 is working.   I'm also glad to hear about the perfomance boost, most likely due to some caching work now done in Kiali.  As for the zoom/pan/relayout issues, is that with or without a graph hide expression, or either way?  (note that I'm asking only about a hide expression that actually hides some nodes).

**Comment by seeruk** [comment] 2020-04-27 13:20
Aah, so that's quite interesting. I'm now not sure if this is different to before. I've just been watching it for a while without hiding anything, and it has kept everything fit on screen. One issue it does have in that view is that that `efs-provisioner` node that's off on it's own that I was hiding does move around closer to and further from the majority of the services in the cluster in the graph as it refreshes.

Does this mean then that when a node is being hidden, the graph is still evaluating where it would be and trying to accommodate it?

**Comment by jshaughn** [comment] 2020-04-27 13:59
The hide logic is tricky because the nodes still exist, but they are sort of hidden away.  They are not supposed to affect the layout, but sometimes it seems they still do.  On refresh those hidden nodes need to be thrown out, and the newly fetched graph must be reprocessed.  I thought in 1.17 I had improved the "fit" situation when using hide (well, actually I'm sure I did, but still not enough for your topology, it seems).   So, for you now it seems you get a somewhat better experience when not using hide.  With hide, you can also try toggling off the "Compress On Hide" display option and see if that helps, but in general things are better with that option enabled.

By the way, do you like the changes to the graph toolbar?

**Comment by seeruk** [comment] 2020-04-27 15:55
Playing with "Compress Hidden" sadly doesn't help.

> By the way, do you like the changes to the graph toolbar?

Which bit are we talking about here, the changes to the bit up at the top? IIRC it was all in one line before, right? I think I do prefer it one line if I'm honest given my use-case of putting it on a TV. In fact, if there was a full-screen option for just the graph, it's legend, and the info panel on the right then it'd be perfect for my use-case! 😄 

Well, I'm glad we have a clue as to what's going on anyway. Is it possible to not pass any data at all about hidden nodes to the graph library?

**Comment by jshaughn** [comment] 2020-04-27 19:46
Everything was on one line before, yes.  There were a couple of issues that we tried to resolve.  Foremost was the fact the everything-on-one-line approach was very wide, causing wrapping on width-challenged screens.  Second was the fact that the Display dropdown was tall and covered the center of the graph.  Now it is left-adjusted and likely less of an interference.   The edge label options are no consolidated into the display options.  And the graph type has been promoted up to the top line.  Overall we're not using any more vertical space.  The idea of allowing the toobar to toggle, giving more space to the graph, is interesting.

As for graph hide, I'll continue to think about how we may be able to do things to improve the experience.

**Comment by seeruk** [comment] 2020-05-07 12:59
Hey Jay, hope you're keeping well.

Just thought I'd give you a heads up that I've just given v1.18.0-snapshot.0 a try as I saw your merged PR above. If it does contain that change, it's still not done the trick it looks like unfortunately. It is really interesting watching how it behaves though. If I don't hide that `efs-provisioner` node  then the graph remains really quite stable (though still quite spaced out). As soon as I hide that, the graph changes shape and size almost every refresh.

On those changes above, sorry I hadn't taken it all in! I suppose I hop in those menus and tick a couple of options and leave them to it. I can definitely see how it will have been a challenge to fit all of that on one screen now that I look over it - I'm either using my 16" MacBook, or my 1440p desktop displays! I do like that simplification of the menu too, consolidating it into one place makes a ton of sense, I quite often want to mess with the edge labels and the "Show" section. I think with a lot of things like this (like if you build something that isn't slow) if it's working well, you don't notice, but if it's not working well you certainly do!

**Comment by jshaughn** [comment] 2020-05-11 13:21
@seeruk Thanks very much for the continued feedback.  I'm not quite sure at the moment where to go next with the layout-refresh issue.  I'll keep thinking but I may also just report it to cytoscape (the underlying graphing package) because it may just be an issue with their handling of "removed" nodes.

As for the menus, I'm glad you like the change. For me it's nice to have that dropdown on the far left.

**Comment by jshaughn** [comment] 2020-06-01 20:19
@seeruk I tried yet another approach to solve the issue but it didn't pan out.  For now I'd request we close this issue as there is no plan to offer the requested toggle (as we're already doing what we can when the graph refreshes).

We are planning to update cytoscape soon (see https://github.com/kiali/kiali/issues/251), perhaps it will have a benefit.

I would say that if you test with a version including that cytoscape update (probably v1.19 but no later than 1.20), and the problem is not resolved, then please open a Bug issue and we'll keep at it.

**Comment by seeruk** [comment] 2020-06-01 20:36
Sure thing, thanks for all of your efforts so far @jshaughn. It's much appreciated. I'll test the new versions as they come.

Hope you're staying safe.

**Comment by jshaughn** [comment] 2020-06-02 12:54
@seeruk Thanks, you too.  Closing this and we'll open something new if needed after the cytoscape update.

**Closed by jshaughn** 2020-06-02 12:54 UTC
Labels: area/visualization, backlog, enhancement, p1, team/saturn
