### ISSUE TITLE
Spikes on VersionApp Rest endpoint

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1603] opened 2019-08-28 12:36 UTC
Requests on REST endpoint: /api/namespaces/graph?namespaces=bookinfo&graphType=service&duration=600s

Kiali Metrics from Workloads metrics shows that data comes from less 1 seconds response time to 10, 13 seconds response_time which matches what I have been seeing on kiali windsock dashboard.

On total of 153516 requests -

minimum: 42.00 ms
percentile_25: 57.00 ms	
percentile_50: 63.00 ms	
percentile_75: 71.00 ms	
percentile_99: 218.00 ms	
maximum: 23.43 s

from Kiali Metrics, it seems to be related to getWorkloadList  and may be related to goLangRoutines.

JIRA:
https://issues.jboss.org/browse/KIALI-2686

**Comment by mwringe** [comment] 2019-08-30 18:33
@burmanm Are you working on this as part of this sprint?

**Comment by lucasponce** [comment] 2019-10-28 14:20
@gbaufake with the merge of https://github.com/kiali/kiali/issues/1386 I think the perf issues should be mitigated.

Please, let me know if that's the case, looking forward to get feedback on this.

**Comment by lucasponce** [comment] 2019-11-29 14:42
@gbaufake any update about this ?

Thanks

**Comment by lucasponce** [comment] 2020-01-14 11:01
@FilipB @hhovsepy I've updated this issue with the QE label mostly to sync on the test related to caching and performance.

**Comment by FilipB** [comment] 2020-01-22 17:18
I'm preparing a simple gatling scenario to replicate this.

**Comment by gbaufake** [comment] 2020-01-22 17:20
@FilipB.
I was preparing a final update to cover that on the kiali-performance-testing repo as it was diagnosed before.

**Comment by FilipB** [comment] 2020-01-23 12:55
Even though the cache significantly improves mean response time (118ms vs. 1094ms) the spikes are still visible.
![cacheEnabled](https://user-images.githubusercontent.com/328182/72986170-e4960c80-3de7-11ea-8b79-e0ce12229e14.png)

**Comment by lucasponce** [comment] 2020-01-27 14:59
Thanks @FilipB,

I think it could be interesting to run also some testing against the same endpoint that Kiali uses, just to check if spikes happen inside Kiali or are due the k8s API.

For example, when Kiali fetches workloads for a given namespace it executes endpoints of controllers and pods like:

http://localhost:8080/apis/apps/v1/namespaces/kube-system/deployments
(same for replica-sets and other workloads included)
http://localhost:8080/api/v1/namespaces/kube-system/pods

Also, Kiali fetches and combine other assets like istio objects.
So, a test against those endpoints in the same condition would also shown interesting info.

Note that a Kiali query spawns several k8s + istio queries, so to have a better comparison that should be taken into consideration.

**Comment by FilipB** [comment] 2020-01-28 13:03
Results for different endpoints - http://web.bc.jonqe.lab.eng.bos.redhat.com/gatling/reports/k8sapisim-20200128123015484/
See which endpoints are used here - https://gitlab.cee.redhat.com/istio/kiali-qe/kiali-qe-utils/blob/master/perf/gatling/K8sApiSim.scala

For each tested endpoints there are spikes with max response times around 2s. Kiali api calls spikes have max response times ~12s.

**Comment by lucasponce** [comment] 2020-01-28 15:40
> For each tested endpoints there are spikes with max response times around 2s. Kiali api calls spikes have max response times ~12s.

That's expected as kiali performs several calls, so yes, it seems that Spikes are in the k8s API itself, but not in Kiali (1 Kiali query may spawn several rounds to p8s and k8s, so it explains the differences).

@FilipB this tests are really valuable, it confirms several things:
- In general, caching improve the mean response, which is good.
- We can reproduce spikes querying directly to k8s API, so those propagated into Kiali logic are also visible there.

**Comment by FilipB** [comment] 2020-01-29 15:20
I tried to run the perf test in different env where the OCP cluster VMs root disks are attached to local ssd instead of shared Ceph storage. The big 12s spikes are no longer visible. Spikes are only 400ms. I will check with @gbaufake what was the original evn used for reporting this issue. I think we can close this issue as the spikes are very possibly caused by the env where the OCP cluster is running, not by kiali.

**Comment by lucasponce** [comment] 2020-01-29 16:28
@FilipB Thanks for the update. In any case, the experience and the work preparing these performance tests is something we will continue working on and iterating.

Thanks !

**Closed** 2020-01-29 16:28 UTC
Labels: backlog, jira, qe

**Comment by FilipB** [comment] 2020-01-30 13:53
Confirming that the original OCP cluster used when the issue was reported was running on slower shared storage which is explaining the spikes.
