### ISSUE TITLE
Kiali doesn't work with Argo Rollout deployments

### ISSUE THREAD

**Issue by fernandovillarreal-up** [kiali/kiali#5373] opened 2022-08-05 20:55 UTC
Hello, I'm using kiali version 1.50.0 installed using the official helm chart.

This is the information from the UI
Kiali UI: 1.50.0 (97bc6bf1a41d9fb231ccca0781eb575c91b451d1)
Kiali Container: v1.50.0
Components: Prometheus: 2.28.1
Kubernetes: v1.21.13-eks-84b4fe6

Istio version: 1.13.1

In the graph option I have selected the Versioned app graph. 
I select an application and the data in the detailed information shows the Application, Service and Workload, each of them is a link for the detailed information of the application, service, and workload.
If I click on the Workload the browser goes to this URL which is wrong:
https://kiali.mesh..../kiali/console/namespaces/upwork-services/workloads/notificationroutingds-7856c7b7b9?duration=60&refresh=15000

If I change it to this the page shows the workload:
https://kiali.mesh..../kiali/console/namespaces/upwork-services/workloads/notificationroutingds?duration=60&refresh=15000

For some reason the URL includes the ID of the replicaset. I'm adding some screenshots to clarify more.
Screenshot 1 has the selection of the workload
Screenshot 2 is the result of the link generated by the UI and visited
Screenshot 3 is the result if I manually change the URL

Thanks in advance.
Fernando.

![Screen Shot 2022-08-05 at 5 38 11 PM](https://user-images.githubusercontent.com/81965617/183160929-d87580ac-4842-4608-871f-907853bf85fa.png)
![Screen Shot 2022-08-05 at 5 38 19 PM](https://user-images.githubusercontent.com/81965617/183161278-2d4bfc11-3e16-48be-a407-f5476086fcff.png)
![Screen Shot 2022-08-05 at 5 39 07 PM](https://user-images.githubusercontent.com/81965617/183161358-deec3172-81ca-4df8-99c2-32d4329d0ec6.png)

**Comment by jshaughn** [comment] 2022-08-06 18:21
Definitely strange, thanks for reporting, we'll look into it shortly.

**Comment by fernandovillarreal-up** [comment] 2022-08-08 12:27
Here it is
`{
  "backendConfigs": {
    "authenticationConfig": {
      "strategy": "anonymous"
    },
    "computedServerConfig": {
      "clusters": {},
      "durations": {
        "60": "1m",
        "300": "5m",
        "600": "10m",
        "1800": "30m",
        "3600": "1h",
        "10800": "3h",
        "21600": "6h",
        "43200": "12h",
        "86400": "1d",
        "604800": "7d"
      },
      "healthConfig": {
        "rate": [
          {
            "tolerance": [
              {
                "code": "/5\\d\\d/",
                "degraded": 0,
                "failure": 10,
                "protocol": "/http/",
                "direction": "/.*/"
              },
              {
                "code": "/4\\d\\d/",
                "degraded": 10,
                "failure": 20,
                "protocol": "/http/",
                "direction": "/.*/"
              },
              {
                "code": "/^[1-9]$|^1[0-6]$/",
                "degraded": 0,
                "failure": 10,
                "protocol": "/grpc/",
                "direction": "/.*/"
              },
              {
                "code": "/^-$/",
                "degraded": 0,
                "failure": 10,
                "protocol": "/http|grpc/",
                "direction": "/.*/"
              }
            ],
            "namespace": "/.*/",
            "name": "/.*/",
            "kind": "/.*/"
          }
        ]
      },
      "deployment": {
        "viewOnlyMode": true
      },
      "installationTag": "Kiali Console",
      "istioAnnotations": {
        "istioInjectionAnnotation": "sidecar.istio.io/inject"
      },
      "istioCanaryRevision": {},
      "istioIdentityDomain": "svc.cluster.local",
      "istioNamespace": "istio-system",
      "istioLabels": {
        "appLabelName": "app",
        "injectionLabelName": "istio-injection",
        "injectionLabelRev": "istio.io/rev",
        "versionLabelName": "version"
      },
      "kialiFeatureFlags": {
        "certificatesInformationIndicators": {
          "enabled": true,
          "secrets": [
            "cacerts",
            "istio-ca-secret"
          ]
        },
        "istioInjectionAction": true,
        "istioUpgradeAction": false,
        "uiDefaults": {
          "graph": {
            "findOptions": [
              {
                "description": "Find: slow edges (> 1s)",
                "expression": "rt > 1000"
              },
              {
                "description": "Find: unhealthy nodes",
                "expression": "! healthy"
              },
              {
                "description": "Find: unknown nodes",
                "expression": "name = unknown"
              },
              {
                "description": "Find: nodes with the 2 top rankings",
                "expression": "rank <= 2"
              }
            ],
            "hideOptions": [
              {
                "description": "Hide: healthy nodes",
                "expression": "healthy"
              },
              {
                "description": "Hide: unknown nodes",
                "expression": "name = unknown"
              },
              {
                "description": "Hide: nodes ranked lower than the 2 top rankings",
                "expression": "rank > 2"
              }
            ],
            "settings": {
              "fontLabel": 13,
              "minFontBadge": 7,
              "minFontLabel": 10
            },
            "traffic": {
              "grpc": "requests",
              "http": "requests",
              "tcp": "sent"
            }
          },
          "metricsPerRefresh": "1m",
          "metricsInbound": {},
          "metricsOutbound": {},
          "refreshInterval": "15s"
        },
        "validations": {
          "ignore": [
            "KIA1201"
          ]
        }
      },
      "prometheus": {
        "globalScrapeInterval": 10,
        "storageTsdbRetention": 864000
      },
      "clusterInfo": {},
      "istioStatusEnabled": true,
      "istioConfigMap": "istio-1-13-1"
    }
  },
  "currentURL": "https://kiali.mesh-infra.staging.platform.usw2.upwork/kiali/console/overview?duration=60&refresh=15000",
  "reduxState": {
    "authentication": {
      "message": "",
      "session": {
        "username": null,
        "expiresOn": "2022-08-09T12:21:12.851Z"
      },
      "status": 1,
      "uiExpiresOn": "2022-08-09T12:21:12.851Z"
    },
    "globalState": {
      "loadingCounter": 0,
      "isPageVisible": true,
      "lastRefreshAt": 1659961288262
    },
    "graph": {
      "edgeMode": "all",
      "graphDefinition": null,
      "layout": {
        "name": "kiali-dagre",
        "fit": false,
        "nodeDimensionsIncludeLabels": true,
        "rankDir": "LR"
      },
      "namespaceLayout": {
        "name": "kiali-dagre",
        "fit": false,
        "nodeDimensionsIncludeLabels": true,
        "rankDir": "LR"
      },
      "rankResult": {
        "upperBound": 0
      },
      "summaryData": null,
      "toolbarState": {
        "boxByCluster": true,
        "boxByNamespace": true,
        "compressOnHide": true,
        "edgeLabels": [],
        "findValue": "",
        "graphType": "versionedApp",
        "hideValue": "",
        "rankBy": [],
        "showFindHelp": false,
        "showIdleEdges": false,
        "showIdleNodes": false,
        "showLegend": false,
        "showMissingSidecars": true,
        "showOperationNodes": false,
        "showRank": false,
        "showSecurity": false,
        "showServiceNodes": true,
        "showTrafficAnimation": false,
        "showVirtualServices": true,
        "trafficRates": [
          "grpc",
          "grpcRequest",
          "http",
          "httpRequest",
          "tcp",
          "tcpSent"
        ]
      },
      "updateTime": 0
    },
    "messageCenter": {
      "nextId": 0,
      "groups": [
        {
          "id": "systemErrors",
          "title": "Open issues",
          "messages": [],
          "showActions": false,
          "hideIfEmpty": true
        },
        {
          "id": "default",
          "title": "Notifications",
          "messages": [],
          "showActions": true,
          "hideIfEmpty": false
        }
      ],
      "hidden": true,
      "expanded": false,
      "expandedGroupId": "default"
    },
    "namespaces": {
      "activeNamespaces": [
        {
          "name": "upwork-services"
        },
        {
          "name": "istio-system"
        }
      ],
      "isFetching": false,
      "items": [
        {
          "name": "upwork-services",
          "labels": {
            "alertmanagerconfig": "enabled",
            "argocd.argoproj.io/instance": "namespaces-staging",
            "kubernetes.io/metadata.name": "upwork-services"
          },
          "annotations": {}
        },
        {
          "name": "istio-system",
          "labels": {
            "argocd.argoproj.io/instance": "namespaces-staging",
            "kubernetes.io/metadata.name": "istio-system"
          },
          "annotations": {}
        }
      ],
      "lastUpdated": "2022-08-08T12:21:13.528Z",
      "filter": ""
    },
    "statusState": {
      "status": {
        "Kiali commit hash": "97bc6bf1a41d9fb231ccca0781eb575c91b451d1",
        "Kiali container version": "v1.50.0",
        "Kiali state": "running",
        "Kiali version": "v1.50.0",
        "Mesh name": "Istio",
        "Mesh version": "1.13.1"
      },
      "externalServices": [
        {
          "name": "Istio",
          "version": "1.13.1"
        },
        {
          "name": "Prometheus",
          "version": "2.28.1"
        },
        {
          "name": "Kubernetes",
          "version": "v1.21.13-eks-84b4fe6"
        },
        {
          "name": "Grafana",
          "url": "https://grafana-v8.staging.platform.usw2.upwork/"
        },
        {
          "name": "Jaeger",
          "url": "https://jaeger.staging.platform.usw2.upwork/"
        }
      ],
      "warningMessages": [],
      "istioEnvironment": {
        "isMaistra": false
      }
    },
    "userSettings": {
      "duration": 60,
      "timeRange": {
        "rangeDuration": 600
      },
      "interface": {
        "navCollapse": false
      },
      "refreshInterval": 15000,
      "replayActive": false,
      "replayQueryTime": 0
    },
    "jaegerState": {
      "info": {
        "enabled": true,
        "integration": true,
        "url": "https://jaeger.staging.platform.usw2.upwork/",
        "namespaceSelector": true,
        "whiteListIstioSystem": [
          "jaeger-query",
          "istio-ingressgateway"
        ]
      }
    },
    "meshTLSStatus": {
      "status": "MTLS_NOT_ENABLED"
    },
    "istioStatus": [
      {
        "name": "grafana",
        "status": "Unreachable",
        "is_core": false
      }
    ],
    "istioCertsInfo": [
      {
        "secretName": "cacerts",
        "secretNamespace": "istio-system",
        "dnsNames": null,
        "issuer": "CN=Upwork Global Root CA,OU=Technical Operations,O=Upwork Global\\, Inc.,L=Mountain View,ST=California,C=US",
        "notBefore": "2022-03-01T08:34:00Z",
        "notAfter": "2027-03-01T08:34:00Z",
        "error": "",
        "accessible": true
      }
    ],
    "tourState": {},
    "metricsStats": {
      "data": {}
    },
    "_persist": {
      "version": -1,
      "rehydrated": true
    }
  }
}`

**Comment by fernandovillarreal-up** [comment] 2022-08-08 12:30
Here it is

`{
  "backendConfigs": {
    "authenticationConfig": {
      "strategy": "anonymous"
    },
    "computedServerConfig": {
      "clusters": {},
      "durations": {
        "60": "1m",
        "300": "5m",
        "600": "10m",
        "1800": "30m",
        "3600": "1h",
        "10800": "3h",
        "21600": "6h",
        "43200": "12h",
        "86400": "1d",
        "604800": "7d"
      },
      "healthConfig": {
        "rate": [
          {
            "tolerance": [
              {
                "code": "/5\\d\\d/",
                "degraded": 0,
                "failure": 10,
                "protocol": "/http/",
                "direction": "/.*/"
              },
              {
                "code": "/4\\d\\d/",
                "degraded": 10,
                "failure": 20,
                "protocol": "/http/",
                "direction": "/.*/"
              },
              {
                "code": "/^[1-9]$|^1[0-6]$/",
                "degraded": 0,
                "failure": 10,
                "protocol": "/grpc/",
                "direction": "/.*/"
              },
              {
                "code": "/^-$/",
                "degraded": 0,
                "failure": 10,
                "protocol": "/http|grpc/",
                "direction": "/.*/"
              }
            ],
            "namespace": "/.*/",
            "name": "/.*/",
            "kind": "/.*/"
          }
        ]
      },
      "deployment": {
        "viewOnlyMode": true
      },
      "installationTag": "Kiali Console",
      "istioAnnotations": {
        "istioInjectionAnnotation": "sidecar.istio.io/inject"
      },
      "istioCanaryRevision": {},
      "istioIdentityDomain": "svc.cluster.local",
      "istioNamespace": "istio-system",
      "istioLabels": {
        "appLabelName": "app",
        "injectionLabelName": "istio-injection",
        "injectionLabelRev": "istio.io/rev",
        "versionLabelName": "version"
      },
      "kialiFeatureFlags": {
        "certificatesInformationIndicators": {
          "enabled": true,
          "secrets": [
            "cacerts",
            "istio-ca-secret"
          ]
        },
        "istioInjectionAction": true,
        "istioUpgradeAction": false,
        "uiDefaults": {
          "graph": {
            "findOptions": [
              {
                "description": "Find: slow edges (> 1s)",
                "expression": "rt > 1000"
              },
              {
                "description": "Find: unhealthy nodes",
                "expression": "! healthy"
              },
              {
                "description": "Find: unknown nodes",
                "expression": "name = unknown"
              },
              {
                "description": "Find: nodes with the 2 top rankings",
                "expression": "rank <= 2"
              }
            ],
            "hideOptions": [
              {
                "description": "Hide: healthy nodes",
                "expression": "healthy"
              },
              {
                "description": "Hide: unknown nodes",
                "expression": "name = unknown"
              },
              {
                "description": "Hide: nodes ranked lower than the 2 top rankings",
                "expression": "rank > 2"
              }
            ],
            "settings": {
              "fontLabel": 13,
              "minFontBadge": 7,
              "minFontLabel": 10
            },
            "traffic": {
              "grpc": "requests",
              "http": "requests",
              "tcp": "sent"
            }
          },
          "metricsPerRefresh": "1m",
          "metricsInbound": {},
          "metricsOutbound": {},
          "refreshInterval": "15s"
        },
        "validations": {
          "ignore": [
            "KIA1201"
          ]
        }
      },
      "prometheus": {
        "globalScrapeInterval": 10,
        "storageTsdbRetention": 864000
      },
      "clusterInfo": {},
      "istioStatusEnabled": true,
      "istioConfigMap": "istio-1-13-1"
    }
  },
  "currentURL": "https://kiali.mesh..../kiali/console/overview?duration=60&refresh=15000",
  "reduxState": {
    "authentication": {
      "message": "",
      "session": {
        "username": null,
        "expiresOn": "2022-08-09T12:21:12.851Z"
      },
      "status": 1,
      "uiExpiresOn": "2022-08-09T12:21:12.851Z"
    },
    "globalState": {
      "loadingCounter": 0,
      "isPageVisible": true,
      "lastRefreshAt": 1659961288262
    },
    "graph": {
      "edgeMode": "all",
      "graphDefinition": null,
      "layout": {
        "name": "kiali-dagre",
        "fit": false,
        "nodeDimensionsIncludeLabels": true,
        "rankDir": "LR"
      },
      "namespaceLayout": {
        "name": "kiali-dagre",
        "fit": false,
        "nodeDimensionsIncludeLabels": true,
        "rankDir": "LR"
      },
      "rankResult": {
        "upperBound": 0
      },
      "summaryData": null,
      "toolbarState": {
        "boxByCluster": true,
        "boxByNamespace": true,
        "compressOnHide": true,
        "edgeLabels": [],
        "findValue": "",
        "graphType": "versionedApp",
        "hideValue": "",
        "rankBy": [],
        "showFindHelp": false,
        "showIdleEdges": false,
        "showIdleNodes": false,
        "showLegend": false,
        "showMissingSidecars": true,
        "showOperationNodes": false,
        "showRank": false,
        "showSecurity": false,
        "showServiceNodes": true,
        "showTrafficAnimation": false,
        "showVirtualServices": true,
        "trafficRates": [
          "grpc",
          "grpcRequest",
          "http",
          "httpRequest",
          "tcp",
          "tcpSent"
        ]
      },
      "updateTime": 0
    },
    "messageCenter": {
      "nextId": 0,
      "groups": [
        {
          "id": "systemErrors",
          "title": "Open issues",
          "messages": [],
          "showActions": false,
          "hideIfEmpty": true
        },
        {
          "id": "default",
          "title": "Notifications",
          "messages": [],
          "showActions": true,
          "hideIfEmpty": false
        }
      ],
      "hidden": true,
      "expanded": false,
      "expandedGroupId": "default"
    },
    "namespaces": {
      "activeNamespaces": [
        {
          "name": "upwork-services"
        },
        {
          "name": "istio-system"
        }
      ],
      "isFetching": false,
      "items": [
        {
          "name": "upwork-services",
          "labels": {
            "alertmanagerconfig": "enabled",
            "argocd.argoproj.io/instance": "namespaces-staging",
            "kubernetes.io/metadata.name": "upwork-services"
          },
          "annotations": {}
        },
        {
          "name": "istio-system",
          "labels": {
            "argocd.argoproj.io/instance": "namespaces-staging",
            "kubernetes.io/metadata.name": "istio-system"
          },
          "annotations": {}
        }
      ],
      "lastUpdated": "2022-08-08T12:21:13.528Z",
      "filter": ""
    },
    "statusState": {
      "status": {
        "Kiali commit hash": "97bc6bf1a41d9fb231ccca0781eb575c91b451d1",
        "Kiali container version": "v1.50.0",
        "Kiali state": "running",
        "Kiali version": "v1.50.0",
        "Mesh name": "Istio",
        "Mesh version": "1.13.1"
      },
      "externalServices": [
        {
          "name": "Istio",
          "version": "1.13.1"
        },
        {
          "name": "Prometheus",
          "version": "2.28.1"
        },
        {
          "name": "Kubernetes",
          "version": "v1.21.13-eks-84b4fe6"
        },
        {
          "name": "Grafana",
          "url": "https://grafana-v8..../"
        },
        {
          "name": "Jaeger",
          "url": "https://jaeger..../"
        }
      ],
      "warningMessages": [],
      "istioEnvironment": {
        "isMaistra": false
      }
    },
    "userSettings": {
      "duration": 60,
      "timeRange": {
        "rangeDuration": 600
      },
      "interface": {
        "navCollapse": false
      },
      "refreshInterval": 15000,
      "replayActive": false,
      "replayQueryTime": 0
    },
    "jaegerState": {
      "info": {
        "enabled": true,
        "integration": true,
        "url": "https://jaeger..../",
        "namespaceSelector": true,
        "whiteListIstioSystem": [
          "jaeger-query",
          "istio-ingressgateway"
        ]
      }
    },
    "meshTLSStatus": {
      "status": "MTLS_NOT_ENABLED"
    },
    "istioStatus": [
      {
        "name": "grafana",
        "status": "Unreachable",
        "is_core": false
      }
    ],
    "istioCertsInfo": [
      {
        "secretName": "cacerts",
        "secretNamespace": "istio-system",
        "dnsNames": null,
        "issuer": "CN=Upwork ,OU=Technical Operations,O=Upwork.,L=Mountain View,ST=California,C=US",
        "notBefore": "2022-03-01T08:34:00Z",
        "notAfter": "2027-03-01T08:34:00Z",
        "error": "",
        "accessible": true
      }
    ],
    "tourState": {},
    "metricsStats": {
      "data": {}
    },
    "_persist": {
      "version": -1,
      "rehydrated": true
    }
  }
}`

**Comment by jshaughn** [comment] 2022-08-08 17:28
@fernandovillarreal-up , I'm sorry, I forgot to say that you need to on the graph page when it is showing the bad link, and then collect the debug info.  That will then include some specifics about the graph itself.

**Comment by fernandovillarreal-up** [comment] 2022-08-09 13:52
Got it
[debug_json.txt](https://github.com/kiali/kiali/files/9291330/debug_json.txt)

**Comment by jshaughn** [comment] 2022-08-10 18:52
Thanks for posting the updated info @fernandovillarreal-up (I'll delete the old data to clean up the thread).  I'm not exactly sure why you see what you see.  It would seem that the Istio telemetry is reporting the pod name for the workload name.  Typically that would be set to the name of the workload.  So, for example, if you used a Deployment is would be the Deployment name.  What mechanism are you using to deploy your pods (at least the ones showing pod names)?

If you change to a "Workload" graph type do you see the same thing, pod names for some of the the workload nodes?

Also, to confirm the suspected telemetry, are you able to access your Prometheus UI and perform a query?  [See here](https://kiali.io/docs/faq/graph/#queryprom) for some instructions.

If so, please try the following query (it should be representative.  If this returns nothing then probably I messed up the query):

istio_requests_total{destination_canonical_service="Brontes"}

Thanks

**Comment by jshaughn** [comment] 2022-08-11 17:28
OK, so this confirms what I suspected, that istio telemetry is reporting the pod name as the workload name.  As such, I'd say the graph is performing as expected because it is just visualizing the telemetry.  I'm not sure why you get pod names for your workloads, can you tell me how you are deploying your services?  I will continue to investigate.

**Comment by jmazzitelli** [comment] 2022-08-11 17:36
I suspect the pods are deployed directly as pods (i.e. no "parent" resource like Deployment or StatefulSet).

**Comment by israel-hdez** [comment] 2022-08-11 17:42
Hmm... Definitely it is not the Deployment name. To my eye, the telemetry could be reporting the ReplicaSet name rather than the pod name, as I see the `pod_name` label having an additional suffix.

**Comment by jshaughn** [comment] 2022-08-11 17:48
@israel-hdez Good eye, you are right, it's probably not the pod name.  I wonder if the problem here is that we're dealing with one of the non-default workload types.  @fernandovillarreal-up , are you using one of "CronJob", "DeploymentConfig", "Job" or 
"ReplicationController" as your deployment mechanism?

If so, you need to configure Kiali to look for the necessary workload type.  By default it does not look for those types for performance reasons.  See https://kiali.io/docs/faq/general/#workload-is-not-found-as-messages for more on this possible issue.

**Comment by fernandovillarreal-up** [comment] 2022-08-11 18:15
We are using our own helm charts in order to deploy our services.
We are also using argo-rollouts as part of our deployment/update process. In order to make argo rollouts work, we had to replace Deployments (apiVersion: apps/v1 - kind: Deployment) to Rollout (apiVersion: argoproj.io/v1alpha1 - kind: Rollout)

**Comment by israel-hdez** [comment] 2022-08-11 18:23
ArgoCD related issue: https://github.com/kiali/kiali/issues/5261

**Comment by fernandovillarreal-up** [comment] 2022-08-11 18:28
Ok, it means that the issue is what is described in #5261, and we need to wait for the other ticket resolution, correct?

**Comment by jmazzitelli** [comment] 2022-08-11 18:34
Ah ha. Argo Rollouts - I'm positive we don't work with those.

**Comment by jmazzitelli** [comment] 2022-08-11 18:35
> Ok, it means that the issue is what is described in #5261, and we need to wait for the other ticket resolution, correct?

Yes. This github issue is essentially a duplicate of that one.

**Comment by jmazzitelli** [comment] 2022-08-11 18:37
closing, as this is a dup of https://github.com/kiali/kiali/issues/5261

**Closed by jmazzitelli** 2022-08-11 18:37 UTC
Labels: bug, backlog

**Comment by fernandovillarreal-up** [comment] 2022-08-11 18:40
ok, thanks

**Comment by jshaughn** [comment] 2022-08-15 13:39
Thanks for reporting @fernandovillarreal-up , please follow any progress in #5261 .  I am adding that issue to our backlog, we will evaluate what can be done for Argo, as the behavior is certainly not ideal.
