### ISSUE TITLE
Jaeger traces & spans fetching error

### ISSUE THREAD

**Issue by pbajjuri20** [kiali/kiali#4238] opened 2021-07-30 01:00 UTC
Jaeger traces & spans are not fetching in the Kiali for Istio 1.11.0-beta.3

Reproduce steps:

1. install upstream istio 1.11.0-beta.3 with upstream kiali
2. install bookinfo 
3. Navigate to Kiali
4. Click on "Applications" (left-side panel)
5. Click on "Details"
6. Click on "Traces" (Jaeger traces are not fetching)

![Jaeger_error](https://user-images.githubusercontent.com/55099523/127583815-60283835-1bf9-4ac5-bebb-52aace9c51d6.png)

![Jaeger_3](https://user-images.githubusercontent.com/55099523/127583993-c7f4fc8b-3173-4f46-af8d-4c723117551e.png)

**Comment by xeviknal** [comment] 2021-07-30 09:20
How did you install kiali?

I think this is a duplicate of this one: https://github.com/kiali/kiali/issues/4207
However, there is one thing missing in our side. Kiali installed via Istio addons won't work because the default value is still using the port 80, old one. So we need to change it.

**Comment by xeviknal** [comment] 2021-07-30 09:38
It shouldn't be broken if you installed kiali the operator in the latest version in master.
What you can also do is to go to the kiali-cr and change the `external_services.tracing.in_cluster_url` to `http://tracing.istio-system:16685/jaeger` and everything should be back to normal.

**Comment by pbajjuri20** [comment] 2021-07-30 21:53
@xeviknal: it works successfully with this port  'http://tracing.istio-system:16685/jaeger'.

**Comment by xeviknal** [comment] 2021-08-02 13:01
Purrfect. It would be wonderful to check kiali 1.38 (or latest master) with latest istio 1.11. Do you mind double checking it? Thank you :)

**Comment by pbajjuri20** [comment] 2021-08-02 13:06
@xeviknal: Yes, I have validated against Kiali 1.38 with the latest Istio 1.11.

**Comment by xeviknal** [comment] 2021-08-03 07:57
I am re-opening the issue.

I see two problems:

1) Default `use_grpc` is false but the default `in_cluster_url` uses the `gRPC` one. My fault:
Should we rephrase this sentence? https://github.com/kiali/kiali-operator/blob/98a2fb7441f600548172bf8cdd83230dd812c7ad/deploy/kiali/kiali_cr.yaml#L642
I read that gRPC defaults to `true`. However, our [config defaults](https://github.com/kiali/kiali/blob/master/config/config.go#L520) to `false`.
The problem this creates is the following: masthead and traces are not present because kiali sends HTTP traffic to gRPC port.
Second problem: default installation via operator leaves `use_grpc=true`, however kiali default installation leave `use_grpc=false`. This leaves us in a inconsistency. Needs to be corrected.
Solution: enable grpc by default (in the config).

2) When enabling gRPC by default, domino effect: the masthead istio component health brokes. The component health uses the gRPC port but sends HTTP traffic. Before the port split, this wasn't a problem because of the shared port for both traffics. Now, it is a problem.
Solution. 2 alternatives:
1) Change the default health_check_url to use the HTTP port.
2) Change the component health to send gRPC or HTTP traffic depending on the `use_grpc`.

I guess that we should implement the second one. Otherwise, the health status won't be as useful as expected. It'd lead to scenarios were traffic http works as expected but gRPC doesn't work.

**Comment by jmazzitelli** [comment] 2021-08-03 11:40
> * Change the component health to send gRPC or HTTP traffic depending on the `use_grpc`.
> 
> I guess that we should implement the second one.

I agree with this solution.

**Closed** 2021-08-04 17:25 UTC
Labels: bug
