### ISSUE TITLE
Client sent an HTTP request to an HTTPS server

### ISSUE THREAD

**Issue by vasuganesan** [kiali/kiali#1308] opened 2019-08-02 13:58 UTC
Hi,

We have tried to enable Kiali mesh observer after the istio installed on the kubernetes cluster using following url( https://www.kiali.io/documentation/getting-started/ ). 

**Command used to install kiali:**

bash <(curl -L https://git.io/getLatestKialiOperator)

kubectl get svc -n istio-system provides me the below one

istio-telemetry          ClusterIP   XX.XX.155.210   <none>        9091/TCP,15004/TCP,15014/TCP,42422/TCP                                                                                                       35m
jaeger-agent             ClusterIP   None             <none>        5775/UDP,6831/UDP,6832/UDP                                                                                                                   24h
jaeger-collector         ClusterIP   XX.XX.31.6      <none>        14267/TCP,14268/TCP                                                                                                                          24h
jaeger-query             ClusterIP   XX.XX.144.89    <none>        16686/TCP                                                                                                                                    24h
kiali                    NodePort    XX.XX.166.185   <none>        20001:30041/TCP                                                                                                                              28h
prometheus               ClusterIP   XX.XX.131.178   <none>        9090/TCP                                                                                                                                     35m
tracing                  ClusterIP   XX.XX.247.8     <none>        80/TCP                                                                                                                                       24h
zipkin                   ClusterIP   XX.XX.224.173   <none>        9411/TCP 

All my pods and services are up and running.
Tried to hit the kiali server and it shows the below error.
[ec2-user@ip-172-x.x.x ~]$ curl  172.x.x.x:20001/kiali
Client sent an HTTP request to an HTTPS server.
[ec2-user@ip-172-x.x.x ~]

**Versions used**
Kiali: v1.0.2
Istio: v1.2.2
Kubernetes flavour and version: EKS 1.12

**To Reproduce**
1. Install istio by downloading it
2. helm template install/kubernetes/helm/istio --name istio --namespace istio-system   --set gateways.enabled=true   --set gateways.istio-ingressgateway.type=NodePort   > istio-system.yaml
3. kubectl apply -f istio-system.yaml
The above one successfully installed istio and everything is fine and then i tried to add Kiali on it
1. bash <(curl -L https://git.io/getLatestKialiOperator)
It started the kiali pod and svc as well . Service is Nodeport type. 

I even tried to put an ELB in front and tried to access it via a domain which has SSL certificate enabled. But still the same issue. 
https://domain/kiali

Please do help me on what might went wrong here.

**Expected behavior**
Kiali UI should be loaded properly in Web browser

**Comment by jmazzitelli** [comment] 2019-08-02 14:38
> Tried to hit the kiali server and it shows the below error.
> $ curl 172.x.x.x:20001/kiali
> Client sent an HTTP request to an HTTPS server.

That all seems correct to me - curl is sending an HTTP request and Kiali is behind HTTPS.

When you try with a browser, go over `https`, and hit the `/kiali` context path but go to the host/port that is exposed from your cluster.

Kiali is behind HTTPS and you have to make sure you know what host the cluster exposes it. If you are on OpenShift, this is done for you via a Route, on K8s via Ingress (which is created for you by the operator, so the route or ingress should exist).

**Comment by VinothChinnadurai** [comment] 2019-08-05 07:31
@jmazzitelli Thanks for your answer

I am vinoth part for Vasu team. As you said we tried via browser too with the domain https://xxx.domain.com/kiali, it still has the same response 'Client sent an HTTP request to an HTTPS server.'

In our current setup, we have kiali hosted as NodePort type 20001:30041/TCP. To access it from outside(browser), created an ELB which has rules defined as port forward from 443->30041.
Infront of ELB, created a Route53 domain 'xxx.domain.com' with A record pointed to ELB address.

Tried to access via the domain https://xxx.domain.com/kiali. Still same issue. 

Am I missing out anything? 

I have a question, Do we need to route traffic to Kiali only via IngressGateway exposed by Istio or like I stated above, we can try access the kiali?

**Comment by jmazzitelli** [comment] 2019-08-05 12:53
@VinothChinnadurai You can route to Kiali any way you want - there is no restriction such as "you must route over istio ingressgateway". Kiali is just a normal service like any other cluster service - if you can expose it, you should be able to access it.

If you are getting errors like "Client sent an HTTP request to an HTTPS server" then I have to think the problem is in the loadbalancing configuration. Otherwise, how can you explain your client sending HTTP? The client request has nothing to do with Kiali.

When you start up Kiali and submit a client request to it, see what the Kiali pod logs say. Maybe that can help determine if there is something on the server-side that does not look right?

**Comment by jotak** [comment] 2019-08-05 13:19
Are you on AWS? According to this [1] you would need to set specific annotation to target https pods: `service.beta.kubernetes.io/aws-load-balancer-backend-protocol`
Maybe other providers have similar configurations?

[1] https://kubernetes.io/docs/concepts/services-networking/#ssl-support-on-aws

**Comment by VinothChinnadurai** [comment] 2019-08-06 08:04
@jmazzitelli I can find these in kiali pod while trying to access it

2019/08/06 07:59:05 http: TLS handshake error from 172.31.85.38:25978: EOF
2019/08/06 07:59:05 http: TLS handshake error from 172.31.69.232:24542: EOF
2019/08/06 07:59:34 http: TLS handshake error from 172.31.85.38:26022: EOF
2019/08/06 07:59:34 http: TLS handshake error from 172.31.69.232:24586: EOF
2019/08/06 07:59:42 http: TLS handshake error from 172.31.85.38:6858: EOF
2019/08/06 07:59:42 http: TLS handshake error from 172.31.69.232:21812: EOF

@jotak I have added ELB on my own manually not through service configuration. I made Kiali service run on Nodeport type and placed an ELB where I have attached an AWS Managed Certificate. Then pointed that ELB to Route53 domain Url. 

I would like to know what is that TLS handshake error and multiple ports it is trying out?

**Comment by jmazzitelli** [comment] 2019-08-06 13:00
> 2019/08/06 07:59:05 http: TLS handshake error from 172.31.85.38:25978: EOF

Yeah, I'm pretty sure that's the server getting a request in http but it wants https - and since http is going to be missing the tls handshake protocol data, Kiali will log that error.

It seems clear to me that the Kiali server is receiving plain HTTP requests from your clients when the server wants HTTPS.

**Comment by israel-hdez** [comment] 2019-08-06 14:52
Most likely, related to https://issues.jboss.org/browse/KIALI-3095

**Comment by VinothChinnadurai** [comment] 2019-08-07 07:10
@jmazzitelli  Just found the problem as ELB Health check happens in TCP protocol which hits Kiali with http request. I removed that and moved to HTTPS request on health and it works fine now :)
Please go ahead and close this.  Would also love to hear a better source/ link where I can see how to enable up kiali,jeaggar and grafana on my current istio setup.

**Comment by jmazzitelli** [comment] 2019-08-07 12:12
@VinothChinnadurai for jaeger issues, see this FAQ that might help: https://www.kiali.io/faq/distributed-tracing/

**Closed by jmazzitelli** 2019-08-07 12:12 UTC
Labels: bug :bug:
