### ISSUE TITLE
Show deployment information on Kiali

### ISSUE THREAD

**Issue by omerlh** [kiali/kiali#1298] opened 2019-07-31 14:15 UTC
Be able to be various information about the Deployment object, including:
 - HPA status (number of pods currently, the maximum number of pods)
 - HPA metrics value

**Comment by abonas** [comment] 2019-08-04 13:49
Where in Kiali UI would you see best this info to be displayed, and what metrics seem to be most relevant and important?
cc @pilhuhn @jotak

**Comment by omerlh** [comment] 2019-08-04 14:01
I think this should be part of workload/application view (I'm not clear on the difference). Maybe a different tab? or as part of showing the health of a service?

**Comment by jotak** [comment] 2019-08-05 08:52
I'm not familiar yet with the HPA so i would need to set it up & check.
When you ask for HPA metrics value, do you mean the metrics _used_ by HPA to run its algorithm on, or some metrics that the HPA exposes itself?

HPA status sounds good to include in health, looks very similar to our current pods status in health.

**Comment by omerlh** [comment] 2019-08-05 08:57
The HPA metrics can be very tricky - it can be CPU, memory or external metrics (see the [docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) for more details. Maybe worth starting from getting the status using [Kube State Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/horizontalpodautoscaler-metrics.md)? For example, we monitor the current instances per pod - to ensure it's not reaching the limit of the number of pods defined in the HPA.

**Comment by jotak** [comment] 2019-08-05 09:17
Kiali has stayed away from cluster metrics ( like kube-state-metrics...) til now, because considering it's out of its perimeter and that could open the door to a LOT of new things to monitor. So, I'm not sure up to what point we're ready to go. I think starting with just the live status from HPA would be a okay step...

**Comment by omerlh** [comment] 2019-08-05 09:26
Makes sense, this was just an example...

**Comment by abonas** [comment] 2019-08-06 12:09
tracked also here https://issues.jboss.org/browse/KIALI-3191

**Comment by lucasponce** [comment] 2019-09-24 12:49
@jotak thinking if the current feature we have in Kiali with custom dashboards may work here.
The feature was designed for "runtimes" level, but I guess that there is no limitation to allow an user to fetch custom metrics and perhaps add a solution to this feature.

I don't know just an idea to brainstorm on it.

**Comment by jotak** [comment] 2019-09-24 15:55
The custom dashboards rely on app & version labels to identify their targets, which are not present out of the box with HPA metrics afaik, unless it's specially configured with that.

**Comment by lucasponce** [comment] 2020-01-31 09:22
I think this one is out of the short term context of Kiali.
Kubernetes cluster metrics are typically managed by Kubernetes console, like OpenShift Console.
If there is a specific scenario Istio related, then I'm +1 to bring them into Kiali.
For example, if Istio could develop an adapter to process telemetry and provide a specific metric based in Kubernetes+Istio context, that would be a great addition.

So, I'm going to mark this as "future" and closing.
We can re-open in future iterations.

**Closed by lucasponce** 2020-01-31 09:22 UTC
Labels: enhancement
