### ISSUE TITLE
Metrics: custom time range selection

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1859] opened 2019-10-31 12:47 UTC
In the metrics page, in addition to selection of pre-defined time ranges (last X hours ...), Kiali could also allow selection of a custom time range to allow user to more accurately refine his search

Note: this is related to https://github.com/kiali/kiali/issues/1421, but unlike here there are several problems to deal with when applied to the Graph, as it shows a combination of time-aggregated data + current state. Metrics page doesn't have this problem to deal with.

**Comment by jshaughn** [comment] 2019-11-08 14:17
@jotak What do you think of maybe being able to set a global time window in the UI, that gets applied to all applicable views (i.e. views dealing with metrics, logs, etc like graph, charts, health).  Today we just use a fixed endTime of 'now'.  So we'd be looking at allowing a custom  endTime "range", I think.   As for the graph, it's been a desire for a while to be able to set a custom time period to be able to replay time windows.   I think it would just be an option whether to include any non-metric decorations (anything based on current config).

**Comment by jotak** [comment] 2019-11-08 15:27
@jshaughn yes, these non-metric decoration is IMO what has been restraining us so far to do this. I'm fine to have this as a global setting ; maybe in two steps, first step to implement it in metrics only, and second step to move it to a global setting?

Then, what would be your suggestion for non-metric stuff? To just hide it when "end != now" ? Maybe with some message telling that as we're looking at historical data, less information is available on the graph?

**Comment by abonas** [comment] 2019-11-12 14:03
I like the suggestion of adding a custom range selection.
What I'd like to see more defined is how this will behave in navigation to other pages, where, most likely, in the first stage this won't be implemented.
At the moment, the time selection is pretty much the same in several screens in Kiali, and iirc the setting from screen A is persisted and displayed the same in screen B when user navigates from A to B.
Now, if this enhancement is implemented in metrics page only (whether exclusively, or "as a start/first step"), and user selected a custom time range here, and then navigated to, say, topology - what would be the expected behavior and the selected time range when arriving to topology page? (topology or any other page where time selection exists as it is today without selecting custom from/to as proposed here)

**Comment by jotak** [comment] 2019-11-12 16:53
@abonas good point, let me check if this is the case (I remember it was discussed several times to share the same time frame across various pages but I also remember I wasn't really in favour of that because time frame in Graph and in Metrics do not share exactly the same purpose, as Graph shows aggregated data (so we tend to prefer recent data here) whereas it's not aggregated in Metrics, where we tend to prefer seeing wider time periods to see history trends.

Anyway, I need to check what's the current state.

**Comment by jotak** [comment] 2019-11-12 17:24
So it seems that the time frames of Metrics page is (intentionally) not correlated with the ones of the other pages, hence there should be no undesired side effect related to that matter when implementing this.

**Comment by jshaughn** [comment] 2019-11-12 22:04
+1, although to make sure we're all on the same page I think we need to be careful about terminology.  The graph and overview share the same duration, one minute by default.  Whereas the charts (inbound/outbound traffic on a detail page) defaults to a 10 minute duration.  We offer a fixed set of duration choices.  Given a selected duration we query for data in the time range [(now-duration), now].  We don't allow a custom duration nor do we allow a custom endTime for the time range.  The endTime is always 'now'.  We also offer a fixed set of refreshInterval choices.  Then, given a selected refreshInterval we slide the time range forward.

If I understand @jotak the desire here is to allow both a custom duration and a custom endTime, in other words allow a completely custom time range when querying Prometheus.  I'm not totally sure if that time range would then automatically slide forward or if refresh is disabled given a custom time range.

If the controls are all "in-chart", meaning dragging to expand/narrow/slide a time range, then perhaps maybe both the duration and refresh selections would be disabled.

However, if the refreshInterval is honored then we have created the ability to perform "replay".  Note that replay could also offer SlowMotion (SM) or FastForward (FF) as we are no longer dealing with real time.

For the graph I would envision full replay ability.   In this mode we would either disable, or make optional, features that query current config.

It's not required for this specific chart feature, and in-chart custom ranges may actually work regardless, but my main question is whether it makes any sense to let the user define a custom time *window* by setting a start and [optional] end and just letting Kiali run in replay mode, which would affect the graph and the charts because instead of always setting our query endTime to 'now', we'd implement a little time simulator that would return an endTime based on the defined window and refreshInterval.

**Comment by jotak** [comment] 2019-11-13 08:00
@jshaughn I really didn't mean anything like that "replay" feature while creating that task, in my mind it was implicit that while looking at a past time frame, refresh would be frozen. This "replay" feature is interesting, but I'd have two questions:

- Which use case(s) is it solving? Would it be only for demo purpose or similar?
- If there's identified use cases, are they more important (more likely to happen) than the typical use case I'm thinking about, which is just exploring past metrics manually (for troubleshooting, for trends comparison or whatever)? If not, probably this is something that still could be implemented, however the default behaviour would be that as soon as an end date different from "now" is set, the refresh rate is automatically set to pause (but can still be changed to activate replay). What do you think?

**Comment by lucasponce** [comment] 2019-11-13 09:02
Please, let's not mix the "replay" feature on this Issue.
That should have a separate issue with discussion and research.

This issue was filled together with the https://github.com/kiali/kiali/issues/1860 and goal is to provide in-chart navigation in the metrics charts.

Something not very different as we have today as metrics time range differs from overview/graph on purpose (and we discussed that).

So, please let's drive discussion to help to progress on this and #1860.

Extending the discussion to other topics is always good, but let's create the proper Issues / Research issues.

Thanks.

**Comment by jshaughn** [comment] 2019-11-13 12:58
@lucasponce The intent is not to spoil this issue with talk about another issue, my intent is to *understand* this issue and make sure we're not interpreting things differently.  So, lets not limit questions and healthy discussion just because you may have fond it perfectly clear.

**Comment by lucasponce** [comment] 2019-11-13 13:01
@jshaughn Please, let's not move from a detail to "what is the purpose of Kiali" type of granularity in the same issue.

We have more than 2000 issues in JIRA that prevents us to progress.

Questions are not limited, but it should have their proper channel for clarity.

Let's clarify anything but related current implementation and what the issue is proposed.

**Comment by jshaughn** [comment] 2019-11-13 13:11
>  in my mind it was implicit that while looking at a past time frame, refresh would be frozen.

@jotak, this is what I was wondering about, and trying t understand.  I think it's fine and I think it would  work exactly the same way given if working inside a custom time window (i.e. a custom start time from which we slide forward).

> Which use case(s) is it solving? Would it be only for demo purpose or similar?

No, not just for demo.  Really the same reason as everything else, troubleshooting, comparison, etc.  Imagine something interesting happened while watching the graph or a chart.  How could you watch that again?  What if you wanted to see last week's 02:00-0:300.   We can carry the replay discussion over to https://github.com/kiali/kiali/issues/1421.

**Comment by jshaughn** [comment] 2019-11-13 14:25
@jotak Do you (or UX) have a mock of how the user would define the custom time range?  If it is not in-chart (I see now #1860), then what does it look like.  Setting duration and endTime seem like separate things to me.  Also note that PF4 does not yet have DateTimePicker.

**Comment by mtho11** [comment] 2019-11-13 14:57
FWIW: Victory Charts has a Brush and Zoom Container: https://formidable.com/open-source/victory/gallery/brush-and-zoom/ that would provide a nice graphical sliding window that we could show events (like service degradation) to help provide better context time ranges around a particular event.

**Comment by lucasponce** [comment] 2019-11-13 15:17
@mtho11 that is reflected and detailed in #1860

**Comment by jotak** [comment] 2019-12-20 09:33
@jshaughn , I see that I didn't answer you. I don't have a mockup, but basically the idea is to select something like "custom" within the duration selector, which will trigger two new fields being displayed (from and to), then use a date-time picker from those. As always, nothing is definitive and we can iterate to improve when needed.

I see that PF has no implementation ready and the discussions seems to be leading to using `react-datepicker`. So my suggestion is to start this task with this react-datepicker ahead of patternfly, and switch later. 

We might think it's risky, because maybe we won't want react-datepicker because the design doesn't integrate well ; or maybe PF will ultimately choose a different one so that's a bad bet;
But in any case, there's going to be some refactoring to do in order to allow "from" and "to" dates within the metrics components & API, and this is totally independent from the actual component that we're going to use, so in any case I think it's worth it to start preparing this. Even if for whatever reason we choose to not merge the completed feature, I can still split the work in 2 PRs to have the refactoring done so there's very little work remaining to complete the feature.

Are you, and @lucasponce , ok with this plan?

**Comment by lucasponce** [comment] 2019-12-20 09:44
+1 from my side.
If we don't have a component in PF4 but we have an alternative https://reactdatepicker.com/ it's ok to progress.

We have same situation with the slider where we have imported the component itself.

PF shouldn't block / prevent this feature to progress, we can switch later or adjust it.

To me most important goal is to deliver a feature in upstream that is ready to get feedback from our community users.

Also, I thought that this issue is related to #1860, so I was thinking more in this like the base for next one, or do you see to select custom range as well in the chart ?

**Comment by jotak** [comment] 2019-12-20 09:48
I think #1860 and this one complement each other ; Sometimes navigating in the chart is handy, but not sufficient. Basically, as user user, I think I prefer in-chart navigation to zoom-in something special, but I prefer datapickers when I am searching for a particular date / time.

**Comment by lucasponce** [comment] 2019-12-20 09:48
> but I prefer datepickers when I am searching for a particular date / time.

+1

**Comment by jshaughn** [comment] 2019-12-20 12:48
I have been avoiding the datetimepicker situation with graph replay but it's very hard because there isn't really a great substitute.  It's a huge hole in Patternfly.   In my current POC I actually use a slider to set a start time and then an interval (i.e. start here and play for 5 minutes).    I'm +1 for wrapping a datetimepicker into our code base as an interim solution.  Hopefully it works well because in the past I've had issues with picker impls,  I think with Angular in Hawkular days.

As much as I like the Victory brush/zoom I have not quite been able to figure out how to apply it to what I want to do.  It's really designed to be applied to an existing chart but that doesn't really exist for the graph.  I think most replay will be for short, recent windows, but it's feasible that any time window, constrained only by the TTL of prom data, could be useful to the user.

After the break I'd like to meet with you guys and show you replay, and talk about the bigger picture of custom time ranges, and how we can provide a more integrated experience between metrics, graph, logs, overview etc.  I wish we could be in the same room.   I have designed graph replay such that if an existing time window is supplied it can use it.  I've integrated these changes with redux with the thought that Kiali could more globally apply a custom range.

**Comment by lucasponce** [comment] 2019-12-20 12:52
> I've integrated these changes with redux with the thought that Kiali could more globally apply a custom range.

Mmm. Same custom range may be not needed to be applied in all scenarios.
Today metrics is different than the graph.

All of these open thoughts are ok but taking assumptions perhaps may introduce some feature in a way that we don't want.

But yes, let's try to find an opportunity to discuss this with better context, time and localization for more productive discussions.

**Comment by jshaughn** [comment] 2019-12-20 13:12
@lucasponce Of course I don't actually apply it to any existing pages.  It's only exposed for potential use.  Also remember that Metric charts use a different *duration*, that's different than a custom time window, which is a completely new concept.

**Comment by jotak** [comment] 2019-12-20 13:26
Yeah we should talk about this after the break. I can already see a button "Replay in Graph" from the metrics pages :-)

**Comment by jshaughn** [comment] 2019-12-20 13:30
Exactly :)   Or maybe a stacked view for correlation!

**Closed** 2020-02-03 09:21 UTC
Labels: area/visualization, backlog, enhancement, team/jupiter
