### ISSUE TITLE
there‘s some miss or excess in the display of  the  linktrace data

### ISSUE THREAD

**Issue by HaloGT** [kiali/kiali#4961] opened 2022-04-14 04:30 UTC
for example, there is data in day 26-28, but once you choose the data in a week or a month, it will lose the 27 and before, it is certain; if you choose the last one day or less, it's data is display fully and correctly

**Comment by jmazzitelli** [comment] 2022-04-14 08:46
It is unclear what the problem is that you are reporting. Please provide more information:
1. Provide step-by-step instructions on how to replicate the problem.
2. Also, please indicate what versions of Kiali and Istio you are using.
3. If possible, provide some screenshots of the Kiali UI that show the problem.

**Comment by lucasponce** [comment] 2022-04-18 13:58
As a side comment, Kiali sends queries to Jaeger adjusting the time interval and other filters.
So, you could check if the same query has similar results in the Jaeger instance.

If you see a "gap" perhaps some of the queries built by Kiali may be wrong, but otherwise, perhaps the information that you expect is not stored in the tracing backend.

In any case, the comment is very generic to consider if this is a bug at Kiali, Jaeger, or something expected.

**Comment by HaloGT** [comment] 2022-04-19 06:41
ok, i'll recheck this issue and repetition the problem step by step as soon as possible

**Comment by HaloGT** [comment] 2022-04-20 03:31
till now, i create some data from 14:53 19th to 11:00 20th April, the problem is:
when you adjust the time interval to  last 1d, the data is complete in screenshot No1;
![image](https://user-images.githubusercontent.com/66077164/164144127-01fd0e02-5abc-442e-bdaf-b821adffd671.png)

but while  last 7d, the oldest data is missing in screenshot No2;
![image](https://user-images.githubusercontent.com/66077164/164144178-4cb1a499-c3d0-4a16-b419-1f155aa705f0.png)

note：
1、the kiali version is 1.38.1 ,more detail in screenshot No3
![image](https://user-images.githubusercontent.com/66077164/164144166-9d212841-dd71-4e2f-a557-4507e73b1838.png)

2、i can't  replicate the excess problem this time ,like the request has more header  “endMicros” this time？

3、 i don't know how  to get the data from the jagger derectly, huh~

4、 the http request and response is showed here
###1d
GET /kiali/api/namespaces/xxy/services/zgn-mesh-dont/traces?startMicros=1650421772781350&tags=&limit=100 HTTP/1.1
Referer: http://10.255.23.52:32267/kiali/console/namespaces/xxy/services/zgn-mesh-dont?tab=traces&rangeDuration=86400&refresh=15000



{"data":[{"traceID":"2faf16e925078e6fb60bf551da21f237","spans":[{"traceID":"2faf16e925078e6fb60bf551da21f237","spanID":"b60bf551da21f237","operationName":"zgn-mesh-dont.xxy.svc.cluster.local:8082/*","references":[],"startTime":1650421801131330,"duration":1633,"tags":[{"key":"istio.namespace","type":"string","value":"xxy"},{"key":"response_flags","type":"string","value":"-"},{"key":"upstream_cluster.name","type":"string","value":"inbound|8082||"},{"key":"istio.canonical_revision","type":"string","value":"v0"},{"key":"http.method","type":"string","value":"GET"},{"key":"peer.address","type":"string","value":"10.0.0.1"},{"key":"user_agent","type":"string","value":"curl/7.29.0"},{"key":"http.protocol","type":"string","value":"HTTP/1.1"},{"key":"istio.canonical_service","type":"string","value":"zgn-mesh-dont"},{"key":"http.url","type":"string","value":"http://10.255.23.52:30984/hello"},{"key":"node_id","type":"string","value":"sidecar~10.0.0.118~zgn-mesh-dont-7b79f988fb-hlpqs.xxy~xxy.svc.cluster.local"},{"key":"component","type":"string","value":"proxy"},{"key":"upstream_cluster","type":"string","value":"inbound|8082||"},{"key":"request_size","type":"string","value":"0"},{"key":"downstream_cluster","type":"string","value":"-"},{"key":"http.status_code","type":"string","value":"200"},{"key":"guid:x-request-id","type":"string","value":"fd69f690-1446-93a0-b35d-456c25f45058"},{"key":"istio.mesh_id","type":"string","value":"cluster.local"},{"key":"response_size","type":"string","value":"48"},{"key":"span.kind","type":"string","value":"server"},{"key":"internal.span.format","type":"string","value":"zipkin"}],"logs":[],"processID":"p1","warnings":null}],"processes":{"p1":{"serviceName":"zgn-mesh-dont.xxy","tags":[{"key":"ip","type":"string","value":"10.0.0.118"}]}},"warnings":null},{"traceID":"31b17f2085c93e0912c36170dac50a91","spans":[{"traceID":"31b17f2085c93e0912c36170dac50a91","spanID":"12c36170dac50a91","operationName":"zgn-mesh-dont.xxy.svc.cluster.local:8082/*","references":[],"startTime":1650421793893317,"duration":1349,"tags":[{"key":"http.status_code","type":"string","value":"200"},{"key":"http.method","type":"string","value":"GET"},{"key":"request_size","type":"string","value":"0"},{"key":"downstream_cluster","type":"string","value":"-"},{"key":"component","type":"string","value":"proxy"},{"key":"istio.canonical_revision","type":"string","value":"v0"},{"key":"istio.namespace","type":"string","value":"xxy"},{"key":"upstream_cluster","type":"string","value":"inbound|8082||"},{"key":"response_size","type":"string","value":"48"},{"key":"peer.address","type":"string","value":"10.0.0.1"},{"key":"response_flags","type":"string","value":"-"},{"key":"node_id","type":"string","value":"sidecar~10.0.0.118~zgn-mesh-dont-7b79f988fb-hlpqs.xxy~xxy.svc.cluster.local"},{"key":"http.url","type":"string","value":"http://10.255.23.52:30984/hello"},{"key":"user_agent","type":"string","value":"curl/7.29.0"},{"key":"http.protocol","type":"string","value":"HTTP/1.1"},{"key":"istio.mesh_id","type":"string","value":"cluster.local"},{"key":"guid:x-request-id","type":"string","value":"3a34aaa6-ce21-92c0-850b-c57a47e1d622"},{"key":"upstream_cluster.name","type":"string","value":"inbound|8082||"},{"key":"istio.canonical_service","type":"string","value":"zgn-mesh-dont"},{"key":"span.kind","type":"string","value":"server"},{"key":"internal.span.format","type":"string","value":"zipkin"}],"logs":[],"processID":"p1","warnings":null}],"processes":{"p1":{"serviceName":"zgn-mesh-dont.xxy","tags":[{"key":"ip","type":"string","value":"10.0.0.118"}]}},"warnings":null}],"errors":null,"jaegerServiceName":"zgn-mesh-dont.xxy"}



###7d
GET /kiali/api/namespaces/xxy/services/zgn-mesh-dont/traces?startMicros=1650420939820958&tags=&limit=100 HTTP/1.1
Referer: http://10.255.23.52:32267/kiali/console/namespaces/xxy/services/zgn-mesh-dont?tab=traces&rangeDuration=604800&traceId=701b7b8b357cf1196a450403f96df6d3&refresh=1500

{"data":[{"traceID":"add112151bd719c9bb1f9fd3f62a0c3a","spans":[{"traceID":"add112151bd719c9bb1f9fd3f62a0c3a","spanID":"bb1f9fd3f62a0c3a","operationName":"zgn-mesh-dont.xxy.svc.cluster.local:8082/*","references":[],"startTime":1650420939820958,"duration":1326,"tags":[{"key":"peer.address","type":"string","value":"10.0.0.1"},{"key":"component","type":"string","value":"proxy"},{"key":"http.url","type":"string","value":"http://10.255.23.52:30984/hello"},{"key":"request_size","type":"string","value":"0"},{"key":"response_size","type":"string","value":"48"},{"key":"downstream_cluster","type":"string","value":"-"},{"key":"http.protocol","type":"string","value":"HTTP/1.1"},{"key":"upstream_cluster","type":"string","value":"inbound|8082||"},{"key":"istio.canonical_revision","type":"string","value":"v0"},{"key":"istio.namespace","type":"string","value":"xxy"},{"key":"istio.mesh_id","type":"string","value":"cluster.local"},{"key":"response_flags","type":"string","value":"-"},{"key":"guid:x-request-id","type":"string","value":"51d34406-a4be-9ac5-9464-86861d4b78cd"},{"key":"http.status_code","type":"string","value":"200"},{"key":"node_id","type":"string","value":"sidecar~10.0.0.118~zgn-mesh-dont-7b79f988fb-hlpqs.xxy~xxy.svc.cluster.local"},{"key":"istio.canonical_service","type":"string","value":"zgn-mesh-dont"},{"key":"user_agent","type":"string","value":"curl/7.29.0"},{"key":"http.method","type":"string","value":"GET"},{"key":"upstream_cluster.name","type":"string","value":"inbound|8082||"},{"key":"span.kind","type":"string","value":"server"},{"key":"internal.span.format","type":"string","value":"zipkin"}],"logs":[],"processID":"p1","warnings":null}],"processes":{"p1":{"serviceName":"zgn-mesh-dont.xxy","tags":[{"key":"ip","type":"string","value":"10.0.0.118"}]}},"warnings":null},{"traceID":"31e988177dec9a2a918a47d023110abc","spans":[{"traceID":"31e988177dec9a2a918a47d023110abc","spanID":"918a47d023110abc","operationName":"zgn-mesh-dont.xxy.svc.cluster.local:8082/*","references":[],"startTime":1650420949587293,"duration":1217,"tags":[{"key":"node_id","type":"string","value":"sidecar~10.0.0.118~zgn-mesh-dont-7b79f988fb-hlpqs.xxy~xxy.svc.cluster.local"},{"key":"istio.mesh_id","type":"string","value":"cluster.local"},{"key":"component","type":"string","value":"proxy"},{"key":"peer.address","type":"string","value":"10.0.0.1"},{"key":"response_size","type":"string","value":"48"},{"key":"istio.namespace","type":"string","value":"xxy"},{"key":"http.url","type":"string","value":"http://10.255.23.52:30984/hello"},{"key":"upstream_cluster","type":"string","value":"inbound|8082||"},{"key":"http.method","type":"string","value":"GET"},{"key":"user_agent","type":"string","value":"curl/7.29.0"},{"key":"istio.canonical_service","type":"string","value":"zgn-mesh-dont"},{"key":"request_size","type":"string","value":"0"},{"key":"downstream_cluster","type":"string","value":"-"},{"key":"upstream_cluster.name","type":"string","value":"inbound|8082||"},{"key":"response_flags","type":"string","value":"-"},{"key":"http.protocol","type":"string","value":"HTTP/1.1"},{"key":"http.status_code","type":"string","value":"200"},{"key":"guid:x-request-id","type":"string","value":"81305b96-6790-9b40-b5a8-f53c307bf1ca"},{"key":"istio.canonical_revision","type":"string","value":"v0"},{"key":"span.kind","type":"string","value":"server"},{"key":"internal.span.format","type":"string","value":"zipkin"}],"logs":[],"processID":"p1","warnings":null}],"processes":{"p1":{"serviceName":"zgn-mesh-dont.xxy","tags":[{"key":"ip","type":"string","value":"10.0.0.118"}]}},"warnings":null}],"errors":null,"jaegerServiceName":"zgn-mesh-dont.xxy"}

**Comment by lucasponce** [comment] 2022-04-20 07:39
Ah, thanks @HaloGT for taking the time to provide the example.
I think I know what is happening here and yes, it requires some explanation :).
Kiali introduced a "split" mechanism when querying Jaeger for long intervals
![image](https://user-images.githubusercontent.com/1662329/164174699-3a4ad949-dae2-4383-b963-3d02a755e8b5.png)

Jaeger has a "limit" of returning the last N traces, so, but if you have a lot of traces in the last minutes but you want to extend the query interval, it won't work, as Jaeger will return always the first N traces.

Then to help users in those scenarios, we introduced some time ago a "split strategy" then you'd see the N traces at intervals, as it shows in your example.

Instead of a single query to the backend, Kiali creates some concurrent ones and merges the results.

That's expected as Jaeger won't return uniformly the traces, i.e. if you have a limit of 100, and you have 7 days, you will get always the first 100 if those happened at the beginning of the interval, and probably the same result if you increase the duration from 7 days to 10 days, etc.

This query mechanism was introduced one year ago and it works well for shorter intervals, but yes, for longer ones, there is no good solution (as we depend on the native support that jaeger/open telemetry offers to query the backend).

Perhaps with your feedback, we could refine this feature, but yes, I looks it works as expected, but it deserved an explanation (I can add a FAQ entry in the Kiali doc).

**Comment by jshaughn** [comment] 2022-08-15 19:11
@HaloGT , I am closing this issue given the above explanation.  If you have a suggestion on how this behavior could be improved please feel free to create an Enhancement request, andlink this issue.

**Closed by jshaughn** 2022-08-15 19:11 UTC
Labels: bug
