### ISSUE TITLE
Unable to install kiali on GKE cluster

### ISSUE THREAD

**Issue by SeriyBg** [kiali/kiali#812] opened 2019-01-29 18:32 UTC
**Describe the bug**
Trying to install Kiali on running cluster on GKE and run into an error

**Versions used**
Kiali: latest
Istio: 1.0.3
Kubernetes flavour and version: GKE v1.10.11-gke.1

**To Reproduce**
1. Run `curl -L http://git.io/getLatestKialiKubernetes | bash`
2. Receiving the error:
```
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.11/deploy/kubernetes/secret.yaml
error: error validating "STDIN": error validating data: [unknown object type "nil" in Secret.data.passphrase, unknown object type "nil" in Secret.data.username]; if you choose to ignore these errors, turn validation off with --validate=false
ERROR: Failed to deploy to kubernetes. Aborting.
```

**Expected behavior**
Installation should pass correctly

**Comment by jmazzitelli** [comment] 2019-01-29 19:13
@SeriyBg Can you run the following command as a test - this creates the secret directly with "admin/admin" as the credentials:

```
wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.11/deploy/kubernetes/secret.yaml | VERSION_LABEL=v0.11 KIALI_USERNAME_BASE64=YWRtaW4= KIALI_PASSPHRASE_BASE64=YWRtaW4= envsubst | kubectl create -n istio-system -f - 
```

and tell me if this succeeds or fails.

I don't understand the "unknown object type 'nil'" you are getting. Seems odd unless the "Opaque" type is somehow not supported in your cluster?

**Comment by SeriyBg** [comment] 2019-01-29 19:17
@jmazzitelli this command succeeded and created the secret:
```secret "kiali" created````

**Comment by jmazzitelli** [comment] 2019-01-29 19:34
This must have something to do with the latest change to that file to support asking for credentials by default: https://github.com/kiali/kiali/commit/701f8c3c1b76b6cb3b53a5285dd09f8b23bb5ad9#diff-255fef72757f475ab2b565e898078260

I can replicate the problem.

**Comment by jmazzitelli** [comment] 2019-01-29 19:35
For now, to workaround, provide your own username and password:

```
curl -L http://git.io/getLatestKialiKubernetes | KIALI_USERNAME=admin KIALI_PASSPHRASE=admin bash
```

**Comment by SeriyBg** [comment] 2019-01-29 19:41
@jmazzitelli the problems is that there is 404 under the url: https://raw.githubusercontent.com/kiali/kiali/v0.11/deploy/kubernetes/crds.yaml

**Comment by jmazzitelli** [comment] 2019-01-29 19:48
@SeriyBg right, v0.11 didn't have those CRDs and its OK, you can ignore that error. The CRDs are for an optional experimental feature that was recently added. Not needed to run Kiali. NOTE: You are using an old Istio (1.0.3) - if you install the new 1.05 Istio, you will see its helm chart pulls in  Kiali v0.12 and you won't see that error.

The original problem is caused by the new script wanting to prompt for user/pass on stdin, but stdin was already processed via the pipe passing in the script itself. Will need to document that we can't pipe the script in like this - users will have to download, store the .sh script, and run the script separately on the command line. Unless I can figure out a way to get bash to reclaim the stdin from the keyboard, but I don't think that is possible.

**Comment by SeriyBg** [comment] 2019-01-29 19:53
@jmazzitelli make sense, and it's good that there is a workaround here. Thanks a lot.
Also, I have installed the manually not via helm. Maybe this also matters

**Comment by jmazzitelli** [comment] 2019-01-29 20:00
The fix here is a documentation fix (nothing to be fixed in the script itself). I am going to change our docs to change the install command from:

```
curl -L http://git.io/getLatestKialiKubernetes | bash
```

to

```
curl -o /tmp/deploy-kiali.sh -L http://git.io/getLatestKialiKubernetes && bash /tmp/deploy-kiali.sh 
```

This allows the user to download and install in one command, but does not pipe the script directly into bash, rather, stored the script in /tmp and runs it from there thus preserving keyboard stdin for use by the script.

(this same doc fix is required for the OpenShift install script also)

**Comment by jmazzitelli** [comment] 2019-01-29 20:13
Hmmm... didn't think that would work. I thought `<()` is the same as `|` in that it redirects stdin... but my first attempt worked :) Lemme look closer at this. I'm surprised this worked.

**Comment by jmazzitelli** [comment] 2019-01-29 20:17
Interesting -- it isn't like pipe - it actually seems to create a file descriptor and passes it as if it was a file (or... something like that) :) 

Thanks @israel-hdez - I think I'm going to document it like that.

@SeriyBg see above ^^^

**Comment by SeriyBg** [comment] 2019-01-29 20:19
@jmazzitelli yes, the process substitution is a bit different than the pipe, so it should work. I really like this approach proposed by @israel-hdez

**Comment by jmazzitelli** [comment] 2019-01-29 20:44
docs have been updated - user is now told to use `$()` notation, rather than pipe (`|`) notation. See: https://www.kiali.io/gettingstarted/

Thanks @SeriyBg for reporting this.

**Closed by jmazzitelli** 2019-01-29 20:44 UTC

**Comment by satyajituk** [comment] 2019-11-18 15:35
Where exactly to run the bash command to install Kiali? In terminal? Or somewhere in GKE?

**Comment by israel-hdez** [comment] 2019-11-19 15:44
@satyajituk In a terminal where you have available `kubectl` command and you are logged in into your GKE cluster.
