### ISSUE TITLE
Need to specify namespace in error message "Graph not loading: configmaps "istio" not found'

### ISSUE THREAD

**Issue by friedemannf** [kiali/kiali#3821] opened 2021-03-26 18:36 UTC
**Describe the bug**
Kiali is installed via the kiali-operator using the following CR:
```yaml
cr:
  create: true
  name: kiali
  namespace: "default"
  spec:
    auth:
      strategy: "anonymous"
    deployment:
      accessible_namespaces:
        - istio-system
        - default
      ingress_enabled: false
    external_services:
      prometheus:
        url: "http://monitoring-prod-prometheus-prometheus:9090"
```
Kiali starts just fine and seems completely functional except for the Graph display, which errors out with following message 
```
Cannot load the graph: configmaps "istio" not found
```
![image](https://user-images.githubusercontent.com/59653747/112675674-c0104700-8e67-11eb-9376-72d7b8ceaa2b.png)
The Kiali Server logs show the same error along with a stacktrace. All other functionality works as expected, e.g. Traffic Display, Metrics, etc.

I of course checked but the ConfigMap does in fact exist in the namespace `istio-system` that Istio is installed in:
```
❯ kubectl get configmaps --namespace istio-system
NAME                                   DATA   AGE
istio                                  2      20h
``` 

**Versions used**
Kiali: v1.31.0
Istio: 1.9.1
Kubernetes flavour and version: v1.18.16-gke.302

**To Reproduce**
1. Install the prometheus-operator
2. Install Istio using the default profile (ConfigMap is created as `istio` in the `istio-system` namespace)
3. Install kiali-operator with `cr.create: true` into a separate namespace but give access to `istio-system` using `accessible_namespaces`
4. Open the UI & click on Graph
5. See the error in the UI as well as the Kiali Server logs

**Expected behavior**
Kiali to be able to access the `istio` ConfigMap and show a graph in the UI.

**Comment by jmazzitelli** [comment] 2021-03-26 18:58
_[@friedemannf  I'm not 100% sure of what I am going to say, but I'm 75% sure :)  Please try the fix I describe below and tell me if it works]_

This is probably not a bug, but Kiali could use a little better error message here. So I think we should leave this github bug report in place, but perhaps make the title more descriptive of what the problem actually is.

Notice the error message (`Cannot load the graph: configmaps "istio" not found`) doesn't say WHICH NAMESPACE it is looking in for the "istio" ConfigMap. It should say that - if it did, I suspect you would have found the problem.

Notice you put the Kiali CR in the namespace `default` - that is where it will install Kiali. It is also where it will look by default for the Istio components (including the ConfigMap).

If you want to install Kiali in a different namespace than where you installed your Istio control plane, then you need to tell the operator and Kiali where your Istio control plane is (otherwise, the default behavior is to assume Kiali is installed in the Istio control plane - so it is going to think Istio components are in the `default` namespace).

Thus, in your Kiali CR, you need to explicitly specify this: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L66

Example - your yaml should probably look like this:

```
cr:
  create: true
  name: kiali
  namespace: "default"
  spec:
    istio_namespace: istio-system
    ...and the rest...
```

**Comment by friedemannf** [comment] 2021-03-26 19:12
@jmazzitelli Thank you so much for looking into this, you were 100% right. Setting the `spec.istio_namespace` to `istio-system` fixed the issue. I probably should have read the default CR spec more carefully, sorry for that.
But you're also right, a more descriptive error message would help a lot, pointing maybe out the namespaces it's looking in for the ConfigMap. I'll then leave this issue open? Let me know if there's anything else I can do.

**Comment by jmazzitelli** [comment] 2021-03-26 19:47
OK, thanks for confirming @friedemannf . I just updated the title of the issue to be more clear about the problem we should address.

I'm not even sure where in the code that error message is spit out (perhaps you can post the stack trace you saw in the pod logs?). But where ever that error message is generated, we should put in the namespace it was looking at, too.

**Comment by jshaughn** [comment] 2021-03-26 20:34
@jmazzitelli assigning to you to enhance the message.

**Comment by friedemannf** [comment] 2021-03-26 20:43
The stack trace:
```
2021-03-26T19:02:09Z ERR configmaps "istio" not found: goroutine 103289 [running]:
runtime/debug.Stack(0xc001d12640, 0x1c, 0xc000cbe7c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/kiali/kiali/handlers.handlePanic(0x1d61a20, 0xc0008d0460)
	/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:86 +0x159
panic(0x18455a0, 0xc000cbe7c0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/kiali/kiali/graph.CheckError(0x1d1e060, 0xc0009fb9a0)
	/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/util.go:38 +0x9a
github.com/kiali/kiali/graph/telemetry/istio/appender.IdleNodeAppender.AppendGraph(0xc0003254d7, 0x3, 0xc00fa9cc61c90001, 0xc0008ed110, 0xc0022924c0, 0xc0023cea80)
	/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/appender/idle_node.go:55 +0x2b1
github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap(0xc0008ec930, 0x0, 0xc00164c240, 0x6, 0x6, 0x100, 0xc0019c79e0, 0xdf8475800, 0xc0003254d7, 0x3, ...)
	/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:48 +0x282
github.com/kiali/kiali/graph/api.graphNamespacesIstio(0xc000f9e000, 0xc001206640, 0x1b03e15, 0x9, 0x1afec47, 0x5, 0xc000325510, 0x3, 0xdf8475800, 0xc0003254d7, ...)
	/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:44 +0xb8
github.com/kiali/kiali/graph/api.GraphNamespaces(0xc000f9e000, 0x1b03e15, 0x9, 0x1afec47, 0x5, 0xc000325510, 0x3, 0xdf8475800, 0xc0003254d7, 0x3, ...)
	/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:26 +0x178
github.com/kiali/kiali/handlers.GraphNamespaces(0x1d61a20, 0xc0008d0460, 0xc0014c6400)
	/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:51 +0x158
net/http.HandlerFunc.ServeHTTP(0x1bcde48, 0x1d61a20, 0xc0008d0460, 0xc0014c6400)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/kiali/kiali/routing.metricHandler.func1(0x1d61a20, 0xc0008d0460, 0xc0014c6400)
	/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/routing/router.go:90 +0xa3
net/http.HandlerFunc.ServeHTTP(0xc0000c0120, 0x1d61a20, 0xc0008d0460, 0xc0014c6400)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1(0x1d61a20, 0xc0008d0460, 0xc0014c6300)
	/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/authentication.go:622 +0x1ee
net/http.HandlerFunc.ServeHTTP(0xc000382030, 0x1d61a20, 0xc0008d0460, 0xc0014c6300)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/kiali/kiali/server.plainHttpMiddleware.func1(0x1d61a20, 0xc0008d0460, 0xc0014c6300)
	/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/server/server.go:127 +0x6c
net/http.HandlerFunc.ServeHTTP(0xc0022c0160, 0x1d61a20, 0xc0008d0460, 0xc0014c6300)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000274480, 0x1d61a20, 0xc0008d0460, 0xc0014c6100)
	/home/fedora/workspace/kiali-workflow/kiali-release/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xd3
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x1d61660, 0xc0004aae00, 0xc0014c6100)
	/home/fedora/workspace/kiali-workflow/kiali-release/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x225
net/http.HandlerFunc.ServeHTTP(0xc00067d290, 0x1d61660, 0xc0004aae00, 0xc0014c6100)
	/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0000c3940, 0x1d61660, 0xc0004aae00, 0xc0014c6100)
	/usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0004aa1c0, 0x1d61660, 0xc0004aae00, 0xc0014c6100)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0018023c0, 0x1d660e0, 0xc0014b72c0)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c

```
I believe the error itself is thrown by the native k8s clientset but might be wrapped here?
https://github.com/kiali/kiali/blob/v1.31/business/mesh.go#L127

**Comment by jmazzitelli** [comment] 2021-03-26 22:43
> I believe the error itself is thrown by the native k8s clientset but might be wrapped here?
> https://github.com/kiali/kiali/blob/v1.31/business/mesh.go#L127

Yeah.. that's the place. And down further below, this is where the true error is thrown: https://github.com/kiali/kiali/blob/v1.31/kubernetes/kubernetes.go#L32

**Comment by lucasponce** [comment] 2021-03-30 07:34
Side note as it's related to some of the code I've seen.

ConfigMap is cached for local cluster and this logic seems to bypass it.

I don't know if this is the PR or different, but local cluster should not bypass kubernetes objects that are already cached.

I see some of the logic of the mesh seems to do that.

I understand that for multicluster it can be ok.

I think code is easy to see, but ping me in case of doubts, this may have side effects to drop the performance in other operations.

**Closed** 2021-04-21 21:25 UTC
Labels: backlog, bug, team/saturn
