### ISSUE TITLE
kiali reports wrong rps on edges for service aliases going to same deployment, unless focused

### ISSUE THREAD

**Issue by ldemailly** [kiali/kiali#4366] opened 2021-09-17 15:56 UTC
**Describe the bug**
kiali reports wrong rps on edges for service aliases going to same deployment, unless focused

When double clicking on the node, it's correct:

![image](https://user-images.githubusercontent.com/3664595/133817850-2cef3a68-0565-4be7-b2d3-cd167adb5261.png)

Without:

![image](https://user-images.githubusercontent.com/3664595/133817972-b4eb858d-a67c-4401-b00e-6159d20c68f4.png)

![image](https://user-images.githubusercontent.com/3664595/133818000-6524fa80-caf2-4784-a0e4-1f5e32a7f4d2.png)

**Versions used**
Kiali: 1.8.1
Istio: 1.10.4
Kubernetes flavour and version: eks 1.21

**To Reproduce**

Fortio traffic at 16rps to parallel mode proxy sends 16 rps to both c1 and c2

See screenshot 

**Expected behavior**
16 rps on both legs like when focused
(seems it adds the incoming rps to one of the outgoing otherwise)

cc @jshaughn which helped find the workaround

**Comment by ldemailly** [comment] 2021-09-17 16:19
yaml: https://gist.github.com/ldemailly/6f54d33c757af5d70a358a83cf1b7abb

**Comment by jshaughn** [comment] 2021-09-21 21:09
@ldemailly , First, thanks for supplying the complete recreation scenario.  I started by trying to recreate the issue in test code and I could not reproduce.  And so I moved to recreating your exact scenario and I was able to reproduce.

The result is interesting as I think Kiali is actually reporting correctly.  I do think there may be a problem, but if so, I think it's actually in the Istio telemetry.   The reason for what you see is a little bit complicated, and to understand you have to be familiar with how Istio reports telemetry.  The telemetry for each request is actually reported twice, once from the source proxy (the sender's perspective) and once from the destination proxy (the receiver's perspective).  What I see in the Prometheus telemetry is that the source reporting is exactly what we would expect:
```
{
  reporter="source"
  source_workload="fortio-http-proxy-parallel"
  destination_service="fortio-c1-http.fortio.svc.cluster.local"
  destination_service_name="fortio-c1-http"
  destination_workload="fortio-server-deployment-1"
}  rate = 16 req/sec

{
  reporter="source"
  source_workload="fortio-http-proxy-parallel"
  destination_service="fortio-c2-http.fortio.svc.cluster.local",
  destination_service_name="fortio-c2-http"
  destination_workload="fortio-server-deployment-1"
}  rate = 16 req/sec

```
It's an even split with half of the requests being made to `fortio-c1-http` service (16), and half to `fortio-c2-http` service (16).  And all of the requests (16+16=32) end up at the same destination workload, `fortio-server-deployment-1`.

But the issue seems to be with the destination proxy reporting:
```
{
  reporter="destination"
  source_workload="fortio-http-proxy-parallel"
  destination_service="fortio-c1-http.fortio.svc.cluster.local"
  destination_service_name="fortio-c1-http"
  destination_workload="fortio-server-deployment-1"
} rate = 32 req/sec
```
Note that all of the requests (32) are reported as having the `fortio-c1-http` destination_service.

This is exactly what you see in your graph, with the fortio-c1 edge showing 32.  This is because the main graph combines source and destination telemetry to arrive at the full traffic visualization.   Note that when you double-click into the `fortio-http-proxy-parallel` graph you saw your expected traffic.  This is because node graphs show you traffic from the *perspective of that node*.  In other words, when graphing the `fortio-http-proxy-parallel` node, Kiali will use only the telemetry from `fortio-http-proxy-parallel`'s proxy (destination reporting from incoming, source reporting for outgoing).  As we see above, the source reporting from `fortio-http-proxy-parallel` is correct.

But the destination reporting from `fortio-server-deployment-1` is suspicious, and we can see that clearly by double-clicking on `fortio-server-deployment-1` and looking at the resulting node graph:

![kiali-4366](https://user-images.githubusercontent.com/2104052/134246562-35cab28a-a7ad-40a0-afb3-451ee3770c25.png)

OK, I think the next step is to ask Istio whether this telemetry is somehow expected, a known issue, or if you have found a bug.  I often ask Istio maintainer @bianpengyuan for his opinion on these telemetry issues.  Peter, any thoughts?

**Comment by bianpengyuan** [comment] 2021-09-21 21:17
Yeah this is the same issue we ran into at kiali/kiali#4137. It will need https://github.com/istio/istio/issues/33940 to distinguish wanted service at server side.

**Comment by jmazzitelli** [comment] 2021-09-22 00:45
> Yeah this is the same issue we ran into at #4137. It will need [istio/istio#33940](https://github.com/istio/istio/issues/33940) to distinguish wanted service at server side.

I would then close this issue as "not a bug" and defer to https://github.com/istio/istio/issues/33940.

I say "not a bug" because Kiali is correctly graphing the telemetry; it is the underlying telemetry that is incorrect.

**Comment by jshaughn** [comment] 2021-09-22 12:57
@bianpengyuan , I wish I had a better memory  :-)  Thanks for quickly identifying the root cause, I need to be better at recognizing the symptoms.  I am going to add a comment to https://github.com/istio/istio/issues/33940 suggesting the priority be bumped up.

@ldemailly , I will close this issue in favor of the Istio issue.  If you have any further questions about this one, feel free to ask.

**Closed by jshaughn** 2021-09-22 12:57 UTC
Labels: bug, backlog
