### ISSUE TITLE
Spark-Line HTTP Request Traffic Graph Info Showing Twice

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#2098] opened 2020-01-14 15:47 UTC
The HTTP Request Traffic Graph is showing the info twice, when hover-over a plotted line.

![Selection_121](https://user-images.githubusercontent.com/7262987/72358753-0b9f6080-36bb-11ea-9ddb-743d38e7656a.jpg)

**Comment by jotak** [comment] 2020-01-14 16:20
The same info is displayed twice because there's two datapoint mixed up (one for error rate and one for total rate). When https://github.com/kiali/kiali/issues/2097 is fixed, this will be more explicit that it's two different metrics ; so I think we can say it's a duplicate of #2097

**Closed** 2020-01-20 13:32 UTC
Labels: bug, duplicate
