### ISSUE TITLE
前端项目跑不起来，一直提示    此处应有 KIALI_ENV 

### ISSUE THREAD

**Issue by yanghong1995220** [kiali/kiali#2900] opened 2020-06-12 00:59 UTC
**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to 
>       [Kiali-users](https://groups.google.com/forum/#!forum/kiali-users) mailing list.
>
> For general Kiali-development questions refer to 
>       [Kiali-dev](https://groups.google.com/forum/#!forum/kiali-dev) mailing list.
>
> If you want to propose an enhancement or feature request, please use the feature request template.

**Describe the bug**

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali:
Istio:
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**To Reproduce**

**Expected behavior**

**Comment by cfcosta** [comment] 2020-06-12 01:05
Hello, and thanks for reporting. I’m closing this, as the issue does not follow our reporting rules. In general, we are pretty open about how bugs and problems are reported, but:

* The title is not in english, and as fair as I know none of us speak chinese.
* Even after translating (which I did), it was not descriptive enough to understand what the issue is about.

Please do recreate this issue with more concise details, and we can take a look :)

**Closed** 2020-06-12 01:05 UTC
Labels: bug
