### ISSUE TITLE
Namespace with External Registry Service only - UI Error Loading services

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#4720] opened 2022-02-09 19:21 UTC
Happens on Kiali master after creating steps from https://github.com/kiali/kiali/issues/4711#issuecomment-1032683113

1. Create sample-ns.
2. Create all objects described in issue comment.
3. Go to Kiali Service list.
Error loading services in UI. But API returns the list of services.
![Screenshot from 2022-02-09 20-16-34](https://user-images.githubusercontent.com/604313/153274553-cec47ab4-83ad-4ecc-9ae0-dce354a50bb9.png)

![Screenshot from 2022-02-09 20-21-10](https://user-images.githubusercontent.com/604313/153274640-2baae003-2191-4cc0-9718-037f57bdc3cc.png)

**Comment by lucasponce** [comment] 2022-02-10 07:50
This is weird, I can take a look.
Did you see any extra log in the backend?

**Comment by jshaughn** [comment] 2022-03-10 19:57
I investigated this and it turns out to be a duplicate of https://github.com/kiali/kiali/issues/4793.  So, it was already fixed by https://github.com/kiali/kiali-ui/pull/2322.  I know this because my local fix was almost exactly the same as what Hayk did in that PR. I had yet to pull it down locally and when I did I got the conflict and saw the similar change.  Closing.

**Closed by jshaughn** 2022-03-10 19:57 UTC
Labels: bug, backlog
