### ISSUE TITLE
Move actions out views in details pages

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#1909] opened 2019-11-11 10:13 UTC
Move actions in inbound, outbound metrics and logs out  tabs

**Comment by abonas** [comment] 2020-02-04 19:14
can you please elaborate more about this issue, what is the current/expected result and the use case? I can't understand if this is UX, enhancement, management, etc

**Comment by aljesusg** [comment] 2020-02-04 19:43
Yes sorry, I opened this one because we moved the metricsDuration dropdown (Refresh interval...) out the tabs content for details, traffic, traces tab etc...but in Inbound/Outbound metrics the dropdowns are inside the content tab

**Comment by jotak** [comment] 2020-02-05 09:18
I think we can close this one, after discussion with UX @xeviknal opened this: https://github.com/kiali/kiali/issues/2188 instead
ok?

**Comment by aljesusg** [comment] 2020-02-05 09:21
No, This is different. if you see the images in Overview, Traffic, Traces....the Xm traffic dropdown and refresh button are outside the tab content but in metrics not

## good position

![Screenshot from 2020-02-05 10-19-34](https://user-images.githubusercontent.com/3019213/73828165-13a57880-4801-11ea-8a94-0c7aeb982a42.png)
![Screenshot from 2020-02-05 10-19-25](https://user-images.githubusercontent.com/3019213/73828169-143e0f00-4801-11ea-9131-0c8d99325d2a.png)

## bad position

![Screenshot from 2020-02-05 10-19-41](https://user-images.githubusercontent.com/3019213/73828157-10aa8800-4801-11ea-9bed-80045fea073f.png)

**Comment by jotak** [comment] 2020-02-05 09:38
in my understanding, the task opened by @xeviknal is also to unify this (but not as suggested here, different solution)

**Comment by aljesusg** [comment] 2020-02-05 09:52
Oh I thought it was just for align the items to the right

**Comment by abonas** [comment] 2020-02-05 10:48
so if this is duplicate of another issue, please close

**Comment by aljesusg** [comment] 2020-02-05 11:24
I want to be sure that in the https://github.com/kiali/kiali/issues/2188 of @xeviknal he is addressing this too because the title and description is related with another thing 

> Align the dropdwon button on Detail pages.
Align it to tab-level (shifting it down) and align to the right, to the card border. See the image.

![Screenshot of Kiali Console - 2020-01-30T173901 105](https://user-images.githubusercontent.com/613814/73469942-6dccb680-4387-11ea-91f1-fa9c8c92a753.jpg)

**Comment by lucasponce** [comment] 2021-08-04 08:20
Outdated.
This change is already done.

**Closed by lucasponce** 2021-08-04 08:20 UTC
Labels: team/jupiter
