### ISSUE TITLE
Add ability to turn on/off specific log windows

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2765] opened 2020-05-11 21:35 UTC
**Is your feature request related to a problem? Please describe.**
A pod will have 1 or more app containers (1 is common but not definite).  The pod may or may not have an istio-proxy container (the sidecar is typical for in-mesh pods, but not required).

The user should be able to select the container logs to display.

**Describe the solution you'd like**
The logs tab should display 1 log window per selected container (perhaps up to a max of 2 or 3?).  It should likely default to the first (or only) app container as well as the istio-proxy container, if it exists.

In general there will be 1 or 2 containers, perhaps more, but likely only a few.

**Describe alternatives you've considered**
We have a splitter bar currently that can handle up to two log windows.  If technically easy we could add more log windows but otherwise we should limit to 1 or two windows.

Epic: #2232

**Comment by jshaughn** [comment] 2020-05-12 15:10
@mtho11 I updated the description with some more detail as to what we need here.  Also, I'm going to set to "waiting ux" for an indication of how to display the choices.  In this case the problem is well defined so let's start with UX.

**Comment by jshaughn** [comment] 2020-05-15 18:55
@mtho11 This has been upgraded to bug due to the comments in #2203 , please make this the priority for the epic work.

**Comment by jshaughn** [comment] 2020-05-18 17:19
@mtho11 I'm dropping the Waiting-UX label and now that it is considered a bug.  Please feel free to start work with a solution that you can review with UX in the Tuesday and/or Thursday meetings.  I'd like to see something merged in time for the 1.19.0-alpha.0 (5/22 12:30pm PT), if possible.

**Comment by mtho11** [comment] 2020-05-18 17:24
@jshaughn yep, on it!

**Closed** 2020-05-22 16:26 UTC
Labels: area/ux, backlog, backport/v1.18, bug, epic subtask
