### ISSUE TITLE
[operator] Playbook "create additional kiali labels..." fails due to unquoted string in label

### ISSUE THREAD

**Issue by meseta** [kiali/kiali#4157] opened 2021-07-06 20:24 UTC
**Describe the bug**

When `label_selector` is used, and `accessible_namespaces` is not `"**"`, Kiali Operator fails at Ansible Playbook task with name "Create additional Kiali label on all accessible namespaces" with a k8s return value 422 error due to unquoted label value with error: `v1.Namespace.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found t, error found in #10 byte of ...|enabled":true},"name|...`

It appears that the k8s definition in https://github.com/kiali/kiali-operator/blob/5b07214db85f6f892cf8937239416694873e476e/roles/default/kiali-deploy/tasks/main.yml#L792 does not apply quotes to the value, which kubernetes rejects with 422 error.
```yaml
  k8s:
    state: present
    definition: |
      {% for namespace in namespaces %}
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
        labels:
          {{ the_namespace_label_name }}: {{ the_namespace_label_value }}
      ...
      {% endfor %}
```

I tested the fix by exec-ing into the running kiali-operator pod and directly editing the ansible playbook to add quotes around the label value. This resolves the error the next time kiali-operator
```yaml
        labels:
          {{ the_namespace_label_name }}: "{{ the_namespace_label_value }}"
```
This should be safe as adding quotes to label_selector is forbidden, so there is no chance of accidental double-quoting

**Versions used**
Kiali: 1.36
Istio: 1.10.0
Kubernetes flavour and version: GKE 1.18.17-gke.1901

**To Reproduce**
1. set `spec.api.namespaces.label_selector` to `kiali-enabled=true` in the CR
2. set `spec.deployment.accessible_namespaces` to valid namespace names (not wildcard "**"), in my case ["platform", "projects"]
3. deploy kiali CR
4. observe the following error in logs (ansible.operator-sdk/verbosity: 2)
5. observe the remainder of the playbook was skipped due to error

```
TASK [default/kiali-deploy : Create additional Kiali label on all accessible namespaces] ***

fatal: [localhost]: FAILED! => {"changed": false, "error": 422, "msg": "Failed to patch object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\" \\\\\"\\\\\" is invalid: patch: Invalid value: \\\\\"{\\\\\\\\\\\\\"apiVersion\\\\\\\\\\\\\":\\\\\\\\\\\\\"v1\\\\\\\\\\\\\",\\\\\\\\\\\\\"kind\\\\\\\\\\\\\":\\\\\\\\\\\\\"Namespace\\\\\\\\\\\\\",\\\\\\\\\\\\\"metadata\\\\\\\\\\\\\":{\\\\\\\\\\\\\"creationTimestamp\\\\\\\\\\\\\":\\\\\\\\\\\\\"2020-11-25T22:56:57Z\\\\\\\\\\\\\",\\\\\\\\\\\\\"labels\\\\\\\\\\\\\":{\\\\\\\\\\\\\"kiali-enabled\\\\\\\\\\\\\":true},\\\\\\\\\\\\\"name\\\\\\\\\\\\\":\\\\\\\\\\\\\"istio-system\\\\\\\\\\\\\",\\\\\\\\\\\\\"resourceVersion\\\\\\\\\\\\\":\\\\\\\\\\\\\"8701477\\\\\\\\\\\\\",\\\\\\\\\\\\\"uid\\\\\\\\\\\\\":\\\\\\\\\\\\\"3b13e464-bf0b-4f53-8d1c-0105ba8d31e7\\\\\\\\\\\\\"},\\\\\\\\\\\\\"spec\\\\\\\\\\\\\":{\\\\\\\\\\\\\"finalizers\\\\\\\\\\\\\":[\\\\\\\\\\\\\"kubernetes\\\\\\\\\\\\\"]},\\\\\\\\\\\\\"status\\\\\\\\\\\\\":{\\\\\\\\\\\\\"phase\\\\\\\\\\\\\":\\\\\\\\\\\\\"Active\\\\\\\\\\\\\"}}\\\\\": v1.Namespace.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects \\\\\" or n, but found t, error found in #10 byte of ...|enabled\\\\\":true},\\\\\"name|..., bigger context ...|\\\\\"2020-11-25T22:56:57Z\\\\\",\\\\\"labels\\\\\":{\\\\\"kiali-enabled\\\\\":true},\\\\\"name\\\\\":\\\\\"istio-system\\\\\",\\\\\"resourceVersion\\\\\":\\\\\"8701|...\",\"reason\":\"Invalid\",\"details\":{\"causes\":[{\"reason\":\"FieldValueInvalid\",\"message\":\"Invalid value: \\\\\"{\\\\\\\\\\\\\"apiVersion\\\\\\\\\\\\\":\\\\\\\\\\\\\"v1\\\\\\\\\\\\\",\\\\\\\\\\\\\"kind\\\\\\\\\\\\\":\\\\\\\\\\\\\"Namespace\\\\\\\\\\\\\",\\\\\\\\\\\\\"metadata\\\\\\\\\\\\\":{\\\\\\\\\\\\\"creationTimestamp\\\\\\\\\\\\\":\\\\\\\\\\\\\"2020-11-25T22:56:57Z\\\\\\\\\\\\\",\\\\\\\\\\\\\"labels\\\\\\\\\\\\\":{\\\\\\\\\\\\\"kiali-enabled\\\\\\\\\\\\\":true},\\\\\\\\\\\\\"name\\\\\\\\\\\\\":\\\\\\\\\\\\\"istio-system\\\\\\\\\\\\\",\\\\\\\\\\\\\"resourceVersion\\\\\\\\\\\\\":\\\\\\\\\\\\\"8701477\\\\\\\\\\\\\",\\\\\\\\\\\\\"uid\\\\\\\\\\\\\":\\\\\\\\\\\\\"3b13e464-bf0b-4f53-8d1c-0105ba8d31e7\\\\\\\\\\\\\"},\\\\\\\\\\\\\"spec\\\\\\\\\\\\\":{\\\\\\\\\\\\\"finalizers\\\\\\\\\\\\\":[\\\\\\\\\\\\\"kubernetes\\\\\\\\\\\\\"]},\\\\\\\\\\\\\"status\\\\\\\\\\\\\":{\\\\\\\\\\\\\"phase\\\\\\\\\\\\\":\\\\\\\\\\\\\"Active\\\\\\\\\\\\\"}}\\\\\": v1.Namespace.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects \\\\\" or n, but found t, error found in #10 byte of ...|enabled\\\\\":true},\\\\\"name|..., bigger context ...|\\\\\"2020-11-25T22:56:57Z\\\\\",\\\\\"labels\\\\\":{\\\\\"kiali-enabled\\\\\":true},\\\\\"name\\\\\":\\\\\"istio-system\\\\\",\\\\\"resourceVersion\\\\\":\\\\\"8701|...\",\"field\":\"patch\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}

PLAY RECAP *********************************************************************

localhost : ok=57 changed=4 unreachable=0 failed=1 skipped=62 rescued=0 ignored=0
```

**Expected behavior**
Kiali operator deploys kiali without issues

**Comment by jmazzitelli** [comment] 2021-07-06 20:39
Interesting. No one has seen or reported this before, and our testing has not seen a problem here. I'll run some tests here and see if I can determine what the problem is. Need to replicate to confirm this is really a bug.

**Comment by jmazzitelli** [comment] 2021-07-06 20:45
BTW: for the record, setting the label_selector when using non-** for accessible_namespaces is not needed nor recommended. See: https://kiali.io/documentation/staging/installation-guide/#_namespace_selectors where it says
```
... the default value of label_selector is kiali.io/member-of: <spec.istio_namespace> when
spec.deployment.accessible_namespaces is not set to the "all namespaces" value ["**"].
This allows you to have multiple control planes in the same cluster, with each control plane
having its own Kiali instance.
```

**Comment by jmazzitelli** [comment] 2021-07-06 21:11
Ahh.. OK. Now I see why this is, and I see why we haven't seen this before.

First, to replicate, run this command:

```
helm install \
  --create-namespace \
  --namespace kiali-operator \
  --repo https://kiali.org/helm-charts \
  --version 1.36.0 \
  --set cr.create=true \
  --set cr.spec.deployment.accessible_namespaces[0]=default \
  --set cr.spec.api.namespaces.label_selector=kiali-enabled=true \
  kiali-operator kiali-operator
```

Results in this error:

```
    message: 'Failed to patch object: b''{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"
      \\"\\" is invalid: patch: Invalid value: \\"{\\\\\\"apiVersion\\\\\\":\\\\\\"v1\\\\\\",\\\\\\"kind\\\\\\":\\\\\\"Namespace\\\\\\",\\\\\\"metadata\\\\\\":{\\\\\\"creationTimestamp\\\\\\":\\\\\\"2021-07-03T08:01:11Z\\\\\\",\\\\\\"labels\\\\\\":{\\\\\\"kiali-enabled\\\\\\":true},\\\\\\"managedFields\\\\\\":[{\\\\\\"manager\\\\\\":\\\\\\"kube-apiserver\\\\\\",\\\\\\"operation\\\\\\":\\\\\\"Update\\\\\\",\\\\\\"apiVersion\\\\\\":\\\\\\"v1\\\\\\",\\\\\\"time\\\\\\":\\\\\\"2021-07-03T08:01:11Z\\\\\\",\\\\\\"fieldsType\\\\\\":\\\\\\"FieldsV1\\\\\\",\\\\\\"fieldsV1\\\\\\":{\\\\\\"f:status\\\\\\":{\\\\\\"f:phase\\\\\\":{}}}}],\\\\\\"name\\\\\\":\\\\\\"default\\\\\\",\\\\\\"resourceVersion\\\\\\":\\\\\\"333330\\\\\\",\\\\\\"uid\\\\\\":\\\\\\"05e7c4a0-e44f-47f1-a6e6-f0cf9b52851f\\\\\\"},\\\\\\"spec\\\\\\":{\\\\\\"finalizers\\\\\\":[\\\\\\"kubernetes\\\\\\"]},\\\\\\"status\\\\\\":{\\\\\\"phase\\\\\\":\\\\\\"Active\\\\\\"}}\\":
      v1.Namespace.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects \\" or n,
      but found t, error found in #10 byte of ...|enabled\\":true},\\"mana|..., bigger
      context ...|\\"202    message: 'Failed to patch object: b''{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"
      \\"\\" is invalid: patch: Invalid value: \\"{\\\\\\"apiVersion\\\\\\":\\\\\\"v1\\\\\\",\\\\\\"kind\\\\\\":\\\\\\"Namespace\\\\\\",\\\\\\"metadata\\\\\\":{\\\\\\"creationTimestamp\\\\\\":\\\\\\"2021-07-03T08:01:11Z\\\\\\",\\\\\\"labels\\\\\\":{\\\\\\"kiali-enabled\\\\\\":true},\\\\\\"managedFields\\\\\\":[{\\\\\\"manager\\\\\\":\\\\\\"kube-apiserver\\\\\\",\\\\\\"operation\\\\\\":\\\\\\"Update\\\\\\",\\\\\\"apiVersion\\\\\\":\\\\\\"v1\\\\\\",\\\\\\"time\\\\\\":\\\\\\"2021-07-03T08:01:11Z\\\\\\",\\\\\\"fieldsType\\\\\\":\\\\\\"FieldsV1\\\\\\",\\\\\\"fieldsV1\\\\\\":{\\\\\\"f:status\\\\\\":{\\\\\\"f:phase\\\\\\":{}}}}],\\\\\\"name\\\\\\":\\\\\\"default\\\\\\",\\\\\\"resourceVersion\\\\\\":\\\\\\"333330\\\\\\",\\\\\\"uid\\\\\\":\\\\\\"05e7c4a0-e44f-47f1-a6e6-f0cf9b52851f\\\\\\"},\\\\\\"spec\\\\\\":{\\\\\\"finalizers\\\\\\":[\\\\\\"kubernetes\\\\\\"]},\\\\\\"status\\\\\\":{\\\\\\"phase\\\\\\":\\\\\\"Active\\\\\\"}}\\":
      v1.Namespace.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects \\" or n,
      but found t, error found in #10 byte of ...|enabled\\":true},\\"mana|..., bigger
      context ...|\\"2021-07-03T08:01:11Z\\",\\"labels\\":{\\"kiali-enabled\\":true},\\"managedFields\\":[{\\"manager\\":\\"kube-apiserver\\",|...","reason":"Invalid","details":{"causes":[{"reason":"FieldValueInvalid","message":"Invalid
      value: \\"{\\\\\\"apiVersion\\\\\\":\\\\\\"v1\\\\\\",\\\\\\"kind\\\\\\":\\\\\\"Namespace\\\\\\",\\\\\\"metadata\\\\\\":{\\\\\\"creationTimestamp\\\\\\":\\\\\\"2021-07-03T08:01:11Z\\\\\\",\\\\\\"labels\\\\\\":{\\\\\\"kiali-enabled\\\\\\":true},\\\\\\"managedFields\\\\\\":[{\\\\\\"manager\\\\\\":\\\\\\"kube-apiserver\\\\\\",\\\\\\"operation\\\\\\":\\\\\\"Update\\\\\\",\\\\\\"apiVersion\\\\\\":\\\\\\"v1\\\\\\",\\\\\\"time\\\\\\":\\\\\\"2021-07-03T08:01:11Z\\\\\\",\\\\\\"fieldsType\\\\\\":\\\\\\"FieldsV1\\\\\\",\\\\\\"fieldsV1\\\\\\":{\\\\\\"f:status\\\\\\":{\\\\\\"f:phase\\\\\\":{}}}}],\\\\\\"name\\\\\\":\\\\\\"default\\\\\\",\\\\\\"resourceVersion\\\\\\":\\\\\\"333330\\\\\\",\\\\\\"uid\\\\\\":\\\\\\"05e7c4a0-e44f-47f1-a6e6-f0cf9b52851f\\\\\\"},\\\\\\"spec\\\\\\":{\\\\\\"finalizers\\\\\\":[\\\\\\"kubernetes\\\\\\"]},\\\\\\"status\\\\\\":{\\\\\\"phase\\\\\\":\\\\\\"Active\\\\\\"}}\\":
      v1.Namespace.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects \\" or n,
      but found t, error found in #10 byte of ...|enabled\\":true},\\"mana|..., bigger
      context ...|\\"2021-07-03T08:01:11Z\\",\\"labels\\":{\\"kiali-enabled\\":true},\\"managedFields\\":[{\\"manager\\":\\"kube-apiserver\\",|...","field":"patch"}]},"code":422}\n'''
1-07-03T08:01:11Z\\",\\"labels\\":{\\"kiali-enabled\\":true},\\"managedFields\\":[{\\"manager\\":\\"kube-apiserver\\",|...","reason":"Invalid","details":{"causes":[{"reason":"FieldValueInvalid","message":"Invalid
      value: \\"{\\\\\\"apiVersion\\\\\\":\\\\\\"v1\\\\\\",\\\\\\"kind\\\\\\":\\\\\\"Namespace\\\\\\",\\\\\\"metadata\\\\\\":{\\\\\\"creationTimestamp\\\\\\":\\\\\\"2021-07-03T08:01:11Z\\\\\\",\\\\\\"labels\\\\\\":{\\\\\\"kiali-enabled\\\\\\":true},\\\\\\"managedFields\\\\\\":[{\\\\\\"manager\\\\\\":\\\\\\"kube-apiserver\\\\\\",\\\\\\"operation\\\\\\":\\\\\\"Update\\\\\\",\\\\\\"apiVersion\\\\\\":\\\\\\"v1\\\\\\",\\\\\\"time\\\\\\":\\\\\\"2021-07-03T08:01:11Z\\\\\\",\\\\\\"fieldsType\\\\\\":\\\\\\"FieldsV1\\\\\\",\\\\\\"fieldsV1\\\\\\":{\\\\\\"f:status\\\\\\":{\\\\\\"f:phase\\\\\\":{}}}}],\\\\\\"name\\\\\\":\\\\\\"default\\\\\\",\\\\\\"resourceVersion\\\\\\":\\\\\\"333330\\\\\\",\\\\\\"uid\\\\\\":\\\\\\"05e7c4a0-e44f-47f1-a6e6-f0cf9b52851f\\\\\\"},\\\\\\"spec\\\\\\":{\\\\\\"finalizers\\\\\\":[\\\\\\"kubernetes\\\\\\"]},\\\\\\"status\\\\\\":{\\\\\\"phase\\\\\\":\\\\\\"Active\\\\\\"}}\\":
      v1.Namespace.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects \\" or n,
      but found t, error found in #10 byte of ...|enabled\\":true},\\"mana|..., bigger
      context ...|\\"2021-07-03T08:01:11Z\\",\\"labels\\":{\\"kiali-enabled\\":true},\\"managedFields\\":[{\\"manager\\":\\"kube-apiserver\\",|...","field":"patch"}]},"code":422}\n'''
```

This is because you have told the Kiali operator to create a label called `kiali-enabled` on the accessible namespaces, with a value of `true` (note - not quoted). This is invalid because label values must be strings, not booleans. So you have to quote the value. The same thing will happen if you try to create the label manually like this:

```
$ cat <<EOM | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: testns
  labels:
    kiali-enabled: true
EOM

error: unable to decode "STDIN": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found t, error found in #10 byte of ...|enabled":true},"name|..., bigger context ...|Namespace","metadata":{"labels":{"kiali-enabled":true},"name":"testns"}}|...
```


I don't think we have tested with a label_selector whose value is `true` (or `false` for that matter) which is why no one has reported or seen this. Which is odd because we actually use this example in the docs (see `kiali-enabled=true` in the docs [here](https://kiali.io/documentation/staging/installation-guide/#_namespace_selectors)).

I think the proposed solution in the description is valid. Because no matter what you set label_selector to, it will always be in the form of `KEY=VALUE` -- it should be possible for the Kiali Operator to always wrap that "VALUE" inside double quotes.

**Comment by jmazzitelli** [comment] 2021-07-06 21:39
This is fixed here: https://github.com/kiali/kiali-operator/pull/350

But I just want to reiterate what I said before - when using accessible-namespaces that is not set to `[**]`, you should not set that label_selector - it will be set for you. It is not recommended that you change the label_selector in this case because it will likely affect Kiali if you ever attempt to install multiple instances of Kiali in your cluster.

So, unless you have a really strong reason for needing to override the label_selector, my recommendation is "do not do it."

**Comment by meseta** [comment] 2021-07-06 23:35
Thanks for looking into it and posting a fix! And thank you for the explanation for how label_selector and accessible_namespaces work together, I will remove the label_selector value from our CR

**Comment by jmazzitelli** [comment] 2021-07-07 00:36
Leaving this open - we will close it when we merge the PR for the fix

**Closed** 2021-07-09 13:53 UTC
Labels: bug
