### ISSUE TITLE
Openid auth fails if oidc-secret contains special charaters

### ISSUE THREAD

**Issue by funkypenguin** [kiali/kiali#4153] opened 2021-07-05 22:35 UTC
**Describe the bug**

If the oidc-secret value contains a special charater (`%` or `&` in my case), then openid auth will fail with invalid secret

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: 1.36.0
Istio: 1.9.2
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) : 1.21 on bare-metal

**To Reproduce**

1. Setup oidc auth (I used keycloak), and set the client secret to `secret&%secret`
2. Attempt to setup openid auth with this secret - observe authentication failure
3. Update the client secret to `secretsecret`, update kiali config accordingly
4. Attempt login again - login succeeds

**Expected behavior**

Special characters should not break openid, since AFAIK there's no restriction on the characters permitted in a secret, and random string generators will occasionally generate special characters.

Note - I expect that this behaviour results from how the secret is mounted into the pod's filesystem, and then read from the filesystem for use. Presumably, the special characters are affected by the shell somehow.

**Comment by israel-hdez** [comment] 2021-07-06 17:11
@funkypenguin I wonder how you setup a custom secret?
On Keycloak I can only get an autogenerated one.

**Comment by israel-hdez** [comment] 2021-07-06 17:31
@funkypenguin FWIW, I tested using [Dex](https://github.com/dexidp/dex) and it works OK with special characters in the secret.

**Comment by israel-hdez** [comment] 2021-07-08 22:01
@funkypenguin Any comment about how to configure a custom secret on Keycloak?

**Comment by funkypenguin** [comment] 2021-07-08 22:31
Apologies for the delay. It's possible to specify a custom secret when creating a client via the KeyCloak API (which we do, in the name of gitops and consistency!)

**Comment by israel-hdez** [comment] 2021-07-10 03:59
This seems to be a Keycloak issue which, apparently, is missing some decoding of the oidc-client credentials.

I reported the issue at Keycloak side. Ticket is: https://issues.redhat.com/browse/KEYCLOAK-18704. Please watch that Keycloak ticket to follow it's progress.

I'll close this Kiali issue once that ticket is closed, or work on a fix in Kiali if it results to be a Kiali issue.

**Comment by israel-hdez** [comment] 2021-07-21 17:20
I saw a comment on the Keycloak ticket. The fix is scheduled for Keycloak version 16.

I don't think this is a confirmation that the issue is on Keycloak side, but they will investigate.

**Comment by israel-hdez** [comment] 2022-07-18 15:14
Apparently, the issue is fixed in keycloak/keycloak#12486 and the fix may be released on version 19.
I'll close this ticket.

**Closed by israel-hdez** 2022-07-18 15:14 UTC
Labels: waiting external
