### ISSUE TITLE
Traffic mirroring displayed incorrectly in graph

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1459] opened 2019-08-26 14:21 UTC
When mirroring taffic (doing a 'dark launch') the graph is only showing the traffic to the main version, but not to the mirror.

JIRA:
https://issues.jboss.org/browse/KIALI-2218

**Comment by abonas** [comment] 2020-02-04 19:06
@jshaughn @lucasponce is this duplicate of #2015 or separate issue?

**Comment by jshaughn** [comment] 2020-02-05 00:54
We don't need three issues about mirroring.  Closing as duplicate.

**Closed by jshaughn** 2020-02-05 00:54 UTC
Labels: backlog, enhancement, jira

**Comment by jotak** [comment] 2020-02-05 09:10
Just a remark: yesterday I did a demo of traffic mirroring, and again it was interesting to show how metrics are different depending on point of view: request emitter not knowing it was talking to a mirror, but request receiver being aware of that. It might look mind-twisting but it's actually interesting, I still see that more like a feature than a bug.
