### ISSUE TITLE
Health popover disappearing

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#3583] opened 2021-01-14 22:58 UTC
**General remarks**

In Apps and Worklaods lists, the health popover that appears when hovering the health icon is not showing if there is a non-green health change.

Browser refresh is a workaround. Services list was not tried, so I'm not sure if it's affected or not.

**Versions used**
Kiali: master
Istio: 1.8

**To Reproduce**

It's better with auto-refresh paused.

1. Go to the app/workloads list with an unhealthy app. See that the popover is working
  - The easiest way is, probably, to kill a pod so that it shows as unhealthy.
2. Downscale the app to zero replicas. This will change it's status to idle. Position the mouse cursor over the idle icon and you will no longer see the popover.
  - If you are trying with auto-refresh paused, use Kiali's refresh button (not the browser one) to do a manual refresh.

The popover should still be there. If you do a browser refresh you will see the popover again (so, this is a workaround).

Video demoing the issue:

![healthIssue](https://user-images.githubusercontent.com/23639005/104659042-91b50500-5689-11eb-8457-d3a51cf7b0d7.gif)

**Expected behavior**
The health popover should appear without the need to refresh the browser.

**Comment by lucasponce** [comment] 2021-01-18 08:46
I remember this one, I thought it was fixed.
I'll take a look, last time it was related to the popover component itself, perhaps some clash with the ids.

**Comment by lucasponce** [comment] 2021-01-18 16:46
Okey, I've taken a look to this issue, it's related to the tippy dependency.
We have a bad version pulled that probably it's affecting, but when I've updated I realize that there were some styles pulled as well than need to take a look.

I'll check if that resolve the problem.

**Comment by lucasponce** [comment] 2021-02-11 16:50
Removed, as tippy dependency has more implication in the context menu and the custom datepicker.
But issue is still valid.

I keep it in the Sprint to not forget.

**Comment by aljesusg** [comment] 2021-04-16 09:34
OK, I can reproduce it.

Problem that I found. EventListener (onMouse) is not created after manual refresh, is related with the tooltip component of patternfly that is using tippy 5.X so maybe is related with virtualList or maybe with the render.

**Comment by jshaughn** [comment] 2021-05-27 18:25
This is something to maybe re-visit/re-test if and when #4035 is completed.

**Comment by nrfox** [comment] 2021-06-03 18:44
This doesn't appear to be fixed by bumping the tippy library.

**Comment by nrfox** [comment] 2021-06-03 21:40
This appears related to [this issue](https://github.com/patternfly/patternfly-react/issues/5252) as wrapping the icon in a `<span>` as suggested fixes the issue.

**Comment by jshaughn** [comment] 2021-06-04 13:08
@nrfox Nice find.  Perhaps we should create a `KialiTooltip` component that applies the `<span>` fix, and maybe some consistent default CSS (like how we left-adjust by default).  And then use it consistently in place of the PF `Tooltip`?

**Comment by lucasponce** [comment] 2021-06-04 13:51
Note that tooltip is also affected inside the Charts work, I'm not a big fun of big refactoring, it may be exceptions to the wrapper globally, specially on style aspects.

**Comment by jshaughn** [comment] 2021-06-04 15:19
Right, I'm not sure what we can actually do about the Chart tooltips, as they are likely embedded in Chart packages.  As for KialiTooltip, we could still create it but not require it in a full replacement re-factor.  Just use it as needed.  I just thought it may be better than adding an unexplained `span`, which would likely need a comment in each place it's used as a workaround.  I leave it up to @nrfox to solve as he sees fit.  I'm fine with point-fixes as well.

**Comment by nrfox** [comment] 2021-06-04 15:53
From the patternfly issue it seems that this just affects tooltips where the child element is an svg. Doing a brief search, tooltips are used in a lot of different components across the ui and perhaps only the tooltips for icons would be affected by this bug. I'm wary of wrapping every tooltip especially ones that might not be affected but having an `IconTooltip` to fix the problem consistently for the icon svgs sounds good to me.

**Comment by lucasponce** [comment] 2021-06-04 15:54
Glad to help, if you have a PR, I can review and test how it looks like.

**Comment by nrfox** [comment] 2021-06-04 16:48
@lucasponce opened up https://github.com/kiali/kiali-ui/pull/2173 as a draft. If that's the route we want to go down then I'll do a search for tooltips for icons and replace `<patternfly.Tooltip>` with `<IconTooltip>`.

**Closed** 2021-06-09 13:13 UTC
Labels: backlog, bug
