### ISSUE TITLE
Could not fetch Istio objects list: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port

### ISSUE THREAD

**Issue by pk185235** [kiali/kiali#4679] opened 2022-01-27 10:48 UTC
![image](https://user-images.githubusercontent.com/91538779/151344128-66b0e13b-bdf7-420c-8988-e38d4e14eef2.png)

Does not load graphs with the connections.

**Comment by lucasponce** [comment] 2022-01-27 10:53
Please, these bugs can't be reported without a reproducer or more details about the environment and the failing version.

We'd like and need to learn more about why is failing, it can be a bad combination of Istio + Kiali version, an environment problem (not connectivity between Kiali and Istiod pod), or a bug.

Kiali is an open-source project with an active community but we need more info to progress, the "issues" require more data.

**Comment by jshaughn** [comment] 2022-03-08 21:31
Not enough information to proceed.

**Comment by partnerSun** [comment] 2022-03-22 08:14
> yum install socat -y

**Comment by karan-arora-netapp** [comment] 2022-06-04 18:22
> > check your istio‘s pod log,if have content :"uid : unable to do port forwarding: socat not found", you can try this command:
> > yum install socat -y

This fixed the issue i was having . I was trying to follow https://istio.io/latest/docs/setup/getting-started/ and hit this issue on ubuntu and installing socat fixed the error for me

**Comment by subin123123** [comment] 2022-08-12 07:55
For my deployment process, refer to the Getting Started documentation, i have tried :yum install socat -y,hava no effect.

**Comment by naiame-neltheri** [comment] 2022-10-10 02:55
I'm having also same issue except that one of the service is able to be detected.
I have Grafana, Prometheus, Grafana loki in same namespace. When I access to `kiali` dashboard on the graph, it shows only prometheus traffic. And in the log of `kiali` the following logs are reported:
```
2022-10-10T02:52:54Z WRN GetPodProxyStatus is failing for [namespace: monitoring] [pod: loki-ingester-2]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
2022-10-10T02:52:54Z WRN GetPodProxyStatus is failing for [namespace: monitoring] [pod: loki-query-frontend-67b6c5f5f5-xjkvj]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port
2022-10-10T02:52:54Z WRN GetPodProxyStatus is failing for [namespace: monitoring] [pod: loki-querier-1]: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port 
```

**Comment by nicoche** [comment] 2022-10-14 13:35
I had the same issue in my cluster. Turns out that I had some pods in `istio-system` with status `Terminated`. Garbage collecting the `Terminated` pods fixed it for me.

I run latest (1.15.x) istio and latest (v1.57.1) kiali

**Comment by israel-hdez** [comment] 2022-10-14 16:30
@nrfox I wonder if pods in Terminated status may not be correctly removed from the cache, unless they fully go away?
It's the only reason I can think of for those warnings.

**Comment by naiame-neltheri** [comment] 2022-10-17 11:01
@israel-hdez yes, the service account can list the namespace. I have double checked and please note that Kiali can get prometheus pod information

**Comment by israel-hdez** [comment] 2022-10-19 22:00
@naiame-neltheri Just to double-check, when you say that you have the same issue, do you mean that the "Istio Config" page show the error mentioned in the main comment?

BTW, the logs you posted about the `WRN GetPodProxyStatus is failing` probably make sense. I see it is for `loki-*` pods. My guess is that those deployments don't have an Istio sidecar, so I think the warnings are expected. However, I'm not familiar with that part of Kiali. I think @hhovsepy or @nrfox could know better.

**Comment by naiame-neltheri** [comment] 2022-10-20 01:23
@israel-hdez yes the config page also reports same error. And when I access to graph page there is some traffic but still seeing `WRN GetPodProxyStatus is failing` error. And the monitoring namespace is `istio-injection enabled` so all pods on the namespace already have the sidecar proxy container

**Comment by nrfox** [comment] 2022-10-20 18:18
@naiame-neltheri do you have an `app=istiod` label on any pods other than istiod in your istiod's namespace? Kiali tries to select the istiod pods based on that label.

> Also does istiod service needs to be forwarding 8080 traffic to 8080 of istiod pod?

Kiali attempts to connect to 8080 just to ensure it can actually reach the istiod pod. By default 8080 is the istiod health probe. The actual port that kiali uses when getting the registry info is the istiod monitoring port: 15014.

**Comment by nrfox** [comment] 2022-10-20 18:55
Did some searching on the `socat` issue talked about further up. It seems that the kubelet relies on `socat` to do port forwarding: https://github.com/kubernetes/kubernetes/issues/26093 and kiali relies on port forwarding to talk to istiod so the nodes running your istiod pods need to have socat installed on them.

**Comment by naiame-neltheri** [comment] 2022-10-26 02:24
@nrfox no, I have only one pod labeled as `app=istiod` under `istio-system` namespace which is istiod pod

**Comment by yueyanglouji** [comment] 2022-10-26 03:11
I had the same issue in my cluster, when I use proxy transport the kiali svc port 20001,
but use `kubectl forward` is ok.

follow command
`istioctl dashboard kiali --address 0.0.0.0`

**Comment by naiame-neltheri** [comment] 2022-11-02 01:53
I have fixed the issue by reinstalling istio

**Comment by jshaughn** [comment] 2022-11-02 13:59
@naiame-neltheri , glad the problem is resolved.  If you have any details as to the root cause please add a note.  I'll close this issue, thanks.

**Closed by jshaughn** 2022-11-02 13:59 UTC
Labels: bug

**Comment by jasonhao518** [comment] 2022-11-03 09:06
Hi, I have the same issue. I found the issue is because there are istiod pod with completed status or any other status than running. delete these pods will fix the issue.

**Comment by jshaughn** [comment] 2022-11-03 13:07
> @nrfox I wonder if pods in Terminated status may not be correctly removed from the cache, unless they fully go away?
It's the only reason I can think of for those warnings.

@nrfox , it sounds like we do have some sort of issue with non-`running` pods.  Any ideas?

**Comment by naiame-neltheri** [comment] 2022-11-07 01:58
I am not sure what was the root cause, there was nothing abnormal. And now because I reinstalled, I cannot reproduce the issue
