### ISSUE TITLE
Why my istio configuration below gets warning and error?

### ISSUE THREAD

**Issue by bangau1** [kiali/kiali#800] opened 2019-01-23 09:18 UTC
Hi Guys, I have problem on **Istio Config** menu found at Kiali web.
My Kiali version is:
```
kiali-ui 0.11.0 (f0a8d441e763e62d7a39682eb60bb9b2c12d4609)
kiali v0.11.0 (bff6219618030a012c2ead4c361c6db97bbb5433)
Components
Istio 1.0.0 
```

## Subset is not found on the host

![screen shot 2019-01-23 at 16 09 06](https://user-images.githubusercontent.com/352737/51595487-692a2280-1f29-11e9-9bec-96a1c8d9d944.png)

But in fact, i have 2 deployment `stable` and `canary` both has correct `track` label on it.
```
$ kubectl get deploy -n data-devops  -l track=stable
NAME                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
corn-app-stable       1         1         1            1           47m

$ kubectl get deploy -n data-devops  -l track=canary
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
corn-app-canary   1         1         1            1           21m

$ kubectl get svc -n data-devops corn-app-global -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-01-23T08:25:01Z
  name: corn-app-global
  namespace: data-devops
  resourceVersion: "148223782"
  selfLink: /api/v1/namespaces/data-devops/services/corn-app-global
  uid: 60af40cc-1ee8-11e9-af67-42010a9401fd
spec:
  clusterIP: 10.32.77.78
  ports:
  - name: http-corn-app
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: corn-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

And as much as I can tell, I can access both deployment just fine through Istio Ingress Gateway (using traffic splitting for example). So I am not sure why the Kiali indicates that error above.

## More than 1 gateways with the same host port combinaton
![screen shot 2019-01-23 at 16 06 44](https://user-images.githubusercontent.com/352737/51595692-ea81b500-1f29-11e9-83cb-d1d59b2b5f53.png)

i've checked it multiple times, but the corn-app-stg.tvlk-data.com only listed on `corn-app-gateway` gateway. 
```
$ kubectl get gateway --all-namespaces -o yaml | grep -i corn-app-stg.tvlk-data.com -B10

    name: corn-app-gateway
    namespace: data-devops
    resourceVersion: "148223785"
    selfLink: /apis/networking.istio.io/v1alpha3/namespaces/data-devops/gateways/corn-app-gateway
    uid: 60b1529c-1ee8-11e9-af67-42010a9401fd
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - corn-app-stg.tvlk-data.com
--
      port:
        name: http-corn-app
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
      - corn-app-stg.tvlk-data.com
```
So, I believe there is an error on Kiali on doing istio config validation. 

Anyway, the public url can't be resolved in public, since I hardcoded that in my `/etc/hosts` for testing.

**Comment by burmanm** [comment] 2019-01-23 10:08
The subset validation (at least in 0.11) requires app labels for matching. But there's been an update to the subset validation after 0.11, so you might want to update to check the current status for that.

As for latter one, something from the k8s API is returning that host as a duplicate. Why is the hosts part defined twice in the same yaml (at the same level also - unless that paste is incomplete) ?

**Comment by bangau1** [comment] 2019-01-23 10:21
Hi @burmanm thanks for the reply.

> As  for latter one, something from the k8s API is returning that host as a  duplicate. Why is the hosts part defined twice in the same yaml (at the  same level also - unless that paste is incomplete)?

Yup, that duplicate host is included within the same gatewat, but having different port `80` and `443`. We need to list that as separate hosts for https redirection.
Anyway, **after I've upgraded kiali to v0.13.0**, the `Gateway` issue is now disappeared. So I guess the latest kiali detects it correctly now.

However, about the subset validation, I still get the error below
<img width="928" alt="screen shot 2019-01-23 at 17 20 39" src="https://user-images.githubusercontent.com/352737/51599887-469d0700-1f33-11e9-9b17-3216d49643b4.png">

**Comment by burmanm** [comment] 2019-01-24 08:12
That's probably because our current validation requires appLabel to be present for the workloads to match (rest of the labels are not checked if appLabel does not match)

**Comment by burmanm** [comment] 2019-01-24 08:13
It's something that technically should be there always - but your situation isn't unique. I'm currently investigating (KIALI-2288) a suitable mid-way, since certain istio-system configs have the same issue.

**Comment by burmanm** [comment] 2019-02-06 14:20
Do you mean empty installation of bookinfo gives you errors? Or that you're trying to connect to those examples?

**Comment by markmssd** [comment] 2019-02-06 16:37
No it's a fully working bookinfo installation, I can even see it working in my browser and see its Reviews component rotate between the 3 versions of it. It means it's properly set up, but Kiali still reports that its DestinationRule subsets are no found.

**Comment by abonas** [comment] 2019-02-07 07:02
@xeviknal perhaps you could assist here?

**Comment by lucasponce** [comment] 2019-02-07 08:23
@markmssd Probably it's fixed in master and it will be released in next Sprint.
Please, could you attach your scenario or a couple of screenshots of the validation error and the service/workload details.
Just to confirm that this issue is fixed or to work in additional case otherwise.

Thanks.

**Comment by burmanm** [comment] 2019-02-07 10:29
@markmssd Which files did you install from the samples? I just made an empty installation and then used ``destination-rule-all.yaml`` and reviews is correctly showing all v1/v2/v3 validated.

**Comment by markmssd** [comment] 2019-02-07 16:28
@lucasponce Good to know, once it's released I will update and give it a try!

@lucasponce @burmanm Here are a couple of screenshots:
I have installed the bookinfo app in the `bookinfo` namespace, following this documentation: https://istio.io/docs/examples/bookinfo (precisely files `bookinfo.yaml`, `destination-rule-all.yaml`, `bookinfo-gateway.yaml`)

<img width="992" alt="screen shot 2019-02-07 at 11 18 50 am" src="https://user-images.githubusercontent.com/5899024/52425518-29873d00-2aca-11e9-8dca-6b5ac37cdf46.png">

<img width="1180" alt="screen shot 2019-02-07 at 11 02 39 am" src="https://user-images.githubusercontent.com/5899024/52425524-2d1ac400-2aca-11e9-8897-52fdd049feb4.png">

I've also tried specifying the full FQDN, but in vain.
<img width="1167" alt="screen shot 2019-02-07 at 11 24 56 am" src="https://user-images.githubusercontent.com/5899024/52425932-0446fe80-2acb-11e9-8d12-39d69abb6055.png">

Also, specifycing the full FQDN for the Gateway in the VirtualService reports it as not found (but everything still works as expected)
<img width="1166" alt="screen shot 2019-02-07 at 11 26 37 am" src="https://user-images.githubusercontent.com/5899024/52426144-699aef80-2acb-11e9-88cd-244e69056ff6.png">

Let me know if you need more details!

**Comment by burmanm** [comment] 2019-02-08 11:42
The FQDN for gateways[] is true, the validation fails also with a valid IP+Gateway combination. I'll log a JIRA for this if there isn't one already.

As for those labels v2, v2-mysql .. are there workloads in the bookinfo namespace that actually do match to those?  At least my installation didn't have, only v1 and v2 (which wasn't reported as error in my installation, but v2-mysql is).

**Comment by burmanm** [comment] 2019-02-08 11:45
For previous, meant to say IP+Gateway in the hosts section, not gateways.

**Comment by burmanm** [comment] 2019-02-08 11:48
KIALI-2371 and KIALI-2372

**Comment by lucasponce** [comment] 2019-02-08 13:44
Thanks @burmanm for creating the JIRAs.
I add here the links for easy browsing.
https://issues.jboss.org/browse/KIALI-2371
https://issues.jboss.org/browse/KIALI-2372

**Comment by markmssd** [comment] 2019-02-08 15:01
Thanks for opening the tickets!

@burmanm You're right, there is no `v2-mysql` or `v2-mysql-vm` deployment in mine neither, so it was normal, good catch!

However in my project's deployment, it complains about missing versions that are actually deployed. I will double check my installation again and get back to you!

**Comment by burmanm** [comment] 2019-02-21 08:33
@markmssd Still having issues with the current master?

**Comment by markmssd** [comment] 2019-02-21 15:21
I'm getting new policies errors
```
Could not fetch Istio objects list, Error: [ policies.authentication.istio.io is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list policies.authentication.istio.io in the namespace "xxxxxx" ]
```
I guess just upgrating Kiali's image version is not enough, some changes need to be made in the roles right?

**Comment by markmssd** [comment] 2019-02-21 15:27
Update:
Changing to image tag `v0.15.0-snapshot.1` did not require a rules modification, but the issue is not fixed for cross-namespace gateways, nor for DestinationRules :/

**Comment by markmssd** [comment] 2019-02-21 15:30
I'm eager to try it with the `latest` image tag. Can you advice on to which role to update/create?

**Comment by jotak** [comment] 2019-02-21 15:46
@markmssd my guess is you're missing these ones : https://github.com/kiali/kiali/blob/master/deploy/kubernetes/clusterrole.yaml#L107-L118

@xeviknal , do you know if that was reported / merged upstream?

By the way... I think I'm going to change a bit how we report errors in that particular page: we fetch tons of objects and fail for all if just 1 call fails. We should still be able to provide what didn't fail, I think. That would improve the user experience.

**Comment by markmssd** [comment] 2019-02-21 16:21
Thanks @jotak , adding those rules worked 👍

Here are some updates:
<img width="657" alt="screen shot 2019-02-21 at 11 11 42 am" src="https://user-images.githubusercontent.com/5899024/53183618-a4238280-35c9-11e9-8ede-88759dec59cf.png">

The VirtualService referencing a cross-namespaced Gateway works ✅ Here is its content:
<img width="977" alt="screen shot 2019-02-21 at 11 12 13 am" src="https://user-images.githubusercontent.com/5899024/53183642-af76ae00-35c9-11e9-82de-897a577f6453.png">

However, the DestinationRules are not being detected properly ❌ Here are some screenshots:
Deployment has proper `version: uatgg`:
<img width="944" alt="screen shot 2019-02-21 at 11 09 26 am" src="https://user-images.githubusercontent.com/5899024/53183874-172cf900-35ca-11e9-9116-557fa91779ae.png">
DestinationRule referencing `subset uatgg` erroring:
<img width="1165" alt="screen shot 2019-02-21 at 11 10 53 am" src="https://user-images.githubusercontent.com/5899024/53183712-d46b2100-35c9-11e9-8f22-6117a602afc6.png">

Let me know if you need more details!

**Comment by SeriyBg** [comment] 2019-02-21 17:16
I have the same warning on the gateway, even though I have only one gateway whit the specific host

**Comment by israel-hdez** [comment] 2019-02-21 17:37
@jotak I don't see that yaml change replicated in Istio. Is that what you meant by _upstream_?

**Comment by burmanm** [comment] 2019-02-22 09:30
@markmssd I'm not entirely sure if I can tell the whole picture from your example, but is the deployment actually pointing to the same service? From what I can tell, the DestinationRule is pointing to a service called ``react-uat-dynamic-service-www`` but I can't see your deployment's service name.

**Comment by xeviknal** [comment] 2019-02-22 10:56
> @xeviknal , do you know if that was reported / merged upstream?
Since @markmssd just changed the image tag, the clusterroles aren't matching with the expected in @kiali.

In istio/istio master there are the enough permissions for running the v0.14 of kiali:
https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/kiali/templates/clusterrole.yaml#L100

For kiali v0.15, there is a draft PR updating the clusterrole.yaml:
https://github.com/istio/istio/pull/11823

RbacConfigs, ServiceRole, ServiceRoleBinding should be added soon.

**Comment by markmssd** [comment] 2019-02-22 16:57
@burmanm yes the deployment is pointing to that same Service as well:
<img width="837" alt="screen shot 2019-02-22 at 11 56 19 am" src="https://user-images.githubusercontent.com/5899024/53257766-f1baf080-3698-11e9-84f1-e2b1d9142b36.png">

(does the deployment also need to have the label `version` on it?)

**Comment by markmssd** [comment] 2019-02-26 16:12
@burmanm do you need more info in order to debug this?

**Comment by burmanm** [comment] 2019-02-27 09:00
@markmssd If you can share the yaml files, then that would be great (so that I don't accidentially miss the real reason by making assumptions from the UI screenshots). You can mail them to miburman@redhat.com

**Comment by markmssd** [comment] 2019-03-06 03:23
@burmanm Sorry for the long delay. I have sent you the files by email!

**Comment by gadiener** [comment] 2021-03-23 09:11
Hello, 

I'm facing the same issue with Kiali version v1.32.0-snapshot.1  and with the v1.31.0 too. 

This is an example of the destination rule I'm using: 

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: test-rule
  namespace: network
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: default-egress
     labels:
       istio.io/rev: default
  - name: default-sni-egress
     labels:
       istio.io/rev: default
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
```

In the validation section in Kiali I see the warning `KIA0203 - This subset's labels are not found in any matching host`. The destination rule is pointing to the Istio egress gateway and the labels are in place. The traffic seems to use the destination rule correctly so seems to be only a validation problem.

**Comment by lucasponce** [comment] 2021-03-23 09:24
@gadiener thanks for the comment
@xeviknal perhaps the validation is skipping the egress host here.

**Comment by lucasponce** [comment] 2021-03-23 09:26
I'll re-open it to investigate.

**Comment by xeviknal** [comment] 2021-03-23 15:06
Good catch. The point is since we are not implementing cross-ns validation (for security reasons and soft multi-tenancy support), we can't check whether the workloads are present or not.

I just published a PR (https://github.com/kiali/kiali/pull/3800) slightly modifying the validation: if the host is not found (or in other namespace) then it won't check for the workload+label matching.

**Comment by gadiener** [comment] 2021-03-23 16:19
Great @xeviknal, thank you!

**Closed** 2021-03-25 10:40 UTC
Labels: backlog, bug
