### ISSUE TITLE
Traces not show up in the Kiali UI

### ISSUE THREAD

**Issue by dimitarshenkov** [kiali/kiali#5149] opened 2022-06-03 14:13 UTC
Hi , I have installed jaeger with Helm chart https://artifacthub.io/packages/helm/jaegertracing/jaeger-operator, 
Kiali is installed   with Helm too
repository = "https://kiali.org/helm-charts"
 chart      = "kiali-server"
Jaeger is accessible if use kubectl  port-forward service/jaeger-query -n istio-system 16686:16686 
and has traces from all name spaces 
![image](https://user-images.githubusercontent.com/99493924/171872751-b854f7cd-964b-483e-882e-596c717d89e8.png)
curl is working 
![image](https://user-images.githubusercontent.com/99493924/171870940-1a8bc151-6776-45cb-a2ab-ea88126f8e6a.png)
This is Kiali config
![image](https://user-images.githubusercontent.com/99493924/171871069-f42b09d4-d634-4270-bb78-1abf0e598083.png)
Kiali logs looks fine
![image](https://user-images.githubusercontent.com/99493924/171871201-871f65d4-5511-484c-8fee-18f0e10c374f.png)
But no traces in Kiali for any svc or app
![image](https://user-images.githubusercontent.com/99493924/171871405-23a56391-51bb-4cf6-8b75-2d539d76ed5c.png)
What can be wrong ?

**Comment by lucasponce** [comment] 2022-06-06 06:34
Hi @dimitarshenkov, which versions of Istio, Kiali and Jaeger are you using?
Also, there are two ways that Jaeger can be configured: using grpc or the old legacy HTTP protocol.

Default (like in the addons) is using grpc, but it seems you are using HTTP only, so, then your jaeger config should be something like:

![image](https://user-images.githubusercontent.com/1662329/172107915-3f5fd69d-da75-4a13-bbbe-047a9bedd942.png)

Disable the grpc flag, and point the "in_cluster_url" to your service 16686 one.

https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.tracing.use_grpc

**Comment by dimitarshenkov** [comment] 2022-06-06 07:00
Hi @lucasponce , yes the grpc is disabled 
![image](https://user-images.githubusercontent.com/99493924/172111522-7a143282-7ac0-435e-8766-06d8f2930cdd.png)

**Comment by dimitarshenkov** [comment] 2022-06-06 07:11
![image](https://user-images.githubusercontent.com/99493924/172113098-cc93affb-937f-40bc-8b45-579051772753.png)

**Comment by lucasponce** [comment] 2022-06-06 09:11
Thanks for confirming, then you'd need to propagate a configuration as I posted, defaults point to grpc port.

![image](https://user-images.githubusercontent.com/1662329/172131772-c615b3ca-c233-4074-8cd3-4e78bbcd7c0c.png)

Note that the preferred way to deal with configuration in Kiali is using the operator, using helm you'd need to ensure that those defaults are correctly propagated into the ConfigMap and restart the Kiali pod.

**Comment by dimitarshenkov** [comment] 2022-06-06 09:34
Thats from my ConfigMap looks ok to me
![image](https://user-images.githubusercontent.com/99493924/172135583-9239c363-1a25-4706-af48-15c85487bf53.png)

**Comment by dimitarshenkov** [comment] 2022-06-07 14:27
Hi, @lucasponce here is my CM , looks like this , as you say
![image](https://user-images.githubusercontent.com/99493924/172405549-b612b2df-a90a-4204-af0c-3351216c47dc.png)

**Comment by lucasponce** [comment] 2022-06-07 15:23
Not sure why you can't get the traces from grpc.
A workaround can be to change the "use_grpc: false" and move the port to "16686".
Let me know if that works for you, or if the error is different.

**Comment by dimitarshenkov** [comment] 2022-06-07 16:14
@lucasponce already tried 16686 same result, it was my first try

**Comment by lucasponce** [comment] 2022-06-07 16:26
I wonder if it's the jaeger version here, if you try to use the jaeger addon provided by Istio, do you still have the same problem?
(It's to see if there are some configuration different between jaeger installations that it's affecting to Kiali)

**Comment by dimitarshenkov** [comment] 2022-06-08 06:56
Yes its the same result with 
https://raw.githubusercontent.com/istio/istio/release-1.14/samples/addons/jaeger.yaml

**Comment by lucasponce** [comment] 2022-06-08 07:05
I wonder if the format is different.
Could you confirm if you have traces for any other demo app (i.e. bookinfo or any of the https://github.com/kiali/demos ones), but not your test app?

Then perhaps we could check if it's a configuration Kiali or something missed in the data plane/app.

Note, if I could reproduce your error in a local environment, that would help me to investigate if it's a problem with the code.

Thanks

**Comment by dimitarshenkov** [comment] 2022-06-08 08:47
![image](https://user-images.githubusercontent.com/99493924/172573772-b782a17a-9f75-42d4-9f2e-719faf6a5406.png)
![image](https://user-images.githubusercontent.com/99493924/172573881-6a22cbfd-e172-4116-b379-c80a4c1c7a8c.png)

**Comment by lucasponce** [comment] 2022-06-08 08:54
ah ! 

> I have jaeger-query service which should appear

I think you're a hitting a corner case exception, as the jaeger-query I think it's filtered from Kiali IIRC.

Could you try with a bookinfo or a travels-demo ?

**Comment by dimitarshenkov** [comment] 2022-06-08 11:16
![image](https://user-images.githubusercontent.com/99493924/172603423-1b6331bb-61dd-4323-9da5-eefcf18c28fe.png)
after a wile it disappears

**Comment by lucasponce** [comment] 2022-06-08 11:47
The last screenshot shows progress, I think then the connectivity between Kiali and Jaeger is linked.
Now you should adjust the query interval and check that is pulling the right data for your environment, here Kiali is just passing a query to Jaeger to process that data, but it's not doing anything special that may differ. So both systems should have same information.

If you have some client that creates traffic you should see something like this:
![image](https://user-images.githubusercontent.com/1662329/172608793-904a1d1d-4103-4c32-b964-ec0e3ce1f4f0.png)

**Comment by dimitarshenkov** [comment] 2022-06-08 11:51
How come I have traces in Jeger UI but not in Kiali for jaeger service or others
![image](https://user-images.githubusercontent.com/99493924/172609310-e470ed84-1ac2-4c4f-99d0-43bec794275b.png)
![image](https://user-images.githubusercontent.com/99493924/172609453-42e30317-2abb-4973-b77e-6d078687f944.png)

**Comment by lucasponce** [comment] 2022-06-08 12:07
The "jaeger.istio-system" is filtered out (I remember) because Kiali focused on workloads that belongs to the "data plane" (i.e. having a sidecar and connected to the mesh).

Then for data-plane applications/workloads/services you'd see traces both in the Graph ("traces" tab in the side panel) or in the details under the "traces" tab.

Also in the details of any app/workload/service you'll see an "Inbound Metrics"/"Outbound Metrics" tabs where you can visualize Istio metrics combined with traces (i.e. enable the traces checkbox) and that feature allows you to correlate the information and be able to see if a specific trace/span is "slow" in terms of your business domain.

The jaeger workload is typically not part of the data plane and I think Kiali has some logic to filter it out for convenience as it's considered part of the "control plane".

Hope this helps.

**Comment by dimitarshenkov** [comment] 2022-06-08 14:27
Ok but my test-aws app is  workload that belong to the "data plane" and still dont get traces for it

**Comment by lucasponce** [comment] 2022-06-08 14:30
> Ok but my test-aws app is workload that belong to the "data plane" and still dont get traces for it

Ok, then if now you have the jaeger integration correctly configured, and you can see traces from any of the demo apps, I wonder if your app has the "app" and "version" label properly set.

If you navigate into the "workload" details for your app, do you have that info? you could also check if there is any additional warning pointing to any misconfiguration that perhaps is hitting that scenario.

**Comment by lucasponce** [comment] 2022-06-08 15:00
Can you show the information of the metrics + traces with the correlation enabled?
![image](https://user-images.githubusercontent.com/1662329/172649861-eac8241b-fda0-440e-bb5e-0e5222f9ef18.png)

**Comment by dimitarshenkov** [comment] 2022-06-09 06:56
after 24h seems ok
![image](https://user-images.githubusercontent.com/99493924/172784071-d2af9023-dfef-46f9-bb29-821fbfd2c89f.png)

**Comment by lucasponce** [comment] 2022-06-09 07:19
Glad it helped but it's curious it seems you have something in your environment that perhaps is affecting here.
Anyway, if you'd like to provide me with an example that I can run locally, I can check if everything is working as expected.

I'm going to close this issue, we can open a new one or a discussion with more accurate info if we keep seeing some problems.

**Closed by lucasponce** 2022-06-09 07:19 UTC
Labels: bug
