### ISSUE TITLE
How to sync kiali with a revision based istio install?

### ISSUE THREAD

**Issue by sergiomacedo** [kiali/kiali#3965] opened 2021-04-29 22:29 UTC
My istio install is using the "revision" feature, to be able to do canary upgrades later. So, the resources are all versioned like:
- ConfigMaps
  - istio-1-8-5
  - istio-sidecar-injector-1-8-5

- Deployment
  - istiod-1-8-5

I was able to configure kiali to look for the istio-1-8-5 configmap and the istiod-1-8-5 deployment. However, kiali complains, with a warning, about not finding the "istio-sidecar-injector". Looking the kiali-cr reference I couldn't find an entry similar to external_services.istio.config_map_name, where I did set the "istio-1-8-5".

Is this a bug of am I missing something?

The warning message:

```
2021-04-29T22:09:00Z WRN Cannot resolve the network ID of the cluster where Kiali is hosted: cannot get the sidecar injector config map :configmaps "istio-sidecar-injector" not found

```

**Comment by jmazzitelli** [comment] 2021-04-29 22:56
Duplicate of https://github.com/kiali/kiali/issues/3923 (see associated PRs)

This will be available in the next release in 1 week.

We will be further documenting this as part of [this issue](https://github.com/kiali/kiali/issues/2884#issuecomment-829578709)

cc @nrfox

**Closed by jmazzitelli** 2021-04-29 22:56 UTC
