### ISSUE TITLE
Kiali 1.46.0 is showing us KIA1106 on all of our `VirtualService` resources... but its invalid?

### ISSUE THREAD

**Issue by diranged** [kiali/kiali#4738] opened 2022-02-16 15:15 UTC
_(We just noticed this after our upgrade to 1.46.0 ... but it could have been there before)_

After upgrading to Kiali 1.46.0, we noticed that `KIA1106` is being presented to us for all of our VirtualService resources... but it's invalid as far as I can tell. We have no `VirtualService` resources with overlapping hostnames at all. I'm pretty confused as to how this can happen. What can I do to debug this for you?

**Comment by israel-hdez** [comment] 2022-02-16 18:50
I think this is a duplicate of #4711 .

I'll close this one. Please, share the details of your env in the other issue so that there is more information to replicate the bug.

**Closed by israel-hdez** 2022-02-16 18:50 UTC
Labels: bug
