### ISSUE TITLE
Mesh expansion not properly visualized

### ISSUE THREAD

**Issue by sfudeus** [kiali/kiali#1109] opened 2019-06-01 07:28 UTC
**Describe the bug**

I am currently playing around with outbound mesh expansion in Istio. 
So I added two machines, installed the istio-proxy on them and added them as ServiceEntries to the ControlPlane, as described [here](https://istio.io/docs/setup/kubernetes/additional-setup/mesh-expansion/). Additionally, I added a VirtualService and made it available from an ingress gateway. The two service entries, which make up a common workload (together with the virtual service), are not visualized as such (see screenshot). 

**Versions used**
Kiali: 0.19
Istio: 1.1.6
Kubernetes flavour and version: vanilla kubernetes 1.14.1

**To Reproduce**

Add two mesh expansion nodes to an existing istio control plane. 
e.g. with the following spec. The second node might have a different version label. 
```
spec:
  hosts:
    - po-istio-meshtest-qa-bs01.ams-istio-dev.svc.cluster.local
  ports:
    - name: http
      number: 80
      protocol: HTTP
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
    - address: 10.90.22.53
      labels:
        app: po-istio-meshtest-qa
        version: v1
      ports:
        http: 80
```

Add a virtual service aggregating those dedicated hosts:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshtest
spec:
  hosts:
  - "po-istio-meshtest-qa.ams-istio-dev.svc.cluster.local"
  - "meshtest.istio.fe-sandbox-iz1-bs.myexternaldomain"
  gateways:
  - istio-system/default-gateway
  - mesh
  http:
  - route:
    - destination:
        host: po-istio-meshtest-qa-bs01
      weight: 40
    - destination:
        host: po-istio-meshtest-qa-bs02
      weight: 60
    fault:
      abort:
        percent: 1
        httpStatus: 418
```
 
**Expected behavior**

As for in-mesh services, I'd expect a visualization of the workload identified by the app label with attached virtual service and each expansion node would either be grouped into a single versioned app (when having the same version label) or be a dedicated versioned app, as e.g. available for the bookinfo sample app (see screenshot). The orange color of the expansion workload comes from the 1% injected http 418. 

<img width="1104" alt="Bildschirmfoto 2019-05-31 um 17 41 01" src="https://user-images.githubusercontent.com/8386006/58745173-becd8900-844d-11e9-8203-c31ee2b4b840.png">

I am as well surprised that the expansion nodes are displayed as Service, not as ServiceEntry. 

PS: Maybe a different bug but is highly affected by this: 
The two expansion nodes don't reliably show up in the graph, sometimes only a single node is shown, despite both nodes getting constant traffic (aggregated 5 qps). See screenshot below (now even with unused nodes enabled and still no display):
<img width="1105" alt="Bildschirmfoto 2019-06-01 um 09 27 09" src="https://user-images.githubusercontent.com/8386006/58745294-79aa5680-844f-11e9-8284-b98d713bfc83.png">

I'll gladly provide any additional details or apply config changes you might need for debugging this.

**Comment by lucasponce** [comment] 2019-06-03 06:45
Hello @sfudeus, thanks for open the issue.

I think this issue/feature can be also related to multicluster support https://issues.jboss.org/browse/KIALI-2584 which is currently in planning.

**Comment by jshaughn** [comment] 2019-06-03 13:19
I'm not sure if this may have something to do with the setting for outboundTrafficPolicy.  Are you using ALLOW_ANY or REGISTRY_ONLY?  See https://github.com/kiali/kiali/issues/945#issuecomment-476360926.

**Comment by sfudeus** [comment] 2019-06-03 19:40
@jshaughn We do use `REGISTRY_ONLY`, and yes, it is definitely of kind: ServiceEntry. Might it be connected to `location: MESH_INTERNAL`? Or that pre-1.1 ServiceEntry used to be just for mesh-external sources (AFAIK), without a use for `location`?

**Comment by jshaughn** [comment] 2019-06-04 13:54
OK, then it's not clear why there is an issue.  MESH_INTERNAL should not be a problem as the code does allow for MESH_INTERNAL and MESH_EXTERNAL.  I'm wondering whether the call to gather service entries is properly returning your configurations.

Could you execute this Kiali API endpoint:
  `/api/namespaces/{ServiceEntryNamespace}/istio?objects=serviceentries` 

Ensure your serviceEntry definitions are returned and post the result so that we can try to understand why it's not matching.

As for the traffic, Kiali is likely reflecting what is in the telemetry reported by Istio to Prometheus (in the istio_requests_total metric).  We can explore whether Kiali us reflecting the telemetry correctly, or not.

**Comment by sfudeus** [comment] 2019-06-04 19:13
I just checked which `istio_requests_total` metrics I have: 
There are 4 label combination which seem relevant (2 from each ingressgw and to 2 service entries). 
They do contain destination_app="unknown" (see the full label set for one of those below): 
```
istio_requests_total{connection_security_policy="unknown",destination_app="unknown",destination_principal="unknown",destination_service="po-istio-meshtest-qa-bs02.ams-istio-dev.svc.cluster.local",destination_service_name="po-istio-meshtest-qa-bs02",destination_service_namespace="ams-istio-dev",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="100.64.5.224:42422",job="istio-mesh",permissive_response_code="none",permissive_response_policyid="none",reporter="source",request_protocol="http",response_code="200",response_flags="-",source_app="istio-ingressgateway",source_principal="unknown",source_version="unknown",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"}
```

As to the API output:

```json
{
  "namespace": {
    "name": "ams-istio-dev"
  },
  "gateways": [],
  "virtualServices": {
    "permissions": {
      "create": false,
      "update": false,
      "delete": false
    },
    "items": []
  },
  "destinationRules": {
    "permissions": {
      "create": false,
      "update": false,
      "delete": false
    },
    "items": []
  },
  "serviceEntries": [
    {
      "kind": "ServiceEntry",
      "apiVersion": "networking.istio.io/v1alpha3",
      "metadata": {
        "name": "bs01-se",
        "namespace": "ams-istio-dev",
        "selfLink": "/apis/networking.istio.io/v1alpha3/namespaces/ams-istio-dev/serviceentries/bs01-se",
        "uid": "cd32d49e-7252-11e9-9add-246e96748a40",
        "resourceVersion": "2297111",
        "generation": 1,
        "creationTimestamp": "2019-05-09T12:05:56Z",
        "annotations": {
          "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"ServiceEntry\",\"metadata\":{\"annotations\":{},\"name\":\"bs01-se\",\"namespace\":\"ams-istio-dev\"},\"spec\":{\"endpoints\":[{\"address\":\"10.90.22.53\",\"labels\":{\"app\":\"po-istio-meshtest-qa\",\"version\":\"v1\"},\"ports\":{\"http\":80}}],\"hosts\":[\"po-istio-meshtest-qa-bs01.ams-istio-dev.svc.cluster.local\"],\"location\":\"MESH_INTERNAL\",\"ports\":[{\"name\":\"http\",\"number\":80,\"protocol\":\"HTTP\"}],\"resolution\":\"STATIC\"}}\n"
        }
      },
      "spec": {
        "hosts": [
          "po-istio-meshtest-qa-bs01.ams-istio-dev.svc.cluster.local"
        ],
        "addresses": null,
        "ports": [
          {
            "name": "http",
            "number": 80,
            "protocol": "HTTP"
          }
        ],
        "location": "MESH_INTERNAL",
        "resolution": "STATIC",
        "endpoints": [
          {
            "address": "10.90.22.53",
            "labels": {
              "app": "po-istio-meshtest-qa",
              "version": "v1"
            },
            "ports": {
              "http": 80
            }
          }
        ]
      }
    },
    {
      "kind": "ServiceEntry",
      "apiVersion": "networking.istio.io/v1alpha3",
      "metadata": {
        "name": "bs02-se",
        "namespace": "ams-istio-dev",
        "selfLink": "/apis/networking.istio.io/v1alpha3/namespaces/ams-istio-dev/serviceentries/bs02-se",
        "uid": "cd34d60d-7252-11e9-9add-246e96748a40",
        "resourceVersion": "2297112",
        "generation": 1,
        "creationTimestamp": "2019-05-09T12:05:56Z",
        "annotations": {
          "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"ServiceEntry\",\"metadata\":{\"annotations\":{},\"name\":\"bs02-se\",\"namespace\":\"ams-istio-dev\"},\"spec\":{\"endpoints\":[{\"address\":\"10.90.22.217\",\"labels\":{\"app\":\"po-istio-meshtest-qa\",\"version\":\"v2\"},\"ports\":{\"http\":80}}],\"hosts\":[\"po-istio-meshtest-qa-bs02.ams-istio-dev.svc.cluster.local\"],\"location\":\"MESH_INTERNAL\",\"ports\":[{\"name\":\"http\",\"number\":80,\"protocol\":\"HTTP\"}],\"resolution\":\"STATIC\"}}\n"
        }
      },
      "spec": {
        "hosts": [
          "po-istio-meshtest-qa-bs02.ams-istio-dev.svc.cluster.local"
        ],
        "addresses": null,
        "ports": [
          {
            "name": "http",
            "number": 80,
            "protocol": "HTTP"
          }
        ],
        "location": "MESH_INTERNAL",
        "resolution": "STATIC",
        "endpoints": [
          {
            "address": "10.90.22.217",
            "labels": {
              "app": "po-istio-meshtest-qa",
              "version": "v2"
            },
            "ports": {
              "http": 80
            }
          }
        ]
      }
    }
  ],
  "rules": [],
  "adapters": [],
  "templates": [],
  "quotaSpecs": [],
  "quotaSpecBindings": [],
  "policies": [],
  "meshPolicies": [],
  "clusterRbacConfigs": [],
  "rbacConfigs": [],
  "serviceRoles": [],
  "serviceRoleBindings": [],
  "validations": {}
}

```

**Comment by jshaughn** [comment] 2019-06-04 20:21
I think the reason that the nodes are not being flagged as ServiceEntries is because Kiali wants the ServiceEntry host to be the service name, as opposed to the fully qualified service.  For example, the service name is "po-istio-meshtest-qa-bs01" but the service entry host is "po-istio-meshtest-qa-bs01.ams-istio-dev.svc.cluster.local". 

I'm not sure, perhaps this is a bug in Kiali such that it should match just the service-name portion of the host in the longer form.

You could try changing your serviceEntry definition and see if it makes a difference in the Kiali rendering.

As for the Prometheus time-series, it seems OK, on the surface at least.  destination_app="unknown" is normal, it is only set when the request is processed by a workload with the "app" label set.

**Comment by jshaughn** [comment] 2019-06-07 14:13
@sfudeus Any update?

**Comment by sfudeus** [comment] 2019-06-09 13:48
@jshaughn I just tried using the short names for the service entries' hosts definition. They are shown as service entries now, but that didn't change anything concerning the grouping together as a single workload. 
<img width="421" alt="Bildschirmfoto 2019-06-09 um 15 47 48" src="https://user-images.githubusercontent.com/8386006/59159700-f4b5e180-8acd-11e9-90e7-1e5bf7977e7f.png">

**Comment by jshaughn** [comment] 2019-06-10 14:12
@sfudeus OK, at least we solved one issue.   I created [KIALI-2999](https://issues.jboss.org/browse/KIALI-2999) to enhance the host-matching for service entry detection.

As for the "grouping" behavior.  I think you need to pursue it as an Istio issue but I'm not sure the desired behavior is possible.  Despite being MESH_INTERNAL I don't think service entries are treated like workloads because they don't map to any workload entity, like a deployment, etc...  As you mentioned above, the generated telemetry for the request has destination_workload="unknown" and destination_app="unknown".  Because it's not a workload these fields, inclduing your label, are not getting assigned.   You could ask the Istio folks whether the telemery is as-designed or if perhaps they could improve the internal mesh service entry telemetry.  Right now the two versions just look like different endpoints.

**Comment by jshaughn** [comment] 2019-06-17 12:28
@sfudeus  [KIALI-2999](https://issues.jboss.org/browse/KIALI-2999) Is included in the Kiali 0.21 release.  That change should solve your original issue around serviceEntry detection for the fully qualified service identifier.  As mentioned above, I think Istio telemetry is preventing your other expected behavior so you may want to ask about that in the [Istio Policies and Telemetry discourse](https://discuss.istio.io/c/policies-and-telemetry).

**Comment by jshaughn** [comment] 2019-06-18 18:00
@sfudeus We have been discussing a bit more the handling of service entries in [KIALI-3034](https://issues.jboss.org/browse/KIALI-3034).  Even these changes would not cause aggregation in your use case, only for serviceEntries with multiple hosts.

**Comment by jshaughn** [comment] 2019-06-26 13:13
@sfudeus,  [KIALI-3034](https://issues.jboss.org/browse/KIALI-3034) has been merged and will be in the next upstream release (I think available in a few days).   The behavior now is that a serviceEntry node represents an actual serviceEntry and not just a serviceEntry host.  In other words, for a serviceEntry defining multiple hosts you can get an aggregated serviceEntry node.   This does not give you the label-based aggregation you were looking for, for the reasons discussed above.  But I wanted to mention the new aggregation and behavioral changes in case you redesigned your service entries with multiple hosts.

**Comment by lucasponce** [comment] 2019-09-10 11:40
Reading the comments it seems there have been some actions around this issue. And changes have been merged.
I'm going to close this issue due lack of activity.
Please, don't hesitate to open it if you think there are pending actions to address on it.
Thanks.

**Closed by lucasponce** 2019-09-10 11:40 UTC
Labels: enhancement
