### ISSUE TITLE
Unable to integrate Kiali dashboard with Active directory

### ISSUE THREAD

**Issue by coolpalani** [kiali/kiali#2180] opened 2020-01-29 16:38 UTC
**Describe the bug**
We're trying to integrate Kiali with Active directory but it's throwing following error message.

 LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580

As per the documents, https://kiali.io/documentation/getting-started/#_ldap
How is it possible to integrate without feed user credentials to config.
is it something missing while document it

**Versions used**
Kiali: v1.12.0
Istio: v1.4.3
Kubernetes flavor and version: (e.g. Kubernetes 1.17.0)

**Comment by israel-hdez** [comment] 2020-01-29 22:01
Hi, @coolpalani. Thanks for reporting the issue.
Probably, the docs may not state it clearly, but you don't need to place any user credentials in the config. I'm assuming that you are talking about the `ldap_bind_dn` configuration. This is a template. You need to literally write the `{USERID}` string in some part of the `ldap_bind_dn` config. Kiali will replace the `{USERID}` string with the login name that the user writes in the Kiali's login form. Then, Kiali will pass to the ldap server the password that the user wrote in the login form to try the authentication.

The same applies with the `ldap_search_filter` configuration.

If my assumption is wrong, in order to better help you, please share your ldap config if possible. Mask or replace any sensitive values with artificial data. I just want to understand how your configuration looks like.

You may want to watch the recorded demo to understand a little better how to setup LDAP. This is the link to the YouTube video with the exact timestamp where the LDAP feature is demoed: https://youtu.be/AKd3tbX6oBY?t=465 (sorry for my poor spoken english)

**Comment by MarkDeckert** [comment] 2020-01-30 00:58
@israel-hdez @coolpalani 

I've been testing this too.  The login name for the user would literally be the user's CN.  Look in the properties of the account in AD and you'll see that it may not be what you expect.  I've seen various cn's such as "FirstName LastName" and "LastName, FirstName".  This makes an awkward experience for the typical enterprise AD user - but it does work.  In case it helps this is a working config with some redactions:

```
ldap:
  ldap_base: OU=Users,DC=domain,DC=com
  ldap_bind_dn: cn={USERID},OU=Users,DC=domain,DC=com
  ldap_host: domain.com
  ldap_insecure_skip_verify: true
  ldap_port: 636
  ldap_use_ssl: true
```

It would be nice to have a separate service binding option so kiali itself would bind using a service account so users could login using upn or sAMAccount as that is more typical in enterprise.

**Comment by jmazzitelli** [comment] 2020-01-30 01:33
> it would be nice to have a separate service binding option so kiali itself would bind using a service account

There is the "token" login strategy which may be a viable alternative - You are able to then login with any service account (its token / credentials). See: https://kiali.io/documentation/getting-started/#_login_options

**Comment by MarkDeckert** [comment] 2020-01-30 04:12
What I meant was an LDAP/AD service account. The service account would bind to LDAP them do the user lookup. In many environments users will not know what their CN or DN is, which is currently required by kiali.

**Comment by jmazzitelli** [comment] 2020-01-30 12:52
> What I meant was an LDAP/AD service account. The service account would bind to LDAP then do the user lookup. In many environments users will not know what their CN or DN is, which is currently required by kiali.

OK, that would be a separate enhancement request, separate from this issue, I think.

**Comment by israel-hdez** [comment] 2020-01-30 18:14
@MarkDeckert 

> It would be nice to have a separate service binding option so kiali itself would bind using a service account so users could login using upn or sAMAccount as that is more typical in enterprise.

I think you are right. It will be better.
I'll ping @Maneshme, the original author, to see if he is interested to implement this enhancement.

Otherwise, I can take a look, but it will be low priority.

**Comment by andye2004** [comment] 2020-02-08 08:58
@israel-hdez, I'm just looking at implementing the exact same thing as the OP now and suffering the same problems. Rather than write a custom layer, as has already been done, it might make more sense to make use of coreos dex. It provides authentication abstraction that can be used against various authentication providers, OIDC, OAuth2, LDAP etc.

**Comment by israel-hdez** [comment] 2020-02-11 16:14
@andye2004 sorry for late reply.
Well... did you try the suggestion from MarkDeckert about checking how the CN is formed, rather than using the sAMAccount? I know it may not be ideal, but it should work.

Even when the LDAP authentication has been around for some time, all this feedback is new. So, I appreciate it. Also, we have been receiving feedback for other authentication methods. So, I'll discuss with the team what would be the right approach to provide a more robust authentication mechanism.

Coreos Dex looks good. In the past, also Keycloak was proposed. If we go ahead with 3rd party auth providers, we may need to choose one of these two.

**Comment by andye2004** [comment] 2020-02-12 11:41
@israel-hdez, hi thanks for getting back to me!

I'm pretty familiar with LDAP / AD and other auth mechanisms and I could make use of the DN for users but the problem is that the CN generally relates to `firstname lastname`, e.g. `John Doe` and users generally use either their sAMAccount (with or without domain), or the uid field. Both of these fields would more likely hold the same value as their email address (minus the domain) and this is the case for us.

We already have a few application that authenticate via LDAP/AD and users are familiar with using their sAMAccount name (email name) and I don't really want to introduce another mechanism that would ask them to provide their CN value, I'm fairly sure a number of them wouldn't even know what this would actually be :)

An added complication, that is also not currently supported is the ability to restrict access based on group membership, this really is a fundamental part that I think is missing. Authentication without authorisation is really limited in value IMO.

I'll hold off for now, we'll use the login mechanism and only a few people will have access to the UI for the moment. Maybe when / if things are updated to use either the double bind mechanism and to allow group membership checks, or, even better, dex is implemented then we can look at this again and provide wider access.

**Comment by israel-hdez** [comment] 2020-06-05 19:33
Hi @coolpalani, @MarkDeckert, @andye2004 ,
The LDAP implementation in Kiali is being deprecated and will no longer be maintained. So, I'm closing this ticket -- sorry for the inconvenience.

In Kiali v1.19 (to be released today) a new _openid_ authentication strategy has been implemented. Our recommendation is that you use an OpenID connect provider that has support for LDAP. As suggested by @andye2004, you could use [Dex](https://github.com/dexidp/dex), but there is also [Keycloak](https://www.keycloak.org/) or any other OpenID provider you like/find. Any of these identity providers will offer a much more robust LDAP implementation that what we could offer in Kiali.

**Closed by israel-hdez** 2020-06-05 19:33 UTC
Labels: backlog, bug
