### ISSUE TITLE
Kiali does not connect to non istio-system namespace prometheus/grafana

### ISSUE THREAD

**Issue by nitishm** [kiali/kiali#2538] opened 2020-03-19 18:01 UTC
**General remarks**
I am trying to configure kiali v1.9.1 started using istio deployments to use our external prometheus and grafana instances.

I have modified the kiali configmap so that the loaded config looks like the following:
```
cat config.yaml
istio_namespace: fed-istio
deployment:
  accessible_namespaces: ['**']
auth:
  strategy: login
server:
  port: 20001
  web_root: /kiali
external_services:
  tracing:
    url: http://10.15.10.211:16686
    in_cluster_url: http://10.15.10.211:16686
  grafana:
    enabled: true
    url: http://10.15.12.31:3000
    in_cluster_url: http://10.15.12.31:3000
    service: "grafana"
    service_namespace: "fed-grafana"
    auth:
      username: "admin"
      password: "admin"
  prometheus:
    url: http://10.15.12.31:9090
    custom_metrics_url: http://10.15.12.31:9090
```
I still see this a client_error in the kiali logs,
```
~ kubectl logs -f kiali-1-0-0-109-main-int-dbg-74bfd545fb-ffbpc
I0319 17:16:39.970246       1 kiali.go:66] Kiali: Version: v1.9.1, Commit: 2431f9b8844202e27ec1c92f404fe7485253ffec
I0319 17:16:39.970828       1 kiali.go:210] Using authentication strategy [login]
I0319 17:16:39.970870       1 kiali.go:87] Kiali: Console version: 1.9.1
I0319 17:16:39.970875       1 kiali.go:272] Updating base URL in index.html with [/kiali]
I0319 17:16:39.971118       1 kiali.go:253] Generating env.js from config
I0319 17:16:39.997325       1 server.go:57] Server endpoint will start at [:20001/kiali]
I0319 17:16:39.997343       1 server.go:58] Server endpoint will serve static content from [/opt/kiali/console]
I0319 17:16:39.997350       1 metrics_server.go:18] Starting Metrics Server on [:9090]
I0319 17:16:39.997522       1 kiali.go:142] Secret is now available.
E0319 17:17:05.272883       1 workloads.go:570] Workload fed-istio-pod-redis-server is not found as StatefulSet
E0319 17:17:05.289635       1 workloads.go:570] Workload alertmanager-prometheus-alerts is not found as StatefulSet
E0319 17:17:05.289658       1 workloads.go:570] Workload prometheus-prometheus is not found as StatefulSet
E0319 17:17:05.310482       1 workloads.go:570] Workload fed-service-reg-pod-service-reg-server is not found as StatefulSet
E0319 17:17:13.008165       1 config.go:103] Failed to fetch Prometheus configuration: client_error: client error: 404
E0319 17:17:13.009351       1 config.go:103] Failed to fetch Prometheus flags: client_error: client error: 404
E0319 17:17:13.584961       1 workloads.go:570] Workload alertmanager-prometheus-alerts is not found as StatefulSet
E0319 17:17:13.584985       1 workloads.go:570] Workload prometheus-prometheus is not found as StatefulSet
E0319 17:17:13.585912       1 workloads.go:570] Workload fed-istio-pod-redis-server is not found as StatefulSet
E0319 17:17:13.604050       1 workloads.go:570] Workload fed-service-reg-pod-service-reg-server is not found as StatefulSet
E0319 17:17:47.608302       1 dashboards.go:305] runtimes discovery failed, cannot load dashboards in namespace fed-example. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io)
```

**Describe the bug**
Cannot access prometheus and grafana if not in istio-system namespace

For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali: 1.9.1
Istio: 1.4.2
Kubernetes flavour and version: "v1.16.2" self deployed

**To Reproduce**
Change kiali configmap

**Expected behavior**
Should connect to external prom/grafana

**Comment by israel-hdez** [comment] 2020-03-19 19:29
With this line:

`E0319 17:17:13.008165       1 config.go:103] Failed to fetch Prometheus configuration: client_error: client error: 404`

I see that Kiali can reach that IP address, but the server is returning a `404` code, which means **NOT FOUND**. Perhaps, are you missing the path? (i.e. `http://10.15.12.31:9090/the/path/for/prometheus/`)

**Comment by nitishm** [comment] 2020-03-19 19:33
I tried changing the path to `http://10.15.12.31:9090/graph` which is what it redirects too on the browser, without any luck.

**Comment by israel-hdez** [comment] 2020-03-19 19:47
@nitishm can you please run these commands and report back the output?

```bash
KIALI_NAMESPACE=your_kiali_installation_namespace
kubectl get pod -o wide -n $KIALI_NAMESPACE
kubectl get service -n $KIALI_NAMESPACE
```

**Comment by israel-hdez** [comment] 2020-03-19 19:49
@nitishm is Prometheus inside the cluster, or it's external to the cluster?

**Comment by nitishm** [comment] 2020-03-19 20:25
> @nitishm can you please run these commands and report back the output?
> 
> ```shell
> KIALI_NAMESPACE=your_kiali_installation_namespace
> kubectl get pod -o wide -n $KIALI_NAMESPACE
> kubectl get service -n $KIALI_NAMESPACE
> ```

```
NAME                                                             READY   STATUS    RESTARTS   AGE    IP                NODE                                                NOMINATED NODE   READINESS GATES
fed-istio-pod-redis-server-0                                     2/2     Running   0          2d3h   192.168.82.28     nitish-malhotra-k8-node-3-cca080-4b2c09f7b029c1b8   <none>           <none>
istio-citadel-1-0-0-109-main-int-dbg-f899f5c86-vkcbc             1/1     Running   0          2d3h   192.168.89.14     nitish-malhotra-k8-node-2-cca080-4b2c09f7b029c1b8   <none>           <none>
istio-galley-1-0-0-109-main-int-dbg-54b9489cb-hssl5              1/1     Running   0          2d3h   192.168.167.89    nitish-malhotra-k8-node-1-cca080-4b2c09f7b029c1b8   <none>           <none>
istio-pilot-1-0-0-109-main-int-dbg-c4659c477-7p8s7               2/2     Running   3          2d3h   192.168.167.85    nitish-malhotra-k8-node-1-cca080-4b2c09f7b029c1b8   <none>           <none>
istio-policy-1-0-0-109-main-int-dbg-767fd6df6c-h5k8g             2/2     Running   4          2d3h   192.168.82.26     nitish-malhotra-k8-node-3-cca080-4b2c09f7b029c1b8   <none>           <none>
istio-sidecar-injector-1-0-0-109-main-int-dbg-57dcb6b6cf-cth57   1/1     Running   0          2d3h   192.168.167.87    nitish-malhotra-k8-node-1-cca080-4b2c09f7b029c1b8   <none>           <none>
istio-telemetry-1-0-0-109-main-int-dbg-5ccc7d8cdc-p489t          2/2     Running   4          2d3h   192.168.89.12     nitish-malhotra-k8-node-2-cca080-4b2c09f7b029c1b8   <none>           <none>
kiali-1-0-0-109-main-int-dbg-74bfd545fb-7tfr4                    1/1     Running   0          72m    192.168.167.100   nitish-malhotra-k8-node-1-cca080-4b2c09f7b029c1b8   <none>           <none>
NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                  AGE
fed-istio-pod-redis              ClusterIP   None             <none>        6379/TCP,26379/TCP                       2d3h
fed-istio-pod-redis-announce-0   ClusterIP   10.97.234.212    <none>        6379/TCP,26379/TCP                       2d3h
istio-citadel                    ClusterIP   10.103.156.39    <none>        8060/TCP,15014/TCP                       2d3h
istio-galley                     ClusterIP   10.103.21.22     <none>        443/TCP,15014/TCP,9901/TCP               2d3h
istio-pilot                      ClusterIP   10.107.144.172   <none>        15010/TCP,15011/TCP,8080/TCP,15014/TCP   2d3h
istio-policy                     ClusterIP   10.110.138.154   <none>        9091/TCP,15004/TCP,15014/TCP             2d3h
istio-sidecar-injector           ClusterIP   10.107.44.249    <none>        443/TCP,15014/TCP                        2d3h
istio-telemetry                  ClusterIP   10.107.220.186   <none>        9091/TCP,15004/TCP,15014/TCP,42422/TCP   2d3h
kiali                            NodePort    10.102.81.243    <none>        20001:31200/TCP                          2d3h
```

**Comment by nitishm** [comment] 2020-03-19 20:26
> @nitishm is Prometheus inside the cluster, or it's external to the cluster?

In this setup they are but in production they dont necessarily have to be, that's why I am using the NodeIP with the NodePort to emulate an external grafana/prometheus

**Comment by israel-hdez** [comment] 2020-03-19 20:46
> In this setup they are but in production they dont necessarily have to be, that's why I am using the NodeIP with the NodePort to emulate an external grafana/prometheus

OK, this explains why I see the same `10.15.12.31` IP for both grafana and prometheus.
I'm not sure that you really can use the NodeIP for this. Kubernetes may handle in-cluster and out-cluster traffic differently.

I think it's better if you use the IP of the grafana and prometheus pods to simulate the scenario. I already gave you a command to find the IP:

```
kubectl get pod -o wide -n $GRAFANA_NS $GRAFANA_POD_NAME
kubectl get pod -o wide -n $PROMETHEUS_NS $PROMETHEUS_POD_NAME
```

and use the reported IPs in the kiali configuration.

**Comment by nitishm** [comment] 2020-03-19 21:01
I made the change and now I am running into a different error
```
~ kubectl logs -f kiali-1-0-0-109-main-int-dbg-74bfd545fb-lrh6q
I0319 20:59:06.541700       1 kiali.go:66] Kiali: Version: v1.9.1, Commit: 2431f9b8844202e27ec1c92f404fe7485253ffec
I0319 20:59:06.542180       1 kiali.go:210] Using authentication strategy [login]
I0319 20:59:06.542221       1 kiali.go:87] Kiali: Console version: 1.9.1
I0319 20:59:06.542228       1 kiali.go:272] Updating base URL in index.html with [/kiali]
I0319 20:59:06.542526       1 kiali.go:253] Generating env.js from config
I0319 20:59:06.575370       1 server.go:57] Server endpoint will start at [:20001/kiali]
I0319 20:59:06.575388       1 server.go:58] Server endpoint will serve static content from [/opt/kiali/console]
I0319 20:59:06.575399       1 metrics_server.go:18] Starting Metrics Server on [:9090]
I0319 20:59:06.575706       1 kiali.go:142] Secret is now available.
E0319 20:59:27.975313       1 workloads.go:570] Workload fed-istio-pod-redis-server is not found as StatefulSet
E0319 20:59:28.008137       1 workloads.go:570] Workload fed-service-reg-pod-service-reg-server is not found as StatefulSet
E0319 20:59:28.008329       1 workloads.go:570] Workload alertmanager-prometheus-alerts is not found as StatefulSet
E0319 20:59:28.008345       1 workloads.go:570] Workload prometheus-prometheus is not found as StatefulSet
E0319 20:59:34.322904       1 dashboards.go:305] runtimes discovery failed, cannot load dashboards in namespace fed-example. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io)
E0319 21:00:08.083602       1 dashboards.go:305] runtimes discovery failed, cannot load dashboards in namespace fed-example. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io)
E0319 21:00:16.300142       1 workloads.go:570] Workload fed-istio-pod-redis-server is not found as StatefulSet
E0319 21:00:16.306650       1 workloads.go:570] Workload alertmanager-prometheus-alerts is not found as StatefulSet
E0319 21:00:16.306670       1 workloads.go:570] Workload prometheus-prometheus is not found as StatefulSet
E0319 21:00:16.308621       1 workloads.go:570] Workload fed-service-reg-pod-service-reg-server is not found as StatefulSet
E0319 21:00:27.581376       1 dashboards.go:305] runtimes discovery failed, cannot load dashboards in namespace fed-example. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io)
E0319 21:00:29.744422       1 dashboards.go:305] runtimes discovery failed, cannot load dashboards in namespace fed-example. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io)
E0319 21:00:31.619069       1 dashboards.go:305] runtimes discovery failed, cannot load dashboards in namespace fed-example. Error was: the server could not find the requested resource (get monitoringdashboards.monitoring.kiali.io)
```

**Comment by israel-hdez** [comment] 2020-03-19 22:26
@nitishm At least, I no longer see the connection errors to Prometheus. I'll assume that's solved and communication is now OK.

AFAIK, you can ignore the `runtimes discovery failed` if you are not configuring custom dashboards. @jotak will need to confirm this.

For those errors about "workloads not found as StatefulSet", I'll ask for @lucasponce help because I don't know what may be the issue. Lucas may answer because since he is in Europe timezone.

**Comment by nitishm** [comment] 2020-03-19 22:38
The errors are gone but I still don't see the grafana icon next to the metrics chart. The logs don't complain but any reason why that is the case? Also we used the pod IP which is not feasible. Why is it not possible to connect to an out of cluster server?

**Comment by israel-hdez** [comment] 2020-03-19 23:21
@nitishm For the grafana config, there are two fields:

```
grafana:
    url: http://10.15.12.31:3000
    in_cluster_url: http://10.15.12.31:3000
```

the `in_cluster_url` field is what I asked to be the pod IP (my fault for not being clear). The `url` field should be the public address to grafana. If you changed both fields to the pod IP, this may be preventing the grafana links to show up. If you can access grafana using `http://10.15.12.31:3000`, then this is the value to use for `url` field.

Since you are simulating, you may need to use pod IPs or kubernetes may not route correctly (I'm not sure how your ingress works). Once you have prometheus and grafana servers outside of the cluster, all these URL fields should be configured with the address of the external servers. If your goal is to check that Kiali will work correctly... well... I suggest you to not simulate, but to setup grafana and prometheus servers outside the cluster and configure Kiali accordingly.

**Comment by jotak** [comment] 2020-03-20 09:12
> AFAIK, you can ignore the `runtimes discovery failed` if you are not configuring custom dashboards. @jotak will need to confirm this.

I can confirm, Kiali will work correctly without these dashboards, it's an optional feature to show some additional application-specific metrics if your app implements them (e.g. springboot metrics, go metrics ...) ; see https://kiali.io/documentation/runtimes-monitoring/ . If you want to add them, you can still install the relevant CRD manually.

**Comment by israel-hdez** [comment] 2020-03-25 23:22
@nitishm If you think that you got all the information you need, please consider closing this issue.

**Comment by jotak** [comment] 2020-09-01 08:34
Closing this issue, I think @israel-hdez gave a correct answer, but should there be any unsolved problem please reopen. Thanks.

**Closed by jotak** 2020-09-01 08:34 UTC
Labels: bug
