### ISSUE TITLE
The graph_test.go test failed on Windows

### ISSUE THREAD

**Issue by sniperking1234** [kiali/kiali#1125] opened 2019-06-08 08:24 UTC
like this
![image](https://user-images.githubusercontent.com/7834655/59144387-dbe3f800-8a09-11e9-9581-77602ee22b07.png)

**Comment by lucasponce** [comment] 2019-06-10 07:30
Thanks @sniperking1234 for opening this issue.
Most of our team use MacOS / Linux, so probably we missed something in the Windows.

Two things, can you describe your environment setup ?

I haven't setup, but did you try to check the target architecture ?
Probably, that could affect, if you can give a try (just to confirm that is a parameter in the config) we would appreciate also if you can help us to with a PR and testing on this platform.

Thanks

**Comment by lucasponce** [comment] 2019-06-10 07:45
cc @jshaughn

**Comment by sniperking1234** [comment] 2019-06-10 08:43
> Thanks @sniperking1234 for opening this issue.
> Most of our team use MacOS / Linux, so probably we missed something in the Windows.
> 
> Two things, can you describe your environment setup ?
> 
> I haven't setup, but did you try to check the target architecture ?
> Probably, that could affect, if you can give a try (just to confirm that is a parameter in the config) we would appreciate also if you can help us to with a PR and testing on this platform.
> 
> Thanks

Go version is go1.12.5 windows/amd64 and IDE is GoLand
I think the problem is caused by newline character，expected used \r\n and acutal used \n
![image](https://user-images.githubusercontent.com/7834655/59183253-2dbd8700-8b9e-11e9-8251-fcdf18bb7854.png)

**Comment by jshaughn** [comment] 2019-06-10 12:32
For sure the problem is line terminators and the usual disparity between \n and \r\n between windows and non-windows.   Those tests validate by comparing the generated json to a file with the expected output.  Those files were generated on a linux env.

**Comment by israel-hdez** [comment] 2019-06-10 16:00
Closing the issue, because I see there is a merged fix :)
Thanks for your contribution!

**Closed by israel-hdez** 2019-06-10 16:00 UTC
