### ISSUE TITLE
More than one Gateway, but cannot find duplicate.

### ISSUE THREAD

**Issue by simonpie** [kiali/kiali#5213] opened 2022-06-15 15:57 UTC
Kiali reports for a few Gateway Objects that we have a duplicate host and port conflict.  
![Capture d’écran, le 2022-06-15 à 09 01 50](https://user-images.githubusercontent.com/1424864/173869664-fc4d8e04-1a91-423a-ab81-b6cef963739d.png)

![Capture d’écran, le 2022-06-15 à 09 11 10](https://user-images.githubusercontent.com/1424864/173869776-2cf96a68-352e-43c8-9407-dcdc8ea5e5f1.png)

But, I cannot find the conflict.  `Istioctl analyze -A` does not report anything on more than one gateway : 

```
istioctl analyze -A | grep -i Error
Error: Analyzers found issues when analyzing all namespaces.
See https://istio.io/v1.13/docs/reference/config/analysis for more information about causes and resolutions.
Error [IST0101] (Gateway istio-gateways/gateway-for-all-apis) Referenced selector not found: "istio=ingressgateway"
Error [IST0101] (Gateway istio-gateways/gateway-for-services) Referenced selector not found: "istio=ingressgateway"
Error [IST0101] (Gateway istio-squelette/httpbin-gateway) Referenced selector not found: "istio=ingressgateway"
Error [IST0101] (Gateway test-automatique/test-automatique-gateway) Referenced selector not found: "app=istio-ingressgateway"
```

As can be seen in the screen capture above, there are a few Validation References, but if one clicks on the links, kiali cannot find the ressource : 

![Capture d’écran, le 2022-06-15 à 09 01 59](https://user-images.githubusercontent.com/1424864/173868006-a513ea1f-bf12-4775-afe3-aac94c86c912.png)

Warnings are not more helpful.  `kubectl `does not help either : 

```
> kc get gateways.networking.istio.io -n istio-system
No resources found in istio-system namespace.
> kc get ingress -n istio-system                                                                                   
No resources found in istio-system namespace.
``` 

Nor in the namespace : 

```
> kc get gw -n istio-squelette
NAME              AGE
httpbin-gateway   26d
> kc get virtualservices.networking.istio.io -n istio-squelette 
NAME       GATEWAYS                                  HOSTS                                 AGE
httpbin    ["istio-gateways/gateway-for-all-apis"]   ["api.kube.lab.ile.montreal.qc.ca"]   28d
httpbin2   ["httpbin-gateway"]                       ["httpbin.squl"]                      14d
```

Yes, we have an `ingressclass` named istio, but I cannot find any conflict.

Finally, the gateway-virtualService pair works correctly and has been published in the ingress-gateway.

So, either I need help to help me find the duplicate entry ( hopefully straight in Kiali's Gui ), or there this is a false positive.

Here are our versions : 

![Capture d’écran, le 2022-06-14 à 17 11 31](https://user-images.githubusercontent.com/1424864/173870030-d6887433-961c-4aa1-8a0d-1e9ce5b65ec0.png)

```
> istioctl version                     
client version: 1.13.2
istiod version: 1.13.2
istiod version: 1.13.2
istiod version: 1.14.1
istiod version: 1.14.1
data plane version: 1.13.2 (108 proxies), 1.14.1 (2 proxies)
>

> kc version --short
Client Version: v1.23.5
Server Version: v1.21.5
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

We have had this problem in version 1.13.2 and version 1.14.1  of istio, this is just the state this morning.

**Comment by lucasponce** [comment] 2022-06-16 04:48
Mmm perhaps you have some wildcard in the hosts of a gateway?
cc @hhovsepy

**Comment by simonpie** [comment] 2022-06-16 15:40
@lucasponce  

I believe we do not have at top level.  Only at subdomain.  But then again, if there were no bug in Kiali and  Kiali found a conflict, why does it not just show it ( prove ) to me ?

@hhovsepy 

Exact, we have deployed istio with the ingress-gateway in a separate namespace.. And the Gateway in the `Validation References`result in an error ( which is in red in one of the capture ).  But I believe those are references to autogenerated stuff by istio when we declare standard ingress object that have the istio ingress class : 

```
> kc get ingressclasses.networking.k8s.io istio
NAME    CONTROLLER                    PARAMETERS   AGE
istio   istio.io/ingress-controller   <none>       77d
> kc get ingress -A | grep -i istio                 
NAMESPACE                         NAME                                               CLASS    HOSTS                                                                                                             ADDRESS        PORTS     AGE
infra-auth                        infra-auth-kubectl-web                             istio    kubectl.kube.lab.ile.montreal.qc.ca,kubectl.lab.interne.montreal.ca                                               172.22.7.243   80        176d
infra-auth                        keycloak                                           istio    kube-auth.lab.interne.montreal.ca                                                                                 172.22.7.243   80, 443   124d
infra-auth                        kube-dashboard-proxy-kubernetes-dashboard-proxy    istio    kube-dashboard.lab.interne.montreal.ca                                                                            172.22.7.243   80, 443   141d
infra-grafana                     graf4-grafana                                      istio    grafana.kube.lab.ile.montreal.qc.ca,grafana.lab.interne.montreal.ca                                               172.22.7.243   80        560d
infra-jenkins                     cicd-rbd-jenkins                                   istio    jenkins.lab.interne.montreal.ca                                                                                                  80        40d
infra-jenkins                     cicd-rbd-jenkins-secondary                         istio    services.lab.montreal.ca                                                                                          172.22.7.243   80        40d
infra-kiali                       kiali                                              istio    kiali.lab.interne.montreal.ca                                                                                                    80        77d
infra-nexus                       sonatype-nexus                                     istio    nexus.lab.interne.montreal.ca                                                                                     172.22.7.243   80, 443   452d
infra-prometheus                  prom2-prometheus-alertmanager                      istio    alertmanager.kube.lab.ile.montreal.qc.ca,prometheus-alertes.lab.interne.montreal.ca                                              80        42d
infra-prometheus                  prom2-prometheus-server                            istio    prometheus.kube.lab.ile.montreal.qc.ca,prometheus.lab.interne.montreal.ca                                                        80        42d
infra-statuspage-istio            statuspage-web-istio                               <none>   services.lab.montreal.ca,services.kube.lab.ile.montreal.qc.ca                                                     172.22.7.243   80        447d
```

**Comment by lucasponce** [comment] 2022-06-17 06:10
> I believe we do not have at top level. Only at subdomain. But then again, if there were no bug in Kiali and Kiali found a conflict, why does it not just show it ( prove ) to me ?

Oh, don't get me wrong, Kiali should explain the warnings and they should be meaningful to the users to perform any action on that. It seems your configuration is a case that was not well treated in Kiali. I see @hhovsepy is asking for more details, hopefully, that may help to understand this scenario to incorporate it into Kiali.

**Comment by simonpie** [comment] 2022-06-17 11:55
Good, we are on the same page.  Its not always easy to convey intent without being too blunt.  In any case, if @hhovsepy needs us to run command, try some beta version or anything, we will be glad to help.  I see Kiali as a pre-requisite before we go to production with Istio, which makes us more than willing to help (We are not developers though).

**Comment by hhovsepy** [comment] 2022-06-17 13:43
@simonpie did you installed Istio and ingress gateway via helm and specified "--set global.k8sIngress.enabled=true" param?

**Comment by simonpie** [comment] 2022-06-17 16:32
Good question.  The guy who installed is at F1 race today.  It will have to wait, but if I had had to guess, I would have said yes we did.  But, after inspecting the configmap of istio : 

```
> kc get cm -n istio-system istio-1-13-2 -oyaml
apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod-1-13-2.istio-system.svc:15012
      tracing:
        zipkin:
          address: jaeger-collector.infra-jaeger:9411
    enablePrometheusMerge: true
    enableTracing: true
    rootNamespace: null
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: istiod-1-13-2
    meta.helm.sh/release-namespace: istio-system
  creationTimestamp: "2022-03-30T20:13:33Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: 1-13-2
    operator.istio.io/component: Pilot
    release: istiod-1-13-2
  name: istio-1-13-2
  namespace: istio-system
  resourceVersion: "614225416"
  uid: 5e3571da-3bbd-48c0-88c1-988f6fad9e67
[Ananke:: 12:29:09] [~] > 
```
I am not so sure anymore.

**Comment by hhovsepy** [comment] 2022-06-20 08:31
Yes, the steps for installing Istio which triggered generated those Gateways would be helpful, as so far I cannot reproduce the problem.

**Comment by hhovsepy** [comment] 2022-06-27 06:38
Hi @simonpie is it possible provide the installation steps of Istio ?

**Comment by simonpie** [comment] 2022-06-28 20:33
Hello @hhovsepy 

I am Sorry for the delays, it is holliday season here.  We have a script to install that replicates the helm instructions [here](https://istio.io/v1.13/docs/setup/install/helm/).

Only, it will install CNI plugin and do a release installation with tags.

Here is the installation function : 

```
function cmd_install() {

    ${HELM} repo add istio https://istio-release.storage.googleapis.com/charts --force-update

    # Install CRD
    ${HELM} show crds ${ISTIO_BASE_CHART_NAME} --version=$CHART_VERSION | kubectl apply -f -


    CHECK_IF_FIRST_INSTALL=$(${HELM} list -n ${ISTIO_BASE_NAMESPACE} | grep ${ISTIO_BASE_RELEASE_NAME}) || true

    # Execute the post upgrade command if not installed
    if [[ -z "${CHECK_IF_FIRST_INSTALL}" ]]; then
        cmd_post_upgrade
    fi

    # Add istio ingressClassName
    kubectl apply -f ${SCRIPTDIR}/config/${ISTIO_INGRESS_CLASS}

    # CNI
    ${HELM_UPGRADE} ${ISTIO_CNI_RELEASE_NAME} ${ISTIO_CNI_CHART_NAME} --version=$CHART_VERSION --set revision=$REVISION \
    -n ${ISTIO_CNI_NAMESPACE} --create-namespace --wait

    # ISTIOD
    ${HELM_UPGRADE} ${ISTIOD_RELEASE_NAME}-$REVISION ${ISTIOD_CHART_NAME} --set istio_cni.enabled=true --version=$CHART_VERSION --set revision=$REVISION \
    -n ${ISTIOD_NAMESPACE} --create-namespace --wait -f ${SCRIPTDIR}/config/${ISTIOD_GLOBAL_VALUES}

    # TAG
    ${HELM} template ${ISTIOD_RELEASE_NAME} ${ISTIOD_CHART_NAME} -s templates/revision-tags.yaml --set revision=$REVISION \
    -n ${ISTIOD_NAMESPACE} --version=$CHART_VERSION --set revisionTags={${CANARY_REVISION_TAG}} | kubectl apply -f -

    # IGWY
    ${HELM_UPGRADE} ${ISTIO_IGWY_RELEASE_NAME} ${ISTIO_IGWY_CHART_NAME} --version=$CHART_VERSION --set revision=$REVISION \
    -n ${ISTIO_IGWY_NAMESPACE} --create-namespace --wait -f ${SCRIPTDIR}/config/${ISTIO_IGWY_GLOBAL_VALUES} \

}
```

and the post-upgrade function : 

```
function cmd_post_upgrade() {
    # BASE
    ${HELM_UPGRADE} ${ISTIO_BASE_RELEASE_NAME} ${ISTIO_BASE_CHART_NAME} --version=$CHART_VERSION  --set revision=$REVISION \
    -n ${ISTIO_BASE_NAMESPACE} --skip-crds

    # TAG
    ${HELM} template ${ISTIOD_RELEASE_NAME} ${ISTIOD_CHART_NAME} \
    -s templates/revision-tags.yaml --set revisionTags={${DEFAULT_REVISION_TAG}} --version=$CHART_VERSION\
    --set revision=$REVISION -n ${ISTIOD_NAMESPACE} | kubectl apply -f -
}
```

And nothing interesting in the custom values.  The namespaces of the ingresses is a parameters given to helm.

**Comment by simonpie** [comment] 2022-07-20 15:29
Hello again,

`Can you just remove those auto-generated istio-system Gateways?`

I believe they are gone from istio's installation :

```
[Ananke:: 11:22:38] [~] > kc get gateways.networking.istio.io -A             
NAMESPACE          NAME                       AGE
istio-cd-tests     httpbin-gateway            24h
istio-gateways     gateway-for-all-apis       18h
test-automatique   test-automatique-gateway   12d
[Ananke:: 11:26:44] [~] > kc get pods -A | grep -i ingre         
istio-gateways                    istio-ingressgateway-b786b8478-hq2n2                              1/1     Running     0          20d
istio-gateways                    istio-ingressgateway-b786b8478-t6484                              1/1     Running     0          20d
kube-system                       ingress-ingress-nginx-controller-58xn7                            1/1     Running     1          84d
kube-system                       ingress-ingress-nginx-controller-c962t                            1/1     Running     1          84d
kube-system                       ingress-ingress-nginx-controller-nnw4f                            1/1     Running     0          84d
kube-system                       ingress-ingress-nginx-controller-pcpzr                            1/1     Running     1          84d
kube-system                       ingress-ingress-nginx-defaultbackend-55fcd5cc7b-g9xsl             1/1     Running     0          56d
[Ananke:: 11:27:34] [~] > 

```

**Comment by hhovsepy** [comment] 2022-07-25 09:19
thanks for the info @simonpie , I am still unable to reproduce the situation when those auto-generated Gateways are removed by Istio after upgrade.
They are available and linkable, and when deleting them manually, it also removes all validation references to them.

**Comment by simonpie** [comment] 2022-07-25 14:31
Hmmm.  @hhovsepy Anything we can run on our side to help you pinpoint something ?

**Comment by hhovsepy** [comment] 2022-07-26 05:50
What comes into my mind is, that those Gateways are cached (and not sure why not updated as autogenerated) and Kiali reads all configurations from cache to perform validations.
Is it possible to restart "kiali" pod?

**Comment by simonpie** [comment] 2022-07-26 13:18
Done, but no change.

I still have the same problem.  Kiali complains about a conflict which I cannot find.


![problemkiali](https://user-images.githubusercontent.com/1424864/181014328-7183d878-8677-4386-a061-8fe6ee5c4034.png)


```
[Ananke:: 9:05:32] [/tmp] > kc get ingress -A | grep -i http                    
it-platforms-utils                core-http-utils-api                                <none>   api.lab.interne.montreal.ca,api.lab.montreal.ca,api.lab.ile.montreal.qc.ca                                        172.22.7.243   80        12d
[Ananke:: 9:08:13] [/tmp] > kc get svc  -A | grep -i http   
infra-auth                        keycloak-http                                             ClusterIP      172.22.123.181   <none>                                        80/TCP,8443/TCP,9990/TCP                                                                      164d
infra-ceph-csi-rbd                ceph-csi-rbd-nodeplugin-http-metrics                      ClusterIP      172.22.44.6      <none>                                        8080/TCP                                                                                      383d
infra-ceph-csi-rbd                ceph-csi-rbd-provisioner-http-metrics                     ClusterIP      172.22.100.205   <none>                                        8080/TCP                                                                                      383d
istio-cd-tests                    httpbin                                                   ClusterIP      172.22.34.58     <none>                                        8000/TCP                                                                                      6d22h
istio-httpbin                     httpbin                                                   ClusterIP      172.22.137.56    <none>                                        8000/TCP                                                                                      273d
it-platforms-utils                core-http-utils-api                                       NodePort       172.22.108.122   <none>                                        12345:32498/TCP                                                                               12d
podspread                         httpbin                                                   ClusterIP      172.22.255.141   <none>                                        8000/TCP                                                                                      88d
simontest-istio-httpbin           httpbin                                                   ClusterIP      172.22.187.152   <none>                                        8000/TCP                                                                                      284d
[Ananke:: 9:08:26] [/tmp] > kc get virtualservices.networking.istio.io  -A | grep -i http 
istio-cd-tests     httpbin                   ["istio-gateways/gateway-for-all-apis"]                               ["api.kube.lab.ile.montreal.qc.ca"]                      6d22h
istio-cd-tests     httpbin2                  ["httpbin-gateway"]                                                   ["httpbin.cd"]                                           6d22h
[Ananke:: 9:08:48] [/tmp] >  kc get gateways.networking.istio.io  -A | head  
NAMESPACE          NAME                        AGE
istio-cd-tests     httpbin-gateway             6d22h
istio-cd-tests     test-projet-istio-gateway   4d18h
istio-gateways     gateway-for-all-apis        6d16h
test-automatique   test-automatique-gateway    18d
[Ananke:: 9:09:47] [/tmp] > kc get gateways.networking.istio.io  -A | grep -i http
istio-cd-tests     httpbin-gateway             6d22h
[Ananke:: 9:09:54] [/tmp] > 

``

We are supposed to do a kubernetes update in our lab soon.  I'll report if the behaviour changes.

**Comment by hhovsepy** [comment] 2022-08-11 19:35
The fix will be released in Kiali v1.55

**Closed by hhovsepy** 2022-08-11 19:35 UTC
Labels: bug, backlog

**Comment by simonpie** [comment] 2022-08-11 20:34
Thank you for persevering on this issue.  We shall try that as soon as we can.

**Comment by ldemailly** [comment] 2022-08-18 20:38
piggy backing on this, do we also changed so "*" doesn't end up conflicting with every entry?

we use `*` in some shared gateway because it's needed for routing some health checks that come with no host entry as well as a catch up for for doing https redirect but the more specific entries like `foo.bar.blah` are marked as KIA0301 (in 1.48) even though they really aren't in conflict - istio uses the most specific if there is a match and * is just the fallback so not an error/warning - imo

**Comment by hhovsepy** [comment] 2022-08-19 09:54
@ldemailly the Kiali validations are designed in a way, that if any of gateways has "*" in hosts, then it will have conflict with any other gateway, and the opposite. Gateways are by default exported to all namespaces (unless exportTo specifies other), as shown in example here: https://kiali.io/docs/features/validations/#kia0301---more-than-one-gateway-for-the-same-host-port-combination.

But there is a way to skip showing particular errors by specifying them in "kiali" configuration section "validations:  ignore:"

**Comment by ldemailly** [comment] 2023-01-12 17:23
@hhovsepy sorry for the late follow up but I don't think it's correct to say * conflicts for istio, afaik istio will match specific hosts first and * is only the fallback

In our use case we don't want to ignore real errors, but do want to not count * as it doesn't actually conflict (so ignoring KIA0301 entirely isn't what we need - unless I mis understand and it's possible through config already to make it not use it maybe for 1 gateway object (the one where we put the *) vs globally?)

Can we make it configurable or an option to ignore * ? (or tbh the default behavior to match 'real' conflicts - like if more than 1 gateway had * that would be an error but not if there is only 1 and more specific hosts in others)

Thanks!

**Comment by hhovsepy** [comment] 2023-01-12 18:24
@ldemailly sure it is not a conflict on Istio side, but a Kiali validation warning, sorry for the confusion.
Feel free to create a separate enhancement issue (feature request) in github. 
My idea for this feature will be, new configuration option to ignore * hosts in gateways in case of KIA0301, even though there is only 1 gateway with * ( to keep the validation logic consistent).

**Comment by ldemailly** [comment] 2023-01-12 18:27
k thx, filling a new issue (imo a bug but ok happy to call it a feature request if that helps :) )
