### ISSUE TITLE
Openid authentication policy login failed

### ISSUE THREAD

**Issue by shinynz** [kiali/kiali#2955] opened 2020-07-02 03:46 UTC
Kiali: v1.20
Istio: 1.6.3
Kubernetes: 1.18.3

kiali configmap:

> `{
> 	"config.yaml": "istio_component_namespaces:
> 		  grafana: istio-system
> 		  tracing: istio-system
> 		  istiod: istio-system
> 		  prometheus: istio-system
> 		istio_namespace: istio-system
> 		auth:
> 		  strategy: openid
> 		  openid:
> 		    client_id: \"kubernetes\"
> 		    issuer_uri: \"https://keycloak.xxx.com.cn/auth/realms/kiali\"
> 		    authentication_timeout: 300
> 		    insecure_skip_verify_tls: true
> 		    scopes: [\"openid\"]
> 		    username_claim: \"preferred_username\"
> 		deployment:
> 		  accessible_namespaces: ['**']
> 		login_token:
> 		  signing_key: \"uEnL7onfiw\"
> 		server:
> 		  port: 20001
> 		  web_root: /kiali
> 		external_services:
> 		  istio:
> 		    url_service_version: http://istiod.istio-system:15014/version
> 		  tracing:
> 		    url: 
> 		    in_cluster_url: http://tracing/jaeger
> 		  grafana:
> 		    url: 
> 		    in_cluster_url: http://grafana:3000
> 		  prometheus:
> 		    url: http://prometheus.istio-system:9090"
> }`

login error
![image](https://user-images.githubusercontent.com/15795798/86314183-9bc96600-bc59-11ea-8aa4-5bac5838b722.png)

**Comment by jmazzitelli** [comment] 2020-07-02 03:51
This is most likely a duplicate of https://github.com/kiali/kiali/issues/2925 ... see https://github.com/kiali/kiali/issues/2925#issuecomment-652112995

@israel-hdez is working on a fix.

**Comment by israel-hdez** [comment] 2020-07-02 15:08
@shinynz To check if this is a duplicate, please provide the logs of the Kiali pod. Also, please provide the content of the response tab (响应) of the browser developer console.

**Comment by shinynz** [comment] 2020-07-03 01:15
@israel-hdez  response
![image](https://user-images.githubusercontent.com/15795798/86421715-a1808380-bd0d-11ea-92ef-122733196c8d.png)

kiali pod logs
I0701 10:06:23.518461       1 kiali.go:66] Kiali: Version: v1.20.0, Commit: cfb83b01565da8a789f6c6b03272950937966a5d
I0701 10:06:23.520334       1 kiali.go:205] Using authentication strategy [openid]
I0701 10:06:23.520424       1 kiali.go:87] Kiali: Console version: 1.20.0
I0701 10:06:23.520446       1 kiali.go:284] Updating base URL in index.html with [/kiali]
I0701 10:06:23.521525       1 kiali.go:265] Generating env.js from config
I0701 10:06:23.527613       1 server.go:67] Server endpoint will start at [:20001/kiali]
I0701 10:06:23.527648       1 server.go:68] Server endpoint will serve static content from [/opt/kiali/console]
I0701 10:06:23.527678       1 metrics_server.go:18] Starting Metrics Server on [:9090]

**Comment by israel-hdez** [comment] 2020-07-03 15:00
As @jmazzitelli, this seems to be a duplicate of https://github.com/kiali/kiali/issues/2954.
Please, follow issue #2954 and try again when it's fixed to see if your problem is also fixed.

**Comment by shinynz** [comment] 2020-07-10 06:28
@israel-hdez  Updated to v1.21.0-snapshot.0, the problem is still the same error connecting to kiali

**Comment by israel-hdez** [comment] 2020-07-10 14:32
@shinynz Related issue #2954 is not fixed yet. Please, try again when that issue is closed.

**Comment by israel-hdez** [comment] 2020-07-17 17:43
@shinynz Issue #2954 is solved.
Today, Kiali v1.21 is going to be released in a few hours.

Try with that coming version to see if your issue is solved.

**Closed** 2020-07-20 03:25 UTC
Labels: bug
