### ISSUE TITLE
Kiali UI is very slow with evicted pods

### ISSUE THREAD

**Issue by sukrit007wawa** [kiali/kiali#4672] opened 2022-01-25 04:02 UTC
**Issue**
If there are a lot of evicted pods in Kubernetes,  Kiali UI slows down significantly.

**Possible Cause**
It looks like Kiali tries to portforward requests to evicted pods, and keeps failing. "unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port"

Why is Kiali trying to port forward to evicted pods ?

**Workaround**
Remove all evicted pods from the system to get around this issue
`kubectl delete pod --all-namespaces --field-selector=status.phase==Failed`

**Debug Info**
Kiali Version:  1.44

**Comment by lucasponce** [comment] 2022-01-25 07:35
Right, good one.
I think is a bug, Kiali tries to connect to the pod proxy to check if it's properly synced with the control plane.
But in this case, is failing and it's causing a slowdown in the app.

Thanks for reporting, proxy query in evicted pods should be skipped to avoid this.

Question: do you have some reproducer to generate similar evicted pods as you're seeing, sometimes, having a good test helps us a lot to add a fix quickly.

Thanks again for reporting this.

**Comment by lucasponce** [comment] 2022-01-25 09:14
One question, is it possible that the cluster is under heavy pressure as well?

This message:

 "unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port"

means that Kiali can't access the istiod pod(s) to fetch registry information, the mechanism is due to a port-forward, but it's a connectivity problem after all, the kiali pod can't connect with the istiod pod.

I'm trying to reproduce it under a minikube cluster, but if you could help me to reproduce your environment I can investigate further.

Kiali only tries to connect to the evicted pod under a detail page (specifically under the Envoy details), so it seems that the istiod pod is just overloaded?

**Comment by sukrit007wawa** [comment] 2022-01-31 08:07
@lucasponce   I checked the IstioD Logs,  and could not see any relevant error.  In addition, in Kiali: https://github.com/kiali/kiali/blob/master/kubernetes/istio.go#L83 is masking off the actual error.   I know for sure that the error related to status code is not logged.  So status code < 400 . 

IMO https://github.com/kiali/kiali/blob/master/kubernetes/istio.go#L83  should include the underlying reason for failure as there could by "n" reasons on why kiali could not establish a connection to istiod.

Surprisingly,  when I deleted all evicted pods,  it started working.

**Comment by lucasponce** [comment] 2022-01-31 08:12
Thanks, @sukrit007wawa I'll keep looking at this issue. I'll try to replicate a test with evicted pods.

One question: do the "istiod" pods were also evicted? Or only pods living in the "data plane"? 

Lucas

**Comment by sukrit007wawa** [comment] 2022-02-03 08:32
> Thanks, @sukrit007wawa I'll keep looking at this issue. I'll try to replicate a test with evicted pods.
> 
> One question: do the "istiod" pods were also evicted? Or only pods living in the "data plane"?
> 
> Lucas

@lucasponce  Both istiod and data plane pods were evicted. I did check the code,  and do see a filtering logic to connect to pods that are still in Running status.

**Comment by lucasponce** [comment] 2022-02-03 08:36
> @lucasponce Both istiod and data plane pods were evicted. I did check the code, and do see a filtering logic to connect to pods that are still in Running status.

Ah, that's the main root cause then, ok, then we need to update the logic to warn/throw an error that Kiali can't connect when the istiod pods are evicted; it will try to connect to the only healthy pods.

It won't solve the problem but it will give more information to the user.

Thanks for the update.

**Comment by jmazzitelli** [comment] 2022-03-15 05:41
Could this be related to the mysterious https://github.com/kiali/kiali/issues/4679 ?

**Comment by lucasponce** [comment] 2022-03-17 11:06
It's probably, I'm going to prepare a patch for this.
It seems it's not detecting correctly when the pod is evicted and trying to connect, so the response will wait until the time-out expires.

**Comment by sukrit007wawa** [comment] 2022-04-05 17:41
Just ran into this problem again.  Is there any other info needed to remove waiting for external label ?    As usual,  after deleting istio evicted pods kiali started connecting to healthy ones.

**Comment by nrfox** [comment] 2022-04-05 19:16
Part of what might be causing this issue is having cached data. If Kiali is caching pods and a pod is evicted, Kiali may not see the update to the pod state if it gets the pod state from cache causing Kiali to see the pod state as running when it's actually terminated.

**Comment by lucasponce** [comment] 2022-04-06 09:14
The state should be updated as an event managed by the informer.
I think it's missing an expression in the "health" check to connect to the Istiod pod.

Sorry for the delay @sukrit007wawa we were busy with a couple of releases and I forgot to progress on this one.

**Comment by lucasponce** [comment] 2022-04-06 09:26
@sukrit007wawa I remembered why I put the "waiting external" label on this one.
Basically, I think that you are hitting the "soft eviction threshold" in your cluster, in other words, the evicted pod looks "running" until it recovers.

My patch wanted to check additionally the "Reason" on this logic:
![image](https://user-images.githubusercontent.com/1662329/161942796-6a376b2a-959a-47ff-ba42-ea7bac82ac21.png)

But I've read the documentation that an "evicted" pod should be marked as "Failed" so, no need to check the additional "Reason" field (finding some 'Evicted' message).

So, probably my patch won't help here as the initial phase wouldn't change.

I wonder if you can play more with the eviction strategy on your side, to make them fail sooner, then the state will be updated and Kiali will see that a pod is not "running" and it will skip it.

Let me know if that sounds ok to you.

If you are still having issues, give us more details and we'll check if we can progress with an additional condition in that code.

[1] https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#eviction-thresholds

**Comment by sukrit007wawa** [comment] 2022-04-10 05:05
@lucasponce  Thanks for the info. In our case pods are evicted because we are performing kubectl drain operation as part of AMI upgrade process to replace existing nodes.  https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/

**Comment by lucasponce** [comment] 2022-04-11 08:28
Thanks, @sukrit007wawa,

Perhaps if the admins of your cluster trigger this process, is safe to stop/start Kiali until the process is finished.

![image](https://user-images.githubusercontent.com/1662329/162696036-4f8e9145-7a20-463f-beed-8e97b026dfdd.png)

**Comment by lucasponce** [comment] 2022-04-11 09:01
I'm going to close this issue for now.
It's more an environmental issue rather than something that Kiali should check into the codebase.

We can discuss further/reopen it if we have new information that may help to improve this scenario.

**Closed** 2022-04-11 09:02 UTC
Labels: backlog, waiting external
