### ISSUE TITLE
Kiali Version 1.84 caused issue in Traffic graph 

### ISSUE THREAD

**Issue by preshit1505** [kiali/kiali#7349] opened 2024-05-08 18:55 UTC
### Describe the bug

We have recently upgraded the kiali version to 1.84 after I opened a [issue](https://github.com/kiali/kiali/issues/7220) of not able to see the trace details/span tab. But now we are seeing a different issue i.e. traffic graph is showing error "**Cannot load the graph: K8s Cache [bdrck-preview-ctrlpln] is not found or is not accessible for Kiali**" once we increasing the time duration in the tab.
<img width="1203" alt="image" src="https://github.com/kiali/kiali/assets/14802056/48af4a75-feaf-44d3-8654-424599cad428">

So we have two environments one is preview and other is Live. We have never experienced seeing this error before as in a live environment we do see preview env's istio NS graph and vice-versa.

### Expected Behavior
once we downgrade the version back to 1.81, i dont see the issue anymore.

<img width="1243" alt="image" src="https://github.com/kiali/kiali/assets/14802056/4d1d2291-e567-409d-9e62-409b1999f05f">
<img width="1188" alt="image" src="https://github.com/kiali/kiali/assets/14802056/f55c0d0b-9066-48c4-b8ea-bc95c9404e16">

Once we downgrade,

![image](https://github.com/kiali/kiali/assets/14802056/4fe92a5f-6f92-4753-bd15-5e40f346f448)
![image](https://github.com/kiali/kiali/assets/14802056/41baa6b3-2ef3-467d-870b-a7e978c05d49)
![image](https://github.com/kiali/kiali/assets/14802056/b5df91d6-6684-4efe-8beb-5b8b3c1d2e69)

### What are the steps to reproduce this bug?

1. Version upgrade to 1.84
2 increase the time duration to more than 2m in traffic graph tab

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: 1.84
- **Istio version: 1.20.3
- **Kubernetes impl:** 
- **Kubernetes version: v1.27.11-gke.1118000
- **Other notable environmental factors:**

**Comment by preshit1505** [comment] 2024-05-09 06:40
Error Seeing in the logs:

`{"level":"error","time":"2024-05-09T06:39:16Z","message":"cluster [bdrck-live-ctrlpln] is not found or is not accessible for Kiali: goroutine 17076262 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/kiali/kiali/handlers.handlePanic({0x254bab0, 0xc005bad278})\n\t/home/runner/work/kiali/kiali/handlers/graph.go:86 +0x1ad\npanic({0x1d3c140?, 0xc00b78dc80?})\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/panic.go:770 +0x132\ngithub.com/kiali/kiali/graph.CheckError(...)\n\t/home/runner/work/kiali/kiali/graph/util.go:38\ngithub.com/kiali/kiali/graph/telemetry/istio/appender.WorkloadEntryAppender.applyWorkloadEntries({{0xc009ba0670?, 0x1?}}, 0xc003cf7b90, 0xc003cf7a40, 0xc0095dbc68)\n\t/home/runner/work/kiali/kiali/graph/telemetry/istio/appender/workload_entry.go:62 +0x5a9\ngithub.com/kiali/kiali/graph/telemetry/istio/appender.WorkloadEntryAppender.AppendGraph({{0xc00981343a?, 0xc18739c51a6ae2aa?}}, 0xc003cf7b90, 0xc003cf7a40, 0xc0095dbc68)\n\t/home/runner/work/kiali/kiali/graph/telemetry/istio/appender/workload_entry.go:41 +0x96\ngithub.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap({_, _}, {0xc003cf7890, {0x0, {0xc00d575440, 0x6, 0x6}}, 0x0, 0x1, 0xc003cf7770, ...}, ...)\n\t/home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:80 +0x674\ngithub.com/kiali/kiali/graph/api.graphNamespacesIstio({_, _}, _, _, {{0x21f5871, 0x9}, {0x21efbd9, 0x5}, {{0xc00981347c, 0x15}, ...}, ...})\n\t/home/runner/work/kiali/kiali/graph/api/api.go:52 +0xf0\ngithub.com/kiali/kiali/graph/api.GraphNamespaces({_, _}, _, {{0x21f5871, 0x9}, {0x21efbd9, 0x5}, {{0xc00981347c, 0x15}, {0x13a52453c000, ...}}, ...})\n\t/home/runner/work/kiali/kiali/graph/api/api.go:33 +0x2f3\ngithub.com/kiali/kiali/handlers.GraphNamespaces({0x254bab0, 0xc005bad278}, 0xc00995b560)\n\t/home/runner/work/kiali/kiali/handlers/graph.go:51 +0x165\nnet/http.HandlerFunc.ServeHTTP(0x21ff85d?, {0x254bab0?, 0xc005bad278?}, 0x120?)\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166 +0x29\ngithub.com/kiali/kiali/routing.NewRouter.metricHandler.func6({0x25557c0, 0xc00d575200}, 0xc00995b560)\n\t/home/runner/work/kiali/kiali/routing/router.go:237 +0x11f\nnet/http.HandlerFunc.ServeHTTP(0xc00995aea0?, {0x25557c0?, 0xc00d575200?}, 0xc0032e9200?)\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166 +0x29\ngithub.com/kiali/kiali/routing.NewRouter.AuthenticationHandler.Handle.func7({0x25557c0, 0xc00d575200}, 0xc00995aea0)\n\t/home/runner/work/kiali/kiali/handlers/authentication.go:70 +0x31f\nnet/http.HandlerFunc.ServeHTTP(0xc00bdb8f40?, {0x25557c0?, 0xc00d575200?}, 0xc0013fde70?)\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166 +0x29\ngithub.com/kiali/kiali/server.plainHttpMiddleware.func1({0x25557c0?, 0xc00d575200?}, 0x0?)\n\t/home/runner/work/kiali/kiali/server/server.go:182 +0x5c\nnet/http.HandlerFunc.ServeHTTP(0x254ba20?, {0x25557c0?, 0xc00d575200?}, 0xc0040d2b40?)\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166 +0x29\ngo.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP({{0x21efc79, 0x5}, {0x253dd68, 0xc0004dabe0}, {0x254b1b0, 0xc0013dbb48}, {0x252eb40, 0xc005bad1a0}, 0x231ddf0, 0x0, ...}, ...)\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux@v0.47.0/mux.go:180 +0xbb2\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0093ec6c0, {0x254ba20, 0xc008438540}, 0xc00995a360)\n\t/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x25450c0, 0xc002257420}, 0xc00995a360)\n\t/home/runner/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x27e\nnet/http.HandlerFunc.ServeHTTP(0xc0035d0ea0?, {0x25450c0?, 0xc002257420?}, 0x6fc37a?)\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2166 +0x29\nnet/http.(*ServeMux).ServeHTTP(0x471639?, {0x25450c0, 0xc002257420}, 0xc00995a360)\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2683 +0x1ad\nnet/http.serverHandler.ServeHTTP({0xc003cf7200?}, {0x25450c0?, 0xc002257420?}, 0x6?)\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:3137 +0x8e\nnet/http.(*conn).serve(0xc00836cf30, {0x25576b0, 0xc006edecc0})\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:2039 +0x5e8\ncreated by net/http.(*Server).Serve in goroutine 1443\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/net/http/server.go:3285 +0x4b4\n"}`

**Comment by nrfox** [comment] 2024-05-09 10:23
This might actually be a duplicate of: https://github.com/kiali/kiali/issues/7305

**Comment by preshit1505** [comment] 2024-05-09 15:47
@nrfox yes Nick, seems like its a similar kind of error. Do we have any update on that then? Can we resolve this with any configuration change?

**Closed** 2024-05-22 20:03 UTC
Labels: bug
