### ISSUE TITLE
Kiali DR and VS warnings with update 

### ISSUE THREAD

**Issue by razorsk8jz** [kiali/kiali#4711] opened 2022-02-04 20:16 UTC
with the update of kiali - versions in screenshot - every DR and VS we have has a warning for an error on them 

![image](https://user-images.githubusercontent.com/12674178/152596917-c0b24103-8d7a-40d2-9625-f7e2eefaf9ed.png)

VS and DR both say there are more than one for the same host.  I also installed the bookinfo application in our cluster to verify on a smaller scale and we receive the same error 

![image](https://user-images.githubusercontent.com/12674178/152597109-0cc746fa-fc43-4026-864b-e6b9d467e143.png)
![image](https://user-images.githubusercontent.com/12674178/152597232-f7a9d4fb-3f78-43d4-b867-5bb07e085a6e.png)

if anyone has an idea of what may be going on - or if they could confirm this is a bug, it would be greatly appreciated.

**Comment by jshaughn** [comment] 2022-02-04 22:04
From which version did you update?

**Comment by razorsk8jz** [comment] 2022-02-04 22:29
I will have to look - I used the kiali-operator helm charts and went from chart version - 1.42.0 to 1.45.0

**Comment by israel-hdez** [comment] 2022-02-04 22:57
@razorsk8jz Perhaps read the explanation here: https://kiali.io/docs/features/validations/#kia1106---more-than-one-virtual-service-for-same-host and check if you are not, by chance, falling in the explained situation.

For some warnings, a sidebar at the right of the editor may list what are the involved CRDs.

**Comment by razorsk8jz** [comment] 2022-02-04 23:03
> @razorsk8jz Perhaps read the explanation here: https://kiali.io/docs/features/validations/#kia1106---more-than-one-virtual-service-for-same-host and check if you are, by chance, falling in the explained situation.
> 
> For some warnings, a sidebar at the right of the editor may list what are the involved CRDs.

i can confirm we only have one gateway - and only one vs / dr for each of our services coming from that gateway

**Comment by israel-hdez** [comment] 2022-02-04 23:31
> i can confirm we only have one gateway - and only one vs / dr for each of our services coming from that gateway

I think that's the underlying idea of that validation.
Anyway, its severity is "warning" not "error". So, IMO it's trying to tell that it's error prone.

In the screenshot of the bookinfo VS, I see you have `*` in the hosts attribute. If you have another VS, regardless of the `hosts` attribute, both definitions will be merged and behavior is undefined if there are conflicting `match` rules. So, if you have no conflicting rules, you can discard the warning. But remember to keep in mind the caveats mentioned here: https://istio.io/latest/docs/ops/best-practices/traffic-management/#split-virtual-services. Citing the Istio docs:

> When a second and subsequent VirtualService for an existing host is applied, istio-pilot will merge the additional route rules into the existing configuration of the host. There are, however, several caveats with this feature that must be considered carefully when using it.
> 1. Although the order of evaluation for rules in any given source VirtualService will be retained, the cross-resource order is UNDEFINED. In other words, there is no guaranteed order of evaluation for rules across the fragment configurations, so it will only have predictable behavior if there are no conflicting rules or order dependency between rules across fragments.
> 1. There should only be one “catch-all” rule (i.e., a rule without a match field) in the fragments. All such “catch-all” rules will be moved to the end of the list in the merged configuration, but since they catch all requests, whichever is applied first will essentially override and disable any others.
> 1. A VirtualService can only be fragmented this way if it is bound to a gateway. Host merging is not supported in sidecars.

The same applies for DestinationRules.

If these validations are noisy for your case, you can turn them off by adding the following to the Kiali CR:

```yaml
spec:
  kiali_feature_flags
    validations:
      ignore: ["KIA0201", "KIA1106"]
```

**Comment by razorsk8jz** [comment] 2022-02-05 00:06
I would rather not just ignore the warnings and i do understand that adding "*" to the host field will match everything and cause this warning to appear - That was only in there due to the demo bookinfo app i used all default yaml files istio provides.  We are not doing this in production and are still seeing the warnings.  

I have been going through the versions and i can say v1.44.0 did not have the issue but v1.45.0 did, i also tried to upgrade to v1.46.0 and the issue still persists.

So the change causing these errors was implemented from 1.44.0 to 1.45.0

**Comment by razorsk8jz** [comment] 2022-02-05 00:16
After looking at the patch notes - https://kiali.io/news/release-notes/#1450

they linked to https://github.com/kiali/kiali/pull/4654 which is what i think may be causing the issue

I still think this may be a bug as even cross namespace we are not setting any duplicate hosts in either the VS or DR that i can find

**Comment by israel-hdez** [comment] 2022-02-05 00:47
> they linked to #4654 which is what i think may be causing the issue


In #4654 I can see that in the screenshots, the sidebar has a "Validation references" header which list _the other_ VirtualService that is in conflict with the one in the editor. In case you have it, can you check it and be sure that they don't collide? If they don't, perhaps can you share how they are defined so that we can try it?

If the sidebar does not show any reference, I think it's less easy to replicate without a proper sample :-/ Right now I have a gateway but it does not have the warning. It's only one in the whole cluster. So, I'm not sure if that spurious warning may appear as soon as a second VS is created.

Anyway... it's Friday and the whole team has left. Si, I think we will check back on Monday. In the meantime, if you can provide the feedback I'm asking, it will be great.

**Comment by israel-hdez** [comment] 2022-02-05 00:50
Hmmm interestingly, in your screenshot of the DR, the sidebar has a reference to "self" :-/

**Comment by razorsk8jz** [comment] 2022-02-05 02:22
Hmm weird I see that now too.  I’ll look at all our services this weekend and confirm they all look like that and reference theirselves then I will get back to you.

**Comment by hhovsepy** [comment] 2022-02-07 08:43
@razorsk8jz thank you for your issue. We are checking that situation. We recently introduced cross-namespace validations functionality in Istio configurations, from Kiali v1.44 to v1.46 releases. Perhaps I missed some scenarios and introduced a regression.
Currently checking with several vanilla "bookinfo" namespaces installed on the same cluster, and could not find a Warning messages on Kiali v1.46 you have in screenshots.
I might need more information about VS and DRs you have in your environment to include it in our regression testsuite.

**Comment by razorsk8jz** [comment] 2022-02-08 14:41
Ok, please let me know what you need me to provide.  i do confirm the validations do seem to link to themselves

![image](https://user-images.githubusercontent.com/12674178/153006584-259d5b00-1750-4141-ab79-b9cde455bdc0.png)

I will also provide a sample DR with names changed but, this is an example of a DR / VS we run in production - 

`
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: sample-dr
  namespace: sample-ns
  labels:
    app: sample
spec:
  host: sample.sample-ns.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 500
      http:
        http1MaxPendingRequests: 1000
        maxRequestsPerConnection: 1
        idleTimeout: 3s
    outlierDetection:
      consecutiveGatewayErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 10
    tls:
      mode: ISTIO_MUTUAL
  exportTo:
    - .
`

`
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: sample-vs
  namespace: sample-ns
  labels:
    app: sample
spec:
  hosts:
    - sample.sample-ns.svc.cluster.local
  http:
    - route:
        - destination:
            host: sample.sample-ns.svc.cluster.local
            port:
              number: 80
      retries:
        attempts: 5
        perTryTimeout: 60s
        retryOn: 'connect-failure,refused-stream'
  exportTo:
    - .
`

TLS Policy

`
kind: PeerAuthentication
apiVersion: security.istio.io/v1beta1
metadata:
  name: sample-tls-policy
  namespace: sample-ns
  labels:
    app: sample
spec:
  selector:
    matchLabels:
      app: sample
  mtls:
    mode: STRICT
`

In our real environment we have approximately 50+ services which all look like the above - there are also several service entries since we do have meshConfig.outboundTrafficPolicy.mode set to REGISTRY_ONLY 

There is one entry point to our applications - this entry point has a Gatway

**Comment by hhovsepy** [comment] 2022-02-09 16:01
Thank you @razorsk8jz , I still cannot reproduce the issue with own reference, can you please tell me what configurations did you do on "bookinfo"?
![Screenshot from 2022-02-09 17-01-45](https://user-images.githubusercontent.com/604313/153239765-303e3b20-ddd4-4139-ac3a-0e0ed14e451d.png)

**Comment by razorsk8jz** [comment] 2022-02-09 16:59
> Thank you @razorsk8jz , I still cannot reproduce the issue with own reference, can you please tell me what configurations did you do on "bookinfo"? ![Screenshot from 2022-02-09 17-01-45](https://user-images.githubusercontent.com/604313/153239765-303e3b20-ddd4-4139-ac3a-0e0ed14e451d.png)

@hhovsepy i did the basic standard install as stated in the docs - i did use the bookinfo with mtls - installed using directions here https://istio.io/latest/docs/examples/bookinfo/

Maybe it has something to do with our istio install? Used istioOperator and can post that if we think that may be an issue

**Comment by hhovsepy** [comment] 2022-02-28 08:54
Hi @razorsk8jz, can you please check if you still see the warning for the released Kiali v1.47 ?

**Comment by razorsk8jz** [comment] 2022-02-28 19:19
ok so after upgrading its actually worse i think - 
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/12674178/156044384-6cd184b7-4d19-4f52-8c34-7f2ff11802f5.png">

the same errors exist on our Destination Rules and Virtual Services however now we have an actual error on our PeerAuthentication objects here is an example of one of the errors and it appears to also be validating against itself

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/12674178/156045005-c59be04d-1645-42fe-8607-c68fa5d368f2.png">

**Comment by lucasponce** [comment] 2022-03-01 07:35
@razorsk8jz thanks for the update.
We are having issues reproducing the problem you are experimenting with.
I have a side question, perhaps it can help @hhovsepy with the scenario, how many istiod pods do you have in the control plane.

I wonder if there is a bug when there is more than one replica and perhaps this is the reason we are failing to get the same result.

**Comment by lucasponce** [comment] 2022-03-01 08:49
@razorsk8jz I'm having the same problems as @hhovsepy reported to reproduce your issue.

In the last screenshot you attached, I have the same result:

![image](https://user-images.githubusercontent.com/1662329/156135775-5ac0ce88-6932-4c6a-aa32-e26434194299.png)

But it's an expected result as I have a duplicate PA:
![image](https://user-images.githubusercontent.com/1662329/156135863-db7efe11-e202-4b9d-a3f9-50e04d35c7a4.png)

Could you help us to reproduce the same problem from a clean cluster? (i.e. minikube or kind)

That would help us to progress, I have the feeling that there is something we are not considering here (perhaps related to your env, or just us that we are not considering a valid scenario in Istio, and Kiali is marking it as an error).

Thank you very much.
Lucas

**Comment by razorsk8jz** [comment] 2022-03-01 13:29
> @razorsk8jz I'm having the same problems as @hhovsepy reported to reproduce your issue.
> 
> In the last screenshot you attached, I have the same result:
> 
> ![image](https://user-images.githubusercontent.com/1662329/156135775-5ac0ce88-6932-4c6a-aa32-e26434194299.png)
> 
> But it's an expected result as I have a duplicate PA: ![image](https://user-images.githubusercontent.com/1662329/156135863-db7efe11-e202-4b9d-a3f9-50e04d35c7a4.png)
> 
> Could you help us to reproduce the same problem from a clean cluster? (i.e. minikube or kind)
> 
> That would help us to progress, I have the feeling that there is something we are not considering here (perhaps related to your env, or just us that we are not considering a valid scenario in Istio, and Kiali is marking it as an error).
> 
> Thank you very much. Lucas
> 
> P.S.: I'm testing with the master branch that will be the base of the next 1.48 release.
 ^ This is it!! I redeployed istio and scaled down istiod to only a single pod and the issue went away! As soon as i redeployed istio and had istio's hpa scaled back to a minimum of 3 all issue reappeared.

**Comment by lucasponce** [comment] 2022-03-01 13:34
> ^ This is it!! I redeployed istio and scaled down istiod to only a single pod and the issue went away! As soon as i redeployed istio and had istio's hpa scaled back to a minimum of 3 all issues reappeared.

Ah, I had a suspicion that could be impacted, it seems the logic of the registry has a bug when there are more than a single pod.
We need to review this.
Thanks for helping us to spot the issue.

@hhovsepy I can take a look at this logic, as probably I introduced this bug :), let me know.

**Comment by hhovsepy** [comment] 2022-03-02 06:27
I can reproduce the problem now, the IstioConfig.GetIstioConfigList returns configs multiplied by istiod pods, (same in GetServiceList). So they need to unique filter the results.

**Comment by hhovsepy** [comment] 2022-03-04 14:51
@jshaughn  I think it is risky to backport this fix into older branches, as we did changes in registry usage and in validations in v1.46 and mostly in v1.47 releases. There had been several improvements and optimizations done.
So the recommendation would be to upgrade to upcoming v1.48 release.

**Closed by hhovsepy** 2022-03-04 14:51 UTC
Labels: bug
