### ISSUE TITLE
Both grafana and jaeger urls in configmap are broken

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2157] opened 2020-01-27 14:16 UTC
**General remarks**

grafana and jaeger urls are broken:

```
oc edit configmap kiali -n istio-system
```
![Screenshot (1)](https://user-images.githubusercontent.com/613814/73181442-8171e600-4117-11ea-97bf-01e9b3b30b37.jpg)

About modal:
![Screenshot of Kiali  istio-system  (15)](https://user-images.githubusercontent.com/613814/73181617-da417e80-4117-11ea-87ba-dfaaa2c109d4.jpg)

Steps to reproduce it:

I have installed kiali using the following:
```bash
./aws-openshift.sh sm-install
make build container-build cluster-push operator-create kiali-create 
```

**Comment by xeviknal** [comment] 2020-01-27 15:01
@jmazzitelli I assigned to you because I think is connected with the operator. I am taking a look also here. un-assign it if its not, please.

**Comment by aljesusg** [comment] 2020-01-27 15:49
Verified, the same behaviour

**Comment by jotak** [comment] 2020-01-27 17:11
@xeviknal @aljesusg the missing part seems to come from that ROUTER_HOSTNAME: https://github.com/kiali/kiali/blob/master/make/Makefile.operator.mk#L78

Can you run the related commands separately and see what it gives?
(Something like `oc get routes -n istio-system -o name 2>/dev/null || echo 'noroute' | head -n 1` and the whole one `oc get `oc get routes -n istio-system -o name 2>/dev/null || echo 'noroute' | head -n 1` -n istio-system -o jsonpath='{.status.ingress[0].routerCanonicalHostname}' 2>/dev/null` if I read correctly)

**Comment by jmazzitelli** [comment] 2020-01-28 02:40
It is definitely because ROUTER_HOSTNAME is empty. I see this, too. The makefile output that shows the problem is:

```
Deploy Kiali using the settings found in /home/jmazzite/source/kiali/kiali/src/github.com/kiali/kiali/operator/deploy/kiali/kiali_cr_dev_servicemesh.yaml
cat /home/jmazzite/source/kiali/kiali/src/github.com/kiali/kiali/operator/deploy/kiali/kiali_cr_dev_servicemesh.yaml | \
ACCESSIBLE_NAMESPACES="**" \
AUTH_STRATEGY="openshift" \
KIALI_EXTERNAL_SERVICES_PASSWORD="..." \
KIALI_IMAGE_NAME="image-registry.openshift-image-registry.svc:5000/kiali/kiali" \
KIALI_IMAGE_PULL_POLICY="Always" \
KIALI_IMAGE_VERSION="dev" \
NAMESPACE="istio-system" \
ROUTER_HOSTNAME="" \
...
```

And in that [kiali_cr_dev_servicemesh.yaml](https://github.com/kiali/kiali/blob/v1.12/operator/deploy/kiali/kiali_cr_dev_servicemesh.yaml#L29) template file (used only for our dev environment/makefile): 

```
      url: https://grafana-${NAMESPACE}.${ROUTER_HOSTNAME}
...
      url: https://jaeger-${NAMESPACE}.${ROUTER_HOSTNAME}
```

So we need to find out why ROUTER_HOSTNAME is empty string in the dev environment. The [make/Makefile.operator.mk](https://github.com/kiali/kiali/blob/master/make/Makefile.operator.mk#L78
) file defines ROUTER_HOSTNAME as:

```
ROUTER_HOSTNAME="$(shell ${OC} get $(shell ${OC} get routes -n ${NAMESPACE} -o name 2>/dev/null || echo 'noroute' | head -n 1) -n ${NAMESPACE} -o jsonpath='{.status.ingress[0].routerCanonicalHostname}' 2>/dev/null)" \
```

**Comment by jmazzitelli** [comment] 2020-01-28 02:47
Something is just wrong with the syntax of that command in the makefile. If I run this, I get the results I want:

```
$ oc get $(oc get routes -n istio-system -o name | head -n 1) -n istio-system -o jsonpath='{.status.ingress[0].routerCanonicalHostname}'
apps.my.cluster.openshift.com
```

I'll figure out the correct syntax for embedding in the makefile

**Comment by jmazzitelli** [comment] 2020-01-28 02:58
this is fixed in PR https://github.com/kiali/kiali/pull/2161

**Comment by jmazzitelli** [comment] 2020-01-28 03:01
BTW: this is just a problem in the makefile - so it isn't really a blocker since it only affects the dev environment and only if you use the default behavior of `kiali-create` make target. You can always create your own Kiali CR and pass it to make via the env var "KIALI_CR_FILE" to work around the problem

**Closed** 2020-01-28 10:23 UTC
Labels: backlog, blocker, bug
