### ISSUE TITLE
[CI] Test flake - workload logs

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6494] opened 2023-08-17 19:52 UTC
Workload logs frontend test is failing. Screenshot shows there's no logs for the time period.

https://github.com/kiali/kiali/actions/runs/5894470126/job/15988439799

![Workload logs tab -- The log pane of the logs tab should show spans (failed)](https://github.com/kiali/kiali/assets/6226732/1c0de24d-e962-4707-966c-12d143d3b375)

The test should probably verify that there are indeed logs for the time period, maybe by querying the kube api and then comparing that to the kiali response?

**Comment by jshaughn** [comment] 2023-08-31 20:40
looking at the screenshot I think the issue is that neither of log-source boxes are checked, so we're not pulling any logs.  The question is why are those both unchecked.

**Comment by jshaughn** [comment] 2023-10-25 13:40
This does not seem to be a problem right now, closing.

**Closed by jshaughn** 2023-10-25 13:40 UTC
Labels: bug, backlog
