### ISSUE TITLE
"Error trying to get OAuth metadata"

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#1953] opened 2019-11-19 13:18 UTC
After leaving Kiali idle overnight, twice now the following error has occured.
    "Error trying to get OAuth metadata"

OCP version: 4.3.0-0.nightly-2019-11-07-062654

Kiali pod log:
I1118 19:43:47.678546 1 kiali.go:66] Kiali: Version: v1.10.0-SNAPSHOT, Commit: 220ceb40f803f2d5a903ffb072d769c9628da77d I1118 19:43:47.679029 1 kiali.go:210] Using authentication strategy [openshift] I1118 19:43:47.679058 1 kiali.go:87] Kiali: Console version: 1.10.0-snapshot.1-local-a29de569f402b7e21f9f35b4594a4e23cd32a61c I1118 19:43:47.759300 1 server.go:57] Server endpoint will start at [:20001/] I1118 19:43:47.759316 1 server.go:58] Server endpoint will serve static content from [/opt/kiali/console] I1118 19:43:47.759332 1 metrics_server.go:18] Starting Metrics Server on [:9090] I1118 19:43:47.759436 1 server.go:63] Server endpoint will require https E1118 20:02:40.410752 1 jaeger.go:27] Get https://jaeger-query.istio-system.svc/api/services: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) W1118 20:05:53.577506 1 authentication.go:229] Token error: could not get info from Openshift: the server has asked for the client to provide credentials E1118 21:46:31.832477 1 jaeger.go:27] Get https://jaeger-query.istio-system.svc/api/services: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by FilipB** [comment] 2019-11-19 13:35
Also noticed this in OCP 4.1.23. I don't see any error in kiali pod log.
I noticed it on kiali instance which was installed 7 hours ago. Automation run fine on that cluster but  several hours afterwards the issue appeared. I'm not sure when exactly.

**Comment by jshaughn** [comment] 2019-11-19 14:18
It smells like some kind of timeout but hard to know because we are not reporting the error message.  I'm going to generate a PR to improve error reporting here, as a start to investigate.

**Comment by jshaughn** [comment] 2019-11-19 18:06
@mattmahoneyrh @FilipB The PR is merged, if convenient try master to see if we can maybe get a better error report.

**Comment by jshaughn** [comment] 2019-11-19 18:41
I see a variety of "e is null" hits for FF on the web, not for chrome/webkit.  This may be limited to FF, although I can't get it to happen anywhere.

**Comment by FilipB** [comment] 2019-11-20 08:51
Tried both FF and chrome (also incognito mode) with the same result:
{"error":"Error trying to get OAuth metadata","detail":"Get https://172.30.0.1:443/version?timeout=32s: http2: no cached connection was available"}

**Comment by FilipB** [comment] 2019-11-20 09:33
It works fine again after kiali pod restart

**Comment by mattmahoneyrh** [comment] 2019-11-20 14:34
Same result as @filipb:   {"error":"Error trying to get OAuth metadata","detail":"Get https://172.30.0.1:443/version?timeout=32s: http2: no cached connection was available"}

**Comment by jshaughn** [comment] 2019-11-20 14:38
OK, thanks for the update, at least we have a little bit of detail now and can see the underlying error.  I don't know what to do about it :)  But maybe our connection has expired and we need to refresh it, or something like that.

**Comment by israel-hdez** [comment] 2019-11-21 20:52
@mattmahoneyrh @FilipB can I know where are you pulling the Kiali image from?
are you building locally and, then, deploying? or perhaps fetching the latest tag from quay/dockerhub?

**Comment by FilipB** [comment] 2019-11-22 09:51
@israel-hdez We are building the latest master locally, pushing it to https://quay.io/organization/kiali-qe and pulling from there.

I need to double check but it seems the issue is gone. I did not see it this morning with the latest master.

**Comment by israel-hdez** [comment] 2019-11-22 14:39
@FilipB What's the go version you are using for building?
That error message is associated with a bug in go, which had a regression and was recently fixed (again). But I don't know which versions are affected, so I want to try your version.

**Comment by FilipB** [comment] 2019-11-25 09:09
go version go1.13.4 linux/amd64
+ yarn -version
1.19.1
+ node --version
v10.17.0

**Comment by mattmahoneyrh** [comment] 2019-11-25 12:46
@israel-hdez v1.10.0 did not show the OAUTH error after being left idle over a weekend time-period.

**Comment by israel-hdez** [comment] 2019-11-25 18:45
I can replicate using go 1.13.4.

**Comment by israel-hdez** [comment] 2019-11-25 18:48
Applying this patch helps to replicate the issue very quickly (in a few minutes):

```diff
diff --git a/kubernetes/client_factory.go b/kubernetes/client_factory.go
index a8edc883..fbcc7732 100644
--- a/kubernetes/client_factory.go
+++ b/kubernetes/client_factory.go
@@ -1,6 +1,7 @@
 package kubernetes
 
 import (
+	"net/http"
 	"sync"
 	"time"
 
@@ -50,6 +51,14 @@ func GetClientFactory() (ClientFactory, error) {
 			TLSClientConfig: config.TLSClientConfig,
 			QPS:             config.QPS,
 			Burst:           config.Burst,
+			WrapTransport:   func(rt http.RoundTripper) http.RoundTripper {
+				tripper := rt.(*http.Transport)
+				tripper.MaxIdleConnsPerHost = 1
+				tripper.MaxConnsPerHost = 1
+				tripper.IdleConnTimeout = time.Duration(1) * time.Second
+
+				return tripper
+			},
 		}
 
 		return getClientFactory(&istioConfig, expirationTime)

```

**Comment by jshaughn** [comment] 2019-11-25 19:46
Interesting.

**Comment by israel-hdez** [comment] 2019-11-25 20:39
Looks like this issue is a compatibility issue of go1.13 and k8s client.

**Comment by israel-hdez** [comment] 2019-11-25 20:48
Related golang issue: https://github.com/golang/go/issues/34498

**Closed** 2019-11-27 20:19 UTC
Labels: backlog, bug, team/saturn
