### ISSUE TITLE
Kiali-operator installed view-only kiali has permissions issue on namespaces causing the graph to break

### ISSUE THREAD

**Issue by Crayeth** [kiali/kiali#3317] opened 2020-10-13 15:09 UTC
**Describe the bug**
Kiali goes back and forth between showing the graph and breaking over a permissions issue:
`namespaces is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list resource "namespaces" in API group "" at the cluster scope`

![image](https://user-images.githubusercontent.com/13447761/95876262-28b0af00-0d73-11eb-8037-3f0a3c8ae45a.png)

**Versions used**
Kiali: 1.25.0
Istio: 1.7.3
Kubernetes flavour and version: AKS 1.18.8

**To Reproduce**
1. install Kiali-operator using the helm chart

```yaml
values:
  clusterRoleCreator: true
  cr:
    namespace: istio-system
    name: kiali
    create: true
    spec:
      istio_namespace: istio-system
      auth:
        strategy: "anonymous"
      deployment:
        view_only_mode: "true"
        accessible_namespaces:
          - '**'
        image_name: "quay.io/kiali/kiali"
        image_pull_policy: "IfNotPresent"
        image_version: "v1.25.0"
        ingress_enabled: false
        namespace: "istio-system"
```

2. go to Kiali UI and click on graph, wait a little while. Graph will switch between showing and breaking, posting messages to message center.

**Expected behavior**
In docs it says that a view-only kiali should get a kiali-viewer clusterrole but that isn't created in my cluster. Whenever I do a `kubectl auth can-i list namespaces --as system:serviceaccount:istio-system:kiali-service-account --all-namespaces` it returns **yes** so I expect it to work. However, the graph breaks and I get those error messages in message center.

**Comment by jmazzitelli** [comment] 2020-10-14 12:23
I just saw a similar error.

Here are the replication steps.

Create a CR file as described in the OP:

`/tmp/kiali-helm-values.yaml`:
```yaml
clusterRoleCreator: true
cr:
  namespace: istio-system
  name: kiali
  create: true
  spec:
    istio_namespace: istio-system
    auth:
      strategy: "anonymous"
    deployment:
      view_only_mode: "true"
      accessible_namespaces:
        - '**'
      image_name: "quay.io/kiali/kiali"
      image_pull_policy: "IfNotPresent"
      image_version: "v1.25.0"
      ingress_enabled: false
      namespace: "istio-system"
```

Install Kiali Operator via helm:

```
helm install -f /tmp/kiali-helm-values.yaml --namespace kiali-operator --repo https://kiali.org/helm-charts kiali-operator kiali-operator
```

I then get the Kiali endpoint via a kubectl port-forward and point my browser to the Kiali URL. Click around. I went to an Application page and got this error:

```
namespaces "istio-system" is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot get resource "namespaces" in API group "" in the namespace "istio-system"
```

But I only see it some times! I keep clicking around and I don't get this error all the time it seems. Here's another one as it fetches the mTLS status:

```
Error fetching Mesh-wide mTLS status : namespaces is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list resource "namespaces" in API group "" at the cluster scope
```

Looks like we are missing a permission - not sure why this is only showing up now.

**Comment by jmazzitelli** [comment] 2020-10-14 12:30
I also just saw this:

```
Could not fetch Istio Config.
envoyfilters.networking.istio.io is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list resource "envoyfilters" in API group "networking.istio.io" in the namespace "istio-system"
```

**Comment by jmazzitelli** [comment] 2020-10-14 12:47
Just saw this in the kiali logs - more missing permissions - this is very odd:

```
E1014 12:46:09.517969       1 services.go:314] Error fetching Endpoints  namespace istio-system and service grafana: endpoints "grafana" is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot get resource "endpoints" in API group "" in the namespace "istio-system"
E1014 12:46:09.517969       1 services.go:304] Error fetching definition for service [istio-system:grafana]: services "grafana" is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot get resource "services" in API group "" in the namespace "istio-system"
E1014 12:46:09.520514       1 errors.go:21] endpoints "grafana" is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot get resource "endpoints" in API group "" in the namespace "istio-system"
E1014 12:46:53.164808       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190820062731-7e43eff7c80a+incompatible/tools/cache/reflector.go:94: Failed to list *kubernetes.GenericIstioObject: requestauthentications.security.istio.io is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list resource "requestauthentications" in API group "security.istio.io" in the namespace "istio-system"
```

**Comment by jmazzitelli** [comment] 2020-10-14 13:00
I turned off view_only_mode and I still see some of these errors. I thought it might have something to do with that, but it does not look related. I'll have to review the roles that are created by the helm chart compared to our OLM set up - my first thought is we just forgot to update the helm chart roles.

**Comment by jmazzitelli** [comment] 2020-10-14 13:35
I'm also seeing this when I install 1.24.0 (passing `--version="1.24.0"` to helm)

**Comment by jmazzitelli** [comment] 2020-10-14 13:43
I just went back to installing v1.25 but this time, starting clean (completely uninstalling everything first), I installed with view_only_mode disabled (which is the default) and I am not seeing the errors. So I think this is related to that feature.

The workaround to avoid seeing the errors is (for now) to disable view_only_mode (`view_only_mode: false`).

I am looking to see what differences we have in the view only roles compared to the others.

**Comment by Crayeth** [comment] 2020-10-14 13:50
I'm giving Kiali to teams in a multi-tenant cluster for observability, so I'm banking on view-only mode to make sure they cannot mess with the mesh config. Would be nice to see it fixed.

The weird thing is that if it is a permission issue, I expect it to either work, or not work, and not work sometimes as seems the case right now :/

Are you getting the kiali-viewer clusterrole as described in the [docs](https://kiali.io/documentation/latest/configuration/rbac/#_privileges_required_for_kiali_to_work_correctly)? Because I'm only getting Kiali and Kiali-operator. Maybe something changed there.

**Comment by jmazzitelli** [comment] 2020-10-14 14:08
fwiw: if you want multi-tenancy, it might be better to use `--accessible-namespaces` with only the namespaces in the tenant. That way your multiple Kialis for the multiple tenants aren't given access greater than they need. But that's a completely separate issue. If on OpenShift, Maistra will provide even better multi-tenancy support.

**Comment by jmazzitelli** [comment] 2020-10-14 14:21
> Are you getting the kiali-viewer clusterrole as described in the [docs](https://kiali.io/documentation/latest/configuration/rbac/#_privileges_required_for_kiali_to_work_correctly)? Because I'm only getting Kiali and Kiali-operator. Maybe something changed there.

```
$ kubectl get clusterrole -l app=kiali 
NAME           CREATED AT
kiali-viewer   2020-10-14T14:10:58Z
```

**Comment by Crayeth** [comment] 2020-10-14 14:25
> > Are you getting the kiali-viewer clusterrole as described in the [docs](https://kiali.io/documentation/latest/configuration/rbac/#_privileges_required_for_kiali_to_work_correctly)? Because I'm only getting Kiali and Kiali-operator. Maybe something changed there.
> 
> ```
> $ kubectl get clusterrole -l app=kiali 
> NAME           CREATED AT
> kiali-viewer   2020-10-14T14:10:58Z
> ```

```
% kubectl get clusterrole -l app=kiali
NAME    CREATED AT
kiali   2020-10-14T13:24:07Z
```
interesting, but at least you're also getting the errors so this might not be the cause.

**Comment by jmazzitelli** [comment] 2020-10-14 14:30
@Crayeth can you do this:

```
kubectl get kiali kiali -n istio-system -o jsonpath={.status}
```

If you see "reason: Running" - run that command again after about 60 seconds and see if you still see "Running"... then try it again... if you continually see it Running, let me know.

**Comment by Crayeth** [comment] 2020-10-14 14:56
@jmazzitelli seems like it keeps Running:
```
~ % kubectl get kiali kiali -n istio-system -o jsonpath={.status}
{"accessibleNamespaces":["**"],"conditions":[{"lastTransitionTime":"2020-10-14T14:39:38Z","message":"Running reconciliation","reason":"Running","status":"False","type":"Running"},{"ansibleResult":{"changed":0,"completion":"2020-10-14T14:39:54.032166","failures":1,"ok":32,"skipped":30},"lastTransitionTime":"2020-10-14T14:39:54Z","message":"Status code was -1 and not [200]: Request failed: \u003curlopen error [Errno -2] Name or service not known\u003e","reason":"Failed","status":"True","type":"Failure"}]}%
~ % kubectl get kiali kiali -n istio-system -o jsonpath={.status}
{"accessibleNamespaces":["**"],"conditions":[{"lastTransitionTime":"2020-10-14T14:39:38Z","message":"Running reconciliation","reason":"Running","status":"False","type":"Running"},{"ansibleResult":{"changed":0,"completion":"2020-10-14T14:39:54.032166","failures":1,"ok":32,"skipped":30},"lastTransitionTime":"2020-10-14T14:39:54Z","message":"Status code was -1 and not [200]: Request failed: \u003curlopen error [Errno -2] Name or service not known\u003e","reason":"Failed","status":"True","type":"Failure"}]}%     
```

**Comment by jmazzitelli** [comment] 2020-10-14 15:09
> "Status code was -1 and not [200]: Request failed: \u003curlopen error [Errno -2] Name or service not known\u003e

@Crayeth this is something I do not see - looks like you are truly getting an error in the operator and that is why it keeps trying. You should look in the kiali-operator logs and find more error messages that can help diagnose your issue. I don't see that myself (which might be why I get the kiali-viewer role and you do not).

**Comment by jmazzitelli** [comment] 2020-10-14 15:32
This is definitely caused by the view_only_mode flag. Didn't see a problem until I set that to `true`. Once true, my operator is continually running a reconciliation loop - changing resources which is causing it to run again due to the dependent resource watching. Until we figure this out, workaround is to not set view_only_mode.

**Comment by jmazzitelli** [comment] 2020-10-14 19:43
I'm baffled. I only see it when I FIRST install with view_only_mode: true. But thereafter, I can delete the Kiali CR, re-create it without specifying view_only_mode, and I see the reconciliation infinitely loop. It is as if the first time you set view_only_mode to true, the operator goes bonkers. I don't know what is special about view_only_mode. I'm going to keep looking to see if it really is specific to that setting or if there is something else going on here.

**Comment by jmazzitelli** [comment] 2020-10-14 19:56
I think I see it. I think I need to implement this asap: https://github.com/kiali/kiali/issues/3241
I believe this is all because of the hack we had to implement because of [this](https://github.com/ansible-collections/community.kubernetes/issues/234).

I'm not 100% sure, but all indications are this is it. Because when I look at the operator logs, I see 4 tasks ending with `"changed": true` and the play recap shows `ok=81   changed=4    unreachable=0    failed=0    skipped=81   rescued=0    ignored=0` and when changed is > 0 a reconciliation loop will happen again. Those 4 tasks are the hack that need to create then delete dummy resources. This PR introduced that: https://github.com/kiali/kiali-operator/pull/137

**Comment by jmazzitelli** [comment] 2020-10-14 22:25
I think this will fix it at least temporarily: https://github.com/kiali/kiali-operator/pull/164

**Comment by jmazzitelli** [comment] 2020-10-15 03:30
Oh, BTW, this has nothing to do with view_only_mode (which is what I thought I was seeing earlier).

The true workaround would be to NOT use "deployment.accessible_namespaces" set to `[**]` but instead populate it with the list of namespaces within the mesh (you can use regular expressions in this list of namespaces).

**Comment by jmazzitelli** [comment] 2020-10-15 04:01
I expect when issue https://github.com/kiali/kiali/issues/3323 is implemented, this problem will go away.

**Comment by Crayeth** [comment] 2020-10-15 07:14
Nice work investigating. In the mean time I'll just list out the namespaces and see if the problem goes away when I do. Thanks.

**Comment by jmazzitelli** [comment] 2020-10-15 13:29
FYI: I see this in the operator logs - if this keeps happening, it explains things, too (ultimately the root cause is that dependent resource watching feature - so its all interrelated): (note: "changed": true is the giveaway - this is always getting changed every reconciliation loop)

```
TASK [default/kiali-deploy : Delete unused Kiali cluster roles] ****************
changed: [localhost] => (item=
{
  "apiVersion": "rbac.authorization.k8s.io/v1",
  "kind": "ClusterRoleBinding",
  "metadata": {
    "annotations": {
      "operator-sdk/primary-resource": "istio-system/kiali",
      "operator-sdk/primary-resource-type": "Kiali.kiali.io"
    },
    "creationTimestamp": "2020-10-15T13:11:19Z",
    "labels": {
      "app": "kiali",
      "version": "v1.25.0"
    },
...
    "name": "kiali",
    "resourceVersion": "503002",
    "selfLink": "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/kiali",
    "uid": "774b31d6-9e2d-41ce-a207-1b89495e10ec"
  },
  "roleRef": {
    "apiGroup": "rbac.authorization.k8s.io",
    "kind": "ClusterRole",
    "name": "kiali"
  },
  "subjects": [
    {
      "kind": "ServiceAccount",
      "name": "kiali-service-account",
      "namespace": "istio-system"
    }
  ]
}
=> {"ansible_loop_var": "k8s_item", "attempts": 1, "changed": true, "k8s_item": 
{
  "apiVersion": "rbac.authorization.k8s.io/v1",
  "kind": "ClusterRoleBinding",
  "metadata": {
    "annotations": {
      "operator-sdk/primary-resource": "istio-system/kiali",
      "operator-sdk/primary-resource-type": "Kiali.kiali.io"
    },
    "creationTimestamp": "2020-10-15T13:11:19Z",
    "labels": {
      "app": "kiali",
      "version": "v1.25.0"
    },
...
    "name": "kiali",
    "resourceVersion": "503002",
    "selfLink": "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/kiali",
    "uid": "774b31d6-9e2d-41ce-a207-1b89495e10ec"
  },
  "roleRef": {
    "apiGroup": "rbac.authorization.k8s.io",
    "kind": "ClusterRole",
    "name": "kiali"
  },
  "subjects": [
    {
      "kind": "ServiceAccount",
      "name": "kiali-service-account",
      "namespace": "istio-system"
    }
  ]
} , "method": "delete", "result": {"apiVersion": "v1", "details": {"group": "rbac.authorization.k8s.io", "kind": "clusterrolebindings", "name": "kiali", "uid": "774b31d6-9e2d-41ce-a207-1b89495e10ec"}, "kind": "Status", "metadata": {}, "status": "Success"}}
```

If we re-enable dependent resource watching, I need to find out why this is happening.

**Comment by jmazzitelli** [comment] 2020-10-15 13:43
> If we re-enable dependent resource watching, I need to find out why this is happening.

For some reason, this is always running, I do not know why - this is causing the delete of resources I mentioned in the last commit (this is in the `tasks/main.yml`)
```
- name: Delete Kiali cluster roles if view_only_mode is changing since role bindings are immutable
  include_tasks: remove-clusterroles.yml
  when:
  - current_view_only_mode is defined
  - current_view_only_mode != kiali_vars.deployment.view_only_mode
  - current_accessible_namespaces is defined
  - '"**" in current_accessible_namespaces'
```

**Comment by jmazzitelli** [comment] 2020-10-15 14:09
@Crayeth I think I found one problem in your Kiali CR that I think will help (though you may need the other fixes coming - there was a couple problems here all conspiring against us).

```
    view_only_mode: "true"
```

That should be a boolean, not a string. So it should be:

```
    view_only_mode: true
```

Try that AND with accessible_namespaces not set to `[**]` and see what happens. You should delete your Kiali CR entirely first - wait for the operator to completely purge/uninstall that Kiali instance - and then create a new Kiali CR with that setting as a boolean (no quotes) and see what happens. I'm not convinced this will fix everything - but I'm testing over here and it worked for me (though I have additional fixes that may or may not be related).

BTW: I think this is why I was waffling back and forth with the view_only_mode setting - because in some of my tests I was entering a boolean, but other tests I was just using your CR example and changing its value, leaving it as a string - and I wasn't paying attention to the difference.

One day we'll put a schema on this CRD :)

**Comment by Crayeth** [comment] 2020-10-15 14:13
> @Crayeth I think I found one problem in your Kiali CR that I think will help (though you may need the other fixes coming - there was a couple problems here all conspiring against us).
> 
> ```
>     view_only_mode: "true"
> ```
> 
> That should be a boolean, not a string. So it should be:
> 
> ```
>     view_only_mode: true
> ```

Oh man I was wondering if that could be related. I'm going to try that out now.

**Comment by jmazzitelli** [comment] 2020-10-15 14:42
@Crayeth and this is also why you were seeing "kiali" role not "kiali-viewer" role: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/kubernetes/k8s-main.yml#L9

I'll have to make some truthy checks to avoid this kind of thing.

**Comment by jmazzitelli** [comment] 2020-10-16 14:14
A few PRs have been merged that should address the issue reported here. The fixes will be in the next release.

Until that release is available, the workaround should be:

1. Make sure you use booleans (not strings) where appropriate
    (`view_only_mode: true` ...do NOT use `view_only_mode: "true"`).
2. Do not use `deployment.accessible_namespaces: ['**']`

**Comment by jmazzitelli** [comment] 2020-11-02 15:01
I believe this issues have been addressed in the latest release. I would suggest opening a new github issue if more problems arise - this github issue has a lot of noise to sift through (mainly due to my ramblings) :)

**Closed by jmazzitelli** 2020-11-02 15:01 UTC
Labels: bug
