### ISSUE TITLE
Unable to delete host in Sidecar

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#4753] opened 2022-02-23 16:35 UTC
Happens in Kiali master.

Edit Sidecar via YAML editor.
Try to delete a host from egress hosts.
Error is shoown "Sidecar.networking.istio.io "productpage-v1" is invalid: spec.egress.hosts: Invalid value: "null": spec.egress.hosts in body must be of type string: "null""
![Screenshot from 2022-02-23 17-34-53](https://user-images.githubusercontent.com/604313/155364059-feb8f293-15b6-4cfd-a7e5-005878f54aa2.png)

**Comment by jshaughn** [comment] 2022-03-10 20:20
@hhovsepy I could not reproduce this, perhaps it was resolved via a different fix?  Perhaps you could try again to reproduce?

**Comment by hhovsepy** [comment] 2022-03-11 07:00
Still can reproduce, on this one:

`apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: dupliacate-workload-sidecar1-auto
  namespace: bookinfo
spec:
  workloadSelector:
    labels:
      version: v1
  egress:
    # If this config is applied, sidecars will only be able to talk to
    # other services in the same namespace, in addition to istio-telemetry
    # and istio-policy
  - hosts:
    - "./*"
    - "istio-system/istio-telemetry.istio-system.svc.cluster.local"
    - "istio-system/istio-policy.istio-system.svc.cluster.local"`

**Comment by hhovsepy** [comment] 2022-03-11 07:01
Kiali latest master.
Istio 1.13.2

**Comment by lucasponce** [comment] 2022-03-11 07:45
It seems there is a change in the Sidecar syntax that galley is rejecting in the webhook.
So probably we need to update it in Istio 1.13.x, and check that is compatible with 1.12.x.

**Comment by jshaughn** [comment] 2022-03-11 15:11
@hhovsepy Thanks for confirming.  For me, I installed travel demo and created sidecars from the overview page kebab, for travel-agency namespace.  I went to travels-v1 SC and edited the yaml by deleting an egress host.  I did not see a crash.

**Comment by hhovsepy** [comment] 2022-03-11 15:16
Still I see the error, it seems coming from UI and shown 'null' edit request:
![Screenshot from 2022-03-11 16-15-50](https://user-images.githubusercontent.com/604313/157895209-da92aa30-c8bb-473f-8fb1-13782c33554a.png)

**Comment by lucasponce** [comment] 2022-03-14 08:43
Ok, it's interesting.
It seems the null happens in the array which is not allowed, but "null" values in the fields are the mechanism used in the merge/patch syntax to "remove" a field.

Perhaps that case can be handled in the "yaml" library that performs the conversion from yaml -> json ?

**Comment by skondkar** [comment] 2022-03-15 08:50
@hhovsepy , I reproduced the issue on master after trying to remove a host from egress hosts.

![Screenshot from 2022-03-15 14-17-20](https://user-images.githubusercontent.com/6614472/158340462-21471c77-4a28-4b9f-bf78-be20de300e88.png)

**Comment by lucasponce** [comment] 2022-03-18 17:35
Fixed by https://github.com/kiali/kiali-ui/pull/2327

**Closed by lucasponce** 2022-03-18 17:35 UTC
Labels: bug, backlog
