### ISSUE TITLE
Graph dashboard reports wrong request distribution

### ISSUE THREAD

**Issue by schurmann** [kiali/kiali#4137] opened 2021-06-30 14:59 UTC
**Describe the bug**

The "Service graph" shows the wrong request distribution. The service `echoserver` should not have ~43% of the traffic. I'm sending traffic from a pod in the same namespace towards `echoserver`. The routing is done with a `VirtualService` managed by flagger and routes all internal traffic towards `echoserver` to `echoserver-primary` and `echoserver-canary`.

```yaml
spec:
  gateways:
  - mesh
  hosts:
  - echoserver
  http:
  - route:
    - destination:
        host: echoserver-primary
      weight: 90
    - destination:
        host: echoserver-canary
      weight: 10
```
![service-graph](https://user-images.githubusercontent.com/8396695/123981024-4a65cb00-d9c2-11eb-9962-f14ed4326d76.png)

**Versions used**
Kiali: 1.36.0
Istio: 1.10.1
Kubernetes flavour and version: minikube v1.21.0

**To Reproduce**
1. Deploy three services: `echoserver`, `echoserver-canary`, `echoserver-primary`.
2. Deploy two pods `echoserver` and `echoserver-primary`. Services `echoserver` and `echoserver-primary` select pod `echoserver-primary`.  The service `echoserver-canary` selects pod `echoserver`.
3. Deploy a VirtualService like the one above.
4. Send traffic to echoserver.
5. Open the kiali dashboard with the "Service graph" view.
6. Verify that the traffic distribution is incorrect.

**Expected behavior**
A request distribution of ~10% to echoserver-canary and ~90% to echoserver-primary.

**Comment by jmazzitelli** [comment] 2021-06-30 15:10
What does the graph look like when you turn off service nodes (the triangles)? (go to the Display dropdown menu on the graph web page and uncheck the "Service Nodes" option). Do you see anything odd in the graph that doesn't have service nodes?

I know generating service node on the graph require some additional processing - I wonder if there is an issue there.

I also wonder if there is a problem at all with Kiali - perhaps the issue is in the Istio telemetry? See this to help debug that and see if it is the case: https://kiali.io/documentation/latest/faq/#prometheus

**Comment by lucasponce** [comment] 2021-06-30 17:45
> Services echoserver and echoserver-primary select pod echoserver-primary.

Note that when you have several services using the same selector for pods, then probably this is why telemetry is resolving the invoked service in a 50%/50% of the 90%.

**Comment by jshaughn** [comment] 2021-06-30 19:12
> What does the graph look like when you turn off service nodes (the triangles)?

That doesn't make sense for a service graph. 

I would recommend first examining the workload graph and see if that makes sense, or can help explain the behavior.  (note that service graphs are aggregated views of the workload graph).

**Comment by schurmann** [comment] 2021-07-01 08:24
The workload graph does make more sense.

![workload-graph](https://user-images.githubusercontent.com/8396695/124091475-2bb11400-da56-11eb-9fd4-3b7b16d3675c.png)

**Comment by jshaughn** [comment] 2021-07-01 12:46
@schurmann OK, so that is good and shows the expected distribution.  Using the same workload graph, can you also turn on the Service Nodes Display option and post the result?

**Comment by schurmann** [comment] 2021-07-01 14:39
@jshaughn With Service Nodes enabled.

![Screenshot 2021-07-01 at 16-36-25 Kiali Console](https://user-images.githubusercontent.com/8396695/124142696-bc094c00-da8a-11eb-83bc-1a96896b69ed.png)

**Comment by jshaughn** [comment] 2021-07-01 17:05
OK, @schurmann , so we can see where the service graph results are coming from, as the workload graph is showing the same.  

Looking more carefully at these two workload graphs, is this actually expected?  Is `echoserver` workload the workload you expect for traffic routed to `echoserver-canary`?  Perhaps it's just a slight naming mismatch.

I guess the fundamental question here is why we see **any** traffic from busybox to echoserver-primary, routed through the echoserver service node. Istio must be reporting that telemetry, and I'm wonndering if it is a difference between source-proxy and desination-proxy reporting.  If you look at the node graphs for busy-box and echoserver-primary (by double-clicking on those nodes from the main graph) you may get a clue.  Node graphs show things a little differently, from the perspective of the selected node.  Meaning, the outgoing edges for `busybox` would only show traffic reported by the source-proxy.  And the incoming edges for `echoserver-primary` would show only traffic reported by the destination-proxy.

Take a look at the node graphs and let's see if you only see traffic routed through one of the service nodes, or still both.

**Comment by schurmann** [comment] 2021-07-06 13:19
Yes, as mentioned in my first post `echoserver` should receive traffic routed to `echoserver-canary.`

I agree, there should not be any traffic from `busybox` to `echoserver-primary` through the `echoserver` service node.
Here are individual service graphs for `busybox` and the three `echoserver` services.


![Screenshot 2021-07-06 at 14-58-51 Kiali Console](https://user-images.githubusercontent.com/8396695/124605952-b8037280-de6c-11eb-8441-c7e4fea57694.png)
This shows the traffic expected.


![Screenshot 2021-07-06 at 15-04-20 Kiali Console](https://user-images.githubusercontent.com/8396695/124605959-ba65cc80-de6c-11eb-8b57-4aff34b2127b.png)
This should be empty. Since all traffic should use the `echoserver-primary` and `echoserver-canary` services. 


![Screenshot 2021-07-06 at 15-04-32 Kiali Console](https://user-images.githubusercontent.com/8396695/124605967-bafe6300-de6c-11eb-9f8d-3fb068bda7dc.png)
This is the service graph for `echoserver-primary`. This should not be empty.


![Screenshot 2021-07-06 at 15-06-14 Kiali Console](https://user-images.githubusercontent.com/8396695/124605973-bb96f980-de6c-11eb-9453-b9ca5a8c5b36.png)
This shows the traffic expected. The `unknown` node is expected since it's sending data for load testing.

**Comment by jshaughn** [comment] 2021-07-07 17:32
I think we may need to look at the underlying Prometheus metrics because it certainly seems like Istio is reporting traffic to the echoserver-primary workload through the echoserver service.  Also, it's unclear why you would have an empty graph for the echoserver-primary workload node.

If you are unfamiliar with accessing the prometheus metrics directly, see https://kiali.io/documentation/latest/faq/#prometheus.

If you could **attach** the results of the following query we should be able to get an idea of what is being reported, and decide whether Kiali is correctly reflecting the telemetry, or maybe has a problem:

`sum(rate(istio_requests_total{destination_workload="echoserver-primary"} [10m])) by (reporter, source_workload, destination_service, destination_service_name) > 0`

Hopefully I got that right, if nothing comes back I probably made a mistake. Note that this is for traffic in the last 10m, adjust the time window if necessary.

**Comment by schurmann** [comment] 2021-07-09 15:14
So it seems that the problem lies within the Istio metrics?

![Screenshot 2021-07-09 at 17-09-32 Prometheus Time Series Collection and Processing Server](https://user-images.githubusercontent.com/8396695/125099836-bd64f500-e0d8-11eb-8956-546adaea0e56.png)

Thanks for all the help!

**Comment by jshaughn** [comment] 2021-07-09 15:34
@schurmann , right, so we can see now that what Kiali is reporting is a reflection of the underlying metrics.  It looks like the source-proxy reporting (reporter="source") has the expected/resolved `echoserver-primary` destination_service and destination_service_name.  But the destination-proxy has the requested/unresolved `echoserver` destination_service and destination_service_name.   To be honest, I don't know whether it is expected or not expected from the Istio side, but because Kiali uses both sides of the reporting you are seeing the different paths.

Perhaps @bianpengyuan could help us understand?

**Comment by bianpengyuan** [comment] 2021-07-09 17:09
Do `echo-primary` and `echo` bind to the same destination workload? Can you add `destination_workload` and `response_code` to the group by of your prom query?

**Comment by bianpengyuan** [comment] 2021-07-09 17:12
Oh sorry, I see you have already filtered out time series by `echoserver-primary`.

Yeah this is a known limitation. If two service bind to the same port of the same workload, the destination proxy cannot distinguish what is the intended `destination_service` of the client, so it just pick a service on that port based on time of creation. The intended `destination_service` needs to be forwarded by the client proxy. I cannot find a tracking issue, I will create one and link it here.

**Comment by jshaughn** [comment] 2021-07-12 17:11
@bianpengyuan Thanks so much for your response, do please add the tracking issue.  @schurmann OK, so the mystery is solved.  From a Kiali perspective there really isn't anything we can do, as Peter described above it is currently expected given the port binding of the two services.

**Comment by schurmann** [comment] 2021-07-13 11:43
Okay, thanks for helping out. Feel free to close this if you want to.

**Comment by jshaughn** [comment] 2021-07-13 18:49
Thanks @schurmann , @bianpengyuan , closing this one, deferring to Istio for any change here.

**Closed by jshaughn** 2021-07-13 18:49 UTC
Labels: bug
