### ISSUE TITLE
Kiali UI hanging on loading graph

### ISSUE THREAD

**Issue by Siddharthk** [kiali/kiali#3354] opened 2020-10-26 08:00 UTC
**Describe the bug**
Kiali UI is hanging when trying to load graph. It is never able to load graph.

![image](https://user-images.githubusercontent.com/718854/97146955-bc7c7500-178e-11eb-86ba-c234f0f4f9a1.png)

**Versions used**
Kiali: 1.18.3
Istio: 1.6.7
Kubernetes flavour and version: AWS EKS 1.16.8

**To Reproduce**
UI hangs when trying to load grap. I think the issue can be to load too many services.
![image](https://user-images.githubusercontent.com/718854/97147799-16ca0580-1790-11eb-84f6-13d2903e4367.png)

How does kiali calculate services? Notice it is showing 3783 services but i dont have those many services.

**Expected behavior**
UI should not hang

**Comment by lucasponce** [comment] 2020-10-26 09:06
@Siddharthk thanks for the feedback.

There may be multiple things here, could you check if the Kiali pod has enough resources ?

For example, if you see suspicious re-starts on that pod that could be a symptom.

Also, I put some FAQ to help to debug these situations as well:

https://github.com/kiali/kiali/issues/3263#issuecomment-699839839

On top of that, in such of large deployments, (I guess you have 3k services in a single namespace, isn't it) we know that there could be some improvements in terms of perf addressed in Kiali 1.25 and beyond (we are currently working on 1.26).

Could you check if other pages are also failing ?

Thanks

**Comment by lucasponce** [comment] 2020-10-26 09:11
Side note, the screenshot looks that there is hang in the browser, so, definitely 3k services may be a high stress for the Graph component.

There was an old discussion around this that we may want to revisit:
https://github.com/kiali/kiali/issues/1826

**Comment by Siddharthk** [comment] 2020-10-26 09:52
@lucasponce Thanks for the reply. I would like to know how kiali is determining number of services. We definitely don't have 3k kubernetes services endpoint. I can investigate more on this first.

**Comment by lucasponce** [comment] 2020-10-26 11:23
> We definitely don't have 3k kubernetes services endpoint. I can investigate more on this first.

May you attach which service do you see in the Kiali's Service list for the given namespace ?

Graph fetches Istio telemetry to determine the "live" entities to show as the purpose of Kiali Graph is focus on "real time" traffic.

I have a gut feeling that telemetry may be corrupted.

It requires more investigation, perhaps checking with the Service List it can give you some hints about the root cause of that duplication.

Is your prometheus configured with some specific non-default way ? or it's working with the out-of-the-box config ?

**Comment by Siddharthk** [comment] 2020-10-27 05:29
One issue I noticed is that prometheus is taking too much of memory on that node and thus causing slowness.
Pod level:
```
[ec2-user@avs-2099 ~]$ kubectl top pod prometheus-5668f757c-hshhw -n istio-system
NAME                         CPU(cores)   MEMORY(bytes)
prometheus-5668f757c-hshhw   3130m        52825Mi

```
Node level:
```
[ec2-user@avs-2099 ~]$ kubectl top node
NAME                           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
ip-10-21-38-165.ec2.internal   5955m        75%    61273Mi         97%

```
Never seen prometheus taking that much of memory. Is it because all the istio related data is getting scraped and stored in RAM? Any ideas?

**Comment by lucasponce** [comment] 2020-10-27 08:59
I don't have any early idea around this, I guess it would need ad-hoc investigation.

How many Apps/Workloads/Services do you see from the others Kiali's pages ? To compare the ratio of "duplication" that happened on the Prometheus server ?

**Comment by jotak** [comment] 2020-10-27 09:36
@Siddharthk this number of services might definitely be the problem if you don't expect that much. You can also try to figure out the issue by querying prometheus directly (if it can respond). In the prometheus console search for "sum(istio_requests_total) by (destination_service_name)" : it should give you the list of all services and you can perhaps understand why you have so many of them.

or curl:
```bash
istioctl dashboard prometheus
curl "http://localhost:9090/api/v1/query?query=sum(istio_requests_total)%20by%20(destination_service_name)"
```

**Comment by Siddharthk** [comment] 2020-10-27 10:34
@lucasponce @jotak seeing some strange destination service name in prometheus:
![image](https://user-images.githubusercontent.com/718854/97290027-00927700-186e-11eb-9af0-3d3d119bf943.png)

Only the yellow highlighted ones are the actual kubernetes service defined.

**Comment by lucasponce** [comment] 2020-10-27 10:38
> Only the yellow highlighted ones are the actual kubernetes service defined.

And the other entries are valid workload IPs ? Perhaps then it's a telemetry issue that at some point is flipping the service name vs IP.

To be honest, I haven't seen this before, perhaps worth to add an issue in Istio repo to involve the telemetry group.

**Comment by Siddharthk** [comment] 2020-10-27 10:51
IP is from one of the pods and is valid but not the ports. I deleted the pod so that it takes a new ip. Now I can see that number of services have reduced drastically from 3k to 45. Could have been telemetry issue.

![image](https://user-images.githubusercontent.com/718854/97291569-1d2fae80-1870-11eb-8b5b-5a0720d9f2f4.png)

Graph is also loading now. I will monitor this behavior and will keep you guys posted.

**Comment by lucasponce** [comment] 2020-10-27 10:53
Ouch, glad you could workaround it.
Yes, it seems a telemetry issue and pretty scary, having a pod that can populate the prometheus server without control is probably something Istio team would like to have it documented.

Now it sounds more "normal" scenario and Kiali shouldn't have major issue to render and show it.

**Comment by jshaughn** [comment] 2020-10-27 13:56
@Siddharthk This should definitely be reported to Istio as a telemetry issue.  That sort of reporting will certainly kill Prometheus.

**Comment by lucasponce** [comment] 2020-10-28 09:21
Thanks for reporting the case and giving us visibility of this problem @Siddharthk.
As I think that is not an action on Kiali but more understanding why Istio Telemetry reported that case I'm going to close this one.

But please, report it to Istio and link with this one for more details.

**Closed by lucasponce** 2020-10-28 09:21 UTC
Labels: bug, waiting external
