### ISSUE TITLE
Add De-Dup to Kiali Logs Tab

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1559] opened 2019-08-27 15:15 UTC
Inspired by Loki, add a de-duplication capability to filter the noise out of the logs and see the more important things going on.

JIRA:
Inspired by Loki, add a de-duplication capability to filter the noise out of the logs and see the more important things going on.

**Comment by abonas** [comment] 2019-11-26 14:02
can you give an example of what de-duplication means here? is it like grouping similar messages?

**Comment by jshaughn** [comment] 2019-11-26 14:10
@mtho11 I think that as a pre-requisite to this work we'd need an issue for breaking the log string we get from k8s interface into individual log entries.  That in itself could be a gateway to doing some more interesting things, like search, severity filtering, etc.

**Comment by mtho11** [comment] 2019-11-26 16:25
@abonas Once you see that a pod is having an issue the first place you go is the logs. If the issue isn't at the very end of the logs then we need to scroll through them hunting for the issue.  At this point, the first thing I would want to do is reduce the noise (de-dup) to make it easier to find the source of the issue.

Here is a screen from Loki show what de-dup features they have:

![Loki_-_Prometheus-inspired__open_source_logging_in_Grafana_-_YouTube](https://user-images.githubusercontent.com/1312165/69652241-36a7f500-1026-11ea-83b1-ebf0b7711eb5.jpg)

**Comment by jshaughn** [comment] 2019-11-26 16:29
Is there any way to leverage Loki?  Otherwise we'll be re-inventing the wheel, which is OK if it's what we have to do.  But I'm curious whether we can leverage anything, even if it's OS only.

**Comment by mtho11** [comment] 2019-11-26 17:54
@jshaughn I have no idea what the long term plans are for logging. Maybe, @abonas or @maltron knows. Seems to me that Loki is a pretty heavyweight solution (that requires the ELK stack) that not everyone will want to install. My proposal is that Kiali provides a lightweight solution that is good enough (and I don't think we are there yet).

Logging is one of the pillars of observability and Kiali only provides bare-bones support.

From the CLI, I use `stern` and `kail` which are great for aggregating logs of multiple pods and stern has colored keyword output.  But a GUI solution with keyword search and de-duping would be awesome and just another reason to use Kiali.

**Comment by abonas** [comment] 2019-11-26 19:13
I still want to refine the understanding between deduplication and grouping.
Above is written "eliminating" identical service entries. I read "eliminating" as removing all, and keeping one similar entry. If indeed so, then user loses valuable information on - first/last time the error started, how many times was the error thrown, etc.
If you take grouping approach instead, that information will still be kept, but visually will be essentially presenting the unique messages to ease search and troubleshooting. That leaves of course the question in which order should those grouped and distinct messages be presented.

**Comment by mtho11** [comment] 2019-11-26 23:33
Yes, I probably used the wrong word 'eliminating'. What we want to eliminate is the clutter in the logs, but keep the context.  I would assume that we would use the same approach that we do in the Message Center. No need for any new methods of doing things, everything should operate the same.

**Comment by jshaughn** [comment] 2019-12-03 15:25
@mtho11 I'm adding this to the backlog with the understanding that Step 1 is to work on the sub-task of adding to the server-side API the ability to fetch the log as a series of log entries, as opposed to just a text blob.  Given log entries we should be able to do some other manipulations.

**Comment by jshaughn** [comment] 2020-08-03 13:21
Just a note that before we break ground on anything in this area we need to first revisit our goals with logging, where we are, and what we may still need to do. In other words, there is still some research/design work here.

**Comment by jshaughn** [comment] 2021-05-20 15:46
I am closing this as it continues to lack priority.

**Closed by jshaughn** 2021-05-20 15:46 UTC
Labels: backlog, research
