### ISSUE TITLE
support manually turn on/off the zoom in/out mode

### ISSUE THREAD

**Issue by Xunzhuo** [kiali/kiali#4757] opened 2022-02-24 10:13 UTC
In v1.45, the zoom in/out has been introduced into kiali, which makes a great work in large scale scenario.
This issue is to have a suggestion that user should be manually turn on/off this mode, because in some meshes,

whose scale is not that big, zoom in/out will make the mesh hard to observe, like this picture below:
There are only one namespace with four apps, but we can not see what nodes are when we zoom out.
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/48784001/155503869-5160a66b-4ae2-4c2f-9475-ba7da60a5c86.png">
We can not directly see what the node is, even if the there are only a few nodes, 
zoom in/out brings some difficulties to the mesh when scale is small, make it hard be observed.

My suggestions are:
+ user can manually turn on/off this mode
+ or we can make this configurable, let user define in what scale, kiali will automatically turn on zoom in/out mode.

**Comment by lucasponce** [comment] 2022-02-24 11:50
> or we can make this configurable, let user define in what scale, kiali will automatically turn on zoom in/out mode.

I think this is configurable, IIRC but I agree that having an on/off control may be helpful.

**Comment by leandroberetta** [comment] 2022-02-24 13:25
I thought that when just one namespace is selected, the graph would behave as always did, but maybe I missed some of the last additions.

Anyway, there could be cases of very simple multi namespace meshes (example, 3 namespaces with 1 service on each of them) that might need to behave like the case I said before. 

I guess that a on/off switch would be nice.

**Comment by jshaughn** [comment] 2022-02-24 14:23
I'm a little surprised with that screenshot, I'm not sure how you ended up with that zoomed out view without manually performing a zoom.  If it is easily reproducible please enter the steps, because by default the graph should "fit" the screen.   If it does not fit the screen, you can always click the on-graph toolbar option to force the fit.

The new zoom-sensitive labeling is configurable in the CR.  You can set the minimum font size that you consider readable.  If you set it very small you can effectively turn off the feature.

I'm sort of -1 on this feature request, because I don't see the benefit of showing labels that are too small to read.

**Comment by Xunzhuo** [comment] 2022-03-03 07:56
Thanks @jshaughn, problem is solved with CR config :)

**Comment by Xunzhuo** [comment] 2022-03-03 07:58
Just for a suggestion, if it is able to turn on/off this mode manually, it would be a better choice in user and experience :)

**Comment by jshaughn** [comment] 2022-11-30 20:08
Closing this, the behavior can be revisited for https://github.com/kiali/openshift-servicemesh-plugin/issues/100

**Closed by jshaughn** 2022-11-30 20:08 UTC
Labels: enhancement
