### ISSUE TITLE
api/namespaces/graph endpoint sometimes returns 500 and 504 response codes under "heavy" load

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#2139] opened 2020-01-23 13:25 UTC
**Describe the bug**
Simple gatling scenario which is hitting /api/namespaces/graph?namespaces=bookinfo,bookinfo2&graphType=service&duration=600s from 10 users is overloading kiali so some response codes are 500 and 504.
Error in kiali logs are:
`E0123 10:11:08.904738       1 graph.go:87] Get http://prometheus-istio-system.apps.fbr-perf-1.maistra.upshift.redhat.com/api/v1/query?query=round%28sum%28rate%28istio_requests_total%7Breporter%3D%22destination%22%2Csource_workload%3D%22unknown%22%2Cdestination_workload_namespace%3D%22bookinfo%22%7D+%5B600s%5D%29%29+by+%28source_workload_namespace%2Csource_workload%2Csource_app%2Csource_version%2Cdestination_service_namespace%2Cdestination_service%2Cdestination_service_name%2Cdestination_workload_namespace%2Cdestination_workload%2Cdestination_app%2Cdestination_version%2Crequest_protocol%2Cresponse_code%2Cresponse_flags%29%2C0.001%29&time=2020-01-23T10%3A11%3A08Z: dial tcp 192.168.0.7:80: connect: connection refused: goroutine 193 [running]:`

and different types of:

`E0123 11:29:05.196103       1 reflector.go:126] github.com/kiali/kiali/kubernetes/cache/cache.go:141: Failed to list *kubernetes.GenericIstioObject: Get https://172.30.0.1:443/apis/networking.istio.io/v1alpha3/namespaces/bookinfo/virtualservices?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: connection refused`

Bigger log is attached.
[kiali-78c54746b8-lcqtv-kiali.log](https://github.com/kiali/kiali/files/4103242/kiali-78c54746b8-lcqtv-kiali.log)

**Versions used**
Kiali UI
    1.13.0 (fbf32cc9028f1f4176cda603be0a0f53097f3705)
Kiali Server
    v1.13.0-SNAPSHOT (d99f35fd45234d4a7167829196e05ea96a2e848b)
Kiali Container
    v1.13.0-SNAPSHOT
Istio
    1.4.3 
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OpenShift Version
    4.2.14
Kubernetes Version
    v1.14.6+b294fe5

**To Reproduce**
1. install istio with 2 bookinfo apps, kiali with caching enabled for both bookinfo namespaces
2. get gatling https://gatling.io/open-source/
3. get attached gatling simulation 
[KialiSim.scala.txt](https://github.com/kiali/kiali/files/4103229/KialiSim.scala.txt)
4. rename it to KialiSim.scala and copy to $GATLING_HOME/user-files/simulations
5. set required variables e.g:
`export JAVA_OPTS="-DtestMaxDuration=20 -DaccessToken=5tiiiCKYJSFRlnRFSvbOjkrqEq-WE1fDcJAIof5lwnY -Dusers=10 -DkialiUrl=https://kiali-istio-system.apps.fbr-perf-1.maistra.upshift.redhat.com"`
6. run it
`./gatling.sh -s KialiSim`
7. check kiali log for errors

Depending on performance of your OCP nodes you might need to increase the number of users to see the errors.
Gatling results from my env (internal):
http://web.bc.jonqe.lab.eng.bos.redhat.com/gatling/reports/kialisim-20200123102731262/index.html

**Comment by lucasponce** [comment] 2020-01-23 13:26
Thanks Filip.
As commented, I have a suspect where it can be the issue related to caching.
I'll put on my todo list to take a look.

**Comment by lucasponce** [comment] 2020-01-29 18:50
Moved from bug -> maintenance as this is related performance scenarios.
@FilipB has started to design and execute more tests around this and we will continue iterating on this.

**Comment by jshaughn** [comment] 2021-02-15 19:58
@FilipB Has this improved since a year ago?

**Comment by FilipB** [comment] 2021-02-19 12:22
I turned this test into jenkins job so it will be now easy to run it repeatedly.
I was not able to see any errors even with 100 parallel users.
It might be because the mean response time is now much worse. For 10 users it was 118ms a year ago, now it is 423ms.
I can't tell if the drop is caused by changes in the env where we run the test as we don't control that or by changes on kiali side. Maybe the /api/namespaces/graph?namespaces=bookinfo,bookinfo2&graphType=service&duration=600s is now fetching more data than one year ago?
For 100 users the kiali pod memory usage does not grow over 100MB and 1 CPU even though there are no limits.

**Comment by jshaughn** [comment] 2021-02-19 14:01
@FilipB There have been changes, there is a new appender for health info and I'm not sure what else.  I would not worry too much about the increase in the last year but it would be nice to start keeping some stats to catch perf regressions.

**Comment by jshaughn** [comment] 2021-03-15 20:17
@FilipB Because the original issue seems resolved I will close this.  We can re-open if you feel there is more to do here.

**Closed by jshaughn** 2021-03-15 20:17 UTC
Labels: backlog, maintenance
